function varargout = CL1_mix(varargin)
%CL1_MIX  Self-contained mixed-variable MOO adaptation of CL1.
%
% Auto-generated by generate_selfcontained_wrappers_MOO_mix.m
% Source: CL1, n=4, m=2, strategy=halton_oscillatory, kappa=1000000
% Variable pattern: C,K,D,C
% D variables: nonuniform sorted finite sets with injected anchors.
% K variables: labels with permuted nonuniform numeric embeddings; labels carry no ordinal information.
%
%   x1   C [500500,1501500] -> orig [1,3]
%   x2   K labels {k2_1,...,k2_35}, 35 levels, permuted embedding in [1.41421356237,3]
%   x3   D sorted nonuniform grid [1.41421356237,...,3], 63 values
%   x4   C [250.75,752.25] -> orig [1,3]
%
% Usage:
%   PB = CL1_mix()
%   F  = PB.func_F(xcell)       % recommended inside benchmark loops
%   F  = CL1_mix(xcell)              % also valid; PB is memoized persistently
%   PD = CL1_mix('ProblemData')
%

persistent PB_cached
if isempty(PB_cached)
lb_orig = [1; 1.414213562373095; 1.414213562373095; 1];
ub_orig = [3; 3; 3; 3];
lb_C_work = [500500; 1.414213562373095; 1.414213562373095; 250.75];
ub_C_work = [1501500; 3; 3; 752.25];
var_types = {'C', 'K', 'D', 'C'};
K2_labels = { ...
    'k2_1', 'k2_2', 'k2_3', 'k2_4', 'k2_5', 'k2_6', 'k2_7', 'k2_8', 'k2_9', 'k2_10', ...
    'k2_11', 'k2_12', 'k2_13', 'k2_14', 'k2_15', 'k2_16', 'k2_17', 'k2_18', 'k2_19', 'k2_20', ...
    'k2_21', 'k2_22', 'k2_23', 'k2_24', 'k2_25', 'k2_26', 'k2_27', 'k2_28', 'k2_29', 'k2_30', ...
    'k2_31', 'k2_32', 'k2_33', 'k2_34', 'k2_35'};
K2_embed  = [ ...
    1.63670552145213; 1.806590922191978; 1.415980280593245; 2.588533162725677; 1.414213562373095; 2.496769866208358; 1.414548292882425; 2.890357659030447; ...
    1.423538357043473; 1.54444933440516; 2.326157902589768; 2.247187346961182; 1.438888627025754; 1.430143838685439; 2.684680488310931; 2.207106781186547; ...
    2.409331543133479; 1.449935136983327; 3; 1.418888612907314; 2.101602088220794; 1.913122869442678; 1.857993114922657; 1.463430123708684; ...
    2.034856910037098; 1.673980130466488; 1.758840571178833; 1.602753163506956; 2.785269728587324; 1.972053665285958; 2.172356893543734; 1.498294064832838; ...
    1.572032582969224; 1.479508170687318; 1.519904498054207; ...
];
D3_vals = [ ...
    1.414213562373095; 1.415155321110452; 1.417492956770275; 1.42101746228974; 1.425633076932036; 1.43127775189627; 1.437906117993276; 1.445482716286034; ...
    1.453978621700514; 1.463369521579423; 1.473634521579464; 1.484755354927604; 1.496715832937389; 1.509501448426546; 1.523099080583904; 1.537496769705152; ...
    1.552683541561047; 1.568649267956805; 1.585384554278814; 1.602880647559394; 1.621129360407896; 1.640123007396038; 1.659854351350078; 1.680316557617881; ...
    1.701503154824917; 1.723408000961582; 1.746025253889608; 1.769349345541081; 1.793374959225936; 1.818097009574079; 1.843510624724596; 1.896394035899792; ...
    1.923855020894246; 1.951989924328826; 1.980794733785746; 2.010265576067014; 2.040398708585719; 2.071190511510575; 2.102637480579495; 2.134736220509346; ...
    2.167483438938588; 2.200875940847647; 2.207106781186547; 2.234910623408736; 2.269584471222762; 2.304894551906009; 2.34083801199363; 2.377412073130758; ...
    2.414614028525285; 2.45244123963923; 2.490891133098041; 2.529961197799387; 2.569648982204856; 2.609952091799689; 2.650868186707095; 2.692394979445055; ...
    2.734530232814639; 2.777271757909892; 2.820617412240281; 2.864565097957473; 2.909112760178978; 2.954258385401819; 3; ...
];
ProblemData = { ...
    [500500; 1501500]; ... % x1 C
    K2_labels; ... % x2 K
    {D3_vals}; ... % x3 D
    [250.75; 752.25]; ... % x4 C
};
x_anchor = {1001000, 'k2_16', 2.207106781186547, 501.5};
anchors_set = [2 1 3; 2.207106781186547 1.414213562373095 3; 2.207106781186547 1.414213562373095 3; 2 1 3];

PB = struct();
PB.name = 'CL1_mix';
PB.problem = 'CL1';
PB.source = 'MOModels_Matlab';
PB.type = 'MOO_MIXED';
PB.nvar = 4; PB.n = 4; PB.nobj = 2; PB.m = 2;
PB.var_types = var_types;
PB.type_counts = struct('C', 2, 'D', 1, 'K', 1);
PB.ProblemData = ProblemData;
PB.strategy = 'halton_oscillatory'; PB.kappa = 1000000;
PB.lb_orig = lb_orig; PB.ub_orig = ub_orig;
PB.lb_C_work = lb_C_work; PB.ub_C_work = ub_C_work;
PB.x_anchor = x_anchor;
PB.anchors_set = anchors_set;
PB.K2_labels = K2_labels; PB.K2_embed = K2_embed;
PB.D3_vals = D3_vals;
PB.pareto_front_known = false;
PB.pareto_set_known = false;
PB.pf_type = 'unknown';
PB.ideal_point = [];
PB.nadir_point = [];
PB.core = @(xh) CL1_orig(xh);
PB.decode = @(xr) decode(xr, PB);
PB.func_F = @(xr) objective(xr, PB);
PB_cached = PB;
else
    PB = PB_cached;
end

if nargin == 0
    varargout{1} = PB; return
end
arg1 = varargin{1};
if ischar(arg1) || (isstring(arg1) && isscalar(arg1))
    key = lower(char(arg1));
    switch key
        case {'problemdata','bounds','domain'}
            varargout{1} = PB.ProblemData; return
        case 'var_types'
            varargout{1} = PB.var_types; return
        case 'info'
            varargout{1} = PB; return
        otherwise
            error('Unknown string argument: %s', char(arg1));
    end
end
varargout{1} = PB.func_F(arg1);
end

function F = objective(xr, PB)
xh = decode(xr, PB);
F = PB.core(xh);
F = F(:);
end

function xh = decode(xr, PB)
if ~iscell(xr) || numel(xr) ~= 4
    error('CL1_mix: input must be a cell array with exactly 4 entries.');
end
xh = zeros(4,1);
tmp = check_C(xr{1}, PB.lb_C_work(1), PB.ub_C_work(1), 'x1');
xh(1) = map_C_to_orig(tmp, PB.lb_C_work(1), PB.ub_C_work(1), PB.lb_orig(1), PB.ub_orig(1));
xh(2) = check_K(xr{2}, PB.K2_labels, PB.K2_embed, 'x2');
xh(3) = check_D(xr{3}, PB.D3_vals, 'x3');
tmp = check_C(xr{4}, PB.lb_C_work(4), PB.ub_C_work(4), 'x4');
xh(4) = map_C_to_orig(tmp, PB.lb_C_work(4), PB.ub_C_work(4), PB.lb_orig(4), PB.ub_orig(4));
end

function v = check_C(val, a, b, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('CL1_mix: %s must be a real scalar.', name);
end
if val < a || val > b
    error('CL1_mix: %s=%g outside [%g,%g].', name, val, a, b);
end
v = double(val);
end

function xorig = map_C_to_orig(xwork, lbw, ubw, lbo, ubo)
if abs(ubw - lbw) <= 1e-14
    t = 0;
else
    t = (xwork - lbw) / (ubw - lbw);
end
t = max(0, min(1, t));
xorig = lbo + t * (ubo - lbo);
end

function v = check_D(val, grid, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('CL1_mix: %s must be a real scalar.', name);
end
grid = grid(:);
[dmin, idx] = min(abs(grid - val));
if dmin > 1e-10 * max(1, max(abs(grid)))
    error('CL1_mix: %s=%g not in grid.', name, val);
end
v = grid(idx);
end

function v = check_K(label, labels, embed, name)
if isstring(label), label = char(label); end
if ~(ischar(label) && isrow(label))
    error('CL1_mix: %s must be a char vector or scalar string.', name);
end
idx = find(strcmp(label, labels), 1);
if isempty(idx)
    error('CL1_mix: %s unknown label ''%s''.', name, label);
end
v = embed(idx);
end


% -------------------------------------------------------------------------
% Embedded original continuous MOO problem (top-level function renamed only)
% -------------------------------------------------------------------------
function f = CL1_orig(x)
%###############################################################################
%
%   As described by F.Y. Cheng and X.S. Li, "Generalized center method for
%   multiobjective engineering optimization", Engineering Optimization,31:5,
%   641-661, 1999.
%
%   Example 2, four bar truss.
%
%   This file is part of a collection of problems developed for
%   derivative-free multiobjective optimization in
%   A. L. Custódio, J. F. A. Madeira, A. I. F. Vaz, and L. N. Vicente,
%   Direct Multisearch for Multiobjective Optimization, 2010.
%
%   Written by the authors in June 1, 2010.
%
%   MATLAB version by J. F. A. Madeira
%   November 7, 2025
%
%###############################################################################
%
% Problem characteristics:
% - Number of variables: 4 (fixed)
% - Number of objectives: 2 (fixed)
%   Bounds: x1 in [1,3], x2 in [1.41421356237,3], x3 in [1.41421356237,3], x4 in [1,3]
%
%
% Check dimension
n = length(x);
if n ~= 4
    error('CL1 requires exactly 4 variables, %d provided', n);
end
% Ensure x is a column vector
x = x(:);
% Parameters
F = 10;
E = 2e5;
L = 200;
sigma = 10;
% Objective functions
f = zeros(2, 1);
f(1) = L * (2*x(1) + sqrt(2)*x(2) + sqrt(x(3)) + x(4));
f(2) = F*L/E * (2/x(1) + (2*sqrt(2))/x(2) - (2*sqrt(2))/x(3) + 2/x(4));
end

