function varargout = Far1_mix(varargin)
%FAR1_MIX  Self-contained mixed-variable MOO adaptation of Far1.
%
% Auto-generated by generate_selfcontained_wrappers_MOO_mix.m
% Source: Far1, n=2, m=2, strategy=halton_oscillatory, kappa=1000000
% Variable pattern: C,K
% D variables: nonuniform sorted finite sets with injected anchors.
% K variables: labels with permuted nonuniform numeric embeddings; labels carry no ordinal information.
%
%   x1   C [-1,1] -> orig [-1,1]
%   x2   K labels {k2_1,...,k2_99}, 99 levels, permuted embedding in [-1,1]
%
% Usage:
%   PB = Far1_mix()
%   F  = PB.func_F(xcell)       % recommended inside benchmark loops
%   F  = Far1_mix(xcell)              % also valid; PB is memoized persistently
%   PD = Far1_mix('ProblemData')
%

persistent PB_cached
if isempty(PB_cached)
lb_orig = [-1; -1];
ub_orig = [1; 1];
lb_C_work = [-1; -1];
ub_C_work = [1; 1];
var_types = {'C', 'K'};
K2_labels = { ...
    'k2_1', 'k2_2', 'k2_3', 'k2_4', 'k2_5', 'k2_6', 'k2_7', 'k2_8', 'k2_9', 'k2_10', ...
    'k2_11', 'k2_12', 'k2_13', 'k2_14', 'k2_15', 'k2_16', 'k2_17', 'k2_18', 'k2_19', 'k2_20', ...
    'k2_21', 'k2_22', 'k2_23', 'k2_24', 'k2_25', 'k2_26', 'k2_27', 'k2_28', 'k2_29', 'k2_30', ...
    'k2_31', 'k2_32', 'k2_33', 'k2_34', 'k2_35', 'k2_36', 'k2_37', 'k2_38', 'k2_39', 'k2_40', ...
    'k2_41', 'k2_42', 'k2_43', 'k2_44', 'k2_45', 'k2_46', 'k2_47', 'k2_48', 'k2_49', 'k2_50', ...
    'k2_51', 'k2_52', 'k2_53', 'k2_54', 'k2_55', 'k2_56', 'k2_57', 'k2_58', 'k2_59', 'k2_60', ...
    'k2_61', 'k2_62', 'k2_63', 'k2_64', 'k2_65', 'k2_66', 'k2_67', 'k2_68', 'k2_69', 'k2_70', ...
    'k2_71', 'k2_72', 'k2_73', 'k2_74', 'k2_75', 'k2_76', 'k2_77', 'k2_78', 'k2_79', 'k2_80', ...
    'k2_81', 'k2_82', 'k2_83', 'k2_84', 'k2_85', 'k2_86', 'k2_87', 'k2_88', 'k2_89', 'k2_90', ...
    'k2_91', 'k2_92', 'k2_93', 'k2_94', 'k2_95', 'k2_96', 'k2_97', 'k2_98', 'k2_99'};
K2_embed  = [ ...
    0.3423780301010872; -0.3073645226621191; -0.521554540343748; -0.9172013131484823; -0.1680278196728662; -0.8832710912969789; 0.2660517541787595; -0.602245204481366; ...
    -0.9975472662057104; -0.8923924833424173; -0.999824385891403; 0.1564169814487841; -0.7671740449036902; 0.2288627583313414; -0.991642287761883; 0.08652578047735049; ...
    -0.7529592084858732; 0.5447059776301468; -0.9010839673543407; 0; 0.9034364135652246; -0.2534146391879665; -0.07720028668413825; -0.9558877303433646; ...
    -0.9995352938443445; -1; -0.6393662368325065; -0.8737139210113845; -0.6743836452944634; -0.9778840074110189; -0.6571356956202492; 0.3038891147459508; ...
    -0.5629859107912591; -0.8637152185787556; -0.013579070699138; 0.3815216670539017; -0.9383072371057615; -0.3589690211136953; -0.723043407426405; -0.1970898640618766; ...
    0.1211536997585134; -0.7941418593237299; -0.9999667273482858; -0.4552627580530876; -0.984312582331731; -0.477918049687131; 0.5029122360058378; 0.9513697856675754; ...
    -0.9951078092428214; -0.2806846111868526; -0.9964492286255343; -0.9894941823519311; -0.4320441220467744; -0.9701348414079664; 0.0525299100156269; 0.1923189134159007; ...
    -0.3334580790161252; -0.8310140021879703; 0.4617856593662557; -0.9812589163281864; -0.5000139713705731; -0.4082582088692829; -0.04569894173030387; -0.8191937595677771; ...
    -0.8423707479252983; -0.9870543934216597; -0.909351536328417; -0.1080865563087032; 0.6741206584401187; 0.7637884345304757; 0.7186134236439532; 0.6303071628687811; ...
    0.421323169602478; -0.9316726788405053; 1; -0.8069047672626222; -0.6911145530924028; -0.9246395583779313; 0.8096486478029066; -0.3839011262019066; ...
    -0.7073329449147933; -0.9504077604269506; -0.9984165096378199; 0.01916274851801303; 0.5871699411914555; -0.9990731031778519; -0.9657436232560522; -0.9445499620169426; ...
    -0.9935096302825721; -0.9609971757282437; -0.8532693404423422; -0.7808999529280163; -0.5425438179184259; -0.1383612306396966; -0.7382505902816674; -0.5828849724220513; ...
    -0.2255509358429844; 0.8561970011493045; -0.9741788623795714; ...
];
ProblemData = { ...
    [-1; 1]; ... % x1 C
    K2_labels; ... % x2 K
};
x_anchor = {0, 'k2_20'};
anchors_set = [0 -1 1; 0 -1 1];

PB = struct();
PB.name = 'Far1_mix';
PB.problem = 'Far1';
PB.source = 'MOModels_Matlab';
PB.type = 'MOO_MIXED';
PB.nvar = 2; PB.n = 2; PB.nobj = 2; PB.m = 2;
PB.var_types = var_types;
PB.type_counts = struct('C', 1, 'D', 0, 'K', 1);
PB.ProblemData = ProblemData;
PB.strategy = 'halton_oscillatory'; PB.kappa = 1000000;
PB.lb_orig = lb_orig; PB.ub_orig = ub_orig;
PB.lb_C_work = lb_C_work; PB.ub_C_work = ub_C_work;
PB.x_anchor = x_anchor;
PB.anchors_set = anchors_set;
PB.K2_labels = K2_labels; PB.K2_embed = K2_embed;
PB.pareto_front_known = false;
PB.pareto_set_known = false;
PB.pf_type = 'unknown';
PB.ideal_point = [];
PB.nadir_point = [];
PB.core = @(xh) Far1_orig(xh);
PB.decode = @(xr) decode(xr, PB);
PB.func_F = @(xr) objective(xr, PB);
PB_cached = PB;
else
    PB = PB_cached;
end

if nargin == 0
    varargout{1} = PB; return
end
arg1 = varargin{1};
if ischar(arg1) || (isstring(arg1) && isscalar(arg1))
    key = lower(char(arg1));
    switch key
        case {'problemdata','bounds','domain'}
            varargout{1} = PB.ProblemData; return
        case 'var_types'
            varargout{1} = PB.var_types; return
        case 'info'
            varargout{1} = PB; return
        otherwise
            error('Unknown string argument: %s', char(arg1));
    end
end
varargout{1} = PB.func_F(arg1);
end

function F = objective(xr, PB)
xh = decode(xr, PB);
F = PB.core(xh);
F = F(:);
end

function xh = decode(xr, PB)
if ~iscell(xr) || numel(xr) ~= 2
    error('Far1_mix: input must be a cell array with exactly 2 entries.');
end
xh = zeros(2,1);
tmp = check_C(xr{1}, PB.lb_C_work(1), PB.ub_C_work(1), 'x1');
xh(1) = map_C_to_orig(tmp, PB.lb_C_work(1), PB.ub_C_work(1), PB.lb_orig(1), PB.ub_orig(1));
xh(2) = check_K(xr{2}, PB.K2_labels, PB.K2_embed, 'x2');
end

function v = check_C(val, a, b, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('Far1_mix: %s must be a real scalar.', name);
end
if val < a || val > b
    error('Far1_mix: %s=%g outside [%g,%g].', name, val, a, b);
end
v = double(val);
end

function xorig = map_C_to_orig(xwork, lbw, ubw, lbo, ubo)
if abs(ubw - lbw) <= 1e-14
    t = 0;
else
    t = (xwork - lbw) / (ubw - lbw);
end
t = max(0, min(1, t));
xorig = lbo + t * (ubo - lbo);
end

function v = check_D(val, grid, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('Far1_mix: %s must be a real scalar.', name);
end
grid = grid(:);
[dmin, idx] = min(abs(grid - val));
if dmin > 1e-10 * max(1, max(abs(grid)))
    error('Far1_mix: %s=%g not in grid.', name, val);
end
v = grid(idx);
end

function v = check_K(label, labels, embed, name)
if isstring(label), label = char(label); end
if ~(ischar(label) && isrow(label))
    error('Far1_mix: %s must be a char vector or scalar string.', name);
end
idx = find(strcmp(label, labels), 1);
if isempty(idx)
    error('Far1_mix: %s unknown label ''%s''.', name, label);
end
v = embed(idx);
end


% -------------------------------------------------------------------------
% Embedded original continuous MOO problem (top-level function renamed only)
% -------------------------------------------------------------------------
function f = Far1_orig(x)
%###############################################################################
%
%   As described by Huband et al. in "A review of multiobjective test problems
%   and a scalable test problem toolkit", IEEE Transactions on Evolutionary 
%   Computing 10(5): 477-506, 2006.
%
%   Example Far1, see the previous cited paper for the original reference.
%
%   This file is part of a collection of problems developed for
%   derivative-free multiobjective optimization in
%   A. L. Custódio, J. F. A. Madeira, A. I. F. Vaz, and L. N. Vicente,
%   Direct Multisearch for Multiobjective Optimization, 2010.
%
%   Written by the authors in June 1, 2010.
%
%   MATLAB version by J. F. A. Madeira
%   November 7, 2025
%
%###############################################################################
%
% Problem characteristics:
% - Number of variables: 2
% - Number of objectives: 2
%   Bounds: x1 in [-1,1], x2 in [-1,1]
%
%
M = 2; % Number of objectives (fixed)
% Check dimension
n = length(x);
if n ~= 2
    error('Far1 requires exactly 2 variables, %d provided', n);
end
% Ensure x is a column vector
x = x(:);
% Initialize objectives
f = zeros(M, 1);
% Objective functions
f(1) = -2*exp(15*(-(x(1)-0.1)^2 - x(2)^2)) ...
       - exp(20*(-(x(1)-0.6)^2 - (x(2)-0.6)^2)) ...
       + exp(20*(-(x(1)+0.6)^2 - (x(2)-0.6)^2)) ...
       + exp(20*(-(x(1)-0.6)^2 - (x(2)+0.6)^2)) ...
       + exp(20*(-(x(1)+0.6)^2 - (x(2)+0.6)^2));
f(2) = 2*exp(20*(-x(1)^2 - x(2)^2)) ...
       + exp(20*(-(x(1)-0.4)^2 - (x(2)-0.6)^2)) ...
       - exp(20*(-(x(1)+0.5)^2 - (x(2)-0.7)^2)) ...
       - exp(20*(-(x(1)-0.5)^2 - (x(2)+0.7)^2)) ...
       + exp(20*(-(x(1)+0.4)^2 - (x(2)+0.8)^2));
end

