function varargout = Kursawe_mix(varargin)
%KURSAWE_MIX  Self-contained mixed-variable MOO adaptation of Kursawe.
%
% Auto-generated by generate_selfcontained_wrappers_MOO_mix.m
% Source: Kursawe, n=3, m=2, strategy=halton_oscillatory, kappa=1000000
% Variable pattern: C,K,D
% D variables: nonuniform sorted finite sets with injected anchors.
% K variables: labels with permuted nonuniform numeric embeddings; labels carry no ordinal information.
%
%   x1   C [-5,5] -> orig [-5,5]
%   x2   K labels {k2_1,...,k2_26}, 26 levels, permuted embedding in [-5,5]
%   x3   D sorted nonuniform grid [-5,...,5], 80 values
%
% Usage:
%   PB = Kursawe_mix()
%   F  = PB.func_F(xcell)       % recommended inside benchmark loops
%   F  = Kursawe_mix(xcell)              % also valid; PB is memoized persistently
%   PD = Kursawe_mix('ProblemData')
%

persistent PB_cached
if isempty(PB_cached)
lb_orig = [-5; -5; -5];
ub_orig = [5; 5; 5];
lb_C_work = [-5; -5; -5];
ub_C_work = [5; 5; 5];
var_types = {'C', 'K', 'D'};
K2_labels = { ...
    'k2_1', 'k2_2', 'k2_3', 'k2_4', 'k2_5', 'k2_6', 'k2_7', 'k2_8', 'k2_9', 'k2_10', ...
    'k2_11', 'k2_12', 'k2_13', 'k2_14', 'k2_15', 'k2_16', 'k2_17', 'k2_18', 'k2_19', 'k2_20', ...
    'k2_21', 'k2_22', 'k2_23', 'k2_24', 'k2_25', 'k2_26'};
K2_embed  = [ ...
    -3.890968250951766; -4.877004857960301; -4.976696778201267; 3.18635899237781; 1.580672632168687; -4.674532985543003; -0.4543290874351635; -5; ...
    -1.573648314068916; -4.995584865083324; 2.357976783249014; 0; -2.513140413136131; 0.1755036770292326; -4.350827748367928; -1.03702447209547; ...
    -2.065304805418679; -4.13875641149013; 0.8535046646697788; -2.918348495495669; -4.938335531791856; -4.528828215700654; -4.789877775647699; 4.066735768635093; ...
    -3.605924086703823; 5; ...
];
D3_vals = [ ...
    -5; -4.996160530378975; -4.986630190234633; -4.972261083440786; -4.95344361831039; -4.930430762484317; -4.903407482256608; -4.872518340673065; ...
    -4.837881262780325; -4.799595369197479; -4.757745844370563; -4.712407160366946; -4.663645317073199; -4.611519459027536; -4.556083078652049; -4.497384934635732; ...
    -4.435469767970224; -4.370378870437214; -4.302150543070855; -4.230820470969856; -4.156422033423865; -4.078986563264996; -3.998543565830052; -3.915120905409743; ...
    -3.828744965243136; -3.739440785776745; -3.647232184907356; -3.552141863170418; -3.45419149625544; -3.353401816780259; -3.249792686904073; -3.143383163081109; ...
    -3.034191554035145; -2.922235472857123; -2.807531883983899; -2.69009714569874; -2.569947048697753; -2.447096851186865; -2.321561310907846; -2.062490904051785; ...
    -1.928983302428644; -1.792844935388171; -1.654088452893206; -1.512726148467294; -1.368769977187405; -1.222231572385049; -1.073122261174795; -0.921453078915965; ...
    -0.7672347827016699; -0.6104778639593018; -0.45119256023776; -0.2893888662489266; -0.1250765442241661; 0; 0.04173486635947743; 0.2110360396339592; ...
    0.3828178547310612; 0.557071387668902; 0.7337879036972819; 0.912958850068426; 1.094575849202619; 1.278630692220878; 1.465115332819236; 1.654021881461334; ...
    1.845342599867932; 2.039069895783781; 2.235196318003744; 2.433714551641641; 2.634617413626433; 2.837897848411675; 3.043548923885147; 3.251563827466587; ...
    3.461935862382319; 3.674658444106448; 3.889725096958896; 4.107129450851424; 4.326865238173228; 4.548926290808398; 4.773306537277996; 5; ...
];
ProblemData = { ...
    [-5; 5]; ... % x1 C
    K2_labels; ... % x2 K
    {D3_vals}; ... % x3 D
};
x_anchor = {0, 'k2_12', 0};
anchors_set = [0 -5 5; 0 -5 5; 0 -5 5];

PB = struct();
PB.name = 'Kursawe_mix';
PB.problem = 'Kursawe';
PB.source = 'MOModels_Matlab';
PB.type = 'MOO_MIXED';
PB.nvar = 3; PB.n = 3; PB.nobj = 2; PB.m = 2;
PB.var_types = var_types;
PB.type_counts = struct('C', 1, 'D', 1, 'K', 1);
PB.ProblemData = ProblemData;
PB.strategy = 'halton_oscillatory'; PB.kappa = 1000000;
PB.lb_orig = lb_orig; PB.ub_orig = ub_orig;
PB.lb_C_work = lb_C_work; PB.ub_C_work = ub_C_work;
PB.x_anchor = x_anchor;
PB.anchors_set = anchors_set;
PB.K2_labels = K2_labels; PB.K2_embed = K2_embed;
PB.D3_vals = D3_vals;
PB.pareto_front_known = false;
PB.pareto_set_known = false;
PB.pf_type = 'unknown';
PB.ideal_point = [];
PB.nadir_point = [];
PB.core = @(xh) Kursawe_orig(xh);
PB.decode = @(xr) decode(xr, PB);
PB.func_F = @(xr) objective(xr, PB);
PB_cached = PB;
else
    PB = PB_cached;
end

if nargin == 0
    varargout{1} = PB; return
end
arg1 = varargin{1};
if ischar(arg1) || (isstring(arg1) && isscalar(arg1))
    key = lower(char(arg1));
    switch key
        case {'problemdata','bounds','domain'}
            varargout{1} = PB.ProblemData; return
        case 'var_types'
            varargout{1} = PB.var_types; return
        case 'info'
            varargout{1} = PB; return
        otherwise
            error('Unknown string argument: %s', char(arg1));
    end
end
varargout{1} = PB.func_F(arg1);
end

function F = objective(xr, PB)
xh = decode(xr, PB);
F = PB.core(xh);
F = F(:);
end

function xh = decode(xr, PB)
if ~iscell(xr) || numel(xr) ~= 3
    error('Kursawe_mix: input must be a cell array with exactly 3 entries.');
end
xh = zeros(3,1);
tmp = check_C(xr{1}, PB.lb_C_work(1), PB.ub_C_work(1), 'x1');
xh(1) = map_C_to_orig(tmp, PB.lb_C_work(1), PB.ub_C_work(1), PB.lb_orig(1), PB.ub_orig(1));
xh(2) = check_K(xr{2}, PB.K2_labels, PB.K2_embed, 'x2');
xh(3) = check_D(xr{3}, PB.D3_vals, 'x3');
end

function v = check_C(val, a, b, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('Kursawe_mix: %s must be a real scalar.', name);
end
if val < a || val > b
    error('Kursawe_mix: %s=%g outside [%g,%g].', name, val, a, b);
end
v = double(val);
end

function xorig = map_C_to_orig(xwork, lbw, ubw, lbo, ubo)
if abs(ubw - lbw) <= 1e-14
    t = 0;
else
    t = (xwork - lbw) / (ubw - lbw);
end
t = max(0, min(1, t));
xorig = lbo + t * (ubo - lbo);
end

function v = check_D(val, grid, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('Kursawe_mix: %s must be a real scalar.', name);
end
grid = grid(:);
[dmin, idx] = min(abs(grid - val));
if dmin > 1e-10 * max(1, max(abs(grid)))
    error('Kursawe_mix: %s=%g not in grid.', name, val);
end
v = grid(idx);
end

function v = check_K(label, labels, embed, name)
if isstring(label), label = char(label); end
if ~(ischar(label) && isrow(label))
    error('Kursawe_mix: %s must be a char vector or scalar string.', name);
end
idx = find(strcmp(label, labels), 1);
if isempty(idx)
    error('Kursawe_mix: %s unknown label ''%s''.', name, label);
end
v = embed(idx);
end


% -------------------------------------------------------------------------
% Embedded original continuous MOO problem (top-level function renamed only)
% -------------------------------------------------------------------------
function f = Kursawe_orig(x)
%###############################################################################
%
%   As described by F. Kursawe in "A variant of evolution strategies for
%   vector optimization", in H. P. Schwefel and R. Männer, editors, Parallel 
%   Problem Solving from Nature, 1st Workshop, PPSN I, volume 496 of Lecture 
%   Notes in Computer Science, pages 193-197, Berlin, Germany, Oct 1991, 
%   Springer-Verlag.
%
%   In the above paper the variables bounds were not set.
%   We considered -5.0 <= x[i] <= 5.0, i=1,2,3.
%
%   This file is part of a collection of problems developed for
%   derivative-free multiobjective optimization in
%   A. L. Custódio, J. F. A. Madeira, A. I. F. Vaz, and L. N. Vicente,
%   Direct Multisearch for Multiobjective Optimization, 2010.
%
%   Written by the authors in June 1, 2010.
%
%   MATLAB version by J. F. A. Madeira
%   November 7, 2025
%
%###############################################################################
%
% Problem characteristics:
% - Number of variables: 3
% - Number of objectives: 2
%   Bounds: x1 in [-5,5], x2 in [-5,5], x3 in [-5,5]
%
%
M = 2; % Number of objectives (fixed)
% Check dimension
n = length(x);
if n ~= 3
    error('Kursawe requires exactly 3 variables, %d provided', n);
end
% Ensure x is a column vector
x = x(:);
% Initialize objectives
f = zeros(M, 1);
% Objective functions
f(1) = 0;
for i = 1:n-1
    f(1) = f(1) - 10*exp(-0.2*sqrt(x(i)^2 + x(i+1)^2));
end
f(2) = 0;
for i = 1:n
    f(2) = f(2) + abs(x(i))^0.8 + 5*sin(x(i))^3;
end
end

