function varargout = lovison4_mix(varargin)
%LOVISON4_MIX  Self-contained mixed-variable MOO adaptation of lovison4.
%
% Auto-generated by generate_selfcontained_wrappers_MOO_mix.m
% Source: lovison4, n=2, m=2, strategy=halton_oscillatory, kappa=1000000
% Variable pattern: C,K
% D variables: nonuniform sorted finite sets with injected anchors.
% K variables: labels with permuted nonuniform numeric embeddings; labels carry no ordinal information.
%
%   x1   C [0,6] -> orig [0,6]
%   x2   K labels {k2_1,...,k2_48}, 48 levels, permuted embedding in [-1,1]
%
% Usage:
%   PB = lovison4_mix()
%   F  = PB.func_F(xcell)       % recommended inside benchmark loops
%   F  = lovison4_mix(xcell)              % also valid; PB is memoized persistently
%   PD = lovison4_mix('ProblemData')
%

persistent PB_cached
if isempty(PB_cached)
lb_orig = [0; -1];
ub_orig = [6; 1];
lb_C_work = [0; -1];
ub_C_work = [6; 1];
var_types = {'C', 'K'};
K2_labels = { ...
    'k2_1', 'k2_2', 'k2_3', 'k2_4', 'k2_5', 'k2_6', 'k2_7', 'k2_8', 'k2_9', 'k2_10', ...
    'k2_11', 'k2_12', 'k2_13', 'k2_14', 'k2_15', 'k2_16', 'k2_17', 'k2_18', 'k2_19', 'k2_20', ...
    'k2_21', 'k2_22', 'k2_23', 'k2_24', 'k2_25', 'k2_26', 'k2_27', 'k2_28', 'k2_29', 'k2_30', ...
    'k2_31', 'k2_32', 'k2_33', 'k2_34', 'k2_35', 'k2_36', 'k2_37', 'k2_38', 'k2_39', 'k2_40', ...
    'k2_41', 'k2_42', 'k2_43', 'k2_44', 'k2_45', 'k2_46', 'k2_47', 'k2_48'};
K2_embed  = [ ...
    -0.423001861773855; -0.6765482012869917; -0.9972892707131106; -0.4712283401121732; 0.05468103924848866; 0.6155463781778954; -0.9945932148065115; 0.4410411836894435; ...
    0.5268396644080122; -0.9084919750007345; -0.9792875996182273; -0.849379843334; -0.1440890306554548; -0.890679295380622; 0.2780569121556158; -0.9244855389553648; ...
    -0.01426893582445621; -0.9856926850479428; -0.8709927379055137; 0.2008140716116367; -1; -0.8001753095533328; -0.7107179782814499; -0.9387173437778883; ...
    -0.7724882772949299; 0.8017941381584055; -0.8257902137344957; -0.5170177484570617; 0; -0.3190955884766928; -0.2050220470294409; 1; ...
    -0.9621403007865218; 0.7071888286221455; -0.6014322850954092; -0.9998059135857006; -0.9989756057638333; -0.08051523555444762; -0.9512476969380858; 0.1263653303699346; ...
    -0.7426838017656261; -0.2633465929498273; -0.971462816661369; -0.9907631658241901; -0.5604066059988519; -0.3723025973657589; 0.3581230365610504; 0.8993890617723173; ...
];
ProblemData = { ...
    [0; 6]; ... % x1 C
    K2_labels; ... % x2 K
};
x_anchor = {3, 'k2_29'};
anchors_set = [3 0 6; 0 -1 1];

PB = struct();
PB.name = 'lovison4_mix';
PB.problem = 'lovison4';
PB.source = 'MOModels_Matlab';
PB.type = 'MOO_MIXED';
PB.nvar = 2; PB.n = 2; PB.nobj = 2; PB.m = 2;
PB.var_types = var_types;
PB.type_counts = struct('C', 1, 'D', 0, 'K', 1);
PB.ProblemData = ProblemData;
PB.strategy = 'halton_oscillatory'; PB.kappa = 1000000;
PB.lb_orig = lb_orig; PB.ub_orig = ub_orig;
PB.lb_C_work = lb_C_work; PB.ub_C_work = ub_C_work;
PB.x_anchor = x_anchor;
PB.anchors_set = anchors_set;
PB.K2_labels = K2_labels; PB.K2_embed = K2_embed;
PB.pareto_front_known = false;
PB.pareto_set_known = false;
PB.pf_type = 'unknown';
PB.ideal_point = [];
PB.nadir_point = [];
PB.core = @(xh) lovison4_orig(xh);
PB.decode = @(xr) decode(xr, PB);
PB.func_F = @(xr) objective(xr, PB);
PB_cached = PB;
else
    PB = PB_cached;
end

if nargin == 0
    varargout{1} = PB; return
end
arg1 = varargin{1};
if ischar(arg1) || (isstring(arg1) && isscalar(arg1))
    key = lower(char(arg1));
    switch key
        case {'problemdata','bounds','domain'}
            varargout{1} = PB.ProblemData; return
        case 'var_types'
            varargout{1} = PB.var_types; return
        case 'info'
            varargout{1} = PB; return
        otherwise
            error('Unknown string argument: %s', char(arg1));
    end
end
varargout{1} = PB.func_F(arg1);
end

function F = objective(xr, PB)
xh = decode(xr, PB);
F = PB.core(xh);
F = F(:);
end

function xh = decode(xr, PB)
if ~iscell(xr) || numel(xr) ~= 2
    error('lovison4_mix: input must be a cell array with exactly 2 entries.');
end
xh = zeros(2,1);
tmp = check_C(xr{1}, PB.lb_C_work(1), PB.ub_C_work(1), 'x1');
xh(1) = map_C_to_orig(tmp, PB.lb_C_work(1), PB.ub_C_work(1), PB.lb_orig(1), PB.ub_orig(1));
xh(2) = check_K(xr{2}, PB.K2_labels, PB.K2_embed, 'x2');
end

function v = check_C(val, a, b, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('lovison4_mix: %s must be a real scalar.', name);
end
if val < a || val > b
    error('lovison4_mix: %s=%g outside [%g,%g].', name, val, a, b);
end
v = double(val);
end

function xorig = map_C_to_orig(xwork, lbw, ubw, lbo, ubo)
if abs(ubw - lbw) <= 1e-14
    t = 0;
else
    t = (xwork - lbw) / (ubw - lbw);
end
t = max(0, min(1, t));
xorig = lbo + t * (ubo - lbo);
end

function v = check_D(val, grid, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('lovison4_mix: %s must be a real scalar.', name);
end
grid = grid(:);
[dmin, idx] = min(abs(grid - val));
if dmin > 1e-10 * max(1, max(abs(grid)))
    error('lovison4_mix: %s=%g not in grid.', name, val);
end
v = grid(idx);
end

function v = check_K(label, labels, embed, name)
if isstring(label), label = char(label); end
if ~(ischar(label) && isrow(label))
    error('lovison4_mix: %s must be a char vector or scalar string.', name);
end
idx = find(strcmp(label, labels), 1);
if isempty(idx)
    error('lovison4_mix: %s unknown label ''%s''.', name, label);
end
v = embed(idx);
end


% -------------------------------------------------------------------------
% Embedded original continuous MOO problem (top-level function renamed only)
% -------------------------------------------------------------------------
function f = lovison4_orig(x)
% LOVISON4 function
%
%   As described by A. Lovison in "A synthetic approach to multiobjective
%   optimization", arxiv Item: http://arxiv.org/abs/1002.0093.
%
%   Example 4.
%
%   In the above paper/papers the variables bounds were not set.
%   We considered 0<=x[1]<=6 and -1<=x[2]<=1.
%
%   This file is part of a collection of problems developed for
%   derivative-free multiobjective optimization in
%   A. L. Custódio, J. F. A. Madeira, A. I. F. Vaz, and L. N. Vicente,
%   Direct Multisearch for Multiobjective Optimization, 2010.
%
%   Written by the authors in June 1, 2010.
%   Adapted to MATLAB format in November 2025.
%
%   Input: x is a 2-dimensional vector
%   Output: f is a 2-dimensional vector with the function values
%   Output: c is a vector of constraints (empty for this problem - bounds are
%          handled by the optimization algorithm)
% Nota: Este problema é originalmente de maximização, 
% mas para manter a consistência com a interface da coleção DMS,
% convertemos para minimização multiplicando por -1.
% Função objetivo 1
%
%   Bounds: x1 in [0,6], x2 in [-1,1]
%
f1 = -(-x(1)^2-x(2)^2-4*(exp(-(x(1)+2)^2-x(2)^2)+exp(-(x(1)-2)^2-x(2)^2)));
% Função objetivo 2
f2 = -(-(x(1)-6)^2-(x(2)+0.5)^2);
% Vetor de funções objetivo
f = [f1; f2];
% Não há restrições de desigualdade para este problema
% As restrições de limites são tratadas pelo algoritmo de otimização
end

