function varargout = MOP3_mix(varargin)
%MOP3_MIX  Self-contained mixed-variable MOO adaptation of MOP3.
%
% Auto-generated by generate_selfcontained_wrappers_MOO_mix.m
% Source: MOP3, n=2, m=2, strategy=halton_oscillatory, kappa=1000000
% Variable pattern: C,K
% D variables: nonuniform sorted finite sets with injected anchors.
% K variables: labels with permuted nonuniform numeric embeddings; labels carry no ordinal information.
%
%   x1   C [-3.14159265359,3.14159265359] -> orig [-3.14159265359,3.14159265359]
%   x2   K labels {k2_1,...,k2_60}, 60 levels, permuted embedding in [-3.14159265359,3.14159265359]
%
% Usage:
%   PB = MOP3_mix()
%   F  = PB.func_F(xcell)       % recommended inside benchmark loops
%   F  = MOP3_mix(xcell)              % also valid; PB is memoized persistently
%   PD = MOP3_mix('ProblemData')
%

persistent PB_cached
if isempty(PB_cached)
lb_orig = [-3.141592653589793; -3.141592653589793];
ub_orig = [3.141592653589793; 3.141592653589793];
lb_C_work = [-3.141592653589793; -3.141592653589793];
ub_C_work = [3.141592653589793; 3.141592653589793];
var_types = {'C', 'K'};
K2_labels = { ...
    'k2_1', 'k2_2', 'k2_3', 'k2_4', 'k2_5', 'k2_6', 'k2_7', 'k2_8', 'k2_9', 'k2_10', ...
    'k2_11', 'k2_12', 'k2_13', 'k2_14', 'k2_15', 'k2_16', 'k2_17', 'k2_18', 'k2_19', 'k2_20', ...
    'k2_21', 'k2_22', 'k2_23', 'k2_24', 'k2_25', 'k2_26', 'k2_27', 'k2_28', 'k2_29', 'k2_30', ...
    'k2_31', 'k2_32', 'k2_33', 'k2_34', 'k2_35', 'k2_36', 'k2_37', 'k2_38', 'k2_39', 'k2_40', ...
    'k2_41', 'k2_42', 'k2_43', 'k2_44', 'k2_45', 'k2_46', 'k2_47', 'k2_48', 'k2_49', 'k2_50', ...
    'k2_51', 'k2_52', 'k2_53', 'k2_54', 'k2_55', 'k2_56', 'k2_57', 'k2_58', 'k2_59', 'k2_60'};
K2_embed  = [ ...
    -0.2008343376023949; -1.221770308172298; 0.8819224180553054; -2.67320328388971; -1.583588912661196; -3.136658347895764; -2.341406446295624; -3.139727961922907; ...
    -1.800671921108845; -3.124778963012525; 1.498675357733184; -2.552817500035135; -0.03401876246220681; -0.9557662268490068; 1.71573195152413; 0; ...
    -2.82448081786244; -3.103890137283541; 0.6876598953590944; -2.777854336876525; 1.287384734797216; -1.347279061942386; -3.131750751967358; 0.4989816508187905; ...
    2.401936109321001; -3.115549232000023; -2.416084962865543; -0.6694187390250335; -2.262426266363481; 3.141592653589793; 1.081815468874266; 0.3158408525917205; ...
    1.938598618104382; -3.07267712952518; 2.167318962871518; 2.88903097477193; -0.5184839011226341; -2.942597579501219; -0.3623060289919757; -3.05284946268582; ...
    -2.486531498223862; -3.089646785398385; -1.902151101414693; -3.141592653589793; -2.727455987773888; -2.975021771360041; 0.1381900670169567; -2.179076394646245; ...
    -3.030040621815731; -1.467866350221964; -0.8151620766070362; -1.091284314029059; -3.004134650344612; -2.091290355730945; -1.694504499511817; 2.642492712992492; ...
    -2.615016306091833; -3.141239360583426; -2.867420717547676; -2.906762391858148; ...
];
ProblemData = { ...
    [-3.141592653589793; 3.141592653589793]; ... % x1 C
    K2_labels; ... % x2 K
};
x_anchor = {0, 'k2_16'};
anchors_set = [0 -3.141592653589793 3.141592653589793; 0 -3.141592653589793 3.141592653589793];

PB = struct();
PB.name = 'MOP3_mix';
PB.problem = 'MOP3';
PB.source = 'MOModels_Matlab';
PB.type = 'MOO_MIXED';
PB.nvar = 2; PB.n = 2; PB.nobj = 2; PB.m = 2;
PB.var_types = var_types;
PB.type_counts = struct('C', 1, 'D', 0, 'K', 1);
PB.ProblemData = ProblemData;
PB.strategy = 'halton_oscillatory'; PB.kappa = 1000000;
PB.lb_orig = lb_orig; PB.ub_orig = ub_orig;
PB.lb_C_work = lb_C_work; PB.ub_C_work = ub_C_work;
PB.x_anchor = x_anchor;
PB.anchors_set = anchors_set;
PB.K2_labels = K2_labels; PB.K2_embed = K2_embed;
PB.pareto_front_known = false;
PB.pareto_set_known = false;
PB.pf_type = 'unknown';
PB.ideal_point = [];
PB.nadir_point = [];
PB.core = @(xh) MOP3_orig(xh);
PB.decode = @(xr) decode(xr, PB);
PB.func_F = @(xr) objective(xr, PB);
PB_cached = PB;
else
    PB = PB_cached;
end

if nargin == 0
    varargout{1} = PB; return
end
arg1 = varargin{1};
if ischar(arg1) || (isstring(arg1) && isscalar(arg1))
    key = lower(char(arg1));
    switch key
        case {'problemdata','bounds','domain'}
            varargout{1} = PB.ProblemData; return
        case 'var_types'
            varargout{1} = PB.var_types; return
        case 'info'
            varargout{1} = PB; return
        otherwise
            error('Unknown string argument: %s', char(arg1));
    end
end
varargout{1} = PB.func_F(arg1);
end

function F = objective(xr, PB)
xh = decode(xr, PB);
F = PB.core(xh);
F = F(:);
end

function xh = decode(xr, PB)
if ~iscell(xr) || numel(xr) ~= 2
    error('MOP3_mix: input must be a cell array with exactly 2 entries.');
end
xh = zeros(2,1);
tmp = check_C(xr{1}, PB.lb_C_work(1), PB.ub_C_work(1), 'x1');
xh(1) = map_C_to_orig(tmp, PB.lb_C_work(1), PB.ub_C_work(1), PB.lb_orig(1), PB.ub_orig(1));
xh(2) = check_K(xr{2}, PB.K2_labels, PB.K2_embed, 'x2');
end

function v = check_C(val, a, b, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('MOP3_mix: %s must be a real scalar.', name);
end
if val < a || val > b
    error('MOP3_mix: %s=%g outside [%g,%g].', name, val, a, b);
end
v = double(val);
end

function xorig = map_C_to_orig(xwork, lbw, ubw, lbo, ubo)
if abs(ubw - lbw) <= 1e-14
    t = 0;
else
    t = (xwork - lbw) / (ubw - lbw);
end
t = max(0, min(1, t));
xorig = lbo + t * (ubo - lbo);
end

function v = check_D(val, grid, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('MOP3_mix: %s must be a real scalar.', name);
end
grid = grid(:);
[dmin, idx] = min(abs(grid - val));
if dmin > 1e-10 * max(1, max(abs(grid)))
    error('MOP3_mix: %s=%g not in grid.', name, val);
end
v = grid(idx);
end

function v = check_K(label, labels, embed, name)
if isstring(label), label = char(label); end
if ~(ischar(label) && isrow(label))
    error('MOP3_mix: %s must be a char vector or scalar string.', name);
end
idx = find(strcmp(label, labels), 1);
if isempty(idx)
    error('MOP3_mix: %s unknown label ''%s''.', name, label);
end
v = embed(idx);
end


% -------------------------------------------------------------------------
% Embedded original continuous MOO problem (top-level function renamed only)
% -------------------------------------------------------------------------
function f = MOP3_orig(x)
% MOP3 function
%
%   As described by Huband et al. in "A review of multiobjective test problems
%   and a scalable test problem toolkit", IEEE Transactions on Evolutionary 
%   Computing 10(5): 477-506, 2006.
%
%   Example MOP3, Van Valedhuizen's test suit.
%
%   This file is part of a collection of problems developed for
%   derivative-free multiobjective optimization in
%   A. L. Custódio, J. F. A. Madeira, A. I. F. Vaz, and L. N. Vicente,
%   Direct Multisearch for Multiobjective Optimization, 2010.
%
%   Written by the authors in June 1, 2010.
%   Adapted to MATLAB format in November 2025.
%
% Problem characteristics:
% - Number of variables: 2
% - Number of objectives: 2
%   Bounds: x1 in [-3.14159265359,3.14159265359], x2 in [-3.14159265359,3.14159265359]
%
%
%   Input: x is a 2-dimensional vector
%   Output: f is a 2-dimensional vector with the function values
%   Output: c is a vector of constraints (empty for this problem - bounds are
%          handled by the optimization algorithm)
% Nota: Este problema é originalmente de maximização, 
% mas para manter a consistência com a interface da coleção DMS,
% convertemos para minimização multiplicando por -1.
% Parâmetros
pi = 4*atan(1);
A1 = 0.5*sin(1) - 2*cos(1) + sin(2) - 1.5*cos(2);
A2 = 1.5*sin(1) - cos(1) + 2*sin(2) - 0.5*cos(2);
% Variáveis adicionais
B1 = 0.5*sin(x(1)) - 2*cos(x(1)) + sin(x(2)) - 1.5*cos(x(2));
B2 = 1.5*sin(x(1)) - cos(x(1)) + 2*sin(x(2)) - 0.5*cos(x(2));
% Função objetivo 1
f1 = -(-1 - (A1-B1)^2 - (A2-B2)^2);
% Função objetivo 2
f2 = -(-(x(1)+3)^2 - (x(2)+1)^2);
% Vetor de funções objetivo
f = [f1; f2];
% Não há restrições de desigualdade para este problema
end

