function varargout = WFG9_mix(varargin)
%WFG9_MIX  Self-contained mixed-variable MOO adaptation of WFG9.
%
% Auto-generated by generate_selfcontained_wrappers_MOO_mix.m
% Source: WFG9, n=8, m=3, strategy=halton_oscillatory, kappa=1000000
% Variable pattern: C,K,D,C,D,K,C,K
% D variables: nonuniform sorted finite sets with injected anchors.
% K variables: labels with permuted nonuniform numeric embeddings; labels carry no ordinal information.
%
%   x1   C [0,1001000] -> orig [0,2]
%   x2   K labels {k2_1,...,k2_61}, 61 levels, permuted embedding in [0,4]
%   x3   D sorted nonuniform grid [0,...,6], 92 values
%   x4   C [0,2006] -> orig [0,8]
%   x5   D sorted nonuniform grid [0,...,10], 56 values
%   x6   K labels {k6_1,...,k6_113}, 113 levels, permuted embedding in [0,12]
%   x7   C [0,10503500] -> orig [0,14]
%   x8   K labels {k8_1,...,k8_58}, 58 levels, permuted embedding in [0,16]
%
% Usage:
%   PB = WFG9_mix()
%   F  = PB.func_F(xcell)       % recommended inside benchmark loops
%   F  = WFG9_mix(xcell)              % also valid; PB is memoized persistently
%   PD = WFG9_mix('ProblemData')
%

persistent PB_cached
if isempty(PB_cached)
lb_orig = [0; 0; 0; 0; 0; 0; 0; 0];
ub_orig = [2; 4; 6; 8; 10; 12; 14; 16];
lb_C_work = [0; 0; 0; 0; 0; 0; 0; 0];
ub_C_work = [1001000; 4; 6; 2006; 10; 12; 10503500; 16];
var_types = {'C', 'K', 'D', 'C', 'D', 'K', 'C', 'K'};
K2_labels = { ...
    'k2_1', 'k2_2', 'k2_3', 'k2_4', 'k2_5', 'k2_6', 'k2_7', 'k2_8', 'k2_9', 'k2_10', ...
    'k2_11', 'k2_12', 'k2_13', 'k2_14', 'k2_15', 'k2_16', 'k2_17', 'k2_18', 'k2_19', 'k2_20', ...
    'k2_21', 'k2_22', 'k2_23', 'k2_24', 'k2_25', 'k2_26', 'k2_27', 'k2_28', 'k2_29', 'k2_30', ...
    'k2_31', 'k2_32', 'k2_33', 'k2_34', 'k2_35', 'k2_36', 'k2_37', 'k2_38', 'k2_39', 'k2_40', ...
    'k2_41', 'k2_42', 'k2_43', 'k2_44', 'k2_45', 'k2_46', 'k2_47', 'k2_48', 'k2_49', 'k2_50', ...
    'k2_51', 'k2_52', 'k2_53', 'k2_54', 'k2_55', 'k2_56', 'k2_57', 'k2_58', 'k2_59', 'k2_60', ...
    'k2_61'};
K2_embed  = [ ...
    3.687433313759668; 1.097135573517763; 0.8848240905300371; 2.708104463860096; 3.246141487304723; 0.02305325671235902; 0.2532244477664035; 2.460183959055776; ...
    0.006017844612725818; 0.4436126996192938; 0.0002160215064770599; 1.603903542242712; 2.341401865867911; 0.5885319225646894; 0.1216758184041442; 0.952643582372424; ...
    0.4005380663263885; 4; 0.04213849428041586; 0.003017088168272583; 0.4892749837862268; 1.173878077832529; 1.900130433811628; 2.226034287425843; ...
    1.699398722187002; 3.841862508092436; 0.2224083062042683; 1.336526648115468; 0.2863973399898908; 1.5116142229639; 0.6986379701959828; 0.05426214910339855; ...
    0.1435872943746294; 2.114052588333391; 3.389598472039828; 0.8199078710213759; 0.32197584954068; 0.08404888974092058; 0.06820864698747564; 2.582408846596823; ...
    0.537567526076357; 1.253663922785606; 3.53668714626109; 1.023402306210737; 2.837298412929469; 0.03176237428917504; 3.106290110265952; 2.970017973001461; ...
    2.005427765211754; 0.1676428165579842; 0.6422088197361375; 0.3600073971323594; 2; 0; 1.42249925387; 0.01028075479130982; ...
    1.798130815375317; 0.01592428682213989; 0.1938984787160702; 0.001140168346774234; 0.1018500006114931; ...
];
D3_vals = [ ...
    0; 0.001785980629194688; 0.006219145771125608; 0.01290312791597937; 0.02165632341709643; 0.03236106099406513; 0.04493130110215115; 0.05929979830774475; ...
    0.07541169819870536; 0.09322089349378779; 0.1126877595089745; 0.1337776545664118; 0.1564598779364218; 0.1807069177462717; 0.206493891280615; 0.2337981177833453; ...
    0.2625987853840011; 0.2928766866582432; 0.3246140053679398; 0.3577941421123034; 0.3924015700684638; 0.4284217143506314; 0.4658408501568966; 0.5046460160398809; ...
    0.5448249394831792; 0.586365972588298; 0.6292580361420926; 0.6734905706869863; 0.7190534934861919; 0.7659371604853213; 0.8141323325354595; 0.8636301452721327; ...
    0.9144220821476806; 0.9664999501973588; 1.019855858186544; 1.07448219684106; 1.130371620907484; 1.187517032827324; 1.245911567839677; 1.305548580352677; ...
    1.366421631445539; 1.4285244773812; 1.491851059024933; 1.55639549207739; 1.622152058041727; 1.757279494114653; 1.826639683864761; 1.897190631859434; ...
    1.968927334292985; 2.04184491093769; 2.115938599660799; 2.191203751288446; 2.26763582478819; 2.345230382744735; 2.423983087105873; 2.503889695177801; ...
    2.584946055851031; 2.667148106039721; 2.750491867318893; 2.834973442745327; 2.920589013849211; 3; 3.007334837784675; 3.095207244628391; ...
    3.184202634816312; 3.274317476709395; 3.365548304279947; 3.457891714910858; 3.551344367300593; 3.645902979467392; 3.741564326846568; 3.838325240475326; ...
    3.936182605259854; 4.035133358319893; 4.135174487406275; 4.236303029387282; 4.338516068799952; 4.441810736462697; 4.546184208145912; 4.651633703297399; ...
    4.758156483819691; 4.865749852896543; 4.97441115386602; 5.084137769137776; 5.1949271191523; 5.306776661379985; 5.419683889358081; 5.53364633176365; ...
    5.648661551520769; 5.764727144940368; 5.881840740891128; 6; ...
];
D5_vals = [ ...
    0; 0.007367958294325679; 0.02565672097387028; 0.05323109713354118; 0.08934189158453704; 0.1335036583638164; 0.1853614463778999; 0.244637838536019; ...
    0.3111065361794398; 0.3845773264247044; 0.4648867399628546; 0.5518918645844859; 0.6454660462306603; 0.7454957862846627; 0.8518784325643104; 0.9645204169410679; ...
    1.08333588126447; 1.208245586432391; 1.339176032599776; 1.476058739912635; 1.618829653374247; 1.76742864514846; 1.92179909437029; 2.081887529349083; ...
    2.247643320538494; 2.419018415216719; 2.59596710674; 2.966412997314719; 3.159828814646624; 3.358655169114637; 3.562855491303235; 3.772394646694748; ...
    3.987238835693844; 4.207355503475095; 4.432713258424357; 4.663281798129614; 4.899031842029747; 5; 5.139935069956447; 5.385964065910392; ...
    5.637092266501682; 5.893293913559415; 6.154544010478789; 6.420818281928101; 6.69209313658415; 6.968345632604117; 7.249553445576082; 7.535694838719715; ...
    7.826748635134226; 8.122694191912851; 8.423511375962452; 8.729180541383791; 9.039682508282869; 9.354998542896787; 9.675110338929121; 10; ...
];
K6_labels = { ...
    'k6_1', 'k6_2', 'k6_3', 'k6_4', 'k6_5', 'k6_6', 'k6_7', 'k6_8', 'k6_9', 'k6_10', ...
    'k6_11', 'k6_12', 'k6_13', 'k6_14', 'k6_15', 'k6_16', 'k6_17', 'k6_18', 'k6_19', 'k6_20', ...
    'k6_21', 'k6_22', 'k6_23', 'k6_24', 'k6_25', 'k6_26', 'k6_27', 'k6_28', 'k6_29', 'k6_30', ...
    'k6_31', 'k6_32', 'k6_33', 'k6_34', 'k6_35', 'k6_36', 'k6_37', 'k6_38', 'k6_39', 'k6_40', ...
    'k6_41', 'k6_42', 'k6_43', 'k6_44', 'k6_45', 'k6_46', 'k6_47', 'k6_48', 'k6_49', 'k6_50', ...
    'k6_51', 'k6_52', 'k6_53', 'k6_54', 'k6_55', 'k6_56', 'k6_57', 'k6_58', 'k6_59', 'k6_60', ...
    'k6_61', 'k6_62', 'k6_63', 'k6_64', 'k6_65', 'k6_66', 'k6_67', 'k6_68', 'k6_69', 'k6_70', ...
    'k6_71', 'k6_72', 'k6_73', 'k6_74', 'k6_75', 'k6_76', 'k6_77', 'k6_78', 'k6_79', 'k6_80', ...
    'k6_81', 'k6_82', 'k6_83', 'k6_84', 'k6_85', 'k6_86', 'k6_87', 'k6_88', 'k6_89', 'k6_90', ...
    'k6_91', 'k6_92', 'k6_93', 'k6_94', 'k6_95', 'k6_96', 'k6_97', 'k6_98', 'k6_99', 'k6_100', ...
    'k6_101', 'k6_102', 'k6_103', 'k6_104', 'k6_105', 'k6_106', 'k6_107', 'k6_108', 'k6_109', 'k6_110', ...
    'k6_111', 'k6_112', 'k6_113'};
K6_embed  = [ ...
    0.09631124864166822; 0.03639636331953958; 0.5499536095663992; 2.683001976216234; 8.083410689632792; 9.587346063076495; 10.27808747116573; 4.731628217820711; ...
    5.513432182586396; 10.5145833555234; 2.372234650669265; 7.880700817355175; 0.08161411530901166; 0.02130462824679409; 3.016305391111657; 1.139872532501768; ...
    4.295689239585585; 8.709647396938768; 0.4686117636738804; 0; 9.814480826756341; 9.142353117864445; 0.2686611058758823; 8.497871387102281; ...
    0.9541420773248322; 3.132491701877214; 0.1124465020308818; 0.01068122325340887; 12; 1.493113598072159; 0.7359042279813224; 0.7873793006653977; ...
    3.25124762219456; 0.1300575003951344; 1.570496458309996; 0.02826441585728307; 1.816462407084161; 6.016283295635262; 9.363307552842047; 11.74446236987922; ...
    0.0001448965321957899; 11.49212750978576; 6.911845273398807; 3.752284932330245; 10.75422350271379; 3.496532087724614; 7.099700268645353; 2.083545626136124; ...
    6.544917822077834; 0.8964759095398653; 4.583582195483899; 0.1491804812682394; 3.623092167355845; 0.004036472247126398; 1.418001818080883; 0.05637583431841757; ...
    1.274513427246303; 0.01546298332936986; 0.4307618831238882; 1.345141664305511; 6.365818831490866; 1.075819093374354; 2.17735100637902; 0.6864476025069149; ...
    5.845819657788862; 0.2414751394896458; 4.018630060488667; 6.18961182216849; 8.289130002323411; 7.680987673779532; 0.8408956955861944; 0.297553437438296; ...
    0.0007647684819036168; 10.04472395064071; 2.576931175390767; 0.3605736837031346; 4.155812864027285; 0.1921011572939875; 0.006895821355519692; 0.5934961958739555; ...
    1.206097132786821; 4.438274089843437; 3.884125801570297; 8.924470507390696; 5.19233866027683; 2.902672553523885; 10.99701974457151; 0.002023713379473489; ...
    0.06831593822956518; 0.5083338179163855; 2.791576898307106; 1.650169606000532; 1.992141022740164; 2.473347716995692; 0.3947580778268504; 0.6389861535337317; ...
    5.678207217071931; 0.2159654601528864; 1.013915986872178; 3.372589137848408; 7.290500317472198; 6; 0.3281814371029032; 11.24298384676735; ...
    0.04575098366560817; 5.035992076125595; 6.726922198551081; 4.882426701335003; 1.732152009704391; 7.484258465792288; 1.903119312251238; 0.1698504234458814; ...
    5.351480662147781; ...
];
K8_labels = { ...
    'k8_1', 'k8_2', 'k8_3', 'k8_4', 'k8_5', 'k8_6', 'k8_7', 'k8_8', 'k8_9', 'k8_10', ...
    'k8_11', 'k8_12', 'k8_13', 'k8_14', 'k8_15', 'k8_16', 'k8_17', 'k8_18', 'k8_19', 'k8_20', ...
    'k8_21', 'k8_22', 'k8_23', 'k8_24', 'k8_25', 'k8_26', 'k8_27', 'k8_28', 'k8_29', 'k8_30', ...
    'k8_31', 'k8_32', 'k8_33', 'k8_34', 'k8_35', 'k8_36', 'k8_37', 'k8_38', 'k8_39', 'k8_40', ...
    'k8_41', 'k8_42', 'k8_43', 'k8_44', 'k8_45', 'k8_46', 'k8_47', 'k8_48', 'k8_49', 'k8_50', ...
    'k8_51', 'k8_52', 'k8_53', 'k8_54', 'k8_55', 'k8_56', 'k8_57', 'k8_58'};
K8_embed  = [ ...
    0.0009772829658645185; 4.3097669337455; 4.629879947589512; 1.456621233262619; 10.07059633093828; 9.072570718422066; 8.134757714269467; 13.43638427794237; ...
    9.563990258254297; 0.5504623434177479; 2.006907283674312; 12.83595996181455; 7.688092961159179; 1.628676248677304; 0.2454823821700524; 0.02722477556585803; ...
    0.3802378271644423; 2.213483810366332; 8.596204776870495; 6.0464568918556; 8; 0.1436932269126651; 4.963449819089059; 5.310633502082998; ...
    0.01364933020535756; 14.05288048076225; 1.006176897221542; 3.709269549106326; 0.7584173985429843; 10.59252014798398; 1.295663780915036; 14.68556919200037; ...
    2.662522968985245; 1.145589359959563; 12.25148553712723; 0.07204159673088283; 1.812037309547512; 4.002951028181067; 7.25607202859693; 16; ...
    0.005158130418087314; 3.428556734203151; 6.838554434477231; 5.671585281659771; 11.1298912561452; 3.160643579953938; 2.43195964514831; 6.435397625142324; ...
    0.6495900301565629; 0.4607701904045054; 11.68283759258442; 0.04651021418019814; 0.3085764464502748; 0.8771982171894646; 0; 15.33456970034; ...
    0.1906348739948401; 0.1042931116448021; ...
];
ProblemData = { ...
    [0; 1001000]; ... % x1 C
    K2_labels; ... % x2 K
    {D3_vals}; ... % x3 D
    [0; 2006]; ... % x4 C
    {D5_vals}; ... % x5 D
    K6_labels; ... % x6 K
    [0; 10503500]; ... % x7 C
    K8_labels; ... % x8 K
};
x_anchor = {500500, 'k2_53', 3, 1003, 5, 'k6_102', 5251750, 'k8_21'};
anchors_set = [ ...
    1 0 2; ...
    2 0 4; ...
    3 0 6; ...
    4 0 8; ...
    5 0 10; ...
    6 0 12; ...
    7 0 14; ...
    8 0 16];

PB = struct();
PB.name = 'WFG9_mix';
PB.problem = 'WFG9';
PB.source = 'MOModels_Matlab';
PB.type = 'MOO_MIXED';
PB.nvar = 8; PB.n = 8; PB.nobj = 3; PB.m = 3;
PB.var_types = var_types;
PB.type_counts = struct('C', 3, 'D', 2, 'K', 3);
PB.ProblemData = ProblemData;
PB.strategy = 'halton_oscillatory'; PB.kappa = 1000000;
PB.lb_orig = lb_orig; PB.ub_orig = ub_orig;
PB.lb_C_work = lb_C_work; PB.ub_C_work = ub_C_work;
PB.x_anchor = x_anchor;
PB.anchors_set = anchors_set;
PB.K2_labels = K2_labels; PB.K2_embed = K2_embed;
PB.D3_vals = D3_vals;
PB.D5_vals = D5_vals;
PB.K6_labels = K6_labels; PB.K6_embed = K6_embed;
PB.K8_labels = K8_labels; PB.K8_embed = K8_embed;
PB.pareto_front_known = false;
PB.pareto_set_known = false;
PB.pf_type = 'unknown';
PB.ideal_point = [];
PB.nadir_point = [];
PB.core = @(xh) WFG9_orig(xh);
PB.decode = @(xr) decode(xr, PB);
PB.func_F = @(xr) objective(xr, PB);
PB_cached = PB;
else
    PB = PB_cached;
end

if nargin == 0
    varargout{1} = PB; return
end
arg1 = varargin{1};
if ischar(arg1) || (isstring(arg1) && isscalar(arg1))
    key = lower(char(arg1));
    switch key
        case {'problemdata','bounds','domain'}
            varargout{1} = PB.ProblemData; return
        case 'var_types'
            varargout{1} = PB.var_types; return
        case 'info'
            varargout{1} = PB; return
        otherwise
            error('Unknown string argument: %s', char(arg1));
    end
end
varargout{1} = PB.func_F(arg1);
end

function F = objective(xr, PB)
xh = decode(xr, PB);
F = PB.core(xh);
F = F(:);
end

function xh = decode(xr, PB)
if ~iscell(xr) || numel(xr) ~= 8
    error('WFG9_mix: input must be a cell array with exactly 8 entries.');
end
xh = zeros(8,1);
tmp = check_C(xr{1}, PB.lb_C_work(1), PB.ub_C_work(1), 'x1');
xh(1) = map_C_to_orig(tmp, PB.lb_C_work(1), PB.ub_C_work(1), PB.lb_orig(1), PB.ub_orig(1));
xh(2) = check_K(xr{2}, PB.K2_labels, PB.K2_embed, 'x2');
xh(3) = check_D(xr{3}, PB.D3_vals, 'x3');
tmp = check_C(xr{4}, PB.lb_C_work(4), PB.ub_C_work(4), 'x4');
xh(4) = map_C_to_orig(tmp, PB.lb_C_work(4), PB.ub_C_work(4), PB.lb_orig(4), PB.ub_orig(4));
xh(5) = check_D(xr{5}, PB.D5_vals, 'x5');
xh(6) = check_K(xr{6}, PB.K6_labels, PB.K6_embed, 'x6');
tmp = check_C(xr{7}, PB.lb_C_work(7), PB.ub_C_work(7), 'x7');
xh(7) = map_C_to_orig(tmp, PB.lb_C_work(7), PB.ub_C_work(7), PB.lb_orig(7), PB.ub_orig(7));
xh(8) = check_K(xr{8}, PB.K8_labels, PB.K8_embed, 'x8');
end

function v = check_C(val, a, b, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('WFG9_mix: %s must be a real scalar.', name);
end
if val < a || val > b
    error('WFG9_mix: %s=%g outside [%g,%g].', name, val, a, b);
end
v = double(val);
end

function xorig = map_C_to_orig(xwork, lbw, ubw, lbo, ubo)
if abs(ubw - lbw) <= 1e-14
    t = 0;
else
    t = (xwork - lbw) / (ubw - lbw);
end
t = max(0, min(1, t));
xorig = lbo + t * (ubo - lbo);
end

function v = check_D(val, grid, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('WFG9_mix: %s must be a real scalar.', name);
end
grid = grid(:);
[dmin, idx] = min(abs(grid - val));
if dmin > 1e-10 * max(1, max(abs(grid)))
    error('WFG9_mix: %s=%g not in grid.', name, val);
end
v = grid(idx);
end

function v = check_K(label, labels, embed, name)
if isstring(label), label = char(label); end
if ~(ischar(label) && isrow(label))
    error('WFG9_mix: %s must be a char vector or scalar string.', name);
end
idx = find(strcmp(label, labels), 1);
if isempty(idx)
    error('WFG9_mix: %s unknown label ''%s''.', name, label);
end
v = embed(idx);
end


% -------------------------------------------------------------------------
% Embedded original continuous MOO problem (top-level function renamed only)
% -------------------------------------------------------------------------
function f = WFG9_orig(z)
% WFG9 function
%
%   As described by Huband et al. in "A review of multiobjective test problems
%   and a scalable test problem toolkit", IEEE Transactions on Evolutionary 
%   Computing 10(5): 477-506, 2006.
%
%   Example WFG9.
%
%   This file is part of a collection of problems developed for
%   derivative-free multiobjective optimization in
%   A. L. Custódio, J. F. A. Madeira, A. I. F. Vaz, and L. N. Vicente,
%   Direct Multisearch for Multiobjective Optimization, 2010.
%
%   Written by the authors in June 1, 2010.
%   Adapted to MATLAB format in November 2025.
%
%   Input: z is a n-dimensional vector where n = k+l (k=4, l=4)
%
%   Problem characteristics:
%   n = 8 (k=4 position-related, l=4 distance-related); M = 3 objectives.
%   Variable z_i has bound [0, 2*i] (z_i in [0, zmax_i], zmax_i = 2*i).
%   Bounds: x1 in [0,2], x2 in [0,4], x3 in [0,6], x4 in [0,8], x5 in [0,10], x6 in [0,12], x7 in [0,14], x8 in [0,16]
%
%   Output: f is a M-dimensional vector (M=3) with the function values
% Parameters
M = 3;      % number of objectives
k = 4;      % number of position-related variables
l = 4;      % number of distance-related variables
n = k + l;  % total number of variables
% Parameters S
S = zeros(M, 1);
for m = 1:M
    S(m) = 2*m;
end
% Parameters A
A = ones(M-1, 1);
% Parameters zmax
zmax = zeros(n, 1);
for i = 1:n
    zmax(i) = 2*i;
end
% Transform z into [0,1] set
y = zeros(n, 1);
for i = 1:n
    y(i) = z(i)/zmax(i);
end
% First level mapping - Similar to WFG7, but applied to first n-1 variables
w = ones(n, 1);  % default weight
AA = 0.98/49.98;
BB = 0.02;
CC = 50;
r_sum = zeros(n-1, 1);
% Calculate r_sum (weighted sum of positions of subsequent variables)
for i = 1:n-1
    sum_numerator = 0;
    sum_denominator = 0;
    for j = i+1:n
        sum_numerator = sum_numerator + w(j)*y(j);
        sum_denominator = sum_denominator + w(j);
    end
    r_sum(i) = sum_numerator / sum_denominator;
end
% Calculate t1
t1 = zeros(n, 1);
for i = 1:n
    if i <= n-1
        t1(i) = y(i)^(BB + (CC-BB)*(AA - (1-2*r_sum(i))*abs(floor(0.5-r_sum(i))+AA)));
    else
        t1(i) = y(i);
    end
end
% Second level mapping - Combines elements from WFG5 (for k) and WFG4 (for l)
AAA = 0.35;
BBB = 0.001;
CCC = 0.05;
AAAA = 30;
BBBB = 95;
CCCC = 0.35;
t2 = zeros(n, 1);
for i = 1:n
    if i <= k
        % For positional variables: deception function (like WFG5)
        t2(i) = 1 + (abs(t1(i)-AAA)-BBB) * ((floor(t1(i)-AAA+BBB)*(1-CCC+(AAA-BBB)/BBB))/(AAA-BBB) + (floor(AAA+BBB-t1(i))*(1-CCC+(1-AAA-BBB)/BBB))/(1-AAA-BBB) + 1/BBB);
    else
        % For distance variables: multimodal function (like WFG4)
        t2(i) = (1 + cos((4*AAAA+2)*pi*(0.5-abs(t1(i)-CCCC)/(2*(floor(CCCC-t1(i))+CCCC)))) + 4*BBBB*(abs(t1(i)-CCCC)/(2*(floor(CCCC-t1(i))+CCCC)))^2) / (BBBB+2);
    end
end
% Third level mapping - Based on WFG6
t3 = zeros(M, 1);
for i = 1:M
    if i <= M-1
        % For position-related variables
        k_per_group = k/(M-1);
        start_idx = floor((i-1)*k_per_group) + 1;
        end_idx = floor(i*k_per_group);
        num_vars = end_idx - start_idx + 1;
        
        sum_val = 0;
        for ii = start_idx:end_idx
            inner_sum = 0;
            for jj = 0:(k_per_group-2)
                % Index calculation with modulo for cyclic pairs
                idx1 = ii;
                tmp = mod(ii + jj - start_idx + 1, num_vars);
                if tmp == 0
                    tmp = num_vars;
                end
                idx2 = start_idx + tmp - 1;
                inner_sum = inner_sum + abs(t2(idx1) - t2(idx2));
            end
            sum_val = sum_val + (t2(ii) + inner_sum);
        end
        
        divisor = (num_vars / k_per_group) * ceil(k_per_group/2) * (1 + 2*k_per_group - 2*ceil(k_per_group/2));
        t3(i) = sum_val / divisor;
    else
        % For distance-related variables
        sum_val = 0;
        for ii = k+1:n
            inner_sum = 0;
            for jj = 0:(l-2)
                % Index calculation with modulo for cyclic pairs
                idx1 = ii;
                tmp = mod(ii + jj - (k+1) + 1, n-k);
                if tmp == 0
                    tmp = n-k;
                end
                idx2 = k + 1 + tmp - 1;
                inner_sum = inner_sum + abs(t2(idx1) - t2(idx2));
            end
            sum_val = sum_val + (t2(ii) + inner_sum);
        end
        
        divisor = ((n-k) / l) * ceil(l/2) * (1 + 2*l - 2*ceil(l/2));
        t3(i) = sum_val / divisor;
    end
end
% Define objective function variables
x = zeros(M, 1);
for i = 1:M
    if i <= M-1
        x(i) = max(t3(M), A(i))*(t3(i)-0.5)+0.5;
    else
        x(i) = t3(M);
    end
end
% Define objective function h
h = zeros(M, 1);
% Compute h[1]
h(1) = 1.0;
for i = 1:M-1
    h(1) = h(1) * sin(x(i)*pi/2);
end
% Compute h[m] for m = 2,...,M-1
for m = 2:M-1
    h(m) = 1.0;
    for i = 1:M-m
        h(m) = h(m) * sin(x(i)*pi/2);
    end
    h(m) = h(m) * cos(x(M-m+1)*pi/2);
end
% Compute h[M]
h(M) = cos(x(1)*pi/2);
% The objective functions
f = zeros(M, 1);
for m = 1:M
    f(m) = x(M) + S(m)*h(m);
end
end

