function varargout = Deb513_mix(varargin)
%DEB513_MIX  Self-contained mixed-variable MOO adaptation of Deb513.
%
% Auto-generated by generate_selfcontained_wrappers_MOO_mix.m
% Source: Deb513, n=2, m=2, strategy=spatial_thermal, kappa=90000
% Variable pattern: C,K
% D variables: nonuniform sorted finite sets with injected anchors.
% K variables: labels with permuted nonuniform numeric embeddings; labels carry no ordinal information.
%
%   x1   C [0,1] -> orig [0,1]
%   x2   K labels {k2_1,...,k2_39}, 39 levels, permuted embedding in [0,1]
%
% Usage:
%   PB = Deb513_mix()
%   F  = PB.func_F(xcell)       % recommended inside benchmark loops
%   F  = Deb513_mix(xcell)              % also valid; PB is memoized persistently
%   PD = Deb513_mix('ProblemData')
%

persistent PB_cached
if isempty(PB_cached)
lb_orig = [0; 0];
ub_orig = [1; 1];
lb_C_work = [0; 0];
ub_C_work = [1; 1];
var_types = {'C', 'K'};
K2_labels = { ...
    'k2_1', 'k2_2', 'k2_3', 'k2_4', 'k2_5', 'k2_6', 'k2_7', 'k2_8', 'k2_9', 'k2_10', ...
    'k2_11', 'k2_12', 'k2_13', 'k2_14', 'k2_15', 'k2_16', 'k2_17', 'k2_18', 'k2_19', 'k2_20', ...
    'k2_21', 'k2_22', 'k2_23', 'k2_24', 'k2_25', 'k2_26', 'k2_27', 'k2_28', 'k2_29', 'k2_30', ...
    'k2_31', 'k2_32', 'k2_33', 'k2_34', 'k2_35', 'k2_36', 'k2_37', 'k2_38', 'k2_39'};
K2_embed  = [ ...
    0.09103882707891367; 0.1450764030702054; 0.5; 0.007692143516783529; 0.02376486419777764; 0.07620499056648354; 0.3660794825723194; 0.9380014416871523; ...
    0.06288605607634637; 0.0001616290305783689; 0; 0.002257409661473449; 0.2996858064080922; 0.2142847958876969; 0.01724863229989811; 1; ...
    0.0008530831378348473; 0.2409049232162137; 0.3319145938801874; 0.5670356699013791; 0.05103425890059982; 0.1254317052296445; 0.2693604333590938; 0.004502599795680177; ...
    0.6134616710990864; 0.4805058100724487; 0.820885670379074; 0.6620325092489989; 0.01191467962467751; 0.1664076855615778; 0.4022123515713952; 0.1074331698339802; ...
    0.7657178460704521; 0.4403443233956707; 0.5227265548210939; 0.7127755991365173; 0.03152836072504208; 0.8783050300476408; 0.04059937688478518; ...
];
ProblemData = { ...
    [0; 1]; ... % x1 C
    K2_labels; ... % x2 K
};
x_anchor = {0.5, 'k2_3'};
anchors_set = [0.5 0 1; 0.5 0 1];

PB = struct();
PB.name = 'Deb513_mix';
PB.problem = 'Deb513';
PB.source = 'MOModels_Matlab';
PB.type = 'MOO_MIXED';
PB.nvar = 2; PB.n = 2; PB.nobj = 2; PB.m = 2;
PB.var_types = var_types;
PB.type_counts = struct('C', 1, 'D', 0, 'K', 1);
PB.ProblemData = ProblemData;
PB.strategy = 'spatial_thermal'; PB.kappa = 90000;
PB.lb_orig = lb_orig; PB.ub_orig = ub_orig;
PB.lb_C_work = lb_C_work; PB.ub_C_work = ub_C_work;
PB.x_anchor = x_anchor;
PB.anchors_set = anchors_set;
PB.K2_labels = K2_labels; PB.K2_embed = K2_embed;
PB.pareto_front_known = true;
PB.pareto_set_known = true;
PB.pf_type = 'disconnected';
PB.ideal_point = [];
PB.nadir_point = [];
PB.core = @(xh) Deb513_orig(xh);
PB.decode = @(xr) decode(xr, PB);
PB.func_F = @(xr) objective(xr, PB);
PB_cached = PB;
else
    PB = PB_cached;
end

if nargin == 0
    varargout{1} = PB; return
end
arg1 = varargin{1};
if ischar(arg1) || (isstring(arg1) && isscalar(arg1))
    key = lower(char(arg1));
    switch key
        case {'problemdata','bounds','domain'}
            varargout{1} = PB.ProblemData; return
        case 'var_types'
            varargout{1} = PB.var_types; return
        case 'info'
            varargout{1} = PB; return
        otherwise
            error('Unknown string argument: %s', char(arg1));
    end
end
varargout{1} = PB.func_F(arg1);
end

function F = objective(xr, PB)
xh = decode(xr, PB);
F = PB.core(xh);
F = F(:);
end

function xh = decode(xr, PB)
if ~iscell(xr) || numel(xr) ~= 2
    error('Deb513_mix: input must be a cell array with exactly 2 entries.');
end
xh = zeros(2,1);
tmp = check_C(xr{1}, PB.lb_C_work(1), PB.ub_C_work(1), 'x1');
xh(1) = map_C_to_orig(tmp, PB.lb_C_work(1), PB.ub_C_work(1), PB.lb_orig(1), PB.ub_orig(1));
xh(2) = check_K(xr{2}, PB.K2_labels, PB.K2_embed, 'x2');
end

function v = check_C(val, a, b, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('Deb513_mix: %s must be a real scalar.', name);
end
if val < a || val > b
    error('Deb513_mix: %s=%g outside [%g,%g].', name, val, a, b);
end
v = double(val);
end

function xorig = map_C_to_orig(xwork, lbw, ubw, lbo, ubo)
if abs(ubw - lbw) <= 1e-14
    t = 0;
else
    t = (xwork - lbw) / (ubw - lbw);
end
t = max(0, min(1, t));
xorig = lbo + t * (ubo - lbo);
end

function v = check_D(val, grid, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('Deb513_mix: %s must be a real scalar.', name);
end
grid = grid(:);
[dmin, idx] = min(abs(grid - val));
if dmin > 1e-10 * max(1, max(abs(grid)))
    error('Deb513_mix: %s=%g not in grid.', name, val);
end
v = grid(idx);
end

function v = check_K(label, labels, embed, name)
if isstring(label), label = char(label); end
if ~(ischar(label) && isrow(label))
    error('Deb513_mix: %s must be a char vector or scalar string.', name);
end
idx = find(strcmp(label, labels), 1);
if isempty(idx)
    error('Deb513_mix: %s unknown label ''%s''.', name, label);
end
v = embed(idx);
end


% -------------------------------------------------------------------------
% Embedded original continuous MOO problem (top-level function renamed only)
% -------------------------------------------------------------------------
function f = Deb513_orig(x)
%###############################################################################
%
%   As described by K. Deb in "Multi-objective Genetic Algorithms: Problem
%   Difficulties and Construction of Test Problems", Evolutionary Computation 
%   7(3): 205-230, 1999.
%
%   Example 5.1.3 (Discontinuous Pareto-optimal Front).
%
%   This file is part of a collection of problems developed for
%   derivative-free multiobjective optimization in
%   A. L. Custódio, J. F. A. Madeira, A. I. F. Vaz, and L. N. Vicente,
%   Direct Multisearch for Multiobjective Optimization, 2010.
%
%   Written by the authors in June 1, 2010.
%
%   MATLAB version by J. F. A. Madeira
%   November 7, 2025
%
%###############################################################################
%
% Problem characteristics:
% - Number of variables: 2
% - Number of objectives: 2
%   Bounds: x1 in [0,1], x2 in [0,1]
%
%
M = 2; % Number of objectives (fixed)
% Check dimension
n = length(x);
if n ~= 2
    error('Deb513 requires exactly 2 variables, %d provided', n);
end
% Ensure x is a column vector
x = x(:);
% Parameters
beta = 1;
alpha = 2;
q = 4;
% Initialize objectives
f = zeros(M, 1);
% Function f1
ff1 = x(1);
% g function
gx = 1 + 10*x(2);
% h function
h = 1 - (ff1/gx)^alpha - (ff1/gx)*sin(2*pi*q*ff1);
% Objective functions
f(1) = ff1;
f(2) = gx * h;
end

