function varargout = DTLZ1_mix(varargin)
%DTLZ1_MIX  Self-contained mixed-variable MOO adaptation of DTLZ1.
%
% Auto-generated by generate_selfcontained_wrappers_MOO_mix.m
% Source: DTLZ1, n=7, m=3, strategy=spatial_thermal, kappa=90000
% Variable pattern: C,K,D,C,D,K,C
% D variables: nonuniform sorted finite sets with injected anchors.
% K variables: labels with permuted nonuniform numeric embeddings; labels carry no ordinal information.
%
%   x1   C [0,1] -> orig [0,1]
%   x2   K labels {k2_1,...,k2_111}, 111 levels, permuted embedding in [0,1]
%   x3   D sorted nonuniform grid [0,...,1], 48 values
%   x4   C [0,300] -> orig [0,1]
%   x5   D sorted nonuniform grid [0,...,1], 103 values
%   x6   K labels {k6_1,...,k6_35}, 35 levels, permuted embedding in [0,1]
%   x7   C [0,300] -> orig [0,1]
%
% Usage:
%   PB = DTLZ1_mix()
%   F  = PB.func_F(xcell)       % recommended inside benchmark loops
%   F  = DTLZ1_mix(xcell)              % also valid; PB is memoized persistently
%   PD = DTLZ1_mix('ProblemData')
%

persistent PB_cached
if isempty(PB_cached)
lb_orig = [0; 0; 0; 0; 0; 0; 0];
ub_orig = [1; 1; 1; 1; 1; 1; 1];
lb_C_work = [0; 0; 0; 0; 0; 0; 0];
ub_C_work = [1; 1; 1; 300; 1; 1; 300];
var_types = {'C', 'K', 'D', 'C', 'D', 'K', 'C'};
K2_labels = { ...
    'k2_1', 'k2_2', 'k2_3', 'k2_4', 'k2_5', 'k2_6', 'k2_7', 'k2_8', 'k2_9', 'k2_10', ...
    'k2_11', 'k2_12', 'k2_13', 'k2_14', 'k2_15', 'k2_16', 'k2_17', 'k2_18', 'k2_19', 'k2_20', ...
    'k2_21', 'k2_22', 'k2_23', 'k2_24', 'k2_25', 'k2_26', 'k2_27', 'k2_28', 'k2_29', 'k2_30', ...
    'k2_31', 'k2_32', 'k2_33', 'k2_34', 'k2_35', 'k2_36', 'k2_37', 'k2_38', 'k2_39', 'k2_40', ...
    'k2_41', 'k2_42', 'k2_43', 'k2_44', 'k2_45', 'k2_46', 'k2_47', 'k2_48', 'k2_49', 'k2_50', ...
    'k2_51', 'k2_52', 'k2_53', 'k2_54', 'k2_55', 'k2_56', 'k2_57', 'k2_58', 'k2_59', 'k2_60', ...
    'k2_61', 'k2_62', 'k2_63', 'k2_64', 'k2_65', 'k2_66', 'k2_67', 'k2_68', 'k2_69', 'k2_70', ...
    'k2_71', 'k2_72', 'k2_73', 'k2_74', 'k2_75', 'k2_76', 'k2_77', 'k2_78', 'k2_79', 'k2_80', ...
    'k2_81', 'k2_82', 'k2_83', 'k2_84', 'k2_85', 'k2_86', 'k2_87', 'k2_88', 'k2_89', 'k2_90', ...
    'k2_91', 'k2_92', 'k2_93', 'k2_94', 'k2_95', 'k2_96', 'k2_97', 'k2_98', 'k2_99', 'k2_100', ...
    'k2_101', 'k2_102', 'k2_103', 'k2_104', 'k2_105', 'k2_106', 'k2_107', 'k2_108', 'k2_109', 'k2_110', ...
    'k2_111'};
K2_embed  = [ ...
    0.4382123389979232; 0.0516437183079097; 0.03435030437059688; 0.0478548127053153; 0.8943589829136296; 0.5235134478374248; 0.0003512380317473215; 0.4248496805467504; ...
    0.2064225835163475; 0.09361357089523016; 0.3265091628277798; 0.3042545503212746; 0.2725771793960552; 0.1978375934159803; 0.08822700461762281; 0.7578794604847833; ...
    0.9783204926323468; 0.2934695194581322; 0.009784654924436885; 0.9569176582149257; 1.260832966501702e-05; 0.7765725275664881; 0.5385958184764241; 0.2334643410396907; ...
    0.06403550842563192; 0.8147584113445503; 0.8740526018430829; 0.04423322117541159; 0.4117277861554913; 6.654716293849005e-05; 0.9357904786173292; 0.6177881565097348; ...
    0.0285570654192142; 0.1366584609309886; 0.0006000474106859476; 0.001853845445819567; 0.1580614560304356; 0.373794080854718; 0.08302571273355284; 0.04077676333427806; ...
    0.02337783892905056; 0.1233889736146269; 0.0001760956252661015; 0.6857477704319422; 0.0009294382823644804; 0.3862012569965104; 0.75; 0.9149379300368918; ...
    0.5695131572900418; 0.07317145540459383; 0.1656020010768847; 0.03137571205993837; 0.3152673135823385; 0.6014417493639227; 0.05560207655106707; 0.00710174119104715; ...
    0.7212876810899516; 0.3988454001733704; 0.01131709514051146; 0.01298110216243332; 0.2829108552290307; 0.4656649221469998; 0.2429121062161926; 0.1813019934178372; ...
    0.1170489679269655; 0.0780078282960661; 0.003981071705534973; 0.5539286634324457; 0.1435913067093436; 0.2624671009387268; 0.252579215732875; 0.8540177454869982; ...
    0.3379814397519426; 0.03748321472739372; 0.7394515401840247; 0.5853504664669779; 0.01879246988592738; 0.834253366481767; 0.3616225855907475; 0.02589193664836417; ...
    0.1733483222357061; 0.215221047181176; 0.349685474431669; 0.06851466797552755; 0.02101222243523014; 0; 0.003167069220955598; 0.4518170074127228; ...
    0.004905604664620412; 0.1507250949164488; 0.0597319862594974; 0.7955318203769981; 0.2242344747042236; 0.5; 0.002459458949895517; 0.703386790892254; ...
    0.1049498564786901; 0.6683695135856287; 0.129924907011408; 0.008380628265711237; 0.508680368609819; 0.005944585819413584; 0.25; 1; ...
    0.6512509071465926; 0.4797573102014058; 0.09918725070977025; 0.1109031749048234; 0.001345528346792431; 0.01671589156406504; 0.4940953894078214; ...
];
D3_vals = [ ...
    0; 0.0009777410646285493; 0.003404692138280543; 0.007063860502953292; 0.01185582663532005; 0.0177161709996338; 0.02459779095956492; 0.0324638727777334; ...
    0.04128438622287625; 0.05103408970977422; 0.06169129057272667; 0.07323702410941181; 0.08565448310275822; 0.09892860608608715; 0.1130457709337181; 0.1279935609899161; ...
    0.1437605827266387; 0.1603363209752357; 0.1777110221765955; 0.1958755989332779; 0.2148215510342083; 0.2345408994094483; 0.2550261303703211; 0.2982662340557781; ...
    0.3210080114692783; 0.3444894150173742; 0.3687046638897229; 0.3936482382583715; 0.4193148584535127; 0.4456994664721933; 0.4727972094884551; 0.5; ...
    0.5006034250898174; 0.5291136280103481; 0.5583234981672783; 0.5882288698380277; 0.6188257218390609; 0.6501101685882591; 0.682078451949323; 0.7147269337707743; ...
    0.7480520890439084; 0.7820504996140026; 0.8167188483874992; 0.8520539139850536; 0.8880525657964553; 0.9247117593986875; 0.9620285323029021; 1; ...
];
D5_vals = [ ...
    0; 0.0002423927862487819; 0.0008440607064311762; 0.001751208874134848; 0.00293919009375914; 0.004392034052382292; 0.006098063487309055; 0.008048151867294509; ...
    0.01023485436702563; 0.01265191331932245; 0.01529395087326865; 0.0181562654701362; 0.0212346904155697; 0.02452549180597715; 0.02802529256626395; 0.03173101447062129; ...
    0.03563983293787183; 0.03974914114181265; 0.04405652106763959; 0.04855971984936901; 0.0532566301909891; 0.05814527399311958; 0.06322378852952415; 0.06849041467622767; ...
    0.07394348681077204; 0.07958142408366559; 0.08540272282723152; 0.09140594991487172; 0.09758973692039906; 0.1039527749554774; 0.1104938100854273; 0.1172116392412074; ...
    0.1241051065593763; 0.1311731000930744; 0.1384145488461686; 0.1458284200901183; 0.1534137169292048; 0.1611694760847954; 0.1690947658734807; 0.1771886843574105; ...
    0.1854503576480757; 0.1938789383472468; 0.2024736041108709; 0.2112335563235036; 0.2201580188723691; 0.2292462370114471; 0.2384974763071005; 0.2479110216577315; ...
    0.2574861763807885; 0.2672222613611777; 0.2771186142557713; 0.2973895538570767; 0.3077628932715855; 0.3182940047480356; 0.3289822995272068; 0.3398272017918958; ...
    0.3508281481546958; 0.3619845871747445; 0.3732959789013283; 0.3847617944424148; 0.3963815155563604; 0.4081546342651809; 0.4200806524879201; 0.4321590816927623; ...
    0.4443894425666549; 0.456771264701299; 0.4693040862944619; 0.4819874538656438; 0.4948209219852075; 0.5; 0.5078040530161452; 0.5209364168677216; ...
    0.5342175907602856; 0.5476471590005934; 0.5612247127670393; 0.5749498499042247; 0.5888221747263394; 0.6028412978288695; 0.6170068359081715; 0.6313184115884865; ...
    0.6457756532560001; 0.6603781948995739; 0.675125675957801; 0.6900177411720592; 0.7050540404452605; 0.7202342287060057; 0.7355579657778785; 0.7510249162536279; ...
    0.7666347493739988; 0.7823871389109897; 0.7982817630553282; 0.8143183043079653; 0.8304964493754016; 0.8468158890686724; 0.8632763182058234; 0.8798774355177197; ...
    0.8966189435570425; 0.9135005486103331; 0.9305219606129493; 0.9476828930668101; 0.9649830629608122; 0.9824221906938024; 1; ...
];
K6_labels = { ...
    'k6_1', 'k6_2', 'k6_3', 'k6_4', 'k6_5', 'k6_6', 'k6_7', 'k6_8', 'k6_9', 'k6_10', ...
    'k6_11', 'k6_12', 'k6_13', 'k6_14', 'k6_15', 'k6_16', 'k6_17', 'k6_18', 'k6_19', 'k6_20', ...
    'k6_21', 'k6_22', 'k6_23', 'k6_24', 'k6_25', 'k6_26', 'k6_27', 'k6_28', 'k6_29', 'k6_30', ...
    'k6_31', 'k6_32', 'k6_33', 'k6_34', 'k6_35'};
K6_embed  = [ ...
    0.001114095932611132; 0.1638093011327097; 0.1403038604693765; 0.000211081707717568; 0.5; 0.8011589050030357; 0.2173224594614802; 0.04117490651006876; ...
    0.09952098015940987; 0.9308593273545517; 0.002948095924704032; 0.5750738678162601; 0.3517750497019375; 0.05302132775556301; 0.2798482456525913; 0.118893437767072; ...
    0.3146131756658163; 0.8645906748111585; 0.005880233585761174; 0.3913788975221543; 0.0225260941591155; 0.0821269301728673; 0.03103605893441732; 0.6826621026317293; ...
    0.6275233266905449; 0.433468536202366; 0.06664890881478067; 0.01004566310718556; 0.2474339233258089; 0; 0.01556014357745721; 0.4780866535251643; ...
    0.7405282152052746; 0.5252748824328543; 1; ...
];
ProblemData = { ...
    [0; 1]; ... % x1 C
    K2_labels; ... % x2 K
    {D3_vals}; ... % x3 D
    [0; 300]; ... % x4 C
    {D5_vals}; ... % x5 D
    K6_labels; ... % x6 K
    [0; 300]; ... % x7 C
};
x_anchor = {0.5, 'k2_94', 0.5, 150, 0.5, 'k6_5', 150};
anchors_set = [ ...
    0.5 0 1 0 0.25 0.75 1; ...
    0.5 0 1 0 0.25 0.75 1; ...
    0.5 0 1 0.5 0.5 0.5 0.5; ...
    0.5 0 1 0.5 0.5 0.5 0.5; ...
    0.5 0 1 0.5 0.5 0.5 0.5; ...
    0.5 0 1 0.5 0.5 0.5 0.5; ...
    0.5 0 1 0.5 0.5 0.5 0.5];

PB = struct();
PB.name = 'DTLZ1_mix';
PB.problem = 'DTLZ1';
PB.source = 'MOModels_Matlab';
PB.type = 'MOO_MIXED';
PB.nvar = 7; PB.n = 7; PB.nobj = 3; PB.m = 3;
PB.var_types = var_types;
PB.type_counts = struct('C', 3, 'D', 2, 'K', 2);
PB.ProblemData = ProblemData;
PB.strategy = 'spatial_thermal'; PB.kappa = 90000;
PB.lb_orig = lb_orig; PB.ub_orig = ub_orig;
PB.lb_C_work = lb_C_work; PB.ub_C_work = ub_C_work;
PB.x_anchor = x_anchor;
PB.anchors_set = anchors_set;
PB.K2_labels = K2_labels; PB.K2_embed = K2_embed;
PB.D3_vals = D3_vals;
PB.D5_vals = D5_vals;
PB.K6_labels = K6_labels; PB.K6_embed = K6_embed;
PB.pareto_front_known = true;
PB.pareto_set_known = true;
PB.pf_type = 'linear';
PB.ideal_point = [0;0;0];
PB.nadir_point = [0.5;0.5;0.5];
PB.core = @(xh) DTLZ1_orig(xh);
PB.decode = @(xr) decode(xr, PB);
PB.func_F = @(xr) objective(xr, PB);
PB_cached = PB;
else
    PB = PB_cached;
end

if nargin == 0
    varargout{1} = PB; return
end
arg1 = varargin{1};
if ischar(arg1) || (isstring(arg1) && isscalar(arg1))
    key = lower(char(arg1));
    switch key
        case {'problemdata','bounds','domain'}
            varargout{1} = PB.ProblemData; return
        case 'var_types'
            varargout{1} = PB.var_types; return
        case 'info'
            varargout{1} = PB; return
        otherwise
            error('Unknown string argument: %s', char(arg1));
    end
end
varargout{1} = PB.func_F(arg1);
end

function F = objective(xr, PB)
xh = decode(xr, PB);
F = PB.core(xh);
F = F(:);
end

function xh = decode(xr, PB)
if ~iscell(xr) || numel(xr) ~= 7
    error('DTLZ1_mix: input must be a cell array with exactly 7 entries.');
end
xh = zeros(7,1);
tmp = check_C(xr{1}, PB.lb_C_work(1), PB.ub_C_work(1), 'x1');
xh(1) = map_C_to_orig(tmp, PB.lb_C_work(1), PB.ub_C_work(1), PB.lb_orig(1), PB.ub_orig(1));
xh(2) = check_K(xr{2}, PB.K2_labels, PB.K2_embed, 'x2');
xh(3) = check_D(xr{3}, PB.D3_vals, 'x3');
tmp = check_C(xr{4}, PB.lb_C_work(4), PB.ub_C_work(4), 'x4');
xh(4) = map_C_to_orig(tmp, PB.lb_C_work(4), PB.ub_C_work(4), PB.lb_orig(4), PB.ub_orig(4));
xh(5) = check_D(xr{5}, PB.D5_vals, 'x5');
xh(6) = check_K(xr{6}, PB.K6_labels, PB.K6_embed, 'x6');
tmp = check_C(xr{7}, PB.lb_C_work(7), PB.ub_C_work(7), 'x7');
xh(7) = map_C_to_orig(tmp, PB.lb_C_work(7), PB.ub_C_work(7), PB.lb_orig(7), PB.ub_orig(7));
end

function v = check_C(val, a, b, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('DTLZ1_mix: %s must be a real scalar.', name);
end
if val < a || val > b
    error('DTLZ1_mix: %s=%g outside [%g,%g].', name, val, a, b);
end
v = double(val);
end

function xorig = map_C_to_orig(xwork, lbw, ubw, lbo, ubo)
if abs(ubw - lbw) <= 1e-14
    t = 0;
else
    t = (xwork - lbw) / (ubw - lbw);
end
t = max(0, min(1, t));
xorig = lbo + t * (ubo - lbo);
end

function v = check_D(val, grid, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('DTLZ1_mix: %s must be a real scalar.', name);
end
grid = grid(:);
[dmin, idx] = min(abs(grid - val));
if dmin > 1e-10 * max(1, max(abs(grid)))
    error('DTLZ1_mix: %s=%g not in grid.', name, val);
end
v = grid(idx);
end

function v = check_K(label, labels, embed, name)
if isstring(label), label = char(label); end
if ~(ischar(label) && isrow(label))
    error('DTLZ1_mix: %s must be a char vector or scalar string.', name);
end
idx = find(strcmp(label, labels), 1);
if isempty(idx)
    error('DTLZ1_mix: %s unknown label ''%s''.', name, label);
end
v = embed(idx);
end


% -------------------------------------------------------------------------
% Embedded original continuous MOO problem (top-level function renamed only)
% -------------------------------------------------------------------------
function f = DTLZ1_orig(x)
%###############################################################################
%
%   As described by K. Deb, L. Thiele, M. Laumanns and E. Zitzler in "Scalable
%   Multi-Objective Optimization Test Problems", Congress on Evolutionary 
%   Computation (CEC'2002): 825-830, 2002.
%
%   Example DTLZ1.
%
%   This file is part of a collection of problems developed for
%   derivative-free multiobjective optimization in
%   A. L. Custódio, J. F. A. Madeira, A. I. F. Vaz, and L. N. Vicente,
%   Direct Multisearch for Multiobjective Optimization, 2010.
%
%   Written by the authors in June 1, 2010.
%
%   CORRECTED MATLAB version by J. F. A. Madeira
%   November 16, 2025
%
%   CORRECTION: Restored multimodal g(x) with cosine term to match the
%   canonical DTLZ1 definition (Deb et al. 2002) and the AMPL .mod source.
%   DTLZ1 and DTLZ3 share the same multimodal g(x); they differ only in the objective functions (DTLZ1 linear simplex, DTLZ3 spherical).
%
%###############################################################################
%
% Problem characteristics:
% - Number of variables: n >= M (default n = 7 for M = 3)
% - Number of objectives: M >= 2 (default M = 3)
%   Bounds: x1 in [0,1], x2 in [0,1], x3 in [0,1], x4 in [0,1], x5 in [0,1], x6 in [0,1], x7 in [0,1]
%
% - Pareto front: Linear simplex with sum(fi) = 0.5, fi in [0, 0.5]
%
% Fixed parameters for DTLZ1
M = 3;  % Number of objectives (fixed)
n = length(x);
% Check minimum dimension
if n < M
    error('DTLZ1 requires n >= M, but n = %d and M = %d', n, M);
end
% Calculate k (number of variables in g function)
k = n - M + 1;
% Ensure x is a column vector
x = x(:);
% Initialize objectives
f = zeros(M, 1);
% Calculate g(x) - MULTIMODAL (canonical DTLZ1, matches AMPL .mod)
% NOTE: DTLZ1 and DTLZ3 share the SAME multimodal g(x) (with cosine term).
% They differ only in the objective functions: DTLZ1 uses linear products of
% x(j) with factor 0.5 (linear simplex front); DTLZ3 uses cos(0.5*pi*x(j))
% (spherical front).
sum_term = 0;
for i = M:n
    sum_term = sum_term + ((x(i)-0.5)^2 - cos(20*pi*(x(i)-0.5)));
end
gx = 100 * (k + sum_term);
% Alternative vectorized implementation:
% gx = 100 * (k + sum((x(M:n) - 0.5).^2));
% Calculate objectives
% f1
prod_term = 1;
for j = 1:(M-1)
    prod_term = prod_term * x(j);
end
f(1) = 0.5 * (1 + gx) * prod_term;
% f2 to fM
for i = 2:M
    prod_term = 1;
    for j = 1:(M-i)
        prod_term = prod_term * x(j);
    end
    f(i) = 0.5 * (1 + gx) * prod_term * (1 - x(M-i+1));
end
end

