function varargout = DTLZ1_4_mix(varargin)
%DTLZ1_4_MIX  Self-contained mixed-variable MOO adaptation of DTLZ1_4.
%
% Auto-generated by generate_selfcontained_wrappers_MOO_mix.m
% Source: DTLZ1_4, n=7, m=4, strategy=spatial_thermal, kappa=90000
% Variable pattern: C,K,D,C,D,K,C
% D variables: nonuniform sorted finite sets with injected anchors.
% K variables: labels with permuted nonuniform numeric embeddings; labels carry no ordinal information.
%
%   x1   C [0,1] -> orig [0,1]
%   x2   K labels {k2_1,...,k2_67}, 67 levels, permuted embedding in [0,1]
%   x3   D sorted nonuniform grid [0,...,1], 111 values
%   x4   C [0,300] -> orig [0,1]
%   x5   D sorted nonuniform grid [0,...,1], 50 values
%   x6   K labels {k6_1,...,k6_104}, 104 levels, permuted embedding in [0,1]
%   x7   C [0,300] -> orig [0,1]
%
% Usage:
%   PB = DTLZ1_4_mix()
%   F  = PB.func_F(xcell)       % recommended inside benchmark loops
%   F  = DTLZ1_4_mix(xcell)              % also valid; PB is memoized persistently
%   PD = DTLZ1_4_mix('ProblemData')
%

persistent PB_cached
if isempty(PB_cached)
lb_orig = [0; 0; 0; 0; 0; 0; 0];
ub_orig = [1; 1; 1; 1; 1; 1; 1];
lb_C_work = [0; 0; 0; 0; 0; 0; 0];
ub_C_work = [1; 1; 1; 300; 1; 1; 300];
var_types = {'C', 'K', 'D', 'C', 'D', 'K', 'C'};
K2_labels = { ...
    'k2_1', 'k2_2', 'k2_3', 'k2_4', 'k2_5', 'k2_6', 'k2_7', 'k2_8', 'k2_9', 'k2_10', ...
    'k2_11', 'k2_12', 'k2_13', 'k2_14', 'k2_15', 'k2_16', 'k2_17', 'k2_18', 'k2_19', 'k2_20', ...
    'k2_21', 'k2_22', 'k2_23', 'k2_24', 'k2_25', 'k2_26', 'k2_27', 'k2_28', 'k2_29', 'k2_30', ...
    'k2_31', 'k2_32', 'k2_33', 'k2_34', 'k2_35', 'k2_36', 'k2_37', 'k2_38', 'k2_39', 'k2_40', ...
    'k2_41', 'k2_42', 'k2_43', 'k2_44', 'k2_45', 'k2_46', 'k2_47', 'k2_48', 'k2_49', 'k2_50', ...
    'k2_51', 'k2_52', 'k2_53', 'k2_54', 'k2_55', 'k2_56', 'k2_57', 'k2_58', 'k2_59', 'k2_60', ...
    'k2_61', 'k2_62', 'k2_63', 'k2_64', 'k2_65', 'k2_66', 'k2_67'};
K2_embed  = [ ...
    4.296299557206924e-05; 0.1170489679269655; 0.1759764298631956; 0.1069130181487709; 0; 0.0285570654192142; 0.5642902928476369; 0.003167069220955598; ...
    0.489288655852483; 0.318989076167365; 0.75; 0.008380628265711237; 0.9640212576468001; 0.03856310243533149; 0.7333676341535037; 0.07159933499747269; ...
    0.07966019425872867; 0.4427202772243738; 0.06403550842563192; 0.05695954930832198; 0.4656649221469998; 0.1507250949164488; 1; 0.03334129875737508; ...
    0.5135971026727086; 0.2829108552290307; 0.377903555740975; 0.3988454001733704; 0.004584899819500306; 0.8606659260533844; 0.25; 0.5385958184764241; ...
    0.764080968675229; 0.02025622909796487; 0.1277243878567133; 0.0006000474106859476; 0.1389471840536253; 0.3006343036255583; 0.8277251643193138; 0.5; ...
    0.01356553727584964; 0.2182015650002369; 0.8943589829136296; 0.0002267600501113848; 0.163065700293766; 0.7955318203769981; 0.3379814397519426; 0.2658123693394165; ...
    0.5906859511535636; 0.00119684671987692; 0.02419924632772747; 0.703386790892254; 0.002044666893495061; 0.9288091652562318; 0.09730845462909581; 0.2334643410396907; ...
    0.2035372749094614; 0.05036202647389178; 0.3576175702078754; 0.6741333607022341; 0.01079181656344869; 0.006316994859440746; 0.4204490259923919; 0.2493323856586503; ...
    0.6456022116492058; 0.08822700461762281; 0.04423322117541159; ...
];
D3_vals = [ ...
    0; 0.0002115890393094667; 0.0007367958294325679; 0.001528661842799653; 0.002565672097387028; 0.00383388581871505; 0.005323109713354117; 0.007025377067408882; ...
    0.008934189158453704; 0.0110440835558304; 0.01335036583638164; 0.01584893192461113; 0.01853614463778999; 0.02140874458406033; 0.0244637838536019; 0.02769857540753147; ...
    0.03111065361794399; 0.03469774293918288; 0.03845773264247045; 0.04238865616041601; 0.04648867399628546; 0.05075605943141685; 0.05518918645844859; 0.05978651950630333; ...
    0.06454660462306602; 0.06946806185667451; 0.07454957862846627; 0.07978990393635996; 0.08518784325643104; 0.09074225403642018; 0.09645204169410679; 0.1023161560488045; ...
    0.108333588126447; 0.1145033672885453; 0.1208245586432391; 0.1272962607031401; 0.1339176032599776; 0.1406877454504416; 0.1476058739912635; 0.1546712015646103; ...
    0.1618829653374247; 0.1692404256004935; 0.176742864514846; 0.1843895849546425; 0.192179909437029; 0.2001131791305781; 0.2081887529349083; 0.2164060066249246; ...
    0.2247643320538494; 0.2332631364098565; 0.2419018415216719; 0.2506798832089921; 0.259596710674; 0.2686517859306299; 0.2778445832685672; 0.2966412997314719; ...
    0.306244224424168; 0.3159828814646624; 0.3258567995202288; 0.3358655169114637; 0.3460085812558797; 0.3562855491303235; 0.3666959857509359; 0.3772394646694748; ...
    0.3879155674849234; 0.3987238835693844; 0.4096640098073516; 0.4207355503475095; 0.431938116366286; 0.4432713258424357; 0.4547348033419911; 0.4663281798129614; ...
    0.4780510923892095; 0.4899031842029747; 0.5; 0.5018841042055489; 0.5139935069956447; 0.5262310526550318; 0.5385964065910392; 0.5510892393855538; ...
    0.5637092266501682; 0.5764560488871513; 0.5893293913559414; 0.6023289439448736; 0.6154544010478789; 0.6287054614459027; 0.6420818281928101; 0.655583208505556; ...
    0.669209313658415; 0.6829598588810747; 0.6968345632604117; 0.7108331496457734; 0.7249553445576082; 0.7392008780992871; 0.7535694838719715; 0.7680608988923949; ...
    0.7826748635134226; 0.7974111213472739; 0.812269419191285; 0.8272495069561094; 0.8423511375962451; 0.8575740670427976; 0.872918054138379; 0.8883828605740601; ...
    0.9039682508282869; 0.9196739921076859; 0.9354998542896787; 0.9514456098668382; 0.9675110338929122; 0.9836959039304548; 1; ...
];
D5_vals = [ ...
    0; 0.0009070830589266053; 0.003158646671619711; 0.006553379442320915; 0.01099904655692787; 0.01643588385941401; 0.02282019266002285; 0.03011781962437861; ...
    0.0383009047034154; 0.04734603043502474; 0.05723307180833016; 0.06794443463524241; 0.07946452629883588; 0.09177937377316214; 0.1048763393570154; 0.1187439037039419; ...
    0.1333714966572378; 0.1487493629435599; 0.1648684538601849; 0.1817203387248328; 0.1992971316076374; 0.2175914300587795; 0.2365962633781879; 0.256305048566504; ...
    0.2978098593967938; 0.3195943421487674; 0.3420596377310325; 0.3652006252147411; 0.3890124064737812; 0.4134902890297895; 0.4386297707539575; 0.464426526170422; ...
    0.4908763941480936; 0.5; 0.5179753668018229; 0.5457195794515658; 0.57410530151098; 0.6031289281956891; 0.6327869729570627; 0.6630760605603971; ...
    0.6939929207373221; 0.7255343823514764; 0.7576973680243188; 0.7904788891745821; 0.8238760414305585; 0.8578860003792792; 0.8925060176208421; 0.9277334170997639; ...
    0.9635655916883741; 1; ...
];
K6_labels = { ...
    'k6_1', 'k6_2', 'k6_3', 'k6_4', 'k6_5', 'k6_6', 'k6_7', 'k6_8', 'k6_9', 'k6_10', ...
    'k6_11', 'k6_12', 'k6_13', 'k6_14', 'k6_15', 'k6_16', 'k6_17', 'k6_18', 'k6_19', 'k6_20', ...
    'k6_21', 'k6_22', 'k6_23', 'k6_24', 'k6_25', 'k6_26', 'k6_27', 'k6_28', 'k6_29', 'k6_30', ...
    'k6_31', 'k6_32', 'k6_33', 'k6_34', 'k6_35', 'k6_36', 'k6_37', 'k6_38', 'k6_39', 'k6_40', ...
    'k6_41', 'k6_42', 'k6_43', 'k6_44', 'k6_45', 'k6_46', 'k6_47', 'k6_48', 'k6_49', 'k6_50', ...
    'k6_51', 'k6_52', 'k6_53', 'k6_54', 'k6_55', 'k6_56', 'k6_57', 'k6_58', 'k6_59', 'k6_60', ...
    'k6_61', 'k6_62', 'k6_63', 'k6_64', 'k6_65', 'k6_66', 'k6_67', 'k6_68', 'k6_69', 'k6_70', ...
    'k6_71', 'k6_72', 'k6_73', 'k6_74', 'k6_75', 'k6_76', 'k6_77', 'k6_78', 'k6_79', 'k6_80', ...
    'k6_81', 'k6_82', 'k6_83', 'k6_84', 'k6_85', 'k6_86', 'k6_87', 'k6_88', 'k6_89', 'k6_90', ...
    'k6_91', 'k6_92', 'k6_93', 'k6_94', 'k6_95', 'k6_96', 'k6_97', 'k6_98', 'k6_99', 'k6_100', ...
    'k6_101', 'k6_102', 'k6_103', 'k6_104'};
K6_embed  = [ ...
    0.2844344950673987; 0.4234368518707239; 0.0246039646673244; 0.6668633764340348; 0.06047148151290486; 0.0007026170285768178; 0.8236208142152271; 0.865850322304904; ...
    0.6130006672623584; 0.529048734408999; 0.0802262814064332; 0.5785540078281004; 0.2520100411478541; 0.1521337322297902; 0.3562625623754169; 0.001575527386758402; ...
    0.7042497097305097; 0.3823212861245524; 0.4821068277927952; 0.04022200305803815; 0.3191703929297392; 0.2029797661134726; 0.1033081631896442; 0.9540298379630736; ...
    0.0002061966817395395; 0.3312704644886538; 0.144480573461931; 0.4670223801332506; 7.792245921136212e-05; 0.3436339830278154; 0.4522168995168615; 1.476354529123654e-05; ...
    0.002170734104315858; 0.0438904401289919; 0.08567908078170938; 0; 0.1298605040596453; 0.1681362096609147; 0.9768571799477533; 0.4094592603954185; ...
    0.01520003797465699; 0.1939093209151658; 0.2218508594405832; 0.01145720329131715; 0.2417076045634582; 0.0477469742868462; 0.006960728686057599; 0.05179426470838482; ...
    0.03031779700736718; 0.5956320829372783; 0.5; 0.1228895500512616; 0.09134216321416441; 0.5452637543046104; 0.1161419083314356; 0.68540784961463; ...
    0.561765036776639; 0.01325159248776261; 0.4376888920985644; 0.2316551318300356; 0.01957323680028792; 0.3691578017533576; 0.90931661744763; 0.02200477681551112; ...
    0.6486149337758449; 0.5131185403507458; 0.00466157960601251; 0.8874282349397875; 0.8445816084051534; 0.001088312610921773; 0.8029666526904534; 0.002879868671221845; ...
    0.6306611558396756; 0.07498147288393417; 0.2625641866216203; 0.0651064651114016; 0.05603491608716679; 0.7428309704978747; 0.09721778402415746; 0.009813178133590466; ...
    0.2122930048888515; 0.03343849184647765; 0.2957540602260476; 0.02737394984189644; 0.008315683401868224; 0.497471724436455; 0.3957545865270176; 0.2733717680615164; ...
    0.7625730385440892; 0.000411277205425082; 0.01730610375057571; 0.005744148398020727; 0.06994232447176567; 0.7233903039771674; 0.003708434909803423; 0.1600182919537111; ...
    0.03673894626398726; 0.1764894180629687; 0.931516733207167; 0.7826178286312955; 0.1096154867857548; 1; 0.1370568334738982; 0.3073321395553163; ...
];
ProblemData = { ...
    [0; 1]; ... % x1 C
    K2_labels; ... % x2 K
    {D3_vals}; ... % x3 D
    [0; 300]; ... % x4 C
    {D5_vals}; ... % x5 D
    K6_labels; ... % x6 K
    [0; 300]; ... % x7 C
};
x_anchor = {0.5, 'k2_40', 0.5, 150, 0.5, 'k6_51', 150};
anchors_set = [ ...
    0.5 0 1 0 0.25 0.75 1; ...
    0.5 0 1 0 0.25 0.75 1; ...
    0.5 0 1 0.5 0.5 0.5 0.5; ...
    0.5 0 1 0.5 0.5 0.5 0.5; ...
    0.5 0 1 0.5 0.5 0.5 0.5; ...
    0.5 0 1 0.5 0.5 0.5 0.5; ...
    0.5 0 1 0.5 0.5 0.5 0.5];

PB = struct();
PB.name = 'DTLZ1_4_mix';
PB.problem = 'DTLZ1_4';
PB.source = 'MOModels_Matlab';
PB.type = 'MOO_MIXED';
PB.nvar = 7; PB.n = 7; PB.nobj = 4; PB.m = 4;
PB.var_types = var_types;
PB.type_counts = struct('C', 3, 'D', 2, 'K', 2);
PB.ProblemData = ProblemData;
PB.strategy = 'spatial_thermal'; PB.kappa = 90000;
PB.lb_orig = lb_orig; PB.ub_orig = ub_orig;
PB.lb_C_work = lb_C_work; PB.ub_C_work = ub_C_work;
PB.x_anchor = x_anchor;
PB.anchors_set = anchors_set;
PB.K2_labels = K2_labels; PB.K2_embed = K2_embed;
PB.D3_vals = D3_vals;
PB.D5_vals = D5_vals;
PB.K6_labels = K6_labels; PB.K6_embed = K6_embed;
PB.pareto_front_known = true;
PB.pareto_set_known = true;
PB.pf_type = 'simplex';
PB.ideal_point = [0;0;0;0];
PB.nadir_point = [0.5;0.5;0.5;0.5];
PB.core = @(xh) DTLZ1_4_orig(xh);
PB.decode = @(xr) decode(xr, PB);
PB.func_F = @(xr) objective(xr, PB);
PB_cached = PB;
else
    PB = PB_cached;
end

if nargin == 0
    varargout{1} = PB; return
end
arg1 = varargin{1};
if ischar(arg1) || (isstring(arg1) && isscalar(arg1))
    key = lower(char(arg1));
    switch key
        case {'problemdata','bounds','domain'}
            varargout{1} = PB.ProblemData; return
        case 'var_types'
            varargout{1} = PB.var_types; return
        case 'info'
            varargout{1} = PB; return
        otherwise
            error('Unknown string argument: %s', char(arg1));
    end
end
varargout{1} = PB.func_F(arg1);
end

function F = objective(xr, PB)
xh = decode(xr, PB);
F = PB.core(xh);
F = F(:);
end

function xh = decode(xr, PB)
if ~iscell(xr) || numel(xr) ~= 7
    error('DTLZ1_4_mix: input must be a cell array with exactly 7 entries.');
end
xh = zeros(7,1);
tmp = check_C(xr{1}, PB.lb_C_work(1), PB.ub_C_work(1), 'x1');
xh(1) = map_C_to_orig(tmp, PB.lb_C_work(1), PB.ub_C_work(1), PB.lb_orig(1), PB.ub_orig(1));
xh(2) = check_K(xr{2}, PB.K2_labels, PB.K2_embed, 'x2');
xh(3) = check_D(xr{3}, PB.D3_vals, 'x3');
tmp = check_C(xr{4}, PB.lb_C_work(4), PB.ub_C_work(4), 'x4');
xh(4) = map_C_to_orig(tmp, PB.lb_C_work(4), PB.ub_C_work(4), PB.lb_orig(4), PB.ub_orig(4));
xh(5) = check_D(xr{5}, PB.D5_vals, 'x5');
xh(6) = check_K(xr{6}, PB.K6_labels, PB.K6_embed, 'x6');
tmp = check_C(xr{7}, PB.lb_C_work(7), PB.ub_C_work(7), 'x7');
xh(7) = map_C_to_orig(tmp, PB.lb_C_work(7), PB.ub_C_work(7), PB.lb_orig(7), PB.ub_orig(7));
end

function v = check_C(val, a, b, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('DTLZ1_4_mix: %s must be a real scalar.', name);
end
if val < a || val > b
    error('DTLZ1_4_mix: %s=%g outside [%g,%g].', name, val, a, b);
end
v = double(val);
end

function xorig = map_C_to_orig(xwork, lbw, ubw, lbo, ubo)
if abs(ubw - lbw) <= 1e-14
    t = 0;
else
    t = (xwork - lbw) / (ubw - lbw);
end
t = max(0, min(1, t));
xorig = lbo + t * (ubo - lbo);
end

function v = check_D(val, grid, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('DTLZ1_4_mix: %s must be a real scalar.', name);
end
grid = grid(:);
[dmin, idx] = min(abs(grid - val));
if dmin > 1e-10 * max(1, max(abs(grid)))
    error('DTLZ1_4_mix: %s=%g not in grid.', name, val);
end
v = grid(idx);
end

function v = check_K(label, labels, embed, name)
if isstring(label), label = char(label); end
if ~(ischar(label) && isrow(label))
    error('DTLZ1_4_mix: %s must be a char vector or scalar string.', name);
end
idx = find(strcmp(label, labels), 1);
if isempty(idx)
    error('DTLZ1_4_mix: %s unknown label ''%s''.', name, label);
end
v = embed(idx);
end


% -------------------------------------------------------------------------
% Embedded original continuous MOO problem (top-level function renamed only)
% -------------------------------------------------------------------------
function f = DTLZ1_4_orig(x)
%###############################################################################
%
%   As described by K. Deb, L. Thiele, M. Laumanns and E. Zitzler in "Scalable
%   Multi-Objective Optimization Test Problems", Congress on Evolutionary 
%   Computation (CEC'2002): 825-830, 2002.
%
%   Example DTLZ1 with M = 4 objectives.
%
%   This file is part of a collection of problems developed for
%   derivative-free multiobjective optimization in
%   A. L. Custódio, J. F. A. Madeira, A. I. F. Vaz, and L. N. Vicente,
%   Direct Multisearch for Multiobjective Optimization, 2010.
%
%   Written by the authors in June 1, 2010.
%
%   MATLAB version by J. F. A. Madeira
%   November 16, 2025
%   DTLZ1 and DTLZ3 share the same multimodal g(x); they differ only in the objective functions (DTLZ1 linear simplex, DTLZ3 spherical).
%
%   This file is part of a collection of problems developed for
%   derivative-free multiobjective optimization.
%
%###############################################################################
%
% Problem characteristics:
% - Number of variables: n >= 4 (recommended n = 13, i.e., k = 10)
% - Number of objectives: M = 4 (fixed)
%   Bounds: x1 in [0,1], x2 in [0,1], x3 in [0,1], x4 in [0,1], x5 in [0,1], x6 in [0,1], x7 in [0,1]
%
% - Pareto front: Linear simplex with sum(fi) = 0.5, fi in [0, 0.5]
%
% Get dimension
n = length(x);
% Fixed parameters
M = 4;  % Number of objectives (fixed for DTLZ1_4)
k = n - M + 1;  % Calculate k from dimension
% Check minimum dimension
if n < M
    error('DTLZ1_4 requires n >= M, but n = %d and M = %d', n, M);
end
% Ensure x is a column vector
x = x(:);
% Initialize objectives
f = zeros(M, 1);
% Calculate g(x) - MULTIMODAL (canonical DTLZ1, matches AMPL .mod)
% NOTE: DTLZ1 and DTLZ3 share the SAME multimodal g(x) (with cosine term).
% They differ only in the objective functions: DTLZ1 uses linear products of
% x(j) with factor 0.5 (linear simplex front); DTLZ3 uses cos(0.5*pi*x(j))
% (spherical front).
sum_term = 0;
for i = M:n
    sum_term = sum_term + ((x(i)-0.5)^2 - cos(20*pi*(x(i)-0.5)));
end
gx = 100 * (k + sum_term);
% Alternative vectorized implementation:
% gx = 100 * (k + sum((x(M:n) - 0.5).^2));
% Calculate objectives
% f1
prod_term = 1;
for j = 1:(M-1)
    prod_term = prod_term * x(j);
end
f(1) = 0.5 * (1 + gx) * prod_term;
% f2 to fM
for i = 2:M
    prod_term = 1;
    for j = 1:(M-i)
        prod_term = prod_term * x(j);
    end
    f(i) = 0.5 * (1 + gx) * prod_term * (1 - x(M-i+1));
end
end

