function varargout = DTLZ4n2_mix(varargin)
%DTLZ4N2_MIX  Self-contained mixed-variable MOO adaptation of DTLZ4n2.
%
% Auto-generated by generate_selfcontained_wrappers_MOO_mix.m
% Source: DTLZ4n2, n=2, m=2, strategy=spatial_thermal, kappa=90000
% Variable pattern: C,K
% D variables: nonuniform sorted finite sets with injected anchors.
% K variables: labels with permuted nonuniform numeric embeddings; labels carry no ordinal information.
%
%   x1   C [0,1] -> orig [0,1]
%   x2   K labels {k2_1,...,k2_37}, 37 levels, permuted embedding in [0,1]
%
% Usage:
%   PB = DTLZ4n2_mix()
%   F  = PB.func_F(xcell)       % recommended inside benchmark loops
%   F  = DTLZ4n2_mix(xcell)              % also valid; PB is memoized persistently
%   PD = DTLZ4n2_mix('ProblemData')
%

persistent PB_cached
if isempty(PB_cached)
lb_orig = [0; 0];
ub_orig = [1; 1];
lb_C_work = [0; 0];
ub_C_work = [1; 1];
var_types = {'C', 'K'};
K2_labels = { ...
    'k2_1', 'k2_2', 'k2_3', 'k2_4', 'k2_5', 'k2_6', 'k2_7', 'k2_8', 'k2_9', 'k2_10', ...
    'k2_11', 'k2_12', 'k2_13', 'k2_14', 'k2_15', 'k2_16', 'k2_17', 'k2_18', 'k2_19', 'k2_20', ...
    'k2_21', 'k2_22', 'k2_23', 'k2_24', 'k2_25', 'k2_26', 'k2_27', 'k2_28', 'k2_29', 'k2_30', ...
    'k2_31', 'k2_32', 'k2_33', 'k2_34', 'k2_35', 'k2_36', 'k2_37'};
K2_embed  = [ ...
    0.02705764328423417; 0.1428110974416723; 0.04622468902698076; 0; 0.5470830675379204; 0.4579415326240115; 0.00875794086749827; 0.002570188697827454; ...
    0.2157161399878615; 0.5; 0.03589682359365735; 0.377903555740975; 0.1223187459465567; 0.3066821026226881; 0.005126464772080319; 0.7537614912817806; ...
    0.01356553727584964; 0.8115353718261809; 0.9346248083476736; 0.2439753713764724; 0.3412092566426912; 0.0009712834478342614; 0.75; 0.1036528585905691; ...
    0.07159933499747269; 0.5013569413029385; 0.8718131171683238; 1; 0.6984608423178577; 0.000184023801582466; 0.6456022116492058; 0.1651776980741374; ...
    0.25; 0.4168022156863458; 0.0581053929496813; 0.2742838933794407; 0.08676369593642203; ...
];
ProblemData = { ...
    [0; 1]; ... % x1 C
    K2_labels; ... % x2 K
};
x_anchor = {0.5, 'k2_10'};
anchors_set = [0.5 0 1 0.25 0.75; 0.5 0 1 0.25 0.75];

PB = struct();
PB.name = 'DTLZ4n2_mix';
PB.problem = 'DTLZ4n2';
PB.source = 'MOModels_Matlab';
PB.type = 'MOO_MIXED';
PB.nvar = 2; PB.n = 2; PB.nobj = 2; PB.m = 2;
PB.var_types = var_types;
PB.type_counts = struct('C', 1, 'D', 0, 'K', 1);
PB.ProblemData = ProblemData;
PB.strategy = 'spatial_thermal'; PB.kappa = 90000;
PB.lb_orig = lb_orig; PB.ub_orig = ub_orig;
PB.lb_C_work = lb_C_work; PB.ub_C_work = ub_C_work;
PB.x_anchor = x_anchor;
PB.anchors_set = anchors_set;
PB.K2_labels = K2_labels; PB.K2_embed = K2_embed;
PB.pareto_front_known = true;
PB.pareto_set_known = true;
PB.pf_type = 'convex';
PB.ideal_point = [0;0];
PB.nadir_point = [1;1];
PB.core = @(xh) DTLZ4n2_orig(xh);
PB.decode = @(xr) decode(xr, PB);
PB.func_F = @(xr) objective(xr, PB);
PB_cached = PB;
else
    PB = PB_cached;
end

if nargin == 0
    varargout{1} = PB; return
end
arg1 = varargin{1};
if ischar(arg1) || (isstring(arg1) && isscalar(arg1))
    key = lower(char(arg1));
    switch key
        case {'problemdata','bounds','domain'}
            varargout{1} = PB.ProblemData; return
        case 'var_types'
            varargout{1} = PB.var_types; return
        case 'info'
            varargout{1} = PB; return
        otherwise
            error('Unknown string argument: %s', char(arg1));
    end
end
varargout{1} = PB.func_F(arg1);
end

function F = objective(xr, PB)
xh = decode(xr, PB);
F = PB.core(xh);
F = F(:);
end

function xh = decode(xr, PB)
if ~iscell(xr) || numel(xr) ~= 2
    error('DTLZ4n2_mix: input must be a cell array with exactly 2 entries.');
end
xh = zeros(2,1);
tmp = check_C(xr{1}, PB.lb_C_work(1), PB.ub_C_work(1), 'x1');
xh(1) = map_C_to_orig(tmp, PB.lb_C_work(1), PB.ub_C_work(1), PB.lb_orig(1), PB.ub_orig(1));
xh(2) = check_K(xr{2}, PB.K2_labels, PB.K2_embed, 'x2');
end

function v = check_C(val, a, b, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('DTLZ4n2_mix: %s must be a real scalar.', name);
end
if val < a || val > b
    error('DTLZ4n2_mix: %s=%g outside [%g,%g].', name, val, a, b);
end
v = double(val);
end

function xorig = map_C_to_orig(xwork, lbw, ubw, lbo, ubo)
if abs(ubw - lbw) <= 1e-14
    t = 0;
else
    t = (xwork - lbw) / (ubw - lbw);
end
t = max(0, min(1, t));
xorig = lbo + t * (ubo - lbo);
end

function v = check_D(val, grid, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('DTLZ4n2_mix: %s must be a real scalar.', name);
end
grid = grid(:);
[dmin, idx] = min(abs(grid - val));
if dmin > 1e-10 * max(1, max(abs(grid)))
    error('DTLZ4n2_mix: %s=%g not in grid.', name, val);
end
v = grid(idx);
end

function v = check_K(label, labels, embed, name)
if isstring(label), label = char(label); end
if ~(ischar(label) && isrow(label))
    error('DTLZ4n2_mix: %s must be a char vector or scalar string.', name);
end
idx = find(strcmp(label, labels), 1);
if isempty(idx)
    error('DTLZ4n2_mix: %s unknown label ''%s''.', name, label);
end
v = embed(idx);
end


% -------------------------------------------------------------------------
% Embedded original continuous MOO problem (top-level function renamed only)
% -------------------------------------------------------------------------
function f = DTLZ4n2_orig(x)
%###############################################################################
%
%   As described by K. Deb, L. Thiele, M. Laumanns and E. Zitzler in "Scalable
%   Multi-Objective Optimization Test Problems", Congress on Evolutionary 
%   Computation (CEC'2002): 825-830, 2002.
%
%   Example DTLZ4 with M=2 and n=2.
%
%   This file is part of a collection of problems developed for
%   derivative-free multiobjective optimization in
%   A. L. Custódio, J. F. A. Madeira, A. I. F. Vaz, and L. N. Vicente,
%   Direct Multisearch for Multiobjective Optimization, 2010.
%
%   Written by the authors in June 1, 2010.
%
%   MATLAB version by J. F. A. Madeira
%   November 7, 2025
%
%###############################################################################
%
% Problem characteristics:
% - Number of variables: 2 (fixed)
% - Number of objectives: 2 (fixed)
%   Bounds: x1 in [0,1], x2 in [0,1]
%
%
n = length(x);
if n ~= 2
    error('DTLZ4n2 requires exactly 2 variables, %d provided', n);
end
% Fixed parameters for this problem
M = 2;  % Number of objectives (fixed for DTLZ4n2)
k = n - M + 1;  % k = 2 - 2 + 1 = 1
alpha = 100;
x = x(:);
f = zeros(M, 1);
% Transform variables
y = x.^alpha;
% Calculate g(x)
gx = 0;
for i = M:n
    gx = gx + (y(i) - 0.5)^2;
end
% Calculate objectives
f(1) = (1 + gx) * cos(0.5*pi*y(1));
f(2) = (1 + gx) * sin(0.5*pi*y(1));
end

