function varargout = LE1_mix(varargin)
%LE1_MIX  Self-contained mixed-variable MOO adaptation of LE1.
%
% Auto-generated by generate_selfcontained_wrappers_MOO_mix.m
% Source: LE1, n=2, m=2, strategy=spatial_thermal, kappa=90000
% Variable pattern: C,K
% D variables: nonuniform sorted finite sets with injected anchors.
% K variables: labels with permuted nonuniform numeric embeddings; labels carry no ordinal information.
%
%   x1   C [-5,10] -> orig [-5,10]
%   x2   K labels {k2_1,...,k2_99}, 99 levels, permuted embedding in [-5,10]
%
% Usage:
%   PB = LE1_mix()
%   F  = PB.func_F(xcell)       % recommended inside benchmark loops
%   F  = LE1_mix(xcell)              % also valid; PB is memoized persistently
%   PD = LE1_mix('ProblemData')
%

persistent PB_cached
if isempty(PB_cached)
lb_orig = [-5; -5];
ub_orig = [10; 10];
lb_C_work = [-5; -5];
ub_C_work = [10; 10];
var_types = {'C', 'K'};
K2_labels = { ...
    'k2_1', 'k2_2', 'k2_3', 'k2_4', 'k2_5', 'k2_6', 'k2_7', 'k2_8', 'k2_9', 'k2_10', ...
    'k2_11', 'k2_12', 'k2_13', 'k2_14', 'k2_15', 'k2_16', 'k2_17', 'k2_18', 'k2_19', 'k2_20', ...
    'k2_21', 'k2_22', 'k2_23', 'k2_24', 'k2_25', 'k2_26', 'k2_27', 'k2_28', 'k2_29', 'k2_30', ...
    'k2_31', 'k2_32', 'k2_33', 'k2_34', 'k2_35', 'k2_36', 'k2_37', 'k2_38', 'k2_39', 'k2_40', ...
    'k2_41', 'k2_42', 'k2_43', 'k2_44', 'k2_45', 'k2_46', 'k2_47', 'k2_48', 'k2_49', 'k2_50', ...
    'k2_51', 'k2_52', 'k2_53', 'k2_54', 'k2_55', 'k2_56', 'k2_57', 'k2_58', 'k2_59', 'k2_60', ...
    'k2_61', 'k2_62', 'k2_63', 'k2_64', 'k2_65', 'k2_66', 'k2_67', 'k2_68', 'k2_69', 'k2_70', ...
    'k2_71', 'k2_72', 'k2_73', 'k2_74', 'k2_75', 'k2_76', 'k2_77', 'k2_78', 'k2_79', 'k2_80', ...
    'k2_81', 'k2_82', 'k2_83', 'k2_84', 'k2_85', 'k2_86', 'k2_87', 'k2_88', 'k2_89', 'k2_90', ...
    'k2_91', 'k2_92', 'k2_93', 'k2_94', 'k2_95', 'k2_96', 'k2_97', 'k2_98', 'k2_99'};
K2_embed  = [ ...
    -3.253805336777677; -3.456063944927974; -4.996514703832583; -3.732605016409777; -4.806341467846785; -4.999750455112144; 6.271841770043784; 8.921477508619784; ...
    7.555904938300891; 4.21647068748506; -2.804997086860949; -2.683359148193021; -0.9144706853981566; -4.320136522463129; -4.743077174420391; -1.250104785279298; ...
    3.67312736086588; 3.942391850619256; 0.808367981177617; -4.192943625068129; 0.1947660800341069; -4.921206367639484; -4.99304827383389; -4.58412471512707; ...
    -1.411659052578111; -0.7403309153508086; -4.973369214691507; -4.62805820320213; 7.227303721515858; -1.084385372653483; -4.258129755157555; -3.036879427112505; ...
    -2.557877339708475; -3.643953196758329; 0.3948654160986056; -0.5619365665196216; -4.834130055582642; 3.148943353580128; -3.977864139340666; -0.1922676583527148; ...
    10; -1.722394330934444; -3.551785754469666; 5.963392445246917; -4.379009848613618; 8.5723648585218; 9.635273392506814; -4.707478817961827; ...
    3.408652748188851; -4.052854407585384; 6.903774558935917; -3.356749646960122; 6.585294832226101; -4.48754509130379; -5; 4.495388156340695; ...
    2.5; -2.295246776243799; 2.643720613885097; -4.124533184727341; 1.689350827684725; -4.981604496542828; 7.88960067732965; -2.428517717151869; ...
    -3.817780609439738; 1.462290770202276; -4.882344367487982; -4.96330856932116; 5.659923772018585; -4.998682894185523; -4.434796687834485; -0.3792584465142994; ...
    -4.776011310559748; -3.899520053317566; -0.0009355926209391185; 9.275773101739185; 1.239791352453504; -4.988123822283649; -4.951322227119291; -4.859441872461398; ...
    -1.871637293165385; 2.893974325117202; 4.779168360594632; -4.937317158214122; -2.016839033610245; 2.157257937022721; -2.922825555698038; -3.147194063644048; ...
    1.021826019535926; 5.067835225758154; 5.361412502904262; 1.920997849868963; -4.537304278293211; -4.669157977575235; -4.902907950662447; 8.228413258978568; ...
    0.5993902060902512; -1.569078634388194; 2.398156969756465; ...
];
ProblemData = { ...
    [-5; 10]; ... % x1 C
    K2_labels; ... % x2 K
};
x_anchor = {2.5, 'k2_57'};
anchors_set = [2.5 -5 10; 2.5 -5 10];

PB = struct();
PB.name = 'LE1_mix';
PB.problem = 'LE1';
PB.source = 'MOModels_Matlab';
PB.type = 'MOO_MIXED';
PB.nvar = 2; PB.n = 2; PB.nobj = 2; PB.m = 2;
PB.var_types = var_types;
PB.type_counts = struct('C', 1, 'D', 0, 'K', 1);
PB.ProblemData = ProblemData;
PB.strategy = 'spatial_thermal'; PB.kappa = 90000;
PB.lb_orig = lb_orig; PB.ub_orig = ub_orig;
PB.lb_C_work = lb_C_work; PB.ub_C_work = ub_C_work;
PB.x_anchor = x_anchor;
PB.anchors_set = anchors_set;
PB.K2_labels = K2_labels; PB.K2_embed = K2_embed;
PB.pareto_front_known = false;
PB.pareto_set_known = false;
PB.pf_type = 'unknown';
PB.ideal_point = [];
PB.nadir_point = [];
PB.core = @(xh) LE1_orig(xh);
PB.decode = @(xr) decode(xr, PB);
PB.func_F = @(xr) objective(xr, PB);
PB_cached = PB;
else
    PB = PB_cached;
end

if nargin == 0
    varargout{1} = PB; return
end
arg1 = varargin{1};
if ischar(arg1) || (isstring(arg1) && isscalar(arg1))
    key = lower(char(arg1));
    switch key
        case {'problemdata','bounds','domain'}
            varargout{1} = PB.ProblemData; return
        case 'var_types'
            varargout{1} = PB.var_types; return
        case 'info'
            varargout{1} = PB; return
        otherwise
            error('Unknown string argument: %s', char(arg1));
    end
end
varargout{1} = PB.func_F(arg1);
end

function F = objective(xr, PB)
xh = decode(xr, PB);
F = PB.core(xh);
F = F(:);
end

function xh = decode(xr, PB)
if ~iscell(xr) || numel(xr) ~= 2
    error('LE1_mix: input must be a cell array with exactly 2 entries.');
end
xh = zeros(2,1);
tmp = check_C(xr{1}, PB.lb_C_work(1), PB.ub_C_work(1), 'x1');
xh(1) = map_C_to_orig(tmp, PB.lb_C_work(1), PB.ub_C_work(1), PB.lb_orig(1), PB.ub_orig(1));
xh(2) = check_K(xr{2}, PB.K2_labels, PB.K2_embed, 'x2');
end

function v = check_C(val, a, b, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('LE1_mix: %s must be a real scalar.', name);
end
if val < a || val > b
    error('LE1_mix: %s=%g outside [%g,%g].', name, val, a, b);
end
v = double(val);
end

function xorig = map_C_to_orig(xwork, lbw, ubw, lbo, ubo)
if abs(ubw - lbw) <= 1e-14
    t = 0;
else
    t = (xwork - lbw) / (ubw - lbw);
end
t = max(0, min(1, t));
xorig = lbo + t * (ubo - lbo);
end

function v = check_D(val, grid, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('LE1_mix: %s must be a real scalar.', name);
end
grid = grid(:);
[dmin, idx] = min(abs(grid - val));
if dmin > 1e-10 * max(1, max(abs(grid)))
    error('LE1_mix: %s=%g not in grid.', name, val);
end
v = grid(idx);
end

function v = check_K(label, labels, embed, name)
if isstring(label), label = char(label); end
if ~(ischar(label) && isrow(label))
    error('LE1_mix: %s must be a char vector or scalar string.', name);
end
idx = find(strcmp(label, labels), 1);
if isempty(idx)
    error('LE1_mix: %s unknown label ''%s''.', name, label);
end
v = embed(idx);
end


% -------------------------------------------------------------------------
% Embedded original continuous MOO problem (top-level function renamed only)
% -------------------------------------------------------------------------
function f = LE1_orig(x)
% LE1 function
%
%   As described by Huband et al. in "A review of multiobjective test problems
%   and a scalable test problem toolkit", IEEE Transactions on Evolutionary 
%   Computing 10(5): 477-506, 2006.
%
%   Example LE1, see the previous cited paper for the original reference.
%
%   This file is part of a collection of problems developed for
%   derivative-free multiobjective optimization in
%   A. L. Custódio, J. F. A. Madeira, A. I. F. Vaz, and L. N. Vicente,
%   Direct Multisearch for Multiobjective Optimization, 2010.
%
%   Written by the authors in June 1, 2010.
%   Adapted to MATLAB format in November 2025.
%
% Problem characteristics:
% - Number of variables: 2
% - Number of objectives: 2
%   Bounds: x1 in [-5,10], x2 in [-5,10]
%
%
%   Input: x is a 2-dimensional vector
%   Output: f is a 2-dimensional vector with the function values
%   Output: c is a vector of constraints (empty for this problem)
% Função objetivo 1
f1 = (x(1)^2 + x(2)^2)^0.125;
% Função objetivo 2
f2 = ((x(1)-0.5)^2 + (x(2)-0.5)^2)^0.25;
% Vetor de funções objetivo
f = [f1; f2];
% Não há restrições de desigualdade para este problema
end

