function varargout = QV1_mix(varargin)
%QV1_MIX  Self-contained mixed-variable MOO adaptation of QV1.
%
% Auto-generated by generate_selfcontained_wrappers_MOO_mix.m
% Source: QV1, n=10, m=2, strategy=spatial_thermal, kappa=90000
% Variable pattern: C,K,D,C,D,K,C,K,D,C
% D variables: nonuniform sorted finite sets with injected anchors.
% K variables: labels with permuted nonuniform numeric embeddings; labels carry no ordinal information.
%
%   x1   C [-5.12,5.12] -> orig [-5.12,5.12]
%   x2   K labels {k2_1,...,k2_90}, 90 levels, permuted embedding in [-5.12,5.12]
%   x3   D sorted nonuniform grid [-5.12,...,5.12], 36 values
%   x4   C [-5.12,5.12] -> orig [-5.12,5.12]
%   x5   D sorted nonuniform grid [-5.12,...,5.12], 27 values
%   x6   K labels {k6_1,...,k6_20}, 20 levels, permuted embedding in [-5.12,5.12]
%   x7   C [-1536,1536] -> orig [-5.12,5.12]
%   x8   K labels {k8_1,...,k8_101}, 101 levels, permuted embedding in [-5.12,5.12]
%   x9   D sorted nonuniform grid [-5.12,...,5.12], 20 values
%   x10  C [-1536,1536] -> orig [-5.12,5.12]
%
% Usage:
%   PB = QV1_mix()
%   F  = PB.func_F(xcell)       % recommended inside benchmark loops
%   F  = QV1_mix(xcell)              % also valid; PB is memoized persistently
%   PD = QV1_mix('ProblemData')
%

persistent PB_cached
if isempty(PB_cached)
lb_orig = [ ...
    -5.12; -5.12; -5.12; -5.12; -5.12; -5.12; -5.12; -5.12; ...
    -5.12; -5.12; ...
];
ub_orig = [ ...
    5.12; 5.12; 5.12; 5.12; 5.12; 5.12; 5.12; 5.12; ...
    5.12; 5.12; ...
];
lb_C_work = [ ...
    -5.12; -5.12; -5.12; -5.12; -5.12; -5.12; -1536; -5.12; ...
    -5.12; -1536; ...
];
ub_C_work = [ ...
    5.12; 5.12; 5.12; 5.12; 5.12; 5.12; 1536; 5.12; ...
    5.12; 1536; ...
];
var_types = {'C', 'K', 'D', 'C', 'D', 'K', 'C', 'K', 'D', 'C'};
K2_labels = { ...
    'k2_1', 'k2_2', 'k2_3', 'k2_4', 'k2_5', 'k2_6', 'k2_7', 'k2_8', 'k2_9', 'k2_10', ...
    'k2_11', 'k2_12', 'k2_13', 'k2_14', 'k2_15', 'k2_16', 'k2_17', 'k2_18', 'k2_19', 'k2_20', ...
    'k2_21', 'k2_22', 'k2_23', 'k2_24', 'k2_25', 'k2_26', 'k2_27', 'k2_28', 'k2_29', 'k2_30', ...
    'k2_31', 'k2_32', 'k2_33', 'k2_34', 'k2_35', 'k2_36', 'k2_37', 'k2_38', 'k2_39', 'k2_40', ...
    'k2_41', 'k2_42', 'k2_43', 'k2_44', 'k2_45', 'k2_46', 'k2_47', 'k2_48', 'k2_49', 'k2_50', ...
    'k2_51', 'k2_52', 'k2_53', 'k2_54', 'k2_55', 'k2_56', 'k2_57', 'k2_58', 'k2_59', 'k2_60', ...
    'k2_61', 'k2_62', 'k2_63', 'k2_64', 'k2_65', 'k2_66', 'k2_67', 'k2_68', 'k2_69', 'k2_70', ...
    'k2_71', 'k2_72', 'k2_73', 'k2_74', 'k2_75', 'k2_76', 'k2_77', 'k2_78', 'k2_79', 'k2_80', ...
    'k2_81', 'k2_82', 'k2_83', 'k2_84', 'k2_85', 'k2_86', 'k2_87', 'k2_88', 'k2_89', 'k2_90'};
K2_embed  = [ ...
    3.793211813986511; -4.425744809061547; 3.540667437991128; 4.050000564529172; -3.706424538551365; -3.333149433875581; 5.12; -0.1234597990088657; ...
    -3.127152924053358; -3.953486034497281; -5.078125853960811; -2.033196640302907; -2.675249561144153; -5.036478375804741; 2.572525769618293; -3.791857810674903; ...
    -4.977313474610563; 2.80829697610498; -4.103017823514692; -1.894222595645957; 0.0601634964397384; 2.113386663629051; 3.292347152300276; -0.6512993877545084; ...
    -4.305235673079427; 0.2476641079495998; -2.55379142938324; 4.57639160703041; -3.874200711647528; 4.846033756321405; 1.455368064865316; -4.240726693761647; ...
    -4.7219746369675; -4.835399322050633; 0.4390650813523651; -5.018788936991532; -4.481819961426948; -3.526158257252738; 2.340896015423671; -5.09709136373435; ...
    -5.08843688123535; -4.535160126268395; -5.052219247653174; -2.168613898900534; 1.889976501782788; -4.633794394549401; -4.868364110119821; -0.4791676667482214; ...
    4.311053829480781; -4.800044007860424; -1.45569913384626; -4.762251044320896; -3.617868616137923; 0.8336592894777866; -5.066078254699007; 1.036897622031588; ...
    -2.907930337054477; -5.11886698429364; -4.029747108557136; -5.114019907249711; -4.585804806810372; -0.9842379411065565; -1.605499622460709; -2.793286496301109; ...
    -4.679170224615017; -4.927317908406927; -3.431262149090556; -2.428884340896824; 1.244126520981271; -5.109783739669016; -3.019209539161448; -5.12; ...
    -4.898986932177724; 0.6343892600075209; -5.117001838990007; -4.366896003951759; 0; -4.173332655265318; -0.8196481008510021; -2.300500866757722; ...
    1.670644151482146; -5.119785333665469; -0.3032290315577315; -1.302238723201972; 3.048230525496478; -4.999087492889823; -4.95340886040552; -5.104175611318174; ...
    -1.145093278318671; -1.751665562422031; ...
];
D3_vals = [ ...
    -5.12; -5.10297929765917; -5.060730471957976; -4.997030973385989; -4.913611515906884; -4.811593527046363; -4.691796978452789; -4.554862730665486; ...
    -4.40131355565962; -4.231588863749606; -4.046066284984162; -3.84507596050687; -3.628910473547891; -3.397832016982648; -3.152077727364823; -2.891863756198098; ...
    -2.617388444184772; -2.026372739594676; -1.710160333971597; -1.380345597801051; -1.037067432249504; -0.6804566370379428; -0.3106367369874823; 0; ...
    0.07227530871133947; 0.4681684935840336; 0.8769372308252219; 1.29848088698941; 1.732703371862169; 2.179512775947719; 2.638821048569024; 3.110543710809195; ...
    3.594599598505346; 4.090910631295395; 4.599401604357166; 5.12; ...
];
D5_vals = [ ...
    -5.12; -5.090936498872422; -5.018795010888116; -4.910025677431646; -4.767583758881084; -4.593384135686431; -4.388826940841589; -4.155006468261952; ...
    -3.892815371116899; -3.603003959347397; -3.28621705072459; -2.943018373895309; -2.57390752593078; -1.759697349473305; -1.315372027698911; -0.8466949202298863; ...
    -0.3539785920458325; 0; 0.1624870308324535; 0.7024318241406782; 1.265603117818143; 1.851763732803291; 2.460690323563004; 3.092171966734312; ...
    3.746008950019925; 4.422011725613181; 5.12; ...
];
K6_labels = { ...
    'k6_1', 'k6_2', 'k6_3', 'k6_4', 'k6_5', 'k6_6', 'k6_7', 'k6_8', 'k6_9', 'k6_10', ...
    'k6_11', 'k6_12', 'k6_13', 'k6_14', 'k6_15', 'k6_16', 'k6_17', 'k6_18', 'k6_19', 'k6_20'};
K6_embed  = [ ...
    -1.001345519908913; 0.6864452597901218; -4.7042623806998; -2.36174916240288; -5.111264428668571; 1.659212894709749; 2.72095074376143; 5.12; ...
    -0.1996205048581254; -4.476046785778213; -4.997993680643303; -4.876647790614757; -3.83557933844844; 3.873843507687842; -1.721194558666881; -2.925723690109983; ...
    -4.187762410711924; -5.073893378092235; 0; -5.12; ...
];
K8_labels = { ...
    'k8_1', 'k8_2', 'k8_3', 'k8_4', 'k8_5', 'k8_6', 'k8_7', 'k8_8', 'k8_9', 'k8_10', ...
    'k8_11', 'k8_12', 'k8_13', 'k8_14', 'k8_15', 'k8_16', 'k8_17', 'k8_18', 'k8_19', 'k8_20', ...
    'k8_21', 'k8_22', 'k8_23', 'k8_24', 'k8_25', 'k8_26', 'k8_27', 'k8_28', 'k8_29', 'k8_30', ...
    'k8_31', 'k8_32', 'k8_33', 'k8_34', 'k8_35', 'k8_36', 'k8_37', 'k8_38', 'k8_39', 'k8_40', ...
    'k8_41', 'k8_42', 'k8_43', 'k8_44', 'k8_45', 'k8_46', 'k8_47', 'k8_48', 'k8_49', 'k8_50', ...
    'k8_51', 'k8_52', 'k8_53', 'k8_54', 'k8_55', 'k8_56', 'k8_57', 'k8_58', 'k8_59', 'k8_60', ...
    'k8_61', 'k8_62', 'k8_63', 'k8_64', 'k8_65', 'k8_66', 'k8_67', 'k8_68', 'k8_69', 'k8_70', ...
    'k8_71', 'k8_72', 'k8_73', 'k8_74', 'k8_75', 'k8_76', 'k8_77', 'k8_78', 'k8_79', 'k8_80', ...
    'k8_81', 'k8_82', 'k8_83', 'k8_84', 'k8_85', 'k8_86', 'k8_87', 'k8_88', 'k8_89', 'k8_90', ...
    'k8_91', 'k8_92', 'k8_93', 'k8_94', 'k8_95', 'k8_96', 'k8_97', 'k8_98', 'k8_99', 'k8_100', ...
    'k8_101'};
K8_embed  = [ ...
    -3.769096739043703; 1.055384479447079; -5.119143412078517; -4.504017999594026; 3.262831608194877; -2.462950714145293; 1.618608775340736; -4.904834842263243; ...
    -2.786300247149319; -4.63752009287747; -4.878105349524922; -0.6188861960501111; 0.520622079971897; -4.455247614328758; -3.447620575671839; 3.933919094428389; ...
    -4.595125889565133; -5.028587151470748; 5.12; -5.088342109012063; -4.952908649612125; -3.0854499439323; 0; -1.203668163250338; ...
    -1.61141587360657; -3.692466264784715; -4.178144898606365; 1.427678975425627; 1.239942692346867; -0.465232985533607; -1.993261503889264; -4.994052974551349; ...
    -5.012125454642136; 2.010110158082934; -4.051301958495282; -4.929757038077294; -4.849532933535215; -1.4784019100928; 2.41456822604699; -1.868827510282424; ...
    4.398140667077391; -5.102680503886538; -4.716135210101951; -3.271708149138679; 2.210712086269991; 4.635342874514353; -5.079233825735322; -0.7695392712012756; ...
    2.832102682280838; -0.1488589716371687; -5.119837706937092; -5.096137500878097; -4.974327568966482; -4.550634736117074; 0.01389507894208997; -4.351136299479016; ...
    -4.115891627096488; 0.8739887766218537; -3.843272380497963; -5.108036370428398; -1.061913059425761; -5.117733316057842; -3.531750407149003; -3.613358278234395; ...
    -2.349697836485229; 0.6957399080702524; -4.786721777196035; -5.12; -5.043481930915161; -5.056855584554861; -2.114872120748727; -4.677846577917875; ...
    -4.29574182517586; -5.112276254289222; 4.164337427082335; -4.238086565365893; -2.988388859387566; -3.360946994087348; -2.573455783051398; -0.3085628080365055; ...
    0.3486193780873101; 3.70687152085931; -4.819082972545294; 3.045810518195544; -4.404296052905705; -1.741551715758029; -0.9172091854578248; -3.984351488974608; ...
    -3.915016187394139; -1.342491920150774; 0.1797157652779342; -2.681232429126595; 2.621693488222716; -4.752416526400949; 1.812747427481845; -2.888679046863988; ...
    -2.2336779671703; 3.483180468473852; 4.875958022788303; -5.068756073332982; -5.115478901845324; ...
];
D9_vals = [ ...
    -5.12; -5.068885575557542; -4.942009236036243; -4.750714943851269; -4.500200160679372; -4.193832616087898; -3.834074745411528; -3.422851100114684; ...
    -2.961731602994322; -1.894897848915288; -1.291309081046715; -0.642148181045175; 0; 0.05179746654715167; 0.7898157231702374; 1.571257469916893; ...
    2.395527075030063; 3.262074825694255; 4.17039082457745; 5.12; ...
];
ProblemData = { ...
    [-5.12; 5.12]; ... % x1 C
    K2_labels; ... % x2 K
    {D3_vals}; ... % x3 D
    [-5.12; 5.12]; ... % x4 C
    {D5_vals}; ... % x5 D
    K6_labels; ... % x6 K
    [-1536; 1536]; ... % x7 C
    K8_labels; ... % x8 K
    {D9_vals}; ... % x9 D
    [-1536; 1536]; ... % x10 C
};
x_anchor = {0, 'k2_77', 0, 0, 0, 'k6_19', 0, 'k8_23', 0, 0};
anchors_set = [ ...
    0 -5.12 5.12; ...
    0 -5.12 5.12; ...
    0 -5.12 5.12; ...
    0 -5.12 5.12; ...
    0 -5.12 5.12; ...
    0 -5.12 5.12; ...
    0 -5.12 5.12; ...
    0 -5.12 5.12; ...
    0 -5.12 5.12; ...
    0 -5.12 5.12];

PB = struct();
PB.name = 'QV1_mix';
PB.problem = 'QV1';
PB.source = 'MOModels_Matlab';
PB.type = 'MOO_MIXED';
PB.nvar = 10; PB.n = 10; PB.nobj = 2; PB.m = 2;
PB.var_types = var_types;
PB.type_counts = struct('C', 4, 'D', 3, 'K', 3);
PB.ProblemData = ProblemData;
PB.strategy = 'spatial_thermal'; PB.kappa = 90000;
PB.lb_orig = lb_orig; PB.ub_orig = ub_orig;
PB.lb_C_work = lb_C_work; PB.ub_C_work = ub_C_work;
PB.x_anchor = x_anchor;
PB.anchors_set = anchors_set;
PB.K2_labels = K2_labels; PB.K2_embed = K2_embed;
PB.D3_vals = D3_vals;
PB.D5_vals = D5_vals;
PB.K6_labels = K6_labels; PB.K6_embed = K6_embed;
PB.K8_labels = K8_labels; PB.K8_embed = K8_embed;
PB.D9_vals = D9_vals;
PB.pareto_front_known = false;
PB.pareto_set_known = false;
PB.pf_type = 'unknown';
PB.ideal_point = [];
PB.nadir_point = [];
PB.core = @(xh) QV1_orig(xh);
PB.decode = @(xr) decode(xr, PB);
PB.func_F = @(xr) objective(xr, PB);
PB_cached = PB;
else
    PB = PB_cached;
end

if nargin == 0
    varargout{1} = PB; return
end
arg1 = varargin{1};
if ischar(arg1) || (isstring(arg1) && isscalar(arg1))
    key = lower(char(arg1));
    switch key
        case {'problemdata','bounds','domain'}
            varargout{1} = PB.ProblemData; return
        case 'var_types'
            varargout{1} = PB.var_types; return
        case 'info'
            varargout{1} = PB; return
        otherwise
            error('Unknown string argument: %s', char(arg1));
    end
end
varargout{1} = PB.func_F(arg1);
end

function F = objective(xr, PB)
xh = decode(xr, PB);
F = PB.core(xh);
F = F(:);
end

function xh = decode(xr, PB)
if ~iscell(xr) || numel(xr) ~= 10
    error('QV1_mix: input must be a cell array with exactly 10 entries.');
end
xh = zeros(10,1);
tmp = check_C(xr{1}, PB.lb_C_work(1), PB.ub_C_work(1), 'x1');
xh(1) = map_C_to_orig(tmp, PB.lb_C_work(1), PB.ub_C_work(1), PB.lb_orig(1), PB.ub_orig(1));
xh(2) = check_K(xr{2}, PB.K2_labels, PB.K2_embed, 'x2');
xh(3) = check_D(xr{3}, PB.D3_vals, 'x3');
tmp = check_C(xr{4}, PB.lb_C_work(4), PB.ub_C_work(4), 'x4');
xh(4) = map_C_to_orig(tmp, PB.lb_C_work(4), PB.ub_C_work(4), PB.lb_orig(4), PB.ub_orig(4));
xh(5) = check_D(xr{5}, PB.D5_vals, 'x5');
xh(6) = check_K(xr{6}, PB.K6_labels, PB.K6_embed, 'x6');
tmp = check_C(xr{7}, PB.lb_C_work(7), PB.ub_C_work(7), 'x7');
xh(7) = map_C_to_orig(tmp, PB.lb_C_work(7), PB.ub_C_work(7), PB.lb_orig(7), PB.ub_orig(7));
xh(8) = check_K(xr{8}, PB.K8_labels, PB.K8_embed, 'x8');
xh(9) = check_D(xr{9}, PB.D9_vals, 'x9');
tmp = check_C(xr{10}, PB.lb_C_work(10), PB.ub_C_work(10), 'x10');
xh(10) = map_C_to_orig(tmp, PB.lb_C_work(10), PB.ub_C_work(10), PB.lb_orig(10), PB.ub_orig(10));
end

function v = check_C(val, a, b, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('QV1_mix: %s must be a real scalar.', name);
end
if val < a || val > b
    error('QV1_mix: %s=%g outside [%g,%g].', name, val, a, b);
end
v = double(val);
end

function xorig = map_C_to_orig(xwork, lbw, ubw, lbo, ubo)
if abs(ubw - lbw) <= 1e-14
    t = 0;
else
    t = (xwork - lbw) / (ubw - lbw);
end
t = max(0, min(1, t));
xorig = lbo + t * (ubo - lbo);
end

function v = check_D(val, grid, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('QV1_mix: %s must be a real scalar.', name);
end
grid = grid(:);
[dmin, idx] = min(abs(grid - val));
if dmin > 1e-10 * max(1, max(abs(grid)))
    error('QV1_mix: %s=%g not in grid.', name, val);
end
v = grid(idx);
end

function v = check_K(label, labels, embed, name)
if isstring(label), label = char(label); end
if ~(ischar(label) && isrow(label))
    error('QV1_mix: %s must be a char vector or scalar string.', name);
end
idx = find(strcmp(label, labels), 1);
if isempty(idx)
    error('QV1_mix: %s unknown label ''%s''.', name, label);
end
v = embed(idx);
end


% -------------------------------------------------------------------------
% Embedded original continuous MOO problem (top-level function renamed only)
% -------------------------------------------------------------------------
function f = QV1_orig(x)
% QV1 function
%
%   As described by Huband et al. in "A review of multiobjective test problems
%   and a scalable test problem toolkit", IEEE Transactions on Evolutionary 
%   Computing 10(5): 477-506, 2006.
%
%   Example QV1, see the previous cited paper for the original reference.
%
%   In the original reference the number of variables was n=16. 
%   We selected n=10 as default.
%
%   This file is part of a collection of problems developed for
%   derivative-free multiobjective optimization in
%   A. L. Custódio, J. F. A. Madeira, A. I. F. Vaz, and L. N. Vicente,
%   Direct Multisearch for Multiobjective Optimization, 2010.
%
%   Written by the authors in June 1, 2010.
%   Adapted to MATLAB format in November 2025.
%
% Problem characteristics:
% - Number of variables: 10
% - Number of objectives: 2
%   Bounds: x1 in [-5.12,5.12], x2 in [-5.12,5.12], x3 in [-5.12,5.12], x4 in [-5.12,5.12], x5 in [-5.12,5.12], x6 in [-5.12,5.12], x7 in [-5.12,5.12], x8 in [-5.12,5.12], x9 in [-5.12,5.12], x10 in [-5.12,5.12]
%
%
%   Input: x is a 10-dimensional vector
%   Output: f is a 2-dimensional vector with the function values
%   Output: c is a vector of constraints (empty for this problem - bounds are
%          handled by the optimization algorithm)
% Parâmetros
pi = 4*atan(1);
n = 10;
% Função objetivo 1
sum1 = 0;
for i = 1:n
    sum1 = sum1 + (x(i)^2 - 10*cos(2*pi*x(i)) + 10);
end
f1 = (sum1/n)^0.25;
% Função objetivo 2
sum2 = 0;
for i = 1:n
    sum2 = sum2 + ((x(i)-1.5)^2 - 10*cos(2*pi*(x(i)-1.5)) + 10);
end
f2 = (sum2/n)^0.25;
% Vetor de funções objetivo
f = [f1; f2];
% Não há restrições de desigualdade para este problema
end

