function varargout = VU1_mix(varargin)
%VU1_MIX  Self-contained mixed-variable MOO adaptation of VU1.
%
% Auto-generated by generate_selfcontained_wrappers_MOO_mix.m
% Source: VU1, n=2, m=2, strategy=spatial_thermal, kappa=90000
% Variable pattern: C,K
% D variables: nonuniform sorted finite sets with injected anchors.
% K variables: labels with permuted nonuniform numeric embeddings; labels carry no ordinal information.
%
%   x1   C [-3,3] -> orig [-3,3]
%   x2   K labels {k2_1,...,k2_64}, 64 levels, permuted embedding in [-3,3]
%
% Usage:
%   PB = VU1_mix()
%   F  = PB.func_F(xcell)       % recommended inside benchmark loops
%   F  = VU1_mix(xcell)              % also valid; PB is memoized persistently
%   PD = VU1_mix('ProblemData')
%

persistent PB_cached
if isempty(PB_cached)
lb_orig = [-3; -3];
ub_orig = [3; 3];
lb_C_work = [-3; -3];
ub_C_work = [3; 3];
var_types = {'C', 'K'};
K2_labels = { ...
    'k2_1', 'k2_2', 'k2_3', 'k2_4', 'k2_5', 'k2_6', 'k2_7', 'k2_8', 'k2_9', 'k2_10', ...
    'k2_11', 'k2_12', 'k2_13', 'k2_14', 'k2_15', 'k2_16', 'k2_17', 'k2_18', 'k2_19', 'k2_20', ...
    'k2_21', 'k2_22', 'k2_23', 'k2_24', 'k2_25', 'k2_26', 'k2_27', 'k2_28', 'k2_29', 'k2_30', ...
    'k2_31', 'k2_32', 'k2_33', 'k2_34', 'k2_35', 'k2_36', 'k2_37', 'k2_38', 'k2_39', 'k2_40', ...
    'k2_41', 'k2_42', 'k2_43', 'k2_44', 'k2_45', 'k2_46', 'k2_47', 'k2_48', 'k2_49', 'k2_50', ...
    'k2_51', 'k2_52', 'k2_53', 'k2_54', 'k2_55', 'k2_56', 'k2_57', 'k2_58', 'k2_59', 'k2_60', ...
    'k2_61', 'k2_62', 'k2_63', 'k2_64'};
K2_embed  = [ ...
    1.144565001161705; -0.9831299777669393; -0.3242596689261097; -2.06784286818947; 0.9627440151329552; -2.703251902063022; -2.986282911453515; -0.7325786655541497; ...
    -1.216740429172254; -2.978753033525948; -2.408110123765751; -1.634526322441259; -2.347185259019243; -2.214751770845002; 1.331161584888246; -2.887857838630245; ...
    2.773962866115703; -1.327299951661161; -0.1793270888430567; -0.4647525459418116; 2.336996679691143; -0.8599930301264456; -2.808418771669192; -3; ...
    -2.570403990015164; 1.522568947690684; -2.282750974555175; -1.988828214647643; 2.552972666229144; -1.10203155130817; 0.7856630522743804; -1.819424191682614; ...
    0; 2.126001862379806; -2.143133415349967; -2.998478731329744; -2.943776748984559; -2.519660429210087; -2.741291115723792; 1.718821889175445; ...
    -2.66213549076352; -2.837654140294595; -0.02991559978240765; -2.927600772600564; 0.2824984052275221; -0.6008454521729014; 1.919954838029463; -1.433754149061393; ...
    0.1240134959899217; -2.617874586850395; -2.991970695820746; -2.957621078469892; -2.776322711163992; -1.536147771741165; -2.86410672122748; -1.728936090987324; ...
    3; -2.969241211367518; 0.6132861329695247; -2.999711773484298; -2.995974452615898; -2.465582417481539; -2.908992669375404; 0.4455768599730696; ...
];
ProblemData = { ...
    [-3; 3]; ... % x1 C
    K2_labels; ... % x2 K
};
x_anchor = {0, 'k2_33'};
anchors_set = [0 -3 3; 0 -3 3];

PB = struct();
PB.name = 'VU1_mix';
PB.problem = 'VU1';
PB.source = 'MOModels_Matlab';
PB.type = 'MOO_MIXED';
PB.nvar = 2; PB.n = 2; PB.nobj = 2; PB.m = 2;
PB.var_types = var_types;
PB.type_counts = struct('C', 1, 'D', 0, 'K', 1);
PB.ProblemData = ProblemData;
PB.strategy = 'spatial_thermal'; PB.kappa = 90000;
PB.lb_orig = lb_orig; PB.ub_orig = ub_orig;
PB.lb_C_work = lb_C_work; PB.ub_C_work = ub_C_work;
PB.x_anchor = x_anchor;
PB.anchors_set = anchors_set;
PB.K2_labels = K2_labels; PB.K2_embed = K2_embed;
PB.pareto_front_known = false;
PB.pareto_set_known = false;
PB.pf_type = 'unknown';
PB.ideal_point = [];
PB.nadir_point = [];
PB.core = @(xh) VU1_orig(xh);
PB.decode = @(xr) decode(xr, PB);
PB.func_F = @(xr) objective(xr, PB);
PB_cached = PB;
else
    PB = PB_cached;
end

if nargin == 0
    varargout{1} = PB; return
end
arg1 = varargin{1};
if ischar(arg1) || (isstring(arg1) && isscalar(arg1))
    key = lower(char(arg1));
    switch key
        case {'problemdata','bounds','domain'}
            varargout{1} = PB.ProblemData; return
        case 'var_types'
            varargout{1} = PB.var_types; return
        case 'info'
            varargout{1} = PB; return
        otherwise
            error('Unknown string argument: %s', char(arg1));
    end
end
varargout{1} = PB.func_F(arg1);
end

function F = objective(xr, PB)
xh = decode(xr, PB);
F = PB.core(xh);
F = F(:);
end

function xh = decode(xr, PB)
if ~iscell(xr) || numel(xr) ~= 2
    error('VU1_mix: input must be a cell array with exactly 2 entries.');
end
xh = zeros(2,1);
tmp = check_C(xr{1}, PB.lb_C_work(1), PB.ub_C_work(1), 'x1');
xh(1) = map_C_to_orig(tmp, PB.lb_C_work(1), PB.ub_C_work(1), PB.lb_orig(1), PB.ub_orig(1));
xh(2) = check_K(xr{2}, PB.K2_labels, PB.K2_embed, 'x2');
end

function v = check_C(val, a, b, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('VU1_mix: %s must be a real scalar.', name);
end
if val < a || val > b
    error('VU1_mix: %s=%g outside [%g,%g].', name, val, a, b);
end
v = double(val);
end

function xorig = map_C_to_orig(xwork, lbw, ubw, lbo, ubo)
if abs(ubw - lbw) <= 1e-14
    t = 0;
else
    t = (xwork - lbw) / (ubw - lbw);
end
t = max(0, min(1, t));
xorig = lbo + t * (ubo - lbo);
end

function v = check_D(val, grid, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('VU1_mix: %s must be a real scalar.', name);
end
grid = grid(:);
[dmin, idx] = min(abs(grid - val));
if dmin > 1e-10 * max(1, max(abs(grid)))
    error('VU1_mix: %s=%g not in grid.', name, val);
end
v = grid(idx);
end

function v = check_K(label, labels, embed, name)
if isstring(label), label = char(label); end
if ~(ischar(label) && isrow(label))
    error('VU1_mix: %s must be a char vector or scalar string.', name);
end
idx = find(strcmp(label, labels), 1);
if isempty(idx)
    error('VU1_mix: %s unknown label ''%s''.', name, label);
end
v = embed(idx);
end


% -------------------------------------------------------------------------
% Embedded original continuous MOO problem (top-level function renamed only)
% -------------------------------------------------------------------------
function f = VU1_orig(x)
% VU1 function
%
%   As described by Huband et al. in "A review of multiobjective test problems
%   and a scalable test problem toolkit", IEEE Transactions on Evolutionary 
%   Computing 10(5): 477-506, 2006.
%
%   Example VU1, see the previous cited paper for the original reference.
%
%   This file is part of a collection of problems developed for
%   derivative-free multiobjective optimization in
%   A. L. Custódio, J. F. A. Madeira, A. I. F. Vaz, and L. N. Vicente,
%   Direct Multisearch for Multiobjective Optimization, 2010.
%
%   Written by the authors in June 1, 2010.
%   Adapted to MATLAB format in November 2025.
%
% Problem characteristics:
% - Number of variables: 2
% - Number of objectives: 2
%   Bounds: x1 in [-3,3], x2 in [-3,3]
%
%
%   Input: x is a 2-dimensional vector
%   Output: f is a 2-dimensional vector with the function values
%   Output: c is a vector of constraints (empty for this problem - bounds are
%          handled by the optimization algorithm)
% Função objetivo 1
f1 = 1 / (x(1)^2 + x(2)^2 + 1);
% Função objetivo 2
f2 = x(1)^2 + 3*x(2)^2 + 1;
% Vetor de funções objetivo
f = [f1; f2];
% Não há restrições de desigualdade para este problema
end

