function varargout = lovison5_mix(varargin)
%LOVISON5_MIX  Self-contained mixed-variable MOO adaptation of lovison5.
%
% Auto-generated by generate_selfcontained_wrappers_MOO_mix.m
% Source: lovison5, n=3, m=3, strategy=baseline, kappa=1
% Variable pattern: C,K,D
% D variables: nonuniform sorted finite sets with injected anchors.
% K variables: labels with permuted nonuniform numeric embeddings; labels carry no ordinal information.
%
%   x1   C [-1,4] -> orig [-1,4]
%   x2   K labels {k2_1,...,k2_80}, 80 levels, permuted embedding in [-1,4]
%   x3   D sorted nonuniform grid [-1,...,4], 93 values
%
% Usage:
%   PB = lovison5_mix()
%   F  = PB.func_F(xcell)       % recommended inside benchmark loops
%   F  = lovison5_mix(xcell)              % also valid; PB is memoized persistently
%   PD = lovison5_mix('ProblemData')
%

persistent PB_cached
if isempty(PB_cached)
lb_orig = [-1; -1; -1];
ub_orig = [4; 4; 4];
lb_C_work = [-1; -1; -1];
ub_C_work = [4; 4; 4];
var_types = {'C', 'K', 'D'};
K2_labels = { ...
    'k2_1', 'k2_2', 'k2_3', 'k2_4', 'k2_5', 'k2_6', 'k2_7', 'k2_8', 'k2_9', 'k2_10', ...
    'k2_11', 'k2_12', 'k2_13', 'k2_14', 'k2_15', 'k2_16', 'k2_17', 'k2_18', 'k2_19', 'k2_20', ...
    'k2_21', 'k2_22', 'k2_23', 'k2_24', 'k2_25', 'k2_26', 'k2_27', 'k2_28', 'k2_29', 'k2_30', ...
    'k2_31', 'k2_32', 'k2_33', 'k2_34', 'k2_35', 'k2_36', 'k2_37', 'k2_38', 'k2_39', 'k2_40', ...
    'k2_41', 'k2_42', 'k2_43', 'k2_44', 'k2_45', 'k2_46', 'k2_47', 'k2_48', 'k2_49', 'k2_50', ...
    'k2_51', 'k2_52', 'k2_53', 'k2_54', 'k2_55', 'k2_56', 'k2_57', 'k2_58', 'k2_59', 'k2_60', ...
    'k2_61', 'k2_62', 'k2_63', 'k2_64', 'k2_65', 'k2_66', 'k2_67', 'k2_68', 'k2_69', 'k2_70', ...
    'k2_71', 'k2_72', 'k2_73', 'k2_74', 'k2_75', 'k2_76', 'k2_77', 'k2_78', 'k2_79', 'k2_80'};
K2_embed  = [ ...
    0.9183465804924533; 2.613289865929307; -0.9342146740618004; -0.619864858924857; -0.9980512505906485; -0.7412908484463543; 1.481474479992199; -0.8364413084750275; ...
    -0.9457124833269139; 0.1614199416670159; -0.9214090984344033; 0.2953138771516446; 0.2273019063613546; 1.79514949181794; 0.589042735814687; -0.6839753157728292; ...
    0.7491755892009908; 2.130812370799038; 1.284360483665745; 2.488882760165226; -0.9727825766898492; -0.5104962800237649; 2.247659059346293; -0.9992635606689579; ...
    3.849444928017371; 2.367010817759523; 4; 1.096695871396546; 1.5; -0.6527829680470895; -0.9961130499075428; 0.3654750882575164; ...
    -0.5487469189375869; 1.006365303245686; -0.7674697710522878; 3.001870001104394; 0.0976484847012995; -0.8917188290402395; -0.9559437599711871; -0.8747601910193965; ...
    1.904573053167186; -0.4284885533233753; -0.71346876917459; -0.9897144389529867; -0.9794845544168933; 1.381728040889985; -0.8150148036725462; -0.3389803252256304; ...
    0.4378045190840396; -0.9933596190399954; 3.556355553249337; 2.86976883001928; -0.3846836701714058; 3.27386807778714; -0.8563455785256062; 0.6679882833490312; ...
    1.688169128550519; 1.583616123445607; -0.4704182011723035; -0.02364228028019122; 3.136564966812625; -0.1367320506285412; -0.5851947346776856; 3.701568041668045; ...
    0.8326224816678007; -0.7920345009416506; 2.740246982814498; -0.1902534189272602; -1; 3.413793567193406; -0.2417874177881356; -0.9072563877829443; ...
    -0.9998604708382137; 0.03596776304744775; 1.189355316092173; 0.5123209030304905; -0.2913557106634416; -0.9851098085650046; -0.9649518591709125; 2.01645549994827; ...
];
D3_vals = [ ...
    -1; -0.9985406753609177; -0.9949183364536599; -0.9894568551409708; -0.982304619749009; -0.9735577794722334; -0.9632866372162381; -0.9515461392198163; ...
    -0.9383811070190424; -0.9238292148699871; -0.90792284009901; -0.8906902884185047; -0.8721566453924045; -0.8523443909698697; -0.8312738568157566; -0.8089635753741904; ...
    -0.7854305520229751; -0.7606904811471071; -0.7347579203934373; -0.7076464331311125; -0.6793687063259436; -0.6499366491160233; -0.6193614760359698; -0.5876537778834705; ...
    -0.5548235825307661; -0.5208804074748479; -0.4858333055399511; -0.4496909048580751; -0.4124614440326977; -0.3741528032199408; -0.3347725317276954; -0.2943278726275123; ...
    -0.2528257847898501; -0.2102729626855913; -0.1666758542419589; -0.1220406769963153; -0.07637343275468567; -0.02967992093158545; 0.01803424927736419; 0.06676364775954369; ...
    0.1165030132732594; 0.1672472440614223; 0.2189913892054984; 0.2717306406449289; 0.3254603257963671; 0.3801759007149172; 0.4925471496246623; 0.5501943239759683; ...
    0.6088103781909591; 0.6683913246359225; 0.7289332721725457; 0.7904324219612073; 0.8528850635246381; 0.9162875710511327; 0.9806363999185506; 1.045928083422106; ...
    1.112159229690542; 1.179326518776723; 1.247426699909891; 1.316456588898038; 1.386413065669759; 1.457293071945974; 1.5; 1.529093609032608; ...
    1.601811735726142; 1.67544456632458; 1.749989268736951; 1.825443062685069; 1.901803217991698; 1.979067052949784; 2.057231932767766; 2.136295268086376; ...
    2.216254513562696; 2.29710716651749; 2.378850765642192; 2.461482889762093; 2.545001156652625; 2.629403221905727; 2.714686777843597; 2.800849552477241; ...
    2.887889308507424; 2.975803842365794; 3.064590983294078; 3.154248592459407; 3.244774562103887; 3.336166814726771; 3.428423302297534; 3.521542005498383; ...
    3.615520932994766; 3.710358120732521; 3.806051631260427; 3.902599553076936; 4; ...
];
ProblemData = { ...
    [-1; 4]; ... % x1 C
    K2_labels; ... % x2 K
    {D3_vals}; ... % x3 D
};
x_anchor = {1.5, 'k2_29', 1.5};
anchors_set = [1.5 -1 4; 1.5 -1 4; 1.5 -1 4];

PB = struct();
PB.name = 'lovison5_mix';
PB.problem = 'lovison5';
PB.source = 'MOModels_Matlab';
PB.type = 'MOO_MIXED';
PB.nvar = 3; PB.n = 3; PB.nobj = 3; PB.m = 3;
PB.var_types = var_types;
PB.type_counts = struct('C', 1, 'D', 1, 'K', 1);
PB.ProblemData = ProblemData;
PB.strategy = 'baseline'; PB.kappa = 1;
PB.lb_orig = lb_orig; PB.ub_orig = ub_orig;
PB.lb_C_work = lb_C_work; PB.ub_C_work = ub_C_work;
PB.x_anchor = x_anchor;
PB.anchors_set = anchors_set;
PB.K2_labels = K2_labels; PB.K2_embed = K2_embed;
PB.D3_vals = D3_vals;
PB.pareto_front_known = false;
PB.pareto_set_known = false;
PB.pf_type = 'unknown';
PB.ideal_point = [];
PB.nadir_point = [];
PB.core = @(xh) lovison5_orig(xh);
PB.decode = @(xr) decode(xr, PB);
PB.func_F = @(xr) objective(xr, PB);
PB_cached = PB;
else
    PB = PB_cached;
end

if nargin == 0
    varargout{1} = PB; return
end
arg1 = varargin{1};
if ischar(arg1) || (isstring(arg1) && isscalar(arg1))
    key = lower(char(arg1));
    switch key
        case {'problemdata','bounds','domain'}
            varargout{1} = PB.ProblemData; return
        case 'var_types'
            varargout{1} = PB.var_types; return
        case 'info'
            varargout{1} = PB; return
        otherwise
            error('Unknown string argument: %s', char(arg1));
    end
end
varargout{1} = PB.func_F(arg1);
end

function F = objective(xr, PB)
xh = decode(xr, PB);
F = PB.core(xh);
F = F(:);
end

function xh = decode(xr, PB)
if ~iscell(xr) || numel(xr) ~= 3
    error('lovison5_mix: input must be a cell array with exactly 3 entries.');
end
xh = zeros(3,1);
tmp = check_C(xr{1}, PB.lb_C_work(1), PB.ub_C_work(1), 'x1');
xh(1) = map_C_to_orig(tmp, PB.lb_C_work(1), PB.ub_C_work(1), PB.lb_orig(1), PB.ub_orig(1));
xh(2) = check_K(xr{2}, PB.K2_labels, PB.K2_embed, 'x2');
xh(3) = check_D(xr{3}, PB.D3_vals, 'x3');
end

function v = check_C(val, a, b, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('lovison5_mix: %s must be a real scalar.', name);
end
if val < a || val > b
    error('lovison5_mix: %s=%g outside [%g,%g].', name, val, a, b);
end
v = double(val);
end

function xorig = map_C_to_orig(xwork, lbw, ubw, lbo, ubo)
if abs(ubw - lbw) <= 1e-14
    t = 0;
else
    t = (xwork - lbw) / (ubw - lbw);
end
t = max(0, min(1, t));
xorig = lbo + t * (ubo - lbo);
end

function v = check_D(val, grid, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('lovison5_mix: %s must be a real scalar.', name);
end
grid = grid(:);
[dmin, idx] = min(abs(grid - val));
if dmin > 1e-10 * max(1, max(abs(grid)))
    error('lovison5_mix: %s=%g not in grid.', name, val);
end
v = grid(idx);
end

function v = check_K(label, labels, embed, name)
if isstring(label), label = char(label); end
if ~(ischar(label) && isrow(label))
    error('lovison5_mix: %s must be a char vector or scalar string.', name);
end
idx = find(strcmp(label, labels), 1);
if isempty(idx)
    error('lovison5_mix: %s unknown label ''%s''.', name, label);
end
v = embed(idx);
end


% -------------------------------------------------------------------------
% Embedded original continuous MOO problem (top-level function renamed only)
% -------------------------------------------------------------------------
function f = lovison5_orig(x)
% LOVISON5 function
%
%   As described by A. Lovison in "A synthetic approach to multiobjective
%   optimization", arxiv Item: http://arxiv.org/abs/1002.0093.
%
%   Example 5.
%
%   In the above paper/papers the variables bounds were not set.
%   We considered -1<=x[i]<=4, i=1,2,3.
%
%   This file is part of a collection of problems developed for
%   derivative-free multiobjective optimization in
%   A. L. Custódio, J. F. A. Madeira, A. I. F. Vaz, and L. N. Vicente,
%   Direct Multisearch for Multiobjective Optimization, 2010.
%
%   Written by the authors in June 1, 2010.
%   Adapted to MATLAB format in November 2025.
%
%   Input: x is a 3-dimensional vector
%   Output: f is a 3-dimensional vector with the function values
%   Output: c is a vector of constraints (empty for this problem - bounds are
%          handled by the optimization algorithm)
% Nota: Este problema é originalmente de maximização, 
% mas para manter a consistência com a interface da coleção DMS,
% convertemos para minimização multiplicando por -1.
% Parâmetros do problema
%
%   Bounds: x1 in [-1,4], x2 in [-1,4], x3 in [-1,4]
%
n = 3;   % número de variáveis
m = 3;   % número de funções usadas nos objetivos
pi = 4*atan(1);
% Matriz C (pontos distintos não colineares)
C = [
    0.218418, -0.620254, 0.843784;
    0.914311, -0.788548, 0.428212;
    0.103064, -0.47373, -0.300792
];
% Matriz alpha (diagonal definida negativa)
alpha = [
    0.407247, 0.665212, 0.575807;
    0.942022, 0.363525, 0.00308876;
    0.755598, 0.450103, 0.170122
];
% Vetor beta
beta = [0.575496; 0.675617; 0.180332];
% Vetor gamma
gamma = [-0.593814; -0.492722; 0.0646786];
% Cálculo das funções f(j)
f_aux = zeros(m,1);
for j = 1:m
    f_aux(j) = 0;
    for i = 1:n
        f_aux(j) = f_aux(j) + (-alpha(j,i)*(x(i)-C(i,j))^2);
    end
end
% Função objetivo 1
f1 = -(f_aux(1));
% Função objetivo 2
f2 = -(f_aux(2) + beta(2)*sin(pi*(x(1)+x(2))/gamma(2)));
% Função objetivo 3
f3 = -(f_aux(3) + beta(3)*cos(pi*(x(1)-x(2))/gamma(3)));
% Vetor de funções objetivo
f = [f1; f2; f3];
% Não há restrições de desigualdade para este problema
% As restrições de limites são tratadas pelo algoritmo de otimização
end

