function varargout = Deb521a_mix(varargin)
%DEB521A_MIX  Self-contained mixed-variable MOO adaptation of Deb521a.
%
% Auto-generated by generate_selfcontained_wrappers_MOO_mix.m
% Source: Deb521a, n=2, m=2, strategy=moderate, kappa=10000
% Variable pattern: C,K
% D variables: nonuniform sorted finite sets with injected anchors.
% K variables: labels with permuted nonuniform numeric embeddings; labels carry no ordinal information.
%
%   x1   C [0,1] -> orig [0,1]
%   x2   K labels {k2_1,...,k2_79}, 79 levels, permuted embedding in [0,1]
%
% Usage:
%   PB = Deb521a_mix()
%   F  = PB.func_F(xcell)       % recommended inside benchmark loops
%   F  = Deb521a_mix(xcell)              % also valid; PB is memoized persistently
%   PD = Deb521a_mix('ProblemData')
%

persistent PB_cached
if isempty(PB_cached)
lb_orig = [0; 0];
ub_orig = [1; 1];
lb_C_work = [0; 0];
ub_C_work = [1; 1];
var_types = {'C', 'K'};
K2_labels = { ...
    'k2_1', 'k2_2', 'k2_3', 'k2_4', 'k2_5', 'k2_6', 'k2_7', 'k2_8', 'k2_9', 'k2_10', ...
    'k2_11', 'k2_12', 'k2_13', 'k2_14', 'k2_15', 'k2_16', 'k2_17', 'k2_18', 'k2_19', 'k2_20', ...
    'k2_21', 'k2_22', 'k2_23', 'k2_24', 'k2_25', 'k2_26', 'k2_27', 'k2_28', 'k2_29', 'k2_30', ...
    'k2_31', 'k2_32', 'k2_33', 'k2_34', 'k2_35', 'k2_36', 'k2_37', 'k2_38', 'k2_39', 'k2_40', ...
    'k2_41', 'k2_42', 'k2_43', 'k2_44', 'k2_45', 'k2_46', 'k2_47', 'k2_48', 'k2_49', 'k2_50', ...
    'k2_51', 'k2_52', 'k2_53', 'k2_54', 'k2_55', 'k2_56', 'k2_57', 'k2_58', 'k2_59', 'k2_60', ...
    'k2_61', 'k2_62', 'k2_63', 'k2_64', 'k2_65', 'k2_66', 'k2_67', 'k2_68', 'k2_69', 'k2_70', ...
    'k2_71', 'k2_72', 'k2_73', 'k2_74', 'k2_75', 'k2_76', 'k2_77', 'k2_78', 'k2_79'};
K2_embed  = [ ...
    0.5; 0.6456022116492058; 0.6696970699848848; 0.3606960415397722; 0.2815734807851035; 0.01912458303861443; 0.06516718694986258; 0.001369307427668739; ...
    0.2136260496664696; 0.02232857008730477; 0.3276751792012505; 0.4137309182859328; 0; 0.576385448913779; 0.07838735086544352; 0.8813107770530868; ...
    0.267105595873055; 0.239495438943328; 0.07159933499747269; 0.003070493975293582; 0.000401849992788396; 0.4710560729266132; 0.1780137649123472; 0.9395622841132336; ...
    0.1178508994657826; 0.622020776547205; 0.1009401544387394; 0.4323579095172346; 0.8529976168847437; 0.1363083166395744; 0.05334819868949733; 0.9101646956939311; ...
    0.3955806507687764; 0.5327653291862174; 0.377903555740975; 0.01620616436152157; 0.6943084966914098; 0.771273215457186; 0.2964884724800591; 0.1461289487467751; ...
    0.1563503851402328; 0.7979818077037905; 0.4911341558143484; 0.002120976977713276; 0.5117027859530133; 2.877219225238835e-05; 0.01356553727584964; 0.03372730156806651; ...
    1; 0.04794986486067369; 0.5543251172974017; 0.04288439236763809; 0.3439544748126391; 0.1092046217017684; 0.02582559671046847; 0.4514651364413496; ...
    0.2530809040166006; 0.009084800566407239; 0.5989495903719194; 0.825222280179704; 0.2013339122749826; 0.08553664831325386; 0.2263451799111488; 0.1268838679399454; ...
    0.004230472948477047; 0.0590853664859649; 0.03814564327944279; 0.7450934941138824; 0.00015186054114922; 0.969506430417433; 0.09305252204336338; 0.3118544339565853; ...
    0.007227247932355934; 0.02962285861716651; 0.01119458360263941; 0.1669771681279394; 0.7194396084402195; 0.005612482194179324; 0.0008015247415225937; ...
];
ProblemData = { ...
    [0; 1]; ... % x1 C
    K2_labels; ... % x2 K
};
x_anchor = {0.5, 'k2_1'};
anchors_set = [0.5 0 1; 0.5 0 1];

PB = struct();
PB.name = 'Deb521a_mix';
PB.problem = 'Deb521a';
PB.source = 'MOModels_Matlab';
PB.type = 'MOO_MIXED';
PB.nvar = 2; PB.n = 2; PB.nobj = 2; PB.m = 2;
PB.var_types = var_types;
PB.type_counts = struct('C', 1, 'D', 0, 'K', 1);
PB.ProblemData = ProblemData;
PB.strategy = 'moderate'; PB.kappa = 10000;
PB.lb_orig = lb_orig; PB.ub_orig = ub_orig;
PB.lb_C_work = lb_C_work; PB.ub_C_work = ub_C_work;
PB.x_anchor = x_anchor;
PB.anchors_set = anchors_set;
PB.K2_labels = K2_labels; PB.K2_embed = K2_embed;
PB.pareto_front_known = true;
PB.pareto_set_known = true;
PB.pf_type = 'convex';
PB.ideal_point = [0;0];
PB.nadir_point = [1;1];
PB.core = @(xh) Deb521a_orig(xh);
PB.decode = @(xr) decode(xr, PB);
PB.func_F = @(xr) objective(xr, PB);
PB_cached = PB;
else
    PB = PB_cached;
end

if nargin == 0
    varargout{1} = PB; return
end
arg1 = varargin{1};
if ischar(arg1) || (isstring(arg1) && isscalar(arg1))
    key = lower(char(arg1));
    switch key
        case {'problemdata','bounds','domain'}
            varargout{1} = PB.ProblemData; return
        case 'var_types'
            varargout{1} = PB.var_types; return
        case 'info'
            varargout{1} = PB; return
        otherwise
            error('Unknown string argument: %s', char(arg1));
    end
end
varargout{1} = PB.func_F(arg1);
end

function F = objective(xr, PB)
xh = decode(xr, PB);
F = PB.core(xh);
F = F(:);
end

function xh = decode(xr, PB)
if ~iscell(xr) || numel(xr) ~= 2
    error('Deb521a_mix: input must be a cell array with exactly 2 entries.');
end
xh = zeros(2,1);
tmp = check_C(xr{1}, PB.lb_C_work(1), PB.ub_C_work(1), 'x1');
xh(1) = map_C_to_orig(tmp, PB.lb_C_work(1), PB.ub_C_work(1), PB.lb_orig(1), PB.ub_orig(1));
xh(2) = check_K(xr{2}, PB.K2_labels, PB.K2_embed, 'x2');
end

function v = check_C(val, a, b, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('Deb521a_mix: %s must be a real scalar.', name);
end
if val < a || val > b
    error('Deb521a_mix: %s=%g outside [%g,%g].', name, val, a, b);
end
v = double(val);
end

function xorig = map_C_to_orig(xwork, lbw, ubw, lbo, ubo)
if abs(ubw - lbw) <= 1e-14
    t = 0;
else
    t = (xwork - lbw) / (ubw - lbw);
end
t = max(0, min(1, t));
xorig = lbo + t * (ubo - lbo);
end

function v = check_D(val, grid, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('Deb521a_mix: %s must be a real scalar.', name);
end
grid = grid(:);
[dmin, idx] = min(abs(grid - val));
if dmin > 1e-10 * max(1, max(abs(grid)))
    error('Deb521a_mix: %s=%g not in grid.', name, val);
end
v = grid(idx);
end

function v = check_K(label, labels, embed, name)
if isstring(label), label = char(label); end
if ~(ischar(label) && isrow(label))
    error('Deb521a_mix: %s must be a char vector or scalar string.', name);
end
idx = find(strcmp(label, labels), 1);
if isempty(idx)
    error('Deb521a_mix: %s unknown label ''%s''.', name, label);
end
v = embed(idx);
end


% -------------------------------------------------------------------------
% Embedded original continuous MOO problem (top-level function renamed only)
% -------------------------------------------------------------------------
function f = Deb521a_orig(x)
%###############################################################################
%
%   As described by K. Deb in "Multi-objective Genetic Algorithms: Problem
%   Difficulties and Construction of Test Problems", Evolutionary Computation 
%   7(3): 205-230, 1999.
%
%   Example 5.2.1 (Biased Search Space).
%
%   This file is part of a collection of problems developed for
%   derivative-free multiobjective optimization in
%   A. L. Custódio, J. F. A. Madeira, A. I. F. Vaz, and L. N. Vicente,
%   Direct Multisearch for Multiobjective Optimization, 2010.
%
%   Written by the authors in June 1, 2010.
%
%   MATLAB version by J. F. A. Madeira
%   November 7, 2025
%
%###############################################################################
%
% Problem characteristics:
% - Number of variables: 2
% - Number of objectives: 2
%   Bounds: x1 in [0,1], x2 in [0,1]
%
%
M = 2; % Number of objectives (fixed)
% Check dimension
n = length(x);
if n ~= 2
    error('Deb521a requires exactly 2 variables, %d provided', n);
end
% Ensure x is a column vector
x = x(:);
% Parameters
gamma = 0.25;
% Initialize objectives
f = zeros(M, 1);
% Function f1
ff1 = x(1);
% g function
gx = 1 + x(2)^gamma;
% h function
h = 1 - (ff1/gx)^2;
% Objective functions
f(1) = ff1;
f(2) = gx * h;
end

