function varargout = I4_mix(varargin)
%I4_MIX  Self-contained mixed-variable MOO adaptation of I4.
%
% Auto-generated by generate_selfcontained_wrappers_MOO_mix.m
% Source: I4, n=8, m=3, strategy=moderate, kappa=10000
% Variable pattern: C,K,D,C,D,K,C,K
% D variables: nonuniform sorted finite sets with injected anchors.
% K variables: labels with permuted nonuniform numeric embeddings; labels carry no ordinal information.
%
%   x1   C [0,1] -> orig [0,1]
%   x2   K labels {k2_1,...,k2_20}, 20 levels, permuted embedding in [0,1]
%   x3   D sorted nonuniform grid [0,...,1], 64 values
%   x4   C [0,4.64158883361] -> orig [0,1]
%   x5   D sorted nonuniform grid [0,...,1], 78 values
%   x6   K labels {k6_1,...,k6_26}, 26 levels, permuted embedding in [0,1]
%   x7   C [0,21.5443469003] -> orig [0,1]
%   x8   K labels {k8_1,...,k8_121}, 121 levels, permuted embedding in [0,1]
%
% Usage:
%   PB = I4_mix()
%   F  = PB.func_F(xcell)       % recommended inside benchmark loops
%   F  = I4_mix(xcell)              % also valid; PB is memoized persistently
%   PD = I4_mix('ProblemData')
%

persistent PB_cached
if isempty(PB_cached)
lb_orig = [0; 0; 0; 0; 0; 0; 0; 0];
ub_orig = [1; 1; 1; 1; 1; 1; 1; 1];
lb_C_work = [0; 0; 0; 0; 0; 0; 0; 0];
ub_C_work = [1; 1; 1; 4.641588833612778; 1; 1; 21.54434690031884; 1];
var_types = {'C', 'K', 'D', 'C', 'D', 'K', 'C', 'K'};
K2_labels = { ...
    'k2_1', 'k2_2', 'k2_3', 'k2_4', 'k2_5', 'k2_6', 'k2_7', 'k2_8', 'k2_9', 'k2_10', ...
    'k2_11', 'k2_12', 'k2_13', 'k2_14', 'k2_15', 'k2_16', 'k2_17', 'k2_18', 'k2_19', 'k2_20'};
K2_embed  = [ ...
    1; 0.01191467962467751; 0; 0.7657178460704521; 0.0008530831378348473; 0.8783050300476408; 0.4022123515713952; 0.3319145938801874; ...
    0.4805058100724487; 0.5; 0.6620325092489989; 0.1254317052296445; 0.09103882707891367; 0.06288605607634637; 0.2693604333590938; 0.2142847958876969; ...
    0.5670356699013791; 0.04059937688478518; 0.004502599795680177; 0.02376486419777764; ...
];
D3_vals = [ ...
    0; 0.0005770148775317667; 0.002009282506662094; 0.004168744415538648; 0.006996728071982938; 0.01045521622186251; 0.01451641119673897; 0.01915858733228839; ...
    0.0243640222571782; 0.03011781962437861; 0.03640717748530074; 0.04322090380170104; 0.05054907977743708; 0.05838281687272518; 0.06671407597632657; 0.07553552938630932; ...
    0.08484045320058317; 0.09462264188174122; 0.1048763393570154; 0.1155961826896215; 0.1267771554714021; 0.1384145488461686; 0.1505039286029537; 0.1630411071554817; ...
    0.1760221194973943; 0.1894432024239775; 0.2033007764614615; 0.2175914300587795; 0.2323119056838861; 0.247459087534308; 0.2630299906244901; 0.2954316172962645; ...
    0.3122569423661957; 0.329495176762869; 0.3471438620808935; 0.3652006252147411; 0.3836631730841973; 0.4025292878213266; 0.4217968223673567; 0.4414636964348377; ...
    0.4615278927963054; 0.4819874538656438; 0.5; 0.5028404785425766; 0.5240851192943241; 0.5457195794515658; 0.5677421106985134; 0.5901510107392069; ...
    0.6129446211241372; 0.6361213252230462; 0.6596795463312611; 0.6836177458982517; 0.7079344218682588; 0.7326281071238707; 0.7576973680243188; 0.7831408030310729; ...
    0.8089570414140125; 0.8351447420320892; 0.8617025921829469; 0.8886293065164736; 0.9159236260076964; 0.9435843169848408; 0.9716101702087264; 1; ...
];
D5_vals = [ ...
    0; 0.0004020839101796086; 0.001400137497996666; 0.002904925194146154; 0.004875561950292094; 0.007285556029754735; 0.01011553705638815; 0.01335036583638164; ...
    0.01697769280884773; 0.02098713768430972; 0.02536977962251383; 0.03011781962437861; 0.03522434592992608; 0.04068316469741805; 0.04648867399628546; 0.05263576763055285; ...
    0.05911976015284379; 0.06593632733020947; 0.07308145813219658; 0.08055141547909314; 0.0883427037643118; 0.09645204169410679; 0.1048763393570154; 0.1136126786981841; ...
    0.1226582967641388; 0.1320105712237661; 0.1416670077760251; 0.151625229134218; 0.1618829653374247; 0.1724380451867895; 0.1832883886412067; 0.1944320000360703; ...
    0.2058669620119596; 0.2175914300587795; 0.2296036275959659; 0.2419018415216719; 0.2544844181739434; 0.2673497596552303; 0.2939226044989864; 0.3076271621004971; ...
    0.3216085876092115; 0.3358655169114637; 0.3503966252548728; 0.3652006252147411; 0.3802762648097873; 0.3956223257531429; 0.4112376218261458; 0.4271209973638566; ...
    0.4432713258424357; 0.4596875085595709; 0.4763684734000753; 0.4933131736795802; 0.5; 0.5105205870599645; 0.5279897145307896; 0.5457195794515658; ...
    0.5637092266501682; 0.5819577215731601; 0.6004641494841685; 0.6192276147068094; 0.6382472399089658; 0.6575221654255055; 0.6770515486167723; 0.6968345632604117; ...
    0.7168703989742931; 0.7371582606684737; 0.7576973680243188; 0.778486954999033; 0.7995262693540067; 0.8208145722054924; 0.8423511375962451; 0.8641352520868626; ...
    0.8861662143656514; 0.9084433348759322; 0.9309659354597767; 0.9537333490172357; 0.9767449191801887; 1; ...
];
K6_labels = { ...
    'k6_1', 'k6_2', 'k6_3', 'k6_4', 'k6_5', 'k6_6', 'k6_7', 'k6_8', 'k6_9', 'k6_10', ...
    'k6_11', 'k6_12', 'k6_13', 'k6_14', 'k6_15', 'k6_16', 'k6_17', 'k6_18', 'k6_19', 'k6_20', ...
    'k6_21', 'k6_22', 'k6_23', 'k6_24', 'k6_25', 'k6_26'};
K6_embed  = [ ...
    0.5; 0.9066735768635092; 0.5175503677029233; 0.06491722516320722; 0.0004415134916675889; 0.6580672632168687; 0.02101222243523014; 0.002330322179873383; ...
    0.01229951420396986; 0.5853504664669779; 0.396297552790453; 0.1394075913296177; 0.006166446820814373; 0.04711717842993464; 0.1109031749048234; 0.4545670912564836; ...
    0.2934695194581322; 0; 0.3426351685931084; 0.08612435885098703; 0.03254670144569972; 0.7357976783249014; 0.2486859586863869; 1; ...
    0.818635899237781; 0.2081651504504331; ...
];
K8_labels = { ...
    'k8_1', 'k8_2', 'k8_3', 'k8_4', 'k8_5', 'k8_6', 'k8_7', 'k8_8', 'k8_9', 'k8_10', ...
    'k8_11', 'k8_12', 'k8_13', 'k8_14', 'k8_15', 'k8_16', 'k8_17', 'k8_18', 'k8_19', 'k8_20', ...
    'k8_21', 'k8_22', 'k8_23', 'k8_24', 'k8_25', 'k8_26', 'k8_27', 'k8_28', 'k8_29', 'k8_30', ...
    'k8_31', 'k8_32', 'k8_33', 'k8_34', 'k8_35', 'k8_36', 'k8_37', 'k8_38', 'k8_39', 'k8_40', ...
    'k8_41', 'k8_42', 'k8_43', 'k8_44', 'k8_45', 'k8_46', 'k8_47', 'k8_48', 'k8_49', 'k8_50', ...
    'k8_51', 'k8_52', 'k8_53', 'k8_54', 'k8_55', 'k8_56', 'k8_57', 'k8_58', 'k8_59', 'k8_60', ...
    'k8_61', 'k8_62', 'k8_63', 'k8_64', 'k8_65', 'k8_66', 'k8_67', 'k8_68', 'k8_69', 'k8_70', ...
    'k8_71', 'k8_72', 'k8_73', 'k8_74', 'k8_75', 'k8_76', 'k8_77', 'k8_78', 'k8_79', 'k8_80', ...
    'k8_81', 'k8_82', 'k8_83', 'k8_84', 'k8_85', 'k8_86', 'k8_87', 'k8_88', 'k8_89', 'k8_90', ...
    'k8_91', 'k8_92', 'k8_93', 'k8_94', 'k8_95', 'k8_96', 'k8_97', 'k8_98', 'k8_99', 'k8_100', ...
    'k8_101', 'k8_102', 'k8_103', 'k8_104', 'k8_105', 'k8_106', 'k8_107', 'k8_108', 'k8_109', 'k8_110', ...
    'k8_111', 'k8_112', 'k8_113', 'k8_114', 'k8_115', 'k8_116', 'k8_117', 'k8_118', 'k8_119', 'k8_120', ...
    'k8_121'};
K8_embed  = [ ...
    0.001091943847216863; 0.377903555740975; 0.00794059357229376; 0.1223187459465567; 0.6456022116492058; 0.5148305986772841; 0.1675192280672599; 0.5708232608843693; ...
    0.847399618009957; 0.3341316620288669; 0.003230780506818012; 0.2649737348600972; 0.661205270299008; 0.0001429078287272895; 0.4248496805467504; 0.07597072406443715; ...
    0.1471329806411724; 0.759427074016114; 0.5; 0.8115353718261809; 0.04847461967901755; 0.1282724624910471; 0.5853504664669779; 0.08049396238517001; ...
    0.1819742078053405; 0.4495327038438292; 0.1343918815190893; 0.01897194320777961; 0.006801176275750971; 0.1605522049340344; 0.2295921660919542; 0.1109031749048234; ...
    0.07159933499747269; 0.7425044932503653; 0.9218583284399169; 0.004824241663310446; 0.960465627023109; 0.1746594925489957; 0.5285131470833478; 0.6302160749086669; ...
    0.0007542720420681457; 0; 0.03883587322248032; 0.615045989763944; 0.02787648702973483; 0.08517052080053805; 0.204976967755344; 0.105438657720985; ...
    0.2837821315151189; 0.6770261159650239; 0.0004869596985443575; 0.1406782951409983; 1; 0.01525075403640838; 0.238160895593106; 0.01705216174686891; ...
    0.0002850420866935585; 0.3556248134675; 0.04191070413949605; 0.9029003603145904; 0.01199426532890577; 0.8656718072012205; 0.6000910806106846; 0.1537572009232648; ...
    0.02101222243523014; 0.3666654831080765; 0.2934695194581322; 0.9410464867688476; 0.2212060226325093; 0.7765725275664881; 0.8841717865652724; 0.9801165368745665; ...
    0.02546250015287328; 0.4880912537018398; 0.7093246032323672; 0.3134159806964015; 0.001504461153181454; 0.8293544104973307; 0.3893400271206263; 0.09498937770848064; ...
    0.06737830265435749; 0.5565085718564609; 0.4621800718612763; 0.01053462357010396; 0.7258039497448974; 0.6930656086299476; 0.01356553727584964; 5.400537661926498e-05; ...
    0.05560207655106707; 1.023210550280666e-05; 0.3236771501308581; 0.04512305186817801; 0.005763314178089755; 0.1165294244813743; 0.03041895460103605; 0.2130013363524494; ...
    0.05938122426882986; 0.1001345165815971; 0.5424055017249969; 0.400975885560678; 0.5013569413029385; 0.06330611194160086; 0.2742838933794407; 0.3033471183928589; ...
    0.1971317664392385; 0.001995937933394686; 0.3447805434727414; 0.7939416847535639; 0.09000184928308985; 0.002570188697827454; 0.02317506870324658; 0.003981071705534973; ...
    0.03589682359365735; 0.03309178579435153; 0.009184223012847232; 0.05196708014027375; 0.4370895578112912; 0.2558505765526843; 0.4750326084529071; 0.4128121120804482; ...
    0.246913329624783; ...
];
ProblemData = { ...
    [0; 1]; ... % x1 C
    K2_labels; ... % x2 K
    {D3_vals}; ... % x3 D
    [0; 4.641588833612778]; ... % x4 C
    {D5_vals}; ... % x5 D
    K6_labels; ... % x6 K
    [0; 21.54434690031884]; ... % x7 C
    K8_labels; ... % x8 K
};
x_anchor = {0.5, 'k2_10', 0.5, 2.320794416806389, 0.5, 'k6_1', 10.77217345015942, 'k8_19'};
anchors_set = [ ...
    0.5 0 1; ...
    0.5 0 1; ...
    0.5 0 1; ...
    0.5 0 1; ...
    0.5 0 1; ...
    0.5 0 1; ...
    0.5 0 1; ...
    0.5 0 1];

PB = struct();
PB.name = 'I4_mix';
PB.problem = 'I4';
PB.source = 'MOModels_Matlab';
PB.type = 'MOO_MIXED';
PB.nvar = 8; PB.n = 8; PB.nobj = 3; PB.m = 3;
PB.var_types = var_types;
PB.type_counts = struct('C', 3, 'D', 2, 'K', 3);
PB.ProblemData = ProblemData;
PB.strategy = 'moderate'; PB.kappa = 10000;
PB.lb_orig = lb_orig; PB.ub_orig = ub_orig;
PB.lb_C_work = lb_C_work; PB.ub_C_work = ub_C_work;
PB.x_anchor = x_anchor;
PB.anchors_set = anchors_set;
PB.K2_labels = K2_labels; PB.K2_embed = K2_embed;
PB.D3_vals = D3_vals;
PB.D5_vals = D5_vals;
PB.K6_labels = K6_labels; PB.K6_embed = K6_embed;
PB.K8_labels = K8_labels; PB.K8_embed = K8_embed;
PB.pareto_front_known = false;
PB.pareto_set_known = false;
PB.pf_type = 'unknown';
PB.ideal_point = [];
PB.nadir_point = [];
PB.core = @(xh) I4_orig(xh);
PB.decode = @(xr) decode(xr, PB);
PB.func_F = @(xr) objective(xr, PB);
PB_cached = PB;
else
    PB = PB_cached;
end

if nargin == 0
    varargout{1} = PB; return
end
arg1 = varargin{1};
if ischar(arg1) || (isstring(arg1) && isscalar(arg1))
    key = lower(char(arg1));
    switch key
        case {'problemdata','bounds','domain'}
            varargout{1} = PB.ProblemData; return
        case 'var_types'
            varargout{1} = PB.var_types; return
        case 'info'
            varargout{1} = PB; return
        otherwise
            error('Unknown string argument: %s', char(arg1));
    end
end
varargout{1} = PB.func_F(arg1);
end

function F = objective(xr, PB)
xh = decode(xr, PB);
F = PB.core(xh);
F = F(:);
end

function xh = decode(xr, PB)
if ~iscell(xr) || numel(xr) ~= 8
    error('I4_mix: input must be a cell array with exactly 8 entries.');
end
xh = zeros(8,1);
tmp = check_C(xr{1}, PB.lb_C_work(1), PB.ub_C_work(1), 'x1');
xh(1) = map_C_to_orig(tmp, PB.lb_C_work(1), PB.ub_C_work(1), PB.lb_orig(1), PB.ub_orig(1));
xh(2) = check_K(xr{2}, PB.K2_labels, PB.K2_embed, 'x2');
xh(3) = check_D(xr{3}, PB.D3_vals, 'x3');
tmp = check_C(xr{4}, PB.lb_C_work(4), PB.ub_C_work(4), 'x4');
xh(4) = map_C_to_orig(tmp, PB.lb_C_work(4), PB.ub_C_work(4), PB.lb_orig(4), PB.ub_orig(4));
xh(5) = check_D(xr{5}, PB.D5_vals, 'x5');
xh(6) = check_K(xr{6}, PB.K6_labels, PB.K6_embed, 'x6');
tmp = check_C(xr{7}, PB.lb_C_work(7), PB.ub_C_work(7), 'x7');
xh(7) = map_C_to_orig(tmp, PB.lb_C_work(7), PB.ub_C_work(7), PB.lb_orig(7), PB.ub_orig(7));
xh(8) = check_K(xr{8}, PB.K8_labels, PB.K8_embed, 'x8');
end

function v = check_C(val, a, b, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('I4_mix: %s must be a real scalar.', name);
end
if val < a || val > b
    error('I4_mix: %s=%g outside [%g,%g].', name, val, a, b);
end
v = double(val);
end

function xorig = map_C_to_orig(xwork, lbw, ubw, lbo, ubo)
if abs(ubw - lbw) <= 1e-14
    t = 0;
else
    t = (xwork - lbw) / (ubw - lbw);
end
t = max(0, min(1, t));
xorig = lbo + t * (ubo - lbo);
end

function v = check_D(val, grid, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('I4_mix: %s must be a real scalar.', name);
end
grid = grid(:);
[dmin, idx] = min(abs(grid - val));
if dmin > 1e-10 * max(1, max(abs(grid)))
    error('I4_mix: %s=%g not in grid.', name, val);
end
v = grid(idx);
end

function v = check_K(label, labels, embed, name)
if isstring(label), label = char(label); end
if ~(ischar(label) && isrow(label))
    error('I4_mix: %s must be a char vector or scalar string.', name);
end
idx = find(strcmp(label, labels), 1);
if isempty(idx)
    error('I4_mix: %s unknown label ''%s''.', name, label);
end
v = embed(idx);
end


% -------------------------------------------------------------------------
% Embedded original continuous MOO problem (top-level function renamed only)
% -------------------------------------------------------------------------
function f = I4_orig(z)
%###############################################################################
%
%   As described by Huband et al. in "A Scalable Multi-objective Test Problem
%   Toolkit", in C. A. Coello Coello et al. (Eds.): EMO 2005, LNCS 3410, 
%   pp. 280–295, 2005, Springer-Verlag Berlin Heidelberg 2005.
%
%   Example I4.
%
%   This file is part of a collection of problems developed for
%   derivative-free multiobjective optimization in
%   A. L. Custódio, J. F. A. Madeira, A. I. F. Vaz, and L. N. Vicente,
%   Direct Multisearch for Multiobjective Optimization, 2010.
%
%   Written by the authors in June 1, 2010.
%
%   MATLAB version by J. F. A. Madeira
%   November 7, 2025
%
%###############################################################################
%
% Problem characteristics:
% - Number of variables: 8 (k=4, l=4)
% - Number of objectives: 3
%   Bounds: x1 in [0,1], x2 in [0,1], x3 in [0,1], x4 in [0,1], x5 in [0,1], x6 in [0,1], x7 in [0,1], x8 in [0,1]
%
%
% Parameters
M = 3; % Number of objectives (fixed)
k = 4;
l = 4;
n = k + l;
% Check dimension
if length(z) ~= n
    error('I4 requires exactly %d variables, %d provided', n, length(z));
end
% Ensure z is a column vector
z = z(:);
% Constants
pi2 = pi/2;
S = ones(M, 1);
A = ones(M-1, 1);
% Transform z into [0,1] set
zmax = ones(n, 1);
y = z ./ zmax;
% First level mapping
t1 = y;
% Second level mapping
t2 = zeros(n, 1);
for i = 1:n
    if i <= k
        t2(i) = t1(i);
    else
        t2(i) = abs(t1(i) - 0.35) / abs(floor(0.35 - t1(i)) + 0.35);
    end
end
% Third level mapping
t3 = zeros(M, 1);
for i = 1:M
    if i <= M-1
        % Complex calculation for position-related transformation
        j_start = round((i-1)*k/(M-1) + 1);
        j_end = round(i*k/(M-1));
        
        sum_val = 0;
        count = 0;
        for ii = j_start:j_end
            inner_sum = t2(ii);
            for jj = 0:(k/(M-1)-2)
                idx = j_start + mod(ii + jj - j_start + 1, j_end - j_start + 1);
                inner_sum = inner_sum + abs(t2(ii) - t2(idx));
            end
            sum_val = sum_val + inner_sum;
            count = count + 1;
        end
        
        denominator = count / (k/(M-1)) * ceil(k/(M-1)/2) * (1 + 2*k/(M-1) - 2*ceil(k/(M-1)/2));
        if denominator == 0
            t3(i) = sum_val;
        else
            t3(i) = sum_val / denominator;
        end
    else
        % For the last objective
        sum_val = 0;
        count = 0;
        for ii = (k+1):n
            inner_sum = t2(ii);
            for jj = 0:(l-2)
                idx = k + 1 + mod(ii + jj - (k+1) + 1, n - k);
                inner_sum = inner_sum + abs(t2(ii) - t2(idx));
            end
            sum_val = sum_val + inner_sum;
            count = count + 1;
        end
        
        denominator = (count/l) * ceil(l/2) * (1 + 2*l - 2*ceil(l/2));
        if denominator == 0
            t3(i) = sum_val;
        else
            t3(i) = sum_val / denominator;
        end
    end
end
% Define objective function variables
x = zeros(M, 1);
for i = 1:M
    if i <= M-1
        x(i) = max(t3(M), A(i)) * (t3(i) - 0.5) + 0.5;
    else
        x(i) = t3(M);
    end
end
% Define shape function h
h = zeros(M, 1);
for m = 1:M
    if m == 1
        h(m) = 1;
        for i = 1:M-1
            h(m) = h(m) * sin(x(i) * pi2);
        end
    elseif m <= M-1
        h(m) = 1;
        for i = 1:M-m
            h(m) = h(m) * sin(x(i) * pi2);
        end
        h(m) = h(m) * cos(x(M-m+1) * pi2);
    else
        h(m) = cos(x(1) * pi2);
    end
end
% Calculate objectives
f = zeros(M, 1);
for m = 1:M
    f(m) = x(M) + S(m) * h(m);
end
end

