function varargout = Jin4_mix(varargin)
%JIN4_MIX  Self-contained mixed-variable MOO adaptation of Jin4.
%
% Auto-generated by generate_selfcontained_wrappers_MOO_mix.m
% Source: Jin4, n=2, m=2, strategy=moderate, kappa=10000
% Variable pattern: C,K
% D variables: nonuniform sorted finite sets with injected anchors.
% K variables: labels with permuted nonuniform numeric embeddings; labels carry no ordinal information.
%
%   x1   C [0,1] -> orig [0,1]
%   x2   K labels {k2_1,...,k2_73}, 73 levels, permuted embedding in [0,1]
%
% Usage:
%   PB = Jin4_mix()
%   F  = PB.func_F(xcell)       % recommended inside benchmark loops
%   F  = Jin4_mix(xcell)              % also valid; PB is memoized persistently
%   PD = Jin4_mix('ProblemData')
%

persistent PB_cached
if isempty(PB_cached)
lb_orig = [0; 0];
ub_orig = [1; 1];
lb_C_work = [0; 0];
ub_C_work = [1; 1];
var_types = {'C', 'K'};
K2_labels = { ...
    'k2_1', 'k2_2', 'k2_3', 'k2_4', 'k2_5', 'k2_6', 'k2_7', 'k2_8', 'k2_9', 'k2_10', ...
    'k2_11', 'k2_12', 'k2_13', 'k2_14', 'k2_15', 'k2_16', 'k2_17', 'k2_18', 'k2_19', 'k2_20', ...
    'k2_21', 'k2_22', 'k2_23', 'k2_24', 'k2_25', 'k2_26', 'k2_27', 'k2_28', 'k2_29', 'k2_30', ...
    'k2_31', 'k2_32', 'k2_33', 'k2_34', 'k2_35', 'k2_36', 'k2_37', 'k2_38', 'k2_39', 'k2_40', ...
    'k2_41', 'k2_42', 'k2_43', 'k2_44', 'k2_45', 'k2_46', 'k2_47', 'k2_48', 'k2_49', 'k2_50', ...
    'k2_51', 'k2_52', 'k2_53', 'k2_54', 'k2_55', 'k2_56', 'k2_57', 'k2_58', 'k2_59', 'k2_60', ...
    'k2_61', 'k2_62', 'k2_63', 'k2_64', 'k2_65', 'k2_66', 'k2_67', 'k2_68', 'k2_69', 'k2_70', ...
    'k2_71', 'k2_72', 'k2_73'};
K2_embed  = [ ...
    0.671728248995761; 0.4579415326240115; 0.3236771501308581; 0.1537572009232648; 0.04622468902698076; 0.3412092566426912; 0.1651776980741374; 0.9669901393476904; ...
    0.4370895578112912; 0.8115353718261809; 0.00875794086749827; 0.1223187459465567; 0.05196708014027375; 0.8718131171683238; 0.00372080837980397; 0.5951537756680503; ...
    0.2439753713764724; 0.3066821026226881; 0.6456022116492058; 0.5013569413029385; 0.01963854436648566; 0.377903555740975; 0.1036528585905691; 0.2295921660919542; ...
    0.06464706536750314; 0.03589682359365735; 0.01356553727584964; 0.005126464772080319; 0.07159933499747269; 0.02317506870324658; 0.01100891333717856; 0.5470830675379204; ...
    0.5708232608843693; 0.006801176275750971; 0.132333583719998; 0.9346248083476736; 0.2902193078102235; 0.5; 0.04087056588040972; 0.2588709185359725; ...
    0; 0.01643864641281322; 0.2742838933794407; 0.6984608423178577; 0.07896925290925431; 0.3592831647922721; 0.0581053929496813; 0.7537614912817806; ...
    0.7823373497727385; 0.8413593687027142; 0.02705764328423417; 0.08676369593642203; 0.2157161399878615; 0.6200787330191604; 3.486599058634577e-05; 0.0004869596985443575; ...
    0.4168022156863458; 0.03129532167362784; 0.000184023801582466; 0.1770782881855218; 0.9029003603145904; 0.0009712834478342614; 0.5239290308825428; 0.001659319507673197; ...
    0.1127605546751596; 0.09498937770848064; 0.002570188697827454; 0.7258039497448974; 0.4793625430019087; 0.397075051257577; 1; 0.2023420503038015; ...
    0.1428110974416723; ...
];
ProblemData = { ...
    [0; 1]; ... % x1 C
    K2_labels; ... % x2 K
};
x_anchor = {0.5, 'k2_38'};
anchors_set = [0.5 0 1; 0.5 0 1];

PB = struct();
PB.name = 'Jin4_mix';
PB.problem = 'Jin4';
PB.source = 'MOModels_Matlab';
PB.type = 'MOO_MIXED';
PB.nvar = 2; PB.n = 2; PB.nobj = 2; PB.m = 2;
PB.var_types = var_types;
PB.type_counts = struct('C', 1, 'D', 0, 'K', 1);
PB.ProblemData = ProblemData;
PB.strategy = 'moderate'; PB.kappa = 10000;
PB.lb_orig = lb_orig; PB.ub_orig = ub_orig;
PB.lb_C_work = lb_C_work; PB.ub_C_work = ub_C_work;
PB.x_anchor = x_anchor;
PB.anchors_set = anchors_set;
PB.K2_labels = K2_labels; PB.K2_embed = K2_embed;
PB.pareto_front_known = false;
PB.pareto_set_known = false;
PB.pf_type = 'unknown';
PB.ideal_point = [];
PB.nadir_point = [];
PB.core = @(xh) Jin4_orig(xh);
PB.decode = @(xr) decode(xr, PB);
PB.func_F = @(xr) objective(xr, PB);
PB_cached = PB;
else
    PB = PB_cached;
end

if nargin == 0
    varargout{1} = PB; return
end
arg1 = varargin{1};
if ischar(arg1) || (isstring(arg1) && isscalar(arg1))
    key = lower(char(arg1));
    switch key
        case {'problemdata','bounds','domain'}
            varargout{1} = PB.ProblemData; return
        case 'var_types'
            varargout{1} = PB.var_types; return
        case 'info'
            varargout{1} = PB; return
        otherwise
            error('Unknown string argument: %s', char(arg1));
    end
end
varargout{1} = PB.func_F(arg1);
end

function F = objective(xr, PB)
xh = decode(xr, PB);
F = PB.core(xh);
F = F(:);
end

function xh = decode(xr, PB)
if ~iscell(xr) || numel(xr) ~= 2
    error('Jin4_mix: input must be a cell array with exactly 2 entries.');
end
xh = zeros(2,1);
tmp = check_C(xr{1}, PB.lb_C_work(1), PB.ub_C_work(1), 'x1');
xh(1) = map_C_to_orig(tmp, PB.lb_C_work(1), PB.ub_C_work(1), PB.lb_orig(1), PB.ub_orig(1));
xh(2) = check_K(xr{2}, PB.K2_labels, PB.K2_embed, 'x2');
end

function v = check_C(val, a, b, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('Jin4_mix: %s must be a real scalar.', name);
end
if val < a || val > b
    error('Jin4_mix: %s=%g outside [%g,%g].', name, val, a, b);
end
v = double(val);
end

function xorig = map_C_to_orig(xwork, lbw, ubw, lbo, ubo)
if abs(ubw - lbw) <= 1e-14
    t = 0;
else
    t = (xwork - lbw) / (ubw - lbw);
end
t = max(0, min(1, t));
xorig = lbo + t * (ubo - lbo);
end

function v = check_D(val, grid, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('Jin4_mix: %s must be a real scalar.', name);
end
grid = grid(:);
[dmin, idx] = min(abs(grid - val));
if dmin > 1e-10 * max(1, max(abs(grid)))
    error('Jin4_mix: %s=%g not in grid.', name, val);
end
v = grid(idx);
end

function v = check_K(label, labels, embed, name)
if isstring(label), label = char(label); end
if ~(ischar(label) && isrow(label))
    error('Jin4_mix: %s must be a char vector or scalar string.', name);
end
idx = find(strcmp(label, labels), 1);
if isempty(idx)
    error('Jin4_mix: %s unknown label ''%s''.', name, label);
end
v = embed(idx);
end


% -------------------------------------------------------------------------
% Embedded original continuous MOO problem (top-level function renamed only)
% -------------------------------------------------------------------------
function f = Jin4_orig(x)
%###############################################################################
%
%   As described by Y. Jin, M. Olhofer and B. Sendhoff. "Dynamic weighted
%   aggregation for evolutionary multi-objective optimization: Why does it
%   work and how?", in Proceedings of Genetic and Evolutionary Computation 
%   Conference, pp.1042-1049, San Francisco, USA, 2001.
%
%   Test function 4, F4.
%
%   This file is part of a collection of problems developed for
%   derivative-free multiobjective optimization in
%   A. L. Custódio, J. F. A. Madeira, A. I. F. Vaz, and L. N. Vicente,
%   Direct Multisearch for Multiobjective Optimization, 2010.
%
%   Written by the authors in June 1, 2010.
%
%   MATLAB version by J. F. A. Madeira
%   November 7, 2025
%
%###############################################################################
%
% Problem characteristics:
% - Number of variables: 2
% - Number of objectives: 2
%   Bounds: x1 in [0,1], x2 in [0,1]
%
%
M = 2; % Number of objectives (fixed)
% Check dimension
n = length(x);
if n ~= 2
    error('Jin4 requires exactly 2 variables, %d provided', n);
end
% Ensure x is a column vector
x = x(:);
% Initialize objectives
f = zeros(M, 1);
% g(x) function
gx = 1 + (9 * sum(x(2:n))) / (n-1);
% Objective functions
f(1) = x(1);
f(2) = gx * (1 - (x(1)/gx)^0.25 - (x(1)/gx)^4);
end

