function varargout = lovison2_mix(varargin)
%LOVISON2_MIX  Self-contained mixed-variable MOO adaptation of lovison2.
%
% Auto-generated by generate_selfcontained_wrappers_MOO_mix.m
% Source: lovison2, n=2, m=2, strategy=moderate, kappa=10000
% Variable pattern: C,K
% D variables: nonuniform sorted finite sets with injected anchors.
% K variables: labels with permuted nonuniform numeric embeddings; labels carry no ordinal information.
%
%   x1   C [-0.5,0] -> orig [-0.5,0]
%   x2   K labels {k2_1,...,k2_112}, 112 levels, permuted embedding in [-0.5,0.5]
%
% Usage:
%   PB = lovison2_mix()
%   F  = PB.func_F(xcell)       % recommended inside benchmark loops
%   F  = lovison2_mix(xcell)              % also valid; PB is memoized persistently
%   PD = lovison2_mix('ProblemData')
%

persistent PB_cached
if isempty(PB_cached)
lb_orig = [-0.5; -0.5];
ub_orig = [0; 0.5];
lb_C_work = [-0.5; -0.5];
ub_C_work = [0; 0.5];
var_types = {'C', 'K'};
K2_labels = { ...
    'k2_1', 'k2_2', 'k2_3', 'k2_4', 'k2_5', 'k2_6', 'k2_7', 'k2_8', 'k2_9', 'k2_10', ...
    'k2_11', 'k2_12', 'k2_13', 'k2_14', 'k2_15', 'k2_16', 'k2_17', 'k2_18', 'k2_19', 'k2_20', ...
    'k2_21', 'k2_22', 'k2_23', 'k2_24', 'k2_25', 'k2_26', 'k2_27', 'k2_28', 'k2_29', 'k2_30', ...
    'k2_31', 'k2_32', 'k2_33', 'k2_34', 'k2_35', 'k2_36', 'k2_37', 'k2_38', 'k2_39', 'k2_40', ...
    'k2_41', 'k2_42', 'k2_43', 'k2_44', 'k2_45', 'k2_46', 'k2_47', 'k2_48', 'k2_49', 'k2_50', ...
    'k2_51', 'k2_52', 'k2_53', 'k2_54', 'k2_55', 'k2_56', 'k2_57', 'k2_58', 'k2_59', 'k2_60', ...
    'k2_61', 'k2_62', 'k2_63', 'k2_64', 'k2_65', 'k2_66', 'k2_67', 'k2_68', 'k2_69', 'k2_70', ...
    'k2_71', 'k2_72', 'k2_73', 'k2_74', 'k2_75', 'k2_76', 'k2_77', 'k2_78', 'k2_79', 'k2_80', ...
    'k2_81', 'k2_82', 'k2_83', 'k2_84', 'k2_85', 'k2_86', 'k2_87', 'k2_88', 'k2_89', 'k2_90', ...
    'k2_91', 'k2_92', 'k2_93', 'k2_94', 'k2_95', 'k2_96', 'k2_97', 'k2_98', 'k2_99', 'k2_100', ...
    'k2_101', 'k2_102', 'k2_103', 'k2_104', 'k2_105', 'k2_106', 'k2_107', 'k2_108', 'k2_109', 'k2_110', ...
    'k2_111', 'k2_112'};
K2_embed  = [ ...
    0.1045147104267461; -0.4917994331619066; 0.4156846149292388; -0.2128358002578289; -0.3854658798383681; 0.120760668974511; 0.2057905028996792; -0.4633221283735683; ...
    -0.4996563084694725; -0.1578276694218745; -0.1097239659740136; -0.2528475580995254; -0.002248849399738018; 0.2598875305079185; -0.4994128448677902; 0.05727692047134048; ...
    -0.4663877267946059; 0.4785145669383197; -0.07120284287841899; 0; -0.4494658693448512; -0.1805060279341819; -0.3064130329544427; -0.2623069655817872; ...
    -0.4889260575495827; -0.4600993430848125; 0.297252974036166; -0.4930508427939345; -0.4720564954982883; 0.4573008531750242; -0.5; 0.04202726621332176; ...
    -0.03055048337277827; -0.4567171487372552; -0.453173368669744; -0.2980124950842121; -0.496900976632793; -0.499827687865503; -0.4855378289702308; -0.3792620919185196; ...
    0.0885195129174644; 0.01226553469702452; -0.4329573993370039; -0.4455925581427613; 0.2235641036150444; 0.2784394747018516; -0.05789047665617186; -0.4981859852264133; ...
    -0.3594938146991992; -0.09711836363358628; -0.469298408701288; 0.2415960920677152; -0.2431721183893856; -0.345334562802738; 0.4363578679238093; -0.3728665858812306; ...
    -0.337956029632133; -0.280583300092155; -0.4236682036770761; 0.395280092385492; -0.4746643628233315; -0.352513299021094; -0.4904255726239737; 0.5; ...
    -0.4990905311016362; -0.01652046400738516; 0.3552732031737958; 0.1882742210800683; 0.137258499374736; -0.499987662565758; -0.4872978024391444; -0.1461470322655542; ...
    0.3163290716197418; -0.1692802378479381; -0.2894030702214999; -0.4771244440643863; -0.4986833809124352; -0.3225933584256909; -0.4136685907843217; -0.08427839882591293; ...
    -0.4975933835907404; 0.3751432928531263; -0.3303761415380437; -0.483643256605201; -0.4083977572159042; -0.2231676070134154; -0.1915063411801706; -0.3973050366375158; ...
    0.1540093051410169; -0.3914796278359219; 0.07277395820207821; -0.4373403222042176; -0.2022824904533648; -0.4794392342633791; -0.4951997943760283; -0.4999348826316763; ...
    -0.1342370468483384; -0.4415513813329223; -0.3662777052836564; -0.4029438303259266; 0.1710141826131304; -0.122096444259025; -0.04434009036696213; -0.4187581306597822; ...
    -0.2332792593460004; -0.4284006650025273; -0.4816112944678704; -0.4961044633441081; 0.02702385407124797; -0.4941831361812888; 0.33566880438285; -0.2715517414320067; ...
];
ProblemData = { ...
    [-0.5; 0]; ... % x1 C
    K2_labels; ... % x2 K
};
x_anchor = {-0.25, 'k2_20'};
anchors_set = [-0.25 -0.5 0; 0 -0.5 0.5];

PB = struct();
PB.name = 'lovison2_mix';
PB.problem = 'lovison2';
PB.source = 'MOModels_Matlab';
PB.type = 'MOO_MIXED';
PB.nvar = 2; PB.n = 2; PB.nobj = 2; PB.m = 2;
PB.var_types = var_types;
PB.type_counts = struct('C', 1, 'D', 0, 'K', 1);
PB.ProblemData = ProblemData;
PB.strategy = 'moderate'; PB.kappa = 10000;
PB.lb_orig = lb_orig; PB.ub_orig = ub_orig;
PB.lb_C_work = lb_C_work; PB.ub_C_work = ub_C_work;
PB.x_anchor = x_anchor;
PB.anchors_set = anchors_set;
PB.K2_labels = K2_labels; PB.K2_embed = K2_embed;
PB.pareto_front_known = false;
PB.pareto_set_known = false;
PB.pf_type = 'unknown';
PB.ideal_point = [];
PB.nadir_point = [];
PB.core = @(xh) lovison2_orig(xh);
PB.decode = @(xr) decode(xr, PB);
PB.func_F = @(xr) objective(xr, PB);
PB_cached = PB;
else
    PB = PB_cached;
end

if nargin == 0
    varargout{1} = PB; return
end
arg1 = varargin{1};
if ischar(arg1) || (isstring(arg1) && isscalar(arg1))
    key = lower(char(arg1));
    switch key
        case {'problemdata','bounds','domain'}
            varargout{1} = PB.ProblemData; return
        case 'var_types'
            varargout{1} = PB.var_types; return
        case 'info'
            varargout{1} = PB; return
        otherwise
            error('Unknown string argument: %s', char(arg1));
    end
end
varargout{1} = PB.func_F(arg1);
end

function F = objective(xr, PB)
xh = decode(xr, PB);
F = PB.core(xh);
F = F(:);
end

function xh = decode(xr, PB)
if ~iscell(xr) || numel(xr) ~= 2
    error('lovison2_mix: input must be a cell array with exactly 2 entries.');
end
xh = zeros(2,1);
tmp = check_C(xr{1}, PB.lb_C_work(1), PB.ub_C_work(1), 'x1');
xh(1) = map_C_to_orig(tmp, PB.lb_C_work(1), PB.ub_C_work(1), PB.lb_orig(1), PB.ub_orig(1));
xh(2) = check_K(xr{2}, PB.K2_labels, PB.K2_embed, 'x2');
end

function v = check_C(val, a, b, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('lovison2_mix: %s must be a real scalar.', name);
end
if val < a || val > b
    error('lovison2_mix: %s=%g outside [%g,%g].', name, val, a, b);
end
v = double(val);
end

function xorig = map_C_to_orig(xwork, lbw, ubw, lbo, ubo)
if abs(ubw - lbw) <= 1e-14
    t = 0;
else
    t = (xwork - lbw) / (ubw - lbw);
end
t = max(0, min(1, t));
xorig = lbo + t * (ubo - lbo);
end

function v = check_D(val, grid, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('lovison2_mix: %s must be a real scalar.', name);
end
grid = grid(:);
[dmin, idx] = min(abs(grid - val));
if dmin > 1e-10 * max(1, max(abs(grid)))
    error('lovison2_mix: %s=%g not in grid.', name, val);
end
v = grid(idx);
end

function v = check_K(label, labels, embed, name)
if isstring(label), label = char(label); end
if ~(ischar(label) && isrow(label))
    error('lovison2_mix: %s must be a char vector or scalar string.', name);
end
idx = find(strcmp(label, labels), 1);
if isempty(idx)
    error('lovison2_mix: %s unknown label ''%s''.', name, label);
end
v = embed(idx);
end


% -------------------------------------------------------------------------
% Embedded original continuous MOO problem (top-level function renamed only)
% -------------------------------------------------------------------------
function f = lovison2_orig(x)
% LOVISON2 function
%
%   As described by A. Lovison in "A synthetic approach to multiobjective
%   optimization", arxiv Item: http://arxiv.org/abs/1002.0093.
%
%   Example 2.
%
%   In the above paper/papers the variables bounds were not set.
%   We considered -0.5<=x[1]<=0 and -0.5<=x[2]<=0.5.
%
%   This file is part of a collection of problems developed for
%   derivative-free multiobjective optimization in
%   A. L. Custódio, J. F. A. Madeira, A. I. F. Vaz, and L. N. Vicente,
%   Direct Multisearch for Multiobjective Optimization, 2010.
%
%   Written by the authors in June 1, 2010.
%   Adapted to MATLAB format in November 2025.
%
%   Input: x is a 2-dimensional vector
%   Output: f is a 2-dimensional vector with the function values
%   Output: c is a vector of constraints (empty for this problem - bounds are
%          handled by the optimization algorithm)
% Nota: Este problema é originalmente de maximização, 
% mas para manter a consistência com a interface da coleção DMS,
% convertemos para minimização multiplicando por -1.
% Função objetivo 1
%
%   Bounds: x1 in [-0.5,0], x2 in [-0.5,0.5]
%
f1 = -(-x(2));
% Função objetivo 2
f2 = -((x(2)-x(1)^3)/(x(1)+1));
% Vetor de funções objetivo
f = [f1; f2];
% Não há restrições de desigualdade para este problema
% As restrições de limites são tratadas pelo algoritmo de otimização
end

