function varargout = MOP6_mix(varargin)
%MOP6_MIX  Self-contained mixed-variable MOO adaptation of MOP6.
%
% Auto-generated by generate_selfcontained_wrappers_MOO_mix.m
% Source: MOP6, n=2, m=2, strategy=moderate, kappa=10000
% Variable pattern: C,K
% D variables: nonuniform sorted finite sets with injected anchors.
% K variables: labels with permuted nonuniform numeric embeddings; labels carry no ordinal information.
%
%   x1   C [0,1] -> orig [0,1]
%   x2   K labels {k2_1,...,k2_89}, 89 levels, permuted embedding in [0,1]
%
% Usage:
%   PB = MOP6_mix()
%   F  = PB.func_F(xcell)       % recommended inside benchmark loops
%   F  = MOP6_mix(xcell)              % also valid; PB is memoized persistently
%   PD = MOP6_mix('ProblemData')
%

persistent PB_cached
if isempty(PB_cached)
lb_orig = [0; 0];
ub_orig = [1; 1];
lb_C_work = [0; 0];
ub_C_work = [1; 1];
var_types = {'C', 'K'};
K2_labels = { ...
    'k2_1', 'k2_2', 'k2_3', 'k2_4', 'k2_5', 'k2_6', 'k2_7', 'k2_8', 'k2_9', 'k2_10', ...
    'k2_11', 'k2_12', 'k2_13', 'k2_14', 'k2_15', 'k2_16', 'k2_17', 'k2_18', 'k2_19', 'k2_20', ...
    'k2_21', 'k2_22', 'k2_23', 'k2_24', 'k2_25', 'k2_26', 'k2_27', 'k2_28', 'k2_29', 'k2_30', ...
    'k2_31', 'k2_32', 'k2_33', 'k2_34', 'k2_35', 'k2_36', 'k2_37', 'k2_38', 'k2_39', 'k2_40', ...
    'k2_41', 'k2_42', 'k2_43', 'k2_44', 'k2_45', 'k2_46', 'k2_47', 'k2_48', 'k2_49', 'k2_50', ...
    'k2_51', 'k2_52', 'k2_53', 'k2_54', 'k2_55', 'k2_56', 'k2_57', 'k2_58', 'k2_59', 'k2_60', ...
    'k2_61', 'k2_62', 'k2_63', 'k2_64', 'k2_65', 'k2_66', 'k2_67', 'k2_68', 'k2_69', 'k2_70', ...
    'k2_71', 'k2_72', 'k2_73', 'k2_74', 'k2_75', 'k2_76', 'k2_77', 'k2_78', 'k2_79', 'k2_80', ...
    'k2_81', 'k2_82', 'k2_83', 'k2_84', 'k2_85', 'k2_86', 'k2_87', 'k2_88', 'k2_89'};
K2_embed  = [ ...
    0.01213246012070581; 0.069662135199782; 0.2334643410396907; 0.008380628265711237; 0.6597778239206336; 0.04878626917575925; 0.09498937770848064; 0.0001136877251335449; ...
    0.08175412073070421; 0.7955318203769981; 0.5385958184764241; 1; 2.153979604922433e-05; 0.1507250949164488; 0.221960884042001; 0.9463196754173856; ...
    0.2453082639124269; 0.001025107939706065; 0.6813788029942078; 0.0285570654192142; 0.8943589829136296; 0.869018473121036; 0.5013569413029385; 0.9201253767290007; ...
    0.08822700461762281; 0.001587832137512979; 0.8196069494863401; 0.1170489679269655; 0.9729438856134758; 0.3097323805209017; 0.3988454001733704; 0.7486324246786; ...
    0.1999639098836675; 0.2107950376453452; 0.1093968692160331; 0.003167069220955598; 0.5; 0.06403550842563192; 0.557801149110726; 0.1792940511556093; ...
    0.4149857566226034; 0.006801176275750971; 0.005410552143353023; 0.2700287521498927; 0.05868331254252915; 0.1694493408511973; 0.03993819133715409; 0.002298671349685068; ...
    0.1250045222415856; 0.02524935155076799; 0.01671589156406504; 0.35264785003463; 0.0006000474106859476; 0.01015560106288725; 0.4656649221469998; 0.7718743441681565; ...
    0.5197818533530439; 0.03589682359365735; 0.01431728297116515; 0.2574954724580406; 0.4315008361697859; 0.4483930841003844; 0.02217663247248073; 0.04423322117541159; ...
    0.6385816741734933; 0.6177881565097348; 0.03210464663905337; 0.7258039497448974; 0.01933387908412969; 0.1599273875363202; 0.0003008379344582548; 0.8441018120136674; ...
    0.1332668764524968; 0.2829108552290307; 0.367678953909773; 0.3236771501308581; 0; 0.3379814397519426; 0.07556707256490584; 0.3830772973627991; ...
    0.703386790892254; 0.4833187490848116; 0.1418393210390252; 0.05360158376453335; 0.2961445017409676; 0.597395055550701; 0.004201686153493937; 0.1020448255897429; ...
    0.5774001373773734; ...
];
ProblemData = { ...
    [0; 1]; ... % x1 C
    K2_labels; ... % x2 K
};
x_anchor = {0.5, 'k2_37'};
anchors_set = [0.5 0 1; 0.5 0 1];

PB = struct();
PB.name = 'MOP6_mix';
PB.problem = 'MOP6';
PB.source = 'MOModels_Matlab';
PB.type = 'MOO_MIXED';
PB.nvar = 2; PB.n = 2; PB.nobj = 2; PB.m = 2;
PB.var_types = var_types;
PB.type_counts = struct('C', 1, 'D', 0, 'K', 1);
PB.ProblemData = ProblemData;
PB.strategy = 'moderate'; PB.kappa = 10000;
PB.lb_orig = lb_orig; PB.ub_orig = ub_orig;
PB.lb_C_work = lb_C_work; PB.ub_C_work = ub_C_work;
PB.x_anchor = x_anchor;
PB.anchors_set = anchors_set;
PB.K2_labels = K2_labels; PB.K2_embed = K2_embed;
PB.pareto_front_known = false;
PB.pareto_set_known = false;
PB.pf_type = 'unknown';
PB.ideal_point = [];
PB.nadir_point = [];
PB.core = @(xh) MOP6_orig(xh);
PB.decode = @(xr) decode(xr, PB);
PB.func_F = @(xr) objective(xr, PB);
PB_cached = PB;
else
    PB = PB_cached;
end

if nargin == 0
    varargout{1} = PB; return
end
arg1 = varargin{1};
if ischar(arg1) || (isstring(arg1) && isscalar(arg1))
    key = lower(char(arg1));
    switch key
        case {'problemdata','bounds','domain'}
            varargout{1} = PB.ProblemData; return
        case 'var_types'
            varargout{1} = PB.var_types; return
        case 'info'
            varargout{1} = PB; return
        otherwise
            error('Unknown string argument: %s', char(arg1));
    end
end
varargout{1} = PB.func_F(arg1);
end

function F = objective(xr, PB)
xh = decode(xr, PB);
F = PB.core(xh);
F = F(:);
end

function xh = decode(xr, PB)
if ~iscell(xr) || numel(xr) ~= 2
    error('MOP6_mix: input must be a cell array with exactly 2 entries.');
end
xh = zeros(2,1);
tmp = check_C(xr{1}, PB.lb_C_work(1), PB.ub_C_work(1), 'x1');
xh(1) = map_C_to_orig(tmp, PB.lb_C_work(1), PB.ub_C_work(1), PB.lb_orig(1), PB.ub_orig(1));
xh(2) = check_K(xr{2}, PB.K2_labels, PB.K2_embed, 'x2');
end

function v = check_C(val, a, b, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('MOP6_mix: %s must be a real scalar.', name);
end
if val < a || val > b
    error('MOP6_mix: %s=%g outside [%g,%g].', name, val, a, b);
end
v = double(val);
end

function xorig = map_C_to_orig(xwork, lbw, ubw, lbo, ubo)
if abs(ubw - lbw) <= 1e-14
    t = 0;
else
    t = (xwork - lbw) / (ubw - lbw);
end
t = max(0, min(1, t));
xorig = lbo + t * (ubo - lbo);
end

function v = check_D(val, grid, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('MOP6_mix: %s must be a real scalar.', name);
end
grid = grid(:);
[dmin, idx] = min(abs(grid - val));
if dmin > 1e-10 * max(1, max(abs(grid)))
    error('MOP6_mix: %s=%g not in grid.', name, val);
end
v = grid(idx);
end

function v = check_K(label, labels, embed, name)
if isstring(label), label = char(label); end
if ~(ischar(label) && isrow(label))
    error('MOP6_mix: %s must be a char vector or scalar string.', name);
end
idx = find(strcmp(label, labels), 1);
if isempty(idx)
    error('MOP6_mix: %s unknown label ''%s''.', name, label);
end
v = embed(idx);
end


% -------------------------------------------------------------------------
% Embedded original continuous MOO problem (top-level function renamed only)
% -------------------------------------------------------------------------
function f = MOP6_orig(x)
% MOP6 function
%
%   As described by Huband et al. in "A review of multiobjective test problems
%   and a scalable test problem toolkit", IEEE Transactions on Evolutionary 
%   Computing 10(5): 477-506, 2006.
%
%   Example MOP6, Van Valedhuizen's test suit.
%
%   This file is part of a collection of problems developed for
%   derivative-free multiobjective optimization in
%   A. L. Custódio, J. F. A. Madeira, A. I. F. Vaz, and L. N. Vicente,
%   Direct Multisearch for Multiobjective Optimization, 2010.
%
%   Written by the authors in June 1, 2010.
%   Adapted to MATLAB format in November 2025.
%
% Problem characteristics:
% - Number of variables: 2
% - Number of objectives: 2
%   Bounds: x1 in [0,1], x2 in [0,1]
%
%
%   Input: x is a 2-dimensional vector
%   Output: f is a 2-dimensional vector with the function values
%   Output: c is a vector of constraints (empty for this problem - bounds are
%          handled by the optimization algorithm)
% Parâmetros
pi = 4*atan(1);
% Função objetivo 1
f1 = x(1);
% Função objetivo 2
f2 = (1 + 10*x(2)) * (1 - (x(1)/(1 + 10*x(2)))^2 - (x(1)/(1 + 10*x(2))) * sin(8*pi*x(1)));
% Vetor de funções objetivo
f = [f1; f2];
% Não há restrições de desigualdade para este problema
end

