function varargout = SK2_mix(varargin)
%SK2_MIX  Self-contained mixed-variable MOO adaptation of SK2.
%
% Auto-generated by generate_selfcontained_wrappers_MOO_mix.m
% Source: SK2, n=4, m=2, strategy=moderate, kappa=10000
% Variable pattern: C,K,D,C
% D variables: nonuniform sorted finite sets with injected anchors.
% K variables: labels with permuted nonuniform numeric embeddings; labels carry no ordinal information.
%
%   x1   C [-10,10] -> orig [-10,10]
%   x2   K labels {k2_1,...,k2_20}, 20 levels, permuted embedding in [-10,10]
%   x3   D sorted nonuniform grid [-10,...,10], 126 values
%   x4   C [-46.4158883361,46.4158883361] -> orig [-10,10]
%
% Usage:
%   PB = SK2_mix()
%   F  = PB.func_F(xcell)       % recommended inside benchmark loops
%   F  = SK2_mix(xcell)              % also valid; PB is memoized persistently
%   PD = SK2_mix('ProblemData')
%

persistent PB_cached
if isempty(PB_cached)
lb_orig = [-10; -10; -10; -10];
ub_orig = [10; 10; 10; 10];
lb_C_work = [-10; -10; -10; -46.41588833612779];
ub_C_work = [10; 10; 10; 46.41588833612779];
var_types = {'C', 'K', 'D', 'C'};
K2_labels = { ...
    'k2_1', 'k2_2', 'k2_3', 'k2_4', 'k2_5', 'k2_6', 'k2_7', 'k2_8', 'k2_9', 'k2_10', ...
    'k2_11', 'k2_12', 'k2_13', 'k2_14', 'k2_15', 'k2_16', 'k2_17', 'k2_18', 'k2_19', 'k2_20'};
K2_embed  = [ ...
    10; -9.982938337243302; -7.49136589540711; -9.76170640750645; 1.340713398027582; 5.314356921409043; -9.188012462304297; 3.240650184979978; ...
    7.566100600952815; 0; -0.3898837985510255; -10; -9.524702716044446; -8.179223458421728; -9.909948004086397; -3.361708122396251; ...
    -8.742278878473073; -4.612791332818125; -1.955752968572096; -5.714304082246061; ...
];
D3_vals = [ ...
    -10; -9.996638044410362; -9.98829299067066; -9.975710966674658; -9.959233825735321; -9.939083073961092; -9.915420673426819; -9.888373207902623; ...
    -9.858043936121826; -9.824519651092915; -9.787874942890241; -9.748175021505777; -9.705477678434043; -9.659834702419444; -9.611292933042755; -9.559895064885049; ...
    -9.505680274510221; -9.44868471824973; -9.388941933646148; -9.326483167649942; -9.261337648175507; -9.193532811197201; -9.123094492479277; -9.050047090836456; ...
    -8.974413708229896; -8.896216270831028; -8.815475634309815; -8.732211675940869; -8.646443375612746; -8.55818888743195; -8.467465603305104; -8.374290209639222; ...
    -8.278678738105947; -8.180646611259794; -8.080208683674167; -7.977379279156071; -7.872172224516055; -7.76460088030017; -7.654678168832944; -7.542416599871959; ...
    -7.42782829413419; -7.310925004919965; -7.191718138031526; -7.070218770158487; -6.946437665881446; -6.820385293426961; -6.69207183929154; -6.561507221838891; ...
    -6.428701103963012; -6.293662904899598; -6.156401811259419; -6.016926787349565; -5.875246584841697; -5.731369751840514; -5.585304641400297; -5.437059419532845; ...
    -5.286642072745902; -5.1340604151476; -4.979322095149086; -4.82243460179469; -4.663405270746291; -4.502241289946321; -4.173537424168523; -4.006011223378147; ...
    -3.836377750618539; -3.664643530390007; -3.490814967827878; -3.314898352646152; -3.136899862894438; -2.956825568539618; -2.774681434882779; -2.590473325821248; ...
    -2.404207006964826; -2.215888148614614; -2.025522328612313; -1.833115035067287; -1.638671668968163; -1.442197546685319; -1.243697902370155; -1.043177890256665; ...
    -0.840642586870489; -0.636096993150213; -0.4295460364854975; -0.2209945726762257; -0.01044738781664378; 0; 0.20209079989176; 0.4166153383951965; ...
    0.6331216401069391; 0.851605180288157; 1.072061495487199; 1.294486182034635; 1.518874894591447; 1.745223344747973; 1.973527299671233; 2.203782580798546; ...
    2.435985062575307; 2.670130671235052; 2.906215383619903; 3.144235226039726; 3.3841862731683; 3.626064646974942; 3.869866515690157; 4.115588092803829; ...
    4.36322563609469; 4.612775446689735; 4.864233868152459; 5.117597285598702; 5.372862124839024; 5.630024851546613; 5.889081970449705; 6.150030024547576; ...
    6.412865594349228; 6.677585297133916; 6.944185786232666; 7.212663750330048; 7.483015912785472; 7.755239030973215; 8.029329895640622; 8.305285330283731; ...
    8.583102190539773; 8.862777363595896; 9.144307767613615; 9.427690351168387; 9.712922092703817; 10; ...
];
ProblemData = { ...
    [-10; 10]; ... % x1 C
    K2_labels; ... % x2 K
    {D3_vals}; ... % x3 D
    [-46.41588833612779; 46.41588833612779]; ... % x4 C
};
x_anchor = {0, 'k2_10', 0, 0};
anchors_set = [0 -10 10; 0 -10 10; 0 -10 10; 0 -10 10];

PB = struct();
PB.name = 'SK2_mix';
PB.problem = 'SK2';
PB.source = 'MOModels_Matlab';
PB.type = 'MOO_MIXED';
PB.nvar = 4; PB.n = 4; PB.nobj = 2; PB.m = 2;
PB.var_types = var_types;
PB.type_counts = struct('C', 2, 'D', 1, 'K', 1);
PB.ProblemData = ProblemData;
PB.strategy = 'moderate'; PB.kappa = 10000;
PB.lb_orig = lb_orig; PB.ub_orig = ub_orig;
PB.lb_C_work = lb_C_work; PB.ub_C_work = ub_C_work;
PB.x_anchor = x_anchor;
PB.anchors_set = anchors_set;
PB.K2_labels = K2_labels; PB.K2_embed = K2_embed;
PB.D3_vals = D3_vals;
PB.pareto_front_known = false;
PB.pareto_set_known = false;
PB.pf_type = 'unknown';
PB.ideal_point = [];
PB.nadir_point = [];
PB.core = @(xh) SK2_orig(xh);
PB.decode = @(xr) decode(xr, PB);
PB.func_F = @(xr) objective(xr, PB);
PB_cached = PB;
else
    PB = PB_cached;
end

if nargin == 0
    varargout{1} = PB; return
end
arg1 = varargin{1};
if ischar(arg1) || (isstring(arg1) && isscalar(arg1))
    key = lower(char(arg1));
    switch key
        case {'problemdata','bounds','domain'}
            varargout{1} = PB.ProblemData; return
        case 'var_types'
            varargout{1} = PB.var_types; return
        case 'info'
            varargout{1} = PB; return
        otherwise
            error('Unknown string argument: %s', char(arg1));
    end
end
varargout{1} = PB.func_F(arg1);
end

function F = objective(xr, PB)
xh = decode(xr, PB);
F = PB.core(xh);
F = F(:);
end

function xh = decode(xr, PB)
if ~iscell(xr) || numel(xr) ~= 4
    error('SK2_mix: input must be a cell array with exactly 4 entries.');
end
xh = zeros(4,1);
tmp = check_C(xr{1}, PB.lb_C_work(1), PB.ub_C_work(1), 'x1');
xh(1) = map_C_to_orig(tmp, PB.lb_C_work(1), PB.ub_C_work(1), PB.lb_orig(1), PB.ub_orig(1));
xh(2) = check_K(xr{2}, PB.K2_labels, PB.K2_embed, 'x2');
xh(3) = check_D(xr{3}, PB.D3_vals, 'x3');
tmp = check_C(xr{4}, PB.lb_C_work(4), PB.ub_C_work(4), 'x4');
xh(4) = map_C_to_orig(tmp, PB.lb_C_work(4), PB.ub_C_work(4), PB.lb_orig(4), PB.ub_orig(4));
end

function v = check_C(val, a, b, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('SK2_mix: %s must be a real scalar.', name);
end
if val < a || val > b
    error('SK2_mix: %s=%g outside [%g,%g].', name, val, a, b);
end
v = double(val);
end

function xorig = map_C_to_orig(xwork, lbw, ubw, lbo, ubo)
if abs(ubw - lbw) <= 1e-14
    t = 0;
else
    t = (xwork - lbw) / (ubw - lbw);
end
t = max(0, min(1, t));
xorig = lbo + t * (ubo - lbo);
end

function v = check_D(val, grid, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('SK2_mix: %s must be a real scalar.', name);
end
grid = grid(:);
[dmin, idx] = min(abs(grid - val));
if dmin > 1e-10 * max(1, max(abs(grid)))
    error('SK2_mix: %s=%g not in grid.', name, val);
end
v = grid(idx);
end

function v = check_K(label, labels, embed, name)
if isstring(label), label = char(label); end
if ~(ischar(label) && isrow(label))
    error('SK2_mix: %s must be a char vector or scalar string.', name);
end
idx = find(strcmp(label, labels), 1);
if isempty(idx)
    error('SK2_mix: %s unknown label ''%s''.', name, label);
end
v = embed(idx);
end


% -------------------------------------------------------------------------
% Embedded original continuous MOO problem (top-level function renamed only)
% -------------------------------------------------------------------------
function f = SK2_orig(x)
% SK2 function
%
%   As described by Huband et al. in "A review of multiobjective test problems
%   and a scalable test problem toolkit", IEEE Transactions on Evolutionary 
%   Computing 10(5): 477-506, 2006.
%
%   Example SK2, see the previous cited paper for the original reference.
%
%   In the above paper/papers the variables bounds were not set.
%   We considered -10<=x[i]<=10, i=1,2,3,4.
%
%   This file is part of a collection of problems developed for
%   derivative-free multiobjective optimization in
%   A. L. Custódio, J. F. A. Madeira, A. I. F. Vaz, and L. N. Vicente,
%   Direct Multisearch for Multiobjective Optimization, 2010.
%
%   Written by the authors in June 1, 2010.
%   Adapted to MATLAB format in November 2025.
%
% Problem characteristics:
% - Number of variables: 4
% - Number of objectives: 2
%   Bounds: x1 in [-10,10], x2 in [-10,10], x3 in [-10,10], x4 in [-10,10]
%
%
%   Input: x is a 4-dimensional vector
%   Output: f is a 2-dimensional vector with the function values
%   Output: c is a vector of constraints (empty for this problem - bounds are
%          handled by the optimization algorithm)
% Nota: Este problema é originalmente de maximização, 
% mas para manter a consistência com a interface da coleção DMS,
% convertemos para minimização multiplicando por -1.
% Função objetivo 1
f1 = -(-(x(1)-2)^2 - (x(2)+3)^2 - (x(3)-5)^2 - (x(4)-4)^2 + 5);
% Função objetivo 2
sum_sin = 0;
sum_square = 0;
for i = 1:4
    sum_sin = sum_sin + sin(x(i));
    sum_square = sum_square + x(i)^2;
end
f2 = -(sum_sin / (1 + sum_square/100));
% Vetor de funções objetivo
f = [f1; f2];
% Não há restrições de desigualdade para este problema
end

