function varargout = WFG7_mix(varargin)
%WFG7_MIX  Self-contained mixed-variable MOO adaptation of WFG7.
%
% Auto-generated by generate_selfcontained_wrappers_MOO_mix.m
% Source: WFG7, n=8, m=3, strategy=moderate, kappa=10000
% Variable pattern: C,K,D,C,D,K,C,K
% D variables: nonuniform sorted finite sets with injected anchors.
% K variables: labels with permuted nonuniform numeric embeddings; labels carry no ordinal information.
%
%   x1   C [0,2] -> orig [0,2]
%   x2   K labels {k2_1,...,k2_78}, 78 levels, permuted embedding in [0,4]
%   x3   D sorted nonuniform grid [0,...,6], 66 values
%   x4   C [0,37.1327106689] -> orig [0,8]
%   x5   D sorted nonuniform grid [0,...,10], 88 values
%   x6   K labels {k6_1,...,k6_64}, 64 levels, permuted embedding in [0,12]
%   x7   C [0,301.620856604] -> orig [0,14]
%   x8   K labels {k8_1,...,k8_25}, 25 levels, permuted embedding in [0,16]
%
% Usage:
%   PB = WFG7_mix()
%   F  = PB.func_F(xcell)       % recommended inside benchmark loops
%   F  = WFG7_mix(xcell)              % also valid; PB is memoized persistently
%   PD = WFG7_mix('ProblemData')
%

persistent PB_cached
if isempty(PB_cached)
lb_orig = [0; 0; 0; 0; 0; 0; 0; 0];
ub_orig = [2; 4; 6; 8; 10; 12; 14; 16];
lb_C_work = [0; 0; 0; 0; 0; 0; 0; 0];
ub_C_work = [2; 4; 6; 37.13271066890223; 10; 12; 301.6208566044637; 16];
var_types = {'C', 'K', 'D', 'C', 'D', 'K', 'C', 'K'};
K2_labels = { ...
    'k2_1', 'k2_2', 'k2_3', 'k2_4', 'k2_5', 'k2_6', 'k2_7', 'k2_8', 'k2_9', 'k2_10', ...
    'k2_11', 'k2_12', 'k2_13', 'k2_14', 'k2_15', 'k2_16', 'k2_17', 'k2_18', 'k2_19', 'k2_20', ...
    'k2_21', 'k2_22', 'k2_23', 'k2_24', 'k2_25', 'k2_26', 'k2_27', 'k2_28', 'k2_29', 'k2_30', ...
    'k2_31', 'k2_32', 'k2_33', 'k2_34', 'k2_35', 'k2_36', 'k2_37', 'k2_38', 'k2_39', 'k2_40', ...
    'k2_41', 'k2_42', 'k2_43', 'k2_44', 'k2_45', 'k2_46', 'k2_47', 'k2_48', 'k2_49', 'k2_50', ...
    'k2_51', 'k2_52', 'k2_53', 'k2_54', 'k2_55', 'k2_56', 'k2_57', 'k2_58', 'k2_59', 'k2_60', ...
    'k2_61', 'k2_62', 'k2_63', 'k2_64', 'k2_65', 'k2_66', 'k2_67', 'k2_68', 'k2_69', 'k2_70', ...
    'k2_71', 'k2_72', 'k2_73', 'k2_74', 'k2_75', 'k2_76', 'k2_77', 'k2_78'};
K2_embed  = [ ...
    0.6450720912615886; 3.292321877061546; 0.00875074949961936; 2.471152626038939; 2.111188827216725; 0.6029003796657952; 0.1978320652913185; 0.09212345328206203; ...
    2.026326552998249; 0.000118708618528709; 0.6889161861713301; 3.876456120909662; 1.102027124288591; 0.3234113705948001; 0.1222183069148371; 0.2954053021253081; ...
    3.519306691003483; 0.1769328847016464; 0.486230501493592; 2.763043334107803; 0.2688674769152548; 1.35192575900777; 0.3529080184704912; 0.933857364158763; ...
    0.5234988194366653; 1.706975447734971; 0.4164599687916599; 1.419091050956909; 0.0789044092482403; 0.3839170906924195; 0.005649503230542438; 2; ...
    0.01266827688382239; 0; 1.783826887382594; 2.968271631289566; 0.01745413053797102; 0.001657956998244455; 0.5623823106810549; 1.862659688587999; ...
    3.074114707183832; 4; 3.755167236186555; 2.663632509879212; 3.404710909753922; 0.8813806405574443; 0.4505575962183111; 2.198088893363312; ...
    0.02315603906520888; 1.044163900625738; 0.05596883878329236; 1.286652359066097; 0.06686356625626015; 0.04618673275975876; 0.1391524615408474; 3.636121430050248; ...
    0.02981825681855108; 0.9881128435226995; 2.864585421645803; 0.1573817030301438; 0.1065515231264591; 1.632090879885982; 0.0006265478449022133; 2.378057249875524; ...
    1.943488183874322; 1.223255310859165; 1.161718878600397; 0.2437750369970211; 1.488163586019621; 0.7816949526873109; 1.559158532154404; 0.2201045687403129; ...
    3.182127281507992; 2.287040497745767; 0.03748216734362728; 0.003306939351304715; 2.566339972719465; 0.8306656086367402; ...
];
D3_vals = [ ...
    0; 0.003272707625754519; 0.01139622986841647; 0.02364424587614519; 0.03968397732560829; 0.05929979830774475; 0.08233404626476104; 0.1086634977754317; ...
    0.1381876352585557; 0.1708219697513372; 0.206493891280615; 0.2451399209477786; 0.2867038014169475; 0.3311351187506916; 0.3783882767925169; 0.4284217143506314; ...
    0.48119729485958; 0.5366798218099063; 0.5948366479615202; 0.6556373558593545; 0.7190534934861919; 0.7850583531952147; 0.8536267850698243; 0.9247350379970558; ...
    0.998360623290655; 1.07448219684106; 1.153079456622174; 1.234133053030326; 1.317624510025501; 1.403536155428157; 1.491851059024933; 1.582552977373579; ...
    1.771056026922594; 1.86882768474511; 1.968927334292985; 2.071341515808319; 2.176057223420035; 2.283061877845369; 2.392343301416306; 2.503889695177801; ...
    2.617689617837847; 2.733731966377687; 2.85200595815442; 2.97250111434878; 3; 3.095207244628391; 3.220114432911998; 3.347213024133176; ...
    3.476493611913397; 3.607947027064169; 3.741564326846568; 3.877336784923977; 4.015255881950489; 4.155313296743184; 4.297500897991662; 4.441810736462697; ...
    4.588235037661919; 4.736766194917976; 4.887396762857835; 5.04011945124466; 5.1949271191523; 5.351812769452636; 5.51076954359411; 5.671790716651573; ...
    5.834869692629233; 6; ...
];
D5_vals = [ ...
    0; 0.003227493269569816; 0.01123878433543381; 0.02331758689006596; 0.03913572013590224; 0.05848053716102093; 0.08119655360741299; 0.1071622484569683; ...
    0.1362784928372367; 0.1684619650495029; 0.2036410582695468; 0.241753170596602; 0.2827428219225492; 0.326560294807778; 0.3731606230331718; 0.4225028195989364; ...
    0.4745492748184128; 0.52926527844236; 0.5866186342712669; 0.64657934508487; 0.7091193519470912; 0.7742123161927614; 0.8418334353659834; 0.9119592864892094; ...
    0.9845676915704439; 1.059637601381393; 1.137148994380238; 1.217082788289318; 1.299420762325841; 1.384145488461686; 1.471240270384219; 1.560689089063778; ...
    1.652476554019746; 1.746587859526834; 1.843008745124306; 1.941725459889678; 2.042724730019418; 2.145993729326112; 2.25152005231709; 2.359291689565893; ...
    2.469297005126891; 2.581524715776169; 2.695963871889622; 2.931434285437473; 3.052445159276561; 3.175626682225251; 3.300969332607466; 3.428463833999258; ...
    3.558101143889802; 3.689872443089302; 3.823769125820551; 3.959782790437349; 4.097905230718752; 4.238128427693134; 4.380444541950544; 4.524845906405761; ...
    4.67132501947802; 4.819874538656438; 4.970487274423033; 5; 5.123156184507697; 5.277874368451696; 5.434635062458346; 5.593431634511246; ...
    5.754257579742113; 5.91710651603176; 6.081972179829027; 6.248848422173701; 6.417729204910591; 6.588608597082843; 6.76148077149354; 6.936340001425422; ...
    7.113180657509311; 7.291997204732525; 7.472784199579188; 7.655536287294878; 7.840248199268649; 8.026914750525862; 8.215530837325812; 8.406091434858395; ...
    8.598591595034588; 8.793026444365772; 8.989391181927243; 9.187681077401617; 9.38789146919804; 9.59001776264339; 9.794055428241929; 10; ...
];
K6_labels = { ...
    'k6_1', 'k6_2', 'k6_3', 'k6_4', 'k6_5', 'k6_6', 'k6_7', 'k6_8', 'k6_9', 'k6_10', ...
    'k6_11', 'k6_12', 'k6_13', 'k6_14', 'k6_15', 'k6_16', 'k6_17', 'k6_18', 'k6_19', 'k6_20', ...
    'k6_21', 'k6_22', 'k6_23', 'k6_24', 'k6_25', 'k6_26', 'k6_27', 'k6_28', 'k6_29', 'k6_30', ...
    'k6_31', 'k6_32', 'k6_33', 'k6_34', 'k6_35', 'k6_36', 'k6_37', 'k6_38', 'k6_39', 'k6_40', ...
    'k6_41', 'k6_42', 'k6_43', 'k6_44', 'k6_45', 'k6_46', 'k6_47', 'k6_48', 'k6_49', 'k6_50', ...
    'k6_51', 'k6_52', 'k6_53', 'k6_54', 'k6_55', 'k6_56', 'k6_57', 'k6_58', 'k6_59', 'k6_60', ...
    'k6_61', 'k6_62', 'k6_63', 'k6_64'};
K6_embed  = [ ...
    4.534842668891701; 3.132491701877214; 0.2717865575450398; 6.248026991979843; 9.045137895381368; 0.1124465020308818; 0.5934961958739555; 0.5174177685524153; ...
    11.10594533245829; 6.891153719946139; 0.08475784306021726; 0.1447984547988719; 0.0005764530314049738; 2.542127818025351; 6.564996810455044; 3.345400096677677; ...
    1.43449805088965; 9.437643778350891; 12; 0; 1.068835165036923; 0.06151757726496383; 2.927704456517669; 1.713733169300067; ...
    0.32469171941081; 0.7642508262992114; 10.67399335938229; 11.54792573223141; 1.570496458309996; 0.22428432273951; 0.3831624566616159; 0.1820146612491914; ...
    3.566519141655492; 7.226572265939049; 5.641345822313887; 8.662323169776492; 0.003042537340511514; 7.571326104548761; 1.305629481961515; 7.92548803026591; ...
    5.070494908116377; 10.25200372475961; 0.04249393294810502; 5.351480662147781; 8.289130002323411; 0.008051094768203104; 0.01605860835850746; 5.940168800435185; ...
    0.4473545776720165; 0.6757290184729594; 2.022343570704713; 2.730947355117481; 4.280013939747109; 0.02743417709296965; 4.033740044466121; 9.839909676058927; ...
    2.361151616634772; 4.798309095654197; 1.183779752468497; 0.8591920199696723; 1.86431426362106; 0.9606791415798266; 6; 3.79593689738366; ...
];
K8_labels = { ...
    'k8_1', 'k8_2', 'k8_3', 'k8_4', 'k8_5', 'k8_6', 'k8_7', 'k8_8', 'k8_9', 'k8_10', ...
    'k8_11', 'k8_12', 'k8_13', 'k8_14', 'k8_15', 'k8_16', 'k8_17', 'k8_18', 'k8_19', 'k8_20', ...
    'k8_21', 'k8_22', 'k8_23', 'k8_24', 'k8_25'};
K8_embed  = [ ...
    2.460115214772236; 12.98456594921889; 6.993432924980659; 11.61286319591836; 9.133172174149909; 0.5743491774985175; 5.178834402093729; 1.145589359959563; ...
    8.021711060847016; 0.2170485964135942; 0; 0.1088188204120155; 1.957099935144907; 16; 10.32963538638729; 0.83147328224438; ...
    0.3708010992519452; 3.673474657471267; 8; 0.04112301916523926; 1.51983004333569; 4.388542294071051; 14.44640576503345; 0.00779135517670972; ...
    6.0464568918556; ...
];
ProblemData = { ...
    [0; 2]; ... % x1 C
    K2_labels; ... % x2 K
    {D3_vals}; ... % x3 D
    [0; 37.13271066890223]; ... % x4 C
    {D5_vals}; ... % x5 D
    K6_labels; ... % x6 K
    [0; 301.6208566044637]; ... % x7 C
    K8_labels; ... % x8 K
};
x_anchor = {1, 'k2_32', 3, 18.56635533445111, 5, 'k6_63', 150.8104283022319, 'k8_19'};
anchors_set = [ ...
    1 0 2; ...
    2 0 4; ...
    3 0 6; ...
    4 0 8; ...
    5 0 10; ...
    6 0 12; ...
    7 0 14; ...
    8 0 16];

PB = struct();
PB.name = 'WFG7_mix';
PB.problem = 'WFG7';
PB.source = 'MOModels_Matlab';
PB.type = 'MOO_MIXED';
PB.nvar = 8; PB.n = 8; PB.nobj = 3; PB.m = 3;
PB.var_types = var_types;
PB.type_counts = struct('C', 3, 'D', 2, 'K', 3);
PB.ProblemData = ProblemData;
PB.strategy = 'moderate'; PB.kappa = 10000;
PB.lb_orig = lb_orig; PB.ub_orig = ub_orig;
PB.lb_C_work = lb_C_work; PB.ub_C_work = ub_C_work;
PB.x_anchor = x_anchor;
PB.anchors_set = anchors_set;
PB.K2_labels = K2_labels; PB.K2_embed = K2_embed;
PB.D3_vals = D3_vals;
PB.D5_vals = D5_vals;
PB.K6_labels = K6_labels; PB.K6_embed = K6_embed;
PB.K8_labels = K8_labels; PB.K8_embed = K8_embed;
PB.pareto_front_known = false;
PB.pareto_set_known = false;
PB.pf_type = 'unknown';
PB.ideal_point = [];
PB.nadir_point = [];
PB.core = @(xh) WFG7_orig(xh);
PB.decode = @(xr) decode(xr, PB);
PB.func_F = @(xr) objective(xr, PB);
PB_cached = PB;
else
    PB = PB_cached;
end

if nargin == 0
    varargout{1} = PB; return
end
arg1 = varargin{1};
if ischar(arg1) || (isstring(arg1) && isscalar(arg1))
    key = lower(char(arg1));
    switch key
        case {'problemdata','bounds','domain'}
            varargout{1} = PB.ProblemData; return
        case 'var_types'
            varargout{1} = PB.var_types; return
        case 'info'
            varargout{1} = PB; return
        otherwise
            error('Unknown string argument: %s', char(arg1));
    end
end
varargout{1} = PB.func_F(arg1);
end

function F = objective(xr, PB)
xh = decode(xr, PB);
F = PB.core(xh);
F = F(:);
end

function xh = decode(xr, PB)
if ~iscell(xr) || numel(xr) ~= 8
    error('WFG7_mix: input must be a cell array with exactly 8 entries.');
end
xh = zeros(8,1);
tmp = check_C(xr{1}, PB.lb_C_work(1), PB.ub_C_work(1), 'x1');
xh(1) = map_C_to_orig(tmp, PB.lb_C_work(1), PB.ub_C_work(1), PB.lb_orig(1), PB.ub_orig(1));
xh(2) = check_K(xr{2}, PB.K2_labels, PB.K2_embed, 'x2');
xh(3) = check_D(xr{3}, PB.D3_vals, 'x3');
tmp = check_C(xr{4}, PB.lb_C_work(4), PB.ub_C_work(4), 'x4');
xh(4) = map_C_to_orig(tmp, PB.lb_C_work(4), PB.ub_C_work(4), PB.lb_orig(4), PB.ub_orig(4));
xh(5) = check_D(xr{5}, PB.D5_vals, 'x5');
xh(6) = check_K(xr{6}, PB.K6_labels, PB.K6_embed, 'x6');
tmp = check_C(xr{7}, PB.lb_C_work(7), PB.ub_C_work(7), 'x7');
xh(7) = map_C_to_orig(tmp, PB.lb_C_work(7), PB.ub_C_work(7), PB.lb_orig(7), PB.ub_orig(7));
xh(8) = check_K(xr{8}, PB.K8_labels, PB.K8_embed, 'x8');
end

function v = check_C(val, a, b, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('WFG7_mix: %s must be a real scalar.', name);
end
if val < a || val > b
    error('WFG7_mix: %s=%g outside [%g,%g].', name, val, a, b);
end
v = double(val);
end

function xorig = map_C_to_orig(xwork, lbw, ubw, lbo, ubo)
if abs(ubw - lbw) <= 1e-14
    t = 0;
else
    t = (xwork - lbw) / (ubw - lbw);
end
t = max(0, min(1, t));
xorig = lbo + t * (ubo - lbo);
end

function v = check_D(val, grid, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('WFG7_mix: %s must be a real scalar.', name);
end
grid = grid(:);
[dmin, idx] = min(abs(grid - val));
if dmin > 1e-10 * max(1, max(abs(grid)))
    error('WFG7_mix: %s=%g not in grid.', name, val);
end
v = grid(idx);
end

function v = check_K(label, labels, embed, name)
if isstring(label), label = char(label); end
if ~(ischar(label) && isrow(label))
    error('WFG7_mix: %s must be a char vector or scalar string.', name);
end
idx = find(strcmp(label, labels), 1);
if isempty(idx)
    error('WFG7_mix: %s unknown label ''%s''.', name, label);
end
v = embed(idx);
end


% -------------------------------------------------------------------------
% Embedded original continuous MOO problem (top-level function renamed only)
% -------------------------------------------------------------------------
function f = WFG7_orig(z)
% WFG7 function
%
%   As described by Huband et al. in "A review of multiobjective test problems
%   and a scalable test problem toolkit", IEEE Transactions on Evolutionary 
%   Computing 10(5): 477-506, 2006.
%
%   Example WFG7.
%
%   This file is part of a collection of problems developed for
%   derivative-free multiobjective optimization in
%   A. L. Custódio, J. F. A. Madeira, A. I. F. Vaz, and L. N. Vicente,
%   Direct Multisearch for Multiobjective Optimization, 2010.
%
%   Written by the authors in June 1, 2010.
%   Adapted to MATLAB format in November 2025.
%
%   Input: z is a n-dimensional vector where n = k+l (k=4, l=4)
%
%   Problem characteristics:
%   n = 8 (k=4 position-related, l=4 distance-related); M = 3 objectives.
%   Variable z_i has bound [0, 2*i] (z_i in [0, zmax_i], zmax_i = 2*i).
%   Bounds: x1 in [0,2], x2 in [0,4], x3 in [0,6], x4 in [0,8], x5 in [0,10], x6 in [0,12], x7 in [0,14], x8 in [0,16]
%
%   Output: f is a M-dimensional vector (M=3) with the function values
%   Output: c is a vector of constraints (empty for this problem - bounds are
%          handled by the optimization algorithm)
% Parâmetros
M = 3;      % número de objetivos
k = 4;      % número de variáveis relacionadas à posição
l = 4;      % número de variáveis relacionadas à distância
n = k + l;  % número total de variáveis
pi = 4*atan(1);
pi2 = 2*atan(1);
% Parâmetros S
S = zeros(M, 1);
for m = 1:M
    S(m) = 2*m;
end
% Parâmetros A
A = ones(M-1, 1);  % neq WFG3
% Parâmetros zmax
zmax = zeros(n, 1);
for i = 1:n
    zmax(i) = 2*i;
end
% Transform z into [0,1] set
y = zeros(n, 1);
for i = 1:n
    y(i) = z(i)/zmax(i);
end
% First level mapping - Diferente dos anteriores, função de inclinação dependente
w = ones(n, 1);  % default weight
AA = 0.98/49.98;
BB = 0.02;
CC = 50;
r_sum = zeros(k, 1);
% Cálculo de r_sum (soma ponderada das posições das variáveis restantes)
for i = 1:k
    sum_numerator = 0;
    sum_denominator = 0;
    for j = i+1:n
        sum_numerator = sum_numerator + w(j)*y(j);
        sum_denominator = sum_denominator + w(j);
    end
    r_sum(i) = sum_numerator / sum_denominator;
end
% Cálculo de t1
t1 = zeros(n, 1);
for i = 1:n
    if i <= k
        t1(i) = y(i)^(BB + (CC-BB)*(AA - (1-2*r_sum(i))*abs(floor(0.5-r_sum(i))+AA)));
    else
        t1(i) = y(i);
    end
end
% Second level mapping - Similar ao WFG1/WFG2/WFG3, mas aplicado em t1
t2 = zeros(n, 1);
for i = 1:n
    if i <= k
        t2(i) = t1(i);
    else
        t2(i) = abs(t1(i)-0.35)/abs(floor(0.35-t1(i))+0.35);
    end
end
% Third level mapping - Redução de dimensionalidade, como nos anteriores
t3 = zeros(M, 1);
for i = 1:M
    if i <= M-1
        numerator = 0;
        denominator = 0;
        for j = floor((i-1)*k/(M-1))+1 : floor(i*k/(M-1))
            numerator = numerator + w(j)*t2(j);
            denominator = denominator + w(j);
        end
        t3(i) = numerator / denominator;
    else
        numerator = 0;
        denominator = 0;
        for j = k+1 : n
            numerator = numerator + w(j)*t2(j);
            denominator = denominator + w(j);
        end
        t3(i) = numerator / denominator;
    end
end
% Define objective function variables - Idêntico ao WFG4/WFG5/WFG6
x = zeros(M, 1);
for i = 1:M
    if i <= M-1
        x(i) = max(t3(M), A(i))*(t3(i)-0.5)+0.5;
    else
        x(i) = t3(M);
    end
end
% Define objective function function h - Idêntico ao WFG4/WFG5/WFG6
h = zeros(M, 1);
% Compute h[1]
h(1) = 1.0;
for i = 1:M-1
    h(1) = h(1) * sin(x(i)*pi2);
end
% Compute h[m] for m = 2,...,M-1
for m = 2:M-1
    h(m) = 1.0;
    for i = 1:M-m
        h(m) = h(m) * sin(x(i)*pi2);
    end
    h(m) = h(m) * cos(x(M-m+1)*pi2);
end
% Compute h[M]
h(M) = cos(x(1)*pi2);
% The objective functions
f = zeros(M, 1);
for m = 1:M
    f(m) = x(M) + S(m)*h(m);
end
% Não há restrições de desigualdade para este problema
end

