function varargout = Deb53_mix(varargin)
%DEB53_MIX  Self-contained mixed-variable MOO adaptation of Deb53.
%
% Auto-generated by generate_selfcontained_wrappers_MOO_mix.m
% Source: Deb53, n=2, m=2, strategy=sobol_oscillatory, kappa=1000000
% Variable pattern: C,K
% D variables: nonuniform sorted finite sets with injected anchors.
% K variables: labels with permuted nonuniform numeric embeddings; labels carry no ordinal information.
%
%   x1   C [0,1] -> orig [0,1]
%   x2   K labels {k2_1,...,k2_100}, 100 levels, permuted embedding in [0,1]
%
% Usage:
%   PB = Deb53_mix()
%   F  = PB.func_F(xcell)       % recommended inside benchmark loops
%   F  = Deb53_mix(xcell)              % also valid; PB is memoized persistently
%   PD = Deb53_mix('ProblemData')
%

persistent PB_cached
if isempty(PB_cached)
lb_orig = [0; 0];
ub_orig = [1; 1];
lb_C_work = [0; 0];
ub_C_work = [1; 1];
var_types = {'C', 'K'};
K2_labels = { ...
    'k2_1', 'k2_2', 'k2_3', 'k2_4', 'k2_5', 'k2_6', 'k2_7', 'k2_8', 'k2_9', 'k2_10', ...
    'k2_11', 'k2_12', 'k2_13', 'k2_14', 'k2_15', 'k2_16', 'k2_17', 'k2_18', 'k2_19', 'k2_20', ...
    'k2_21', 'k2_22', 'k2_23', 'k2_24', 'k2_25', 'k2_26', 'k2_27', 'k2_28', 'k2_29', 'k2_30', ...
    'k2_31', 'k2_32', 'k2_33', 'k2_34', 'k2_35', 'k2_36', 'k2_37', 'k2_38', 'k2_39', 'k2_40', ...
    'k2_41', 'k2_42', 'k2_43', 'k2_44', 'k2_45', 'k2_46', 'k2_47', 'k2_48', 'k2_49', 'k2_50', ...
    'k2_51', 'k2_52', 'k2_53', 'k2_54', 'k2_55', 'k2_56', 'k2_57', 'k2_58', 'k2_59', 'k2_60', ...
    'k2_61', 'k2_62', 'k2_63', 'k2_64', 'k2_65', 'k2_66', 'k2_67', 'k2_68', 'k2_69', 'k2_70', ...
    'k2_71', 'k2_72', 'k2_73', 'k2_74', 'k2_75', 'k2_76', 'k2_77', 'k2_78', 'k2_79', 'k2_80', ...
    'k2_81', 'k2_82', 'k2_83', 'k2_84', 'k2_85', 'k2_86', 'k2_87', 'k2_88', 'k2_89', 'k2_90', ...
    'k2_91', 'k2_92', 'k2_93', 'k2_94', 'k2_95', 'k2_96', 'k2_97', 'k2_98', 'k2_99', 'k2_100'};
K2_embed  = [ ...
    0.7744823928405438; 0.377903555740975; 0.006316994859440746; 0.2547573940529875; 0.3006343036255583; 0.04423322117541159; 0.06162310796040634; 0.02705764328423417; ...
    0.4502933879562586; 0.435221988615874; 0.01903198887880482; 0.03334129875737508; 0.6550326602511279; 0.8386221299733454; 0.2771422366119556; 0.2887489149363776; ...
    0.6177881565097348; 0.01079181656344869; 0.1136107723178104; 0.2658123693394165; 0.005126464772080319; 0.0002267600501113848; 0.9288091652562318; 0.1588891819303545; ...
    0.07159933499747269; 0.1940901713182793; 0.5301858764508512; 1.623586879196874e-05; 0.000452292631118411; 0.06650211857190393; 0.8169112454833769; 0.02152521621701827; ...
    0.0125997953534342; 0.5818091567423361; 0; 0.09422359510178409; 0.351000286155137; 0.003167069220955598; 0.03677321100799466; 0.05250863491406071; ...
    0.00119684671987692; 0.05695954930832198; 0.9521989433507417; 0.5135971026727086; 0.4973151164730649; 0.5996412512894758; 0.1004514395332988; 0.3917915449245983; ...
    0.7132993297718992; 0.9057580147683395; 0.004078265852231609; 0.03010387066139036; 0.1428110974416723; 0.3128002827725516; 0.1759764298631956; 0.2439753713764724; ...
    0.5642902928476369; 0.120547106126176; 0.6935550761294618; 0.2334643410396907; 0.4204490259923919; 0.00173264994450532; 0.009144981233499945; 0.2035372749094614; ...
    0.1277243878567133; 0.3379814397519426; 0.00765490100202473; 1; 0.04826750032589135; 0.01457313353071523; 0.7955318203769981; 0.002387214818980119; ...
    0.5; 0.5470830675379204; 0.1673055669617211; 0.7333676341535037; 0.4059727873329207; 0.02419924632772747; 0.6362514406170753; 0.6741333607022341; ...
    0.9759287556304853; 0.2132473081372382; 0.07691745991411383; 0.0007726868893576372; 0.04040280971341995; 0.1351449513770039; 0.1069130181487709; 0.7537614912817806; ...
    0.08245914728183502; 0.4813382750302284; 0.8830440764893406; 8.569342923709401e-05; 0.8606659260533844; 0.3643070610746124; 0.3252487137606731; 0.2232223212671716; ...
    0.4656649221469998; 0.1507250949164488; 0.08822700461762281; 0.01671589156406504; ...
];
ProblemData = { ...
    [0; 1]; ... % x1 C
    K2_labels; ... % x2 K
};
x_anchor = {0.5, 'k2_73'};
anchors_set = [0.5 0 1; 0.5 0 1];

PB = struct();
PB.name = 'Deb53_mix';
PB.problem = 'Deb53';
PB.source = 'MOModels_Matlab';
PB.type = 'MOO_MIXED';
PB.nvar = 2; PB.n = 2; PB.nobj = 2; PB.m = 2;
PB.var_types = var_types;
PB.type_counts = struct('C', 1, 'D', 0, 'K', 1);
PB.ProblemData = ProblemData;
PB.strategy = 'sobol_oscillatory'; PB.kappa = 1000000;
PB.lb_orig = lb_orig; PB.ub_orig = ub_orig;
PB.lb_C_work = lb_C_work; PB.ub_C_work = ub_C_work;
PB.x_anchor = x_anchor;
PB.anchors_set = anchors_set;
PB.K2_labels = K2_labels; PB.K2_embed = K2_embed;
PB.pareto_front_known = true;
PB.pareto_set_known = true;
PB.pf_type = 'disconnected';
PB.ideal_point = [];
PB.nadir_point = [];
PB.core = @(xh) Deb53_orig(xh);
PB.decode = @(xr) decode(xr, PB);
PB.func_F = @(xr) objective(xr, PB);
PB_cached = PB;
else
    PB = PB_cached;
end

if nargin == 0
    varargout{1} = PB; return
end
arg1 = varargin{1};
if ischar(arg1) || (isstring(arg1) && isscalar(arg1))
    key = lower(char(arg1));
    switch key
        case {'problemdata','bounds','domain'}
            varargout{1} = PB.ProblemData; return
        case 'var_types'
            varargout{1} = PB.var_types; return
        case 'info'
            varargout{1} = PB; return
        otherwise
            error('Unknown string argument: %s', char(arg1));
    end
end
varargout{1} = PB.func_F(arg1);
end

function F = objective(xr, PB)
xh = decode(xr, PB);
F = PB.core(xh);
F = F(:);
end

function xh = decode(xr, PB)
if ~iscell(xr) || numel(xr) ~= 2
    error('Deb53_mix: input must be a cell array with exactly 2 entries.');
end
xh = zeros(2,1);
tmp = check_C(xr{1}, PB.lb_C_work(1), PB.ub_C_work(1), 'x1');
xh(1) = map_C_to_orig(tmp, PB.lb_C_work(1), PB.ub_C_work(1), PB.lb_orig(1), PB.ub_orig(1));
xh(2) = check_K(xr{2}, PB.K2_labels, PB.K2_embed, 'x2');
end

function v = check_C(val, a, b, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('Deb53_mix: %s must be a real scalar.', name);
end
if val < a || val > b
    error('Deb53_mix: %s=%g outside [%g,%g].', name, val, a, b);
end
v = double(val);
end

function xorig = map_C_to_orig(xwork, lbw, ubw, lbo, ubo)
if abs(ubw - lbw) <= 1e-14
    t = 0;
else
    t = (xwork - lbw) / (ubw - lbw);
end
t = max(0, min(1, t));
xorig = lbo + t * (ubo - lbo);
end

function v = check_D(val, grid, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('Deb53_mix: %s must be a real scalar.', name);
end
grid = grid(:);
[dmin, idx] = min(abs(grid - val));
if dmin > 1e-10 * max(1, max(abs(grid)))
    error('Deb53_mix: %s=%g not in grid.', name, val);
end
v = grid(idx);
end

function v = check_K(label, labels, embed, name)
if isstring(label), label = char(label); end
if ~(ischar(label) && isrow(label))
    error('Deb53_mix: %s must be a char vector or scalar string.', name);
end
idx = find(strcmp(label, labels), 1);
if isempty(idx)
    error('Deb53_mix: %s unknown label ''%s''.', name, label);
end
v = embed(idx);
end


% -------------------------------------------------------------------------
% Embedded original continuous MOO problem (top-level function renamed only)
% -------------------------------------------------------------------------
function f = Deb53_orig(x)
%###############################################################################
%
%   As described by K. Deb in "Multi-objective Genetic Algorithms: Problem
%   Difficulties and Construction of Test Problems", Evolutionary Computation 
%   7(3): 205-230, 1999.
%
%   Example 5.1.3 (Non-uniformly Represented Pareto-optimal Front).
%
%   In the above paper the variables bounds were not set.
%   We considered 0.0 <= x[i] <= 1.0, i=1,2. The function f1 corresponds
%   to equation (16) and gx to equation (10).
%
%   This file is part of a collection of problems developed for
%   derivative-free multiobjective optimization in
%   A. L. Custódio, J. F. A. Madeira, A. I. F. Vaz, and L. N. Vicente,
%   Direct Multisearch for Multiobjective Optimization, 2010.
%
%   Written by the authors in June 1, 2010.
%
%   MATLAB version by J. F. A. Madeira
%   November 7, 2025
%
%###############################################################################
%
% Problem characteristics:
% - Number of variables: 2
% - Number of objectives: 2
%   Bounds: x1 in [0,1], x2 in [0,1]
%
%
M = 2; % Number of objectives (fixed)
% Check dimension
n = length(x);
if n ~= 2
    error('Deb53 requires exactly 2 variables, %d provided', n);
end
% Ensure x is a column vector
x = x(:);
% Parameters
gamma = 1.0;
beta = 1.0;
alpha = 4;
% Initialize objectives
f = zeros(M, 1);
% Function f1
ff1 = 1 - exp(-4*x(1)) * sin(5*pi*x(1))^4;
% g function
if x(2) <= 0.4
    gx = 4 - 3*exp(-((x(2)-0.2)/0.02)^2);
else
    gx = 4 - 2*exp(-((x(2)-0.7)/0.2)^2);
end
% h function
if ff1 < beta*gx
    h = 1 - (ff1/(beta*gx))^alpha;
else
    h = 0;
end
% Objective functions
f(1) = ff1;
f(2) = gx * h;
end

