function varargout = ex005_mix(varargin)
%EX005_MIX  Self-contained mixed-variable MOO adaptation of ex005.
%
% Auto-generated by generate_selfcontained_wrappers_MOO_mix.m
% Source: ex005, n=2, m=2, strategy=sobol_oscillatory, kappa=1000000
% Variable pattern: C,K
% D variables: nonuniform sorted finite sets with injected anchors.
% K variables: labels with permuted nonuniform numeric embeddings; labels carry no ordinal information.
%
%   x1   C [-1,2] -> orig [-1,2]
%   x2   K labels {k2_1,...,k2_116}, 116 levels, permuted embedding in [1,2]
%
% Usage:
%   PB = ex005_mix()
%   F  = PB.func_F(xcell)       % recommended inside benchmark loops
%   F  = ex005_mix(xcell)              % also valid; PB is memoized persistently
%   PD = ex005_mix('ProblemData')
%

persistent PB_cached
if isempty(PB_cached)
lb_orig = [-1; 1];
ub_orig = [2; 2];
lb_C_work = [-1; 1];
ub_C_work = [2; 2];
var_types = {'C', 'K'};
K2_labels = { ...
    'k2_1', 'k2_2', 'k2_3', 'k2_4', 'k2_5', 'k2_6', 'k2_7', 'k2_8', 'k2_9', 'k2_10', ...
    'k2_11', 'k2_12', 'k2_13', 'k2_14', 'k2_15', 'k2_16', 'k2_17', 'k2_18', 'k2_19', 'k2_20', ...
    'k2_21', 'k2_22', 'k2_23', 'k2_24', 'k2_25', 'k2_26', 'k2_27', 'k2_28', 'k2_29', 'k2_30', ...
    'k2_31', 'k2_32', 'k2_33', 'k2_34', 'k2_35', 'k2_36', 'k2_37', 'k2_38', 'k2_39', 'k2_40', ...
    'k2_41', 'k2_42', 'k2_43', 'k2_44', 'k2_45', 'k2_46', 'k2_47', 'k2_48', 'k2_49', 'k2_50', ...
    'k2_51', 'k2_52', 'k2_53', 'k2_54', 'k2_55', 'k2_56', 'k2_57', 'k2_58', 'k2_59', 'k2_60', ...
    'k2_61', 'k2_62', 'k2_63', 'k2_64', 'k2_65', 'k2_66', 'k2_67', 'k2_68', 'k2_69', 'k2_70', ...
    'k2_71', 'k2_72', 'k2_73', 'k2_74', 'k2_75', 'k2_76', 'k2_77', 'k2_78', 'k2_79', 'k2_80', ...
    'k2_81', 'k2_82', 'k2_83', 'k2_84', 'k2_85', 'k2_86', 'k2_87', 'k2_88', 'k2_89', 'k2_90', ...
    'k2_91', 'k2_92', 'k2_93', 'k2_94', 'k2_95', 'k2_96', 'k2_97', 'k2_98', 'k2_99', 'k2_100', ...
    'k2_101', 'k2_102', 'k2_103', 'k2_104', 'k2_105', 'k2_106', 'k2_107', 'k2_108', 'k2_109', 'k2_110', ...
    'k2_111', 'k2_112', 'k2_113', 'k2_114', 'k2_115', 'k2_116'};
K2_embed  = [ ...
    1.860086629377258; 1.918544777419698; 1.00166625379644; 1.681189217323657; 1.16295594409765; 1.347121337494206; 1.116777733574331; 1.008794540263033; ...
    1.018885983987123; 1.209839954818255; 1.444097602775315; 1.007532587841012; 1.000315696060409; 1.418544030272959; 1.822354853188518; 1.303780910314261; ...
    1.785606734042307; 1.135473138923035; 1.000835387906818; 1.938530601222381; 1.122829915436275; 1.005343049881639; 1.070114172863486; 1.314300607230064; ...
    1.979257319442433; 1.201544063779016; 1.21833169539389; 1.585350466466978; 1.001209373586734; 1.87932369910334; 1.273466863540461; 1.193442709988664; ...
    1.033690267429329; 1.028200786345906; 1.105204717910827; 1.000539328280226; 1.570196470514095; 1.030874378010019; 1.254282948798425; 1.431210401760136; ...
    1.170292545757422; 1.057555719794117; 1.016890849430046; 1.540581524999921; 1.370064823002671; 1.08915043777048; 2; 1.600736831621167; ...
    1.177818297556216; 1.129061222703215; 1.511883804875482; 1.526118527948527; 1.325029795486936; 1.497876314599323; 1; 1.043012357652564; ...
    1.555273830135869; 1.046417861794732; 1.039757236979228; 1.235907909349194; 1.065767195228652; 1.00001133248579; 1.841097320806819; 1.470538831548061; ...
    1.094329922263917; 1.000158276411228; 1.155807109316008; 1.079299265062344; 1.616356573013839; 1.381858905619012; 1.632210691205707; 1.00284659172905; ...
    1.015024401220887; 1.76759921591843; 1.003578224850517; 1.02101222243523; 1.013284151669545; 1.244994943357245; 1.227020584734206; 1.142067129584879; ...
    1.6979907225744; 1.393869389246442; 1.07462429479027; 1.898809445090291; 1.648300180390922; 1.5; 1.000059813218593; 1.110903174904823; ...
    1.457206719838516; 1.049975671570732; 1.002210584933978; 1.335969650391065; 1.025667360122851; 1.061581630703629; 1.0063831120591; 1.023271917211229; ...
    1.263773175935078; 1.958767816749571; 1.010171912003277; 1.732312555583242; 1.293469519458132; 1.484095008732746; 1.011667537231277; 1.664626028503964; ...
    1.749834805392184; 1.00440920380644; 1.406097393714985; 1.099680821094956; 1.803858301144116; 1.283365239176049; 1.036650540025061; 1.05368767342404; ...
    1.084140761709262; 1.148844642693757; 1.358486012806642; 1.715031514024719; ...
];
ProblemData = { ...
    [-1; 2]; ... % x1 C
    K2_labels; ... % x2 K
};
x_anchor = {0.5, 'k2_86'};
anchors_set = [0.5 -1 2; 1.5 1 2];

PB = struct();
PB.name = 'ex005_mix';
PB.problem = 'ex005';
PB.source = 'MOModels_Matlab';
PB.type = 'MOO_MIXED';
PB.nvar = 2; PB.n = 2; PB.nobj = 2; PB.m = 2;
PB.var_types = var_types;
PB.type_counts = struct('C', 1, 'D', 0, 'K', 1);
PB.ProblemData = ProblemData;
PB.strategy = 'sobol_oscillatory'; PB.kappa = 1000000;
PB.lb_orig = lb_orig; PB.ub_orig = ub_orig;
PB.lb_C_work = lb_C_work; PB.ub_C_work = ub_C_work;
PB.x_anchor = x_anchor;
PB.anchors_set = anchors_set;
PB.K2_labels = K2_labels; PB.K2_embed = K2_embed;
PB.pareto_front_known = false;
PB.pareto_set_known = false;
PB.pf_type = 'unknown';
PB.ideal_point = [];
PB.nadir_point = [];
PB.core = @(xh) ex005_orig(xh);
PB.decode = @(xr) decode(xr, PB);
PB.func_F = @(xr) objective(xr, PB);
PB_cached = PB;
else
    PB = PB_cached;
end

if nargin == 0
    varargout{1} = PB; return
end
arg1 = varargin{1};
if ischar(arg1) || (isstring(arg1) && isscalar(arg1))
    key = lower(char(arg1));
    switch key
        case {'problemdata','bounds','domain'}
            varargout{1} = PB.ProblemData; return
        case 'var_types'
            varargout{1} = PB.var_types; return
        case 'info'
            varargout{1} = PB; return
        otherwise
            error('Unknown string argument: %s', char(arg1));
    end
end
varargout{1} = PB.func_F(arg1);
end

function F = objective(xr, PB)
xh = decode(xr, PB);
F = PB.core(xh);
F = F(:);
end

function xh = decode(xr, PB)
if ~iscell(xr) || numel(xr) ~= 2
    error('ex005_mix: input must be a cell array with exactly 2 entries.');
end
xh = zeros(2,1);
tmp = check_C(xr{1}, PB.lb_C_work(1), PB.ub_C_work(1), 'x1');
xh(1) = map_C_to_orig(tmp, PB.lb_C_work(1), PB.ub_C_work(1), PB.lb_orig(1), PB.ub_orig(1));
xh(2) = check_K(xr{2}, PB.K2_labels, PB.K2_embed, 'x2');
end

function v = check_C(val, a, b, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('ex005_mix: %s must be a real scalar.', name);
end
if val < a || val > b
    error('ex005_mix: %s=%g outside [%g,%g].', name, val, a, b);
end
v = double(val);
end

function xorig = map_C_to_orig(xwork, lbw, ubw, lbo, ubo)
if abs(ubw - lbw) <= 1e-14
    t = 0;
else
    t = (xwork - lbw) / (ubw - lbw);
end
t = max(0, min(1, t));
xorig = lbo + t * (ubo - lbo);
end

function v = check_D(val, grid, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('ex005_mix: %s must be a real scalar.', name);
end
grid = grid(:);
[dmin, idx] = min(abs(grid - val));
if dmin > 1e-10 * max(1, max(abs(grid)))
    error('ex005_mix: %s=%g not in grid.', name, val);
end
v = grid(idx);
end

function v = check_K(label, labels, embed, name)
if isstring(label), label = char(label); end
if ~(ischar(label) && isrow(label))
    error('ex005_mix: %s must be a char vector or scalar string.', name);
end
idx = find(strcmp(label, labels), 1);
if isempty(idx)
    error('ex005_mix: %s unknown label ''%s''.', name, label);
end
v = embed(idx);
end


% -------------------------------------------------------------------------
% Embedded original continuous MOO problem (top-level function renamed only)
% -------------------------------------------------------------------------
function f = ex005_orig(x)
%###############################################################################
%
%   ex005.mod
%   Original AMPL coding by Sven Leyffer, Argonne Natl. Lab.
%
%   A simple multi-objective optimization problem (p. 281):
%   C.-L. Hwang & A. S. Md. Masud, Multiple Objective
%   Decision Making - Methods and Applications, No. 164 in 
%   Lecture Notes in Economics and Mathematical Systems,
%   Springer, 1979.
%
%   MATLAB version by J. F. A. Madeira
%   November 7, 2025
%
%###############################################################################
%
% Problem characteristics:
% - Number of variables: 2
% - Number of objectives: 2
%   Bounds: x1 in [-1,2], x2 in [1,2]
%
%
M = 2; % Number of objectives (fixed)
% Check dimension
n = length(x);
if n ~= 2
    error('ex005 requires exactly 2 variables, %d provided', n);
end
% Ensure x is a column vector
x = x(:);
% Initialize objectives
f = zeros(M, 1);
% Objective functions
f(1) = x(1)^2 - x(2)^2;
f(2) = x(1) / x(2);
end

