function varargout = IKK1_mix(varargin)
%IKK1_MIX  Self-contained mixed-variable MOO adaptation of IKK1.
%
% Auto-generated by generate_selfcontained_wrappers_MOO_mix.m
% Source: IKK1, n=2, m=3, strategy=sobol_oscillatory, kappa=1000000
% Variable pattern: C,K
% D variables: nonuniform sorted finite sets with injected anchors.
% K variables: labels with permuted nonuniform numeric embeddings; labels carry no ordinal information.
%
%   x1   C [-50,50] -> orig [-50,50]
%   x2   K labels {k2_1,...,k2_122}, 122 levels, permuted embedding in [-50,50]
%
% Usage:
%   PB = IKK1_mix()
%   F  = PB.func_F(xcell)       % recommended inside benchmark loops
%   F  = IKK1_mix(xcell)              % also valid; PB is memoized persistently
%   PD = IKK1_mix('ProblemData')
%

persistent PB_cached
if isempty(PB_cached)
lb_orig = [-50; -50];
ub_orig = [50; 50];
lb_C_work = [-50; -50];
ub_C_work = [50; 50];
var_types = {'C', 'K'};
K2_labels = { ...
    'k2_1', 'k2_2', 'k2_3', 'k2_4', 'k2_5', 'k2_6', 'k2_7', 'k2_8', 'k2_9', 'k2_10', ...
    'k2_11', 'k2_12', 'k2_13', 'k2_14', 'k2_15', 'k2_16', 'k2_17', 'k2_18', 'k2_19', 'k2_20', ...
    'k2_21', 'k2_22', 'k2_23', 'k2_24', 'k2_25', 'k2_26', 'k2_27', 'k2_28', 'k2_29', 'k2_30', ...
    'k2_31', 'k2_32', 'k2_33', 'k2_34', 'k2_35', 'k2_36', 'k2_37', 'k2_38', 'k2_39', 'k2_40', ...
    'k2_41', 'k2_42', 'k2_43', 'k2_44', 'k2_45', 'k2_46', 'k2_47', 'k2_48', 'k2_49', 'k2_50', ...
    'k2_51', 'k2_52', 'k2_53', 'k2_54', 'k2_55', 'k2_56', 'k2_57', 'k2_58', 'k2_59', 'k2_60', ...
    'k2_61', 'k2_62', 'k2_63', 'k2_64', 'k2_65', 'k2_66', 'k2_67', 'k2_68', 'k2_69', 'k2_70', ...
    'k2_71', 'k2_72', 'k2_73', 'k2_74', 'k2_75', 'k2_76', 'k2_77', 'k2_78', 'k2_79', 'k2_80', ...
    'k2_81', 'k2_82', 'k2_83', 'k2_84', 'k2_85', 'k2_86', 'k2_87', 'k2_88', 'k2_89', 'k2_90', ...
    'k2_91', 'k2_92', 'k2_93', 'k2_94', 'k2_95', 'k2_96', 'k2_97', 'k2_98', 'k2_99', 'k2_100', ...
    'k2_101', 'k2_102', 'k2_103', 'k2_104', 'k2_105', 'k2_106', 'k2_107', 'k2_108', 'k2_109', 'k2_110', ...
    'k2_111', 'k2_112', 'k2_113', 'k2_114', 'k2_115', 'k2_116', 'k2_117', 'k2_118', 'k2_119', 'k2_120', ...
    'k2_121', 'k2_122'};
K2_embed  = [ ...
    -25.79558237249314; -4.693416125240127; 16.36750992928791; 34.86006803155534; 29.55318203769981; 21.14910297478004; -43.79422903519743; 31.29994659825482; ...
    -23.11250099804985; -42.10933858846668; -19.27646109896813; 17.93982917015316; 38.50950829706534; -2.153395027779226; 11.77881565097348; -43.3950403610979; ...
    -12.95487367986841; -47.26732398335551; -45.24813042362481; 4.553417213119083; -38.57685463832041; -46.19299737347402; -47.9402140505041; 1.80908196845003; ...
    -44.17897788823491; -14.05651936156688; -46.48110650371864; -50; -47.50396226693327; -38.00933908646216; -29.90651967186314; 0.4678092379246763; ...
    -49.2215995656202; -29.11990694011414; -39.12838458056518; -49.99899696725497; -40.18401452059064; -48.96731201662196; -5.933212202058904; -49.74804956573932; ...
    50; -49.99470596143266; 24.44511029459062; 42.24889643367835; -41.17729953823772; -49.09968907014893; -3.433507785300016; -45.57667788245884; ...
    -48.82422626758494; -49.43503389024399; -0.8529863244460927; -49.60974353911046; -40.68838214718123; -48.67019763548149; -39.66406022129024; -21.23177261955558; ...
    3.170921582726393; 27.82850824159323; -36.82583386252323; -22.18140779659801; -16.20185602480574; 26.1258446590614; -49.92606022713025; -27.49354123352359; ...
    5.956657418764976; -47.72819457624275; -30.67556899502216; -49.89295893849074; -36.20958936525303; -49.68329307790444; -9.532858036978816; -26.65356589603093; ...
    0; 36.67358384015196; 8.825722984317217; -48.14021852402922; -8.352839385005474; -33.57842663683172; -48.50499922222683; -49.52708928216946; ...
    40.3679198237807; -47.01809099543345; 10.29172268257968; -48.3284108435935; 46.07885494958148; -15.138814024532; -41.6509049627203; -20.26349144114995; ...
    7.3807301952993; -49.95226431910645; -34.92749050835512; -42.55274255337264; -49.97205789692184; 19.53366574494794; -7.152988808001105; -32.87848085525152; ...
    13.28708772323404; 22.78622370142111; -42.98126104101327; 14.81662421444011; -34.26138991707808; 48.02799089173769; -18.27057927510862; -24.91948201204763; ...
    -32.16143401472691; 33.06888203594207; -49.33329435398758; -28.31561802818286; -46.75607872355997; -49.98599103266717; -49.85252069577896; -17.24574447799305; ...
    -45.89157787634717; -35.57684951383294; -37.42570821526687; -44.54944014629029; -49.80434221444471; -10.69313954245141; -11.83377936763035; -24.02515713258467; ...
    -44.90577154133904; 44.15251573764846; ...
];
ProblemData = { ...
    [-50; 50]; ... % x1 C
    K2_labels; ... % x2 K
};
x_anchor = {0, 'k2_73'};
anchors_set = [0 -50 50; 0 -50 50];

PB = struct();
PB.name = 'IKK1_mix';
PB.problem = 'IKK1';
PB.source = 'MOModels_Matlab';
PB.type = 'MOO_MIXED';
PB.nvar = 2; PB.n = 2; PB.nobj = 3; PB.m = 3;
PB.var_types = var_types;
PB.type_counts = struct('C', 1, 'D', 0, 'K', 1);
PB.ProblemData = ProblemData;
PB.strategy = 'sobol_oscillatory'; PB.kappa = 1000000;
PB.lb_orig = lb_orig; PB.ub_orig = ub_orig;
PB.lb_C_work = lb_C_work; PB.ub_C_work = ub_C_work;
PB.x_anchor = x_anchor;
PB.anchors_set = anchors_set;
PB.K2_labels = K2_labels; PB.K2_embed = K2_embed;
PB.pareto_front_known = false;
PB.pareto_set_known = false;
PB.pf_type = 'unknown';
PB.ideal_point = [];
PB.nadir_point = [];
PB.core = @(xh) IKK1_orig(xh);
PB.decode = @(xr) decode(xr, PB);
PB.func_F = @(xr) objective(xr, PB);
PB_cached = PB;
else
    PB = PB_cached;
end

if nargin == 0
    varargout{1} = PB; return
end
arg1 = varargin{1};
if ischar(arg1) || (isstring(arg1) && isscalar(arg1))
    key = lower(char(arg1));
    switch key
        case {'problemdata','bounds','domain'}
            varargout{1} = PB.ProblemData; return
        case 'var_types'
            varargout{1} = PB.var_types; return
        case 'info'
            varargout{1} = PB; return
        otherwise
            error('Unknown string argument: %s', char(arg1));
    end
end
varargout{1} = PB.func_F(arg1);
end

function F = objective(xr, PB)
xh = decode(xr, PB);
F = PB.core(xh);
F = F(:);
end

function xh = decode(xr, PB)
if ~iscell(xr) || numel(xr) ~= 2
    error('IKK1_mix: input must be a cell array with exactly 2 entries.');
end
xh = zeros(2,1);
tmp = check_C(xr{1}, PB.lb_C_work(1), PB.ub_C_work(1), 'x1');
xh(1) = map_C_to_orig(tmp, PB.lb_C_work(1), PB.ub_C_work(1), PB.lb_orig(1), PB.ub_orig(1));
xh(2) = check_K(xr{2}, PB.K2_labels, PB.K2_embed, 'x2');
end

function v = check_C(val, a, b, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('IKK1_mix: %s must be a real scalar.', name);
end
if val < a || val > b
    error('IKK1_mix: %s=%g outside [%g,%g].', name, val, a, b);
end
v = double(val);
end

function xorig = map_C_to_orig(xwork, lbw, ubw, lbo, ubo)
if abs(ubw - lbw) <= 1e-14
    t = 0;
else
    t = (xwork - lbw) / (ubw - lbw);
end
t = max(0, min(1, t));
xorig = lbo + t * (ubo - lbo);
end

function v = check_D(val, grid, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('IKK1_mix: %s must be a real scalar.', name);
end
grid = grid(:);
[dmin, idx] = min(abs(grid - val));
if dmin > 1e-10 * max(1, max(abs(grid)))
    error('IKK1_mix: %s=%g not in grid.', name, val);
end
v = grid(idx);
end

function v = check_K(label, labels, embed, name)
if isstring(label), label = char(label); end
if ~(ischar(label) && isrow(label))
    error('IKK1_mix: %s must be a char vector or scalar string.', name);
end
idx = find(strcmp(label, labels), 1);
if isempty(idx)
    error('IKK1_mix: %s unknown label ''%s''.', name, label);
end
v = embed(idx);
end


% -------------------------------------------------------------------------
% Embedded original continuous MOO problem (top-level function renamed only)
% -------------------------------------------------------------------------
function f = IKK1_orig(x)
%###############################################################################
%
%   As described by Huband et al. in "A review of multiobjective test problems
%   and a scalable test problem toolkit", IEEE Transactions on Evolutionary 
%   Computing 10(5): 477-506, 2006.
%
%   Example IKK1, see the previous cited paper for the original reference.
%
%   This file is part of a collection of problems developed for
%   derivative-free multiobjective optimization in
%   A. L. Custódio, J. F. A. Madeira, A. I. F. Vaz, and L. N. Vicente,
%   Direct Multisearch for Multiobjective Optimization, 2010.
%
%   Written by the authors in June 1, 2010.
%
%   MATLAB version by J. F. A. Madeira
%   November 7, 2025
%
%###############################################################################
%
% Problem characteristics:
% - Number of variables: 2
% - Number of objectives: 3
%   Bounds: x1 in [-50,50], x2 in [-50,50]
%
%
M = 3; % Number of objectives (fixed)
% Check dimension
n = length(x);
if n ~= 2
    error('IKK1 requires exactly 2 variables, %d provided', n);
end
% Ensure x is a column vector
x = x(:);
% Initialize objectives
f = zeros(M, 1);
% Objective functions
f(1) = x(1)^2;
f(2) = (x(1)-20)^2;
f(3) = x(2)^2;
end

