function varargout = MHHM2_mix(varargin)
%MHHM2_MIX  Self-contained mixed-variable MOO adaptation of MHHM2.
%
% Auto-generated by generate_selfcontained_wrappers_MOO_mix.m
% Source: MHHM2, n=2, m=3, strategy=sobol_oscillatory, kappa=1000000
% Variable pattern: C,K
% D variables: nonuniform sorted finite sets with injected anchors.
% K variables: labels with permuted nonuniform numeric embeddings; labels carry no ordinal information.
%
%   x1   C [0,1] -> orig [0,1]
%   x2   K labels {k2_1,...,k2_127}, 127 levels, permuted embedding in [0,1]
%
% Usage:
%   PB = MHHM2_mix()
%   F  = PB.func_F(xcell)       % recommended inside benchmark loops
%   F  = MHHM2_mix(xcell)              % also valid; PB is memoized persistently
%   PD = MHHM2_mix('ProblemData')
%

persistent PB_cached
if isempty(PB_cached)
lb_orig = [0; 0];
ub_orig = [1; 1];
lb_C_work = [0; 0];
ub_C_work = [1; 1];
var_types = {'C', 'K'};
K2_labels = { ...
    'k2_1', 'k2_2', 'k2_3', 'k2_4', 'k2_5', 'k2_6', 'k2_7', 'k2_8', 'k2_9', 'k2_10', ...
    'k2_11', 'k2_12', 'k2_13', 'k2_14', 'k2_15', 'k2_16', 'k2_17', 'k2_18', 'k2_19', 'k2_20', ...
    'k2_21', 'k2_22', 'k2_23', 'k2_24', 'k2_25', 'k2_26', 'k2_27', 'k2_28', 'k2_29', 'k2_30', ...
    'k2_31', 'k2_32', 'k2_33', 'k2_34', 'k2_35', 'k2_36', 'k2_37', 'k2_38', 'k2_39', 'k2_40', ...
    'k2_41', 'k2_42', 'k2_43', 'k2_44', 'k2_45', 'k2_46', 'k2_47', 'k2_48', 'k2_49', 'k2_50', ...
    'k2_51', 'k2_52', 'k2_53', 'k2_54', 'k2_55', 'k2_56', 'k2_57', 'k2_58', 'k2_59', 'k2_60', ...
    'k2_61', 'k2_62', 'k2_63', 'k2_64', 'k2_65', 'k2_66', 'k2_67', 'k2_68', 'k2_69', 'k2_70', ...
    'k2_71', 'k2_72', 'k2_73', 'k2_74', 'k2_75', 'k2_76', 'k2_77', 'k2_78', 'k2_79', 'k2_80', ...
    'k2_81', 'k2_82', 'k2_83', 'k2_84', 'k2_85', 'k2_86', 'k2_87', 'k2_88', 'k2_89', 'k2_90', ...
    'k2_91', 'k2_92', 'k2_93', 'k2_94', 'k2_95', 'k2_96', 'k2_97', 'k2_98', 'k2_99', 'k2_100', ...
    'k2_101', 'k2_102', 'k2_103', 'k2_104', 'k2_105', 'k2_106', 'k2_107', 'k2_108', 'k2_109', 'k2_110', ...
    'k2_111', 'k2_112', 'k2_113', 'k2_114', 'k2_115', 'k2_116', 'k2_117', 'k2_118', 'k2_119', 'k2_120', ...
    'k2_121', 'k2_122', 'k2_123', 'k2_124', 'k2_125', 'k2_126', 'k2_127'};
K2_embed  = [ ...
    0.1823268993872381; 0.5605768498792567; 0.04013692966633287; 1; 0.297209928471291; 0.7377102891852432; 0.001775385687232841; 0.495014066702932; ...
    0.0186903602282925; 0.1685286308920595; 0.0001271164345699025; 0.8370603292200594; 0.04945801632282962; 0.4459567218456484; 0.3163280747819717; 0.3463177386689404; ...
    0.1140982844017542; 0.02479611978652466; 4.803775261708115e-05; 0.5881417220300151; 0.5206689159983203; 0.04622468902698076; 0.007063153588351439; 0.01206653789990599; ...
    0.3671961452516068; 0.005126464772080319; 0.2439753713764724; 0.06368756885826761; 0.01516788843743262; 0.5470830675379204; 0.3361450037055101; 0.6907608335269508; ...
    0.6022143554949208; 0.2524240489419776; 0.1490082606632316; 0.05631075153941328; 0.5; 0.05993296292492182; 0.9254954443715241; 0.6164814753443587; ...
    0.3066821026226881; 0.003541161079008751; 0.004291160289852588; 0.1036528585905691; 0.7700145934558577; 0.3887909197944219; 0.7537614912817806; 0.4579415326240115; ...
    0.006049642533612851; 0; 0.5077469746717251; 0.03727954813933471; 0.02705764328423417; 0.2118439848354459; 0.8718131171683238; 0.4341569000655011; ...
    0.6309438420457301; 0.3566678283122591; 0.1753485971579777; 0.002286181424414137; 0.4111089181571743; 0.8199924730049105; 0.9810580889456052; 0.9623271443526171; ...
    0.4225412423430314; 0.9438064894968293; 0.1428110974416723; 0.03454448774021393; 0.02943512515158411; 0.1967626347195643; 0.1195415042408041; 0.2698270939427608; ...
    0.9073933256446679; 0.1367669451343447; 0.1553595219684217; 0.06757591701427219; 0.000433150382379106; 0.3998590913045165; 0.6604573358554925; 0.05281956612645669; ...
    0.2042221046859763; 0.008169361287518112; 0.0006709245640169252; 0.08449299890601486; 0.0002535447783759595; 0.7864703148625742; 0.1251332656786865; 0.5337806841219158; ...
    0.2787833413898064; 0.009370541835906819; 0.2196292700631586; 0.8894994466151904; 0.161865957141088; 0.02264887979541998; 0.01356553727584964; 0.02061421078680685; ...
    0.2275789462597901; 9.101452182454766e-06; 0.6456022116492058; 0.3261487443175255; 0.03193020472180132; 0.1308747048591663; 0.07159933499747269; 0.09378762769466467; ...
    0.1088024568301263; 0.8031293708484842; 0.08906959708641024; 0.09864831270570812; 0.04311814737936794; 0.08005659513165221; 0.2356939905256168; 0.7062106892330272; ...
    0.2610409751564345; 0.6755099620819267; 0.2879106459233802; 0.7218602641480409; 0.01687553298453479; 0.8543336437299677; 0.5742628099955116; 0.0009712834478342614; ...
    0.07575913112000618; 0.4824693936254196; 0.377903555740975; 0.002873777472949767; 0.4701121518594906; 0.001338217363208955; 0.01066889237261745; ...
];
ProblemData = { ...
    [0; 1]; ... % x1 C
    K2_labels; ... % x2 K
};
x_anchor = {0.5, 'k2_37'};
anchors_set = [0.5 0 1; 0.5 0 1];

PB = struct();
PB.name = 'MHHM2_mix';
PB.problem = 'MHHM2';
PB.source = 'MOModels_Matlab';
PB.type = 'MOO_MIXED';
PB.nvar = 2; PB.n = 2; PB.nobj = 3; PB.m = 3;
PB.var_types = var_types;
PB.type_counts = struct('C', 1, 'D', 0, 'K', 1);
PB.ProblemData = ProblemData;
PB.strategy = 'sobol_oscillatory'; PB.kappa = 1000000;
PB.lb_orig = lb_orig; PB.ub_orig = ub_orig;
PB.lb_C_work = lb_C_work; PB.ub_C_work = ub_C_work;
PB.x_anchor = x_anchor;
PB.anchors_set = anchors_set;
PB.K2_labels = K2_labels; PB.K2_embed = K2_embed;
PB.pareto_front_known = false;
PB.pareto_set_known = false;
PB.pf_type = 'unknown';
PB.ideal_point = [];
PB.nadir_point = [];
PB.core = @(xh) MHHM2_orig(xh);
PB.decode = @(xr) decode(xr, PB);
PB.func_F = @(xr) objective(xr, PB);
PB_cached = PB;
else
    PB = PB_cached;
end

if nargin == 0
    varargout{1} = PB; return
end
arg1 = varargin{1};
if ischar(arg1) || (isstring(arg1) && isscalar(arg1))
    key = lower(char(arg1));
    switch key
        case {'problemdata','bounds','domain'}
            varargout{1} = PB.ProblemData; return
        case 'var_types'
            varargout{1} = PB.var_types; return
        case 'info'
            varargout{1} = PB; return
        otherwise
            error('Unknown string argument: %s', char(arg1));
    end
end
varargout{1} = PB.func_F(arg1);
end

function F = objective(xr, PB)
xh = decode(xr, PB);
F = PB.core(xh);
F = F(:);
end

function xh = decode(xr, PB)
if ~iscell(xr) || numel(xr) ~= 2
    error('MHHM2_mix: input must be a cell array with exactly 2 entries.');
end
xh = zeros(2,1);
tmp = check_C(xr{1}, PB.lb_C_work(1), PB.ub_C_work(1), 'x1');
xh(1) = map_C_to_orig(tmp, PB.lb_C_work(1), PB.ub_C_work(1), PB.lb_orig(1), PB.ub_orig(1));
xh(2) = check_K(xr{2}, PB.K2_labels, PB.K2_embed, 'x2');
end

function v = check_C(val, a, b, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('MHHM2_mix: %s must be a real scalar.', name);
end
if val < a || val > b
    error('MHHM2_mix: %s=%g outside [%g,%g].', name, val, a, b);
end
v = double(val);
end

function xorig = map_C_to_orig(xwork, lbw, ubw, lbo, ubo)
if abs(ubw - lbw) <= 1e-14
    t = 0;
else
    t = (xwork - lbw) / (ubw - lbw);
end
t = max(0, min(1, t));
xorig = lbo + t * (ubo - lbo);
end

function v = check_D(val, grid, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('MHHM2_mix: %s must be a real scalar.', name);
end
grid = grid(:);
[dmin, idx] = min(abs(grid - val));
if dmin > 1e-10 * max(1, max(abs(grid)))
    error('MHHM2_mix: %s=%g not in grid.', name, val);
end
v = grid(idx);
end

function v = check_K(label, labels, embed, name)
if isstring(label), label = char(label); end
if ~(ischar(label) && isrow(label))
    error('MHHM2_mix: %s must be a char vector or scalar string.', name);
end
idx = find(strcmp(label, labels), 1);
if isempty(idx)
    error('MHHM2_mix: %s unknown label ''%s''.', name, label);
end
v = embed(idx);
end


% -------------------------------------------------------------------------
% Embedded original continuous MOO problem (top-level function renamed only)
% -------------------------------------------------------------------------
function f = MHHM2_orig(x)
% MHHM2 function
%
%   As described by Huband et al. in "A review of multiobjective test problems
%   and a scalable test problem toolkit", IEEE Transactions on Evolutionary 
%   Computing 10(5): 477-506, 2006.
%
%   Example MHHM2, see the previous cited paper for the original reference.
%
%   This file is part of a collection of problems developed for
%   derivative-free multiobjective optimization in
%   A. L. Custódio, J. F. A. Madeira, A. I. F. Vaz, and L. N. Vicente,
%   Direct Multisearch for Multiobjective Optimization, 2010.
%
%   Written by the authors in June 1, 2010.
%   Adapted to MATLAB format in November 2025.
%
%   Input: x is a 2-dimensional vector
%   Output: f is a 3-dimensional vector with the function values
%
% Problem characteristics:
% - Number of variables: 2 (fixed)
% - Number of objectives: 3 (fixed)
%   Bounds: x1 in [0,1], x2 in [0,1]
%
% Check dimension
n = length(x);
if n ~= 2
    error('MHHM2 requires exactly 2 variables, %d provided', n);
end
% Objective functions
f = zeros(3, 1);
f(1) = (x(1) - 0.8)^2 + (x(2) - 0.6)^2;
f(2) = (x(1) - 0.85)^2 + (x(2) - 0.7)^2;
f(3) = (x(1) - 0.9)^2 + (x(2) - 0.6)^2;
end

