function varargout = WFG8_mix(varargin)
%WFG8_MIX  Self-contained mixed-variable MOO adaptation of WFG8.
%
% Auto-generated by generate_selfcontained_wrappers_MOO_mix.m
% Source: WFG8, n=8, m=3, strategy=sobol_oscillatory, kappa=1000000
% Variable pattern: C,K,D,C,D,K,C,K
% D variables: nonuniform sorted finite sets with injected anchors.
% K variables: labels with permuted nonuniform numeric embeddings; labels carry no ordinal information.
%
%   x1   C [0,298578.125] -> orig [0,2]
%   x2   K labels {k2_1,...,k2_31}, 31 levels, permuted embedding in [0,4]
%   x3   D sorted nonuniform grid [0,...,6], 99 values
%   x4   C [0,5190.3125] -> orig [0,8]
%   x5   D sorted nonuniform grid [0,...,10], 22 values
%   x6   K labels {k6_1,...,k6_63}, 63 levels, permuted embedding in [0,12]
%   x7   C [0,5586546.875] -> orig [0,14]
%   x8   K labels {k8_1,...,k8_68}, 68 levels, permuted embedding in [0,16]
%
% Usage:
%   PB = WFG8_mix()
%   F  = PB.func_F(xcell)       % recommended inside benchmark loops
%   F  = WFG8_mix(xcell)              % also valid; PB is memoized persistently
%   PD = WFG8_mix('ProblemData')
%

persistent PB_cached
if isempty(PB_cached)
lb_orig = [0; 0; 0; 0; 0; 0; 0; 0];
ub_orig = [2; 4; 6; 8; 10; 12; 14; 16];
lb_C_work = [0; 0; 0; 0; 0; 0; 0; 0];
ub_C_work = [298578.125; 4; 6; 5190.3125; 10; 12; 5586546.875; 16];
var_types = {'C', 'K', 'D', 'C', 'D', 'K', 'C', 'K'};
K2_labels = { ...
    'k2_1', 'k2_2', 'k2_3', 'k2_4', 'k2_5', 'k2_6', 'k2_7', 'k2_8', 'k2_9', 'k2_10', ...
    'k2_11', 'k2_12', 'k2_13', 'k2_14', 'k2_15', 'k2_16', 'k2_17', 'k2_18', 'k2_19', 'k2_20', ...
    'k2_21', 'k2_22', 'k2_23', 'k2_24', 'k2_25', 'k2_26', 'k2_27', 'k2_28', 'k2_29', 'k2_30', ...
    'k2_31'};
K2_embed  = [ ...
    3.389598472039828; 0.3600073971323594; 0.1216758184041442; 0.001140168346774234; 1.900130433811628; 0.03176237428917504; 0.006017844612725818; 1.699398722187002; ...
    1.5116142229639; 0.08404888974092058; 1.023402306210737; 4; 0.4436126996192938; 2.114052588333391; 0.537567526076357; 0.6422088197361375; ...
    1.336526648115468; 0; 0.1676428165579842; 1.173878077832529; 0.05426214910339855; 2.582408846596823; 0.01592428682213989; 0.2224083062042683; ...
    2.341401865867911; 2; 0.8848240905300371; 3.687433313759668; 0.2863973399898908; 2.837298412929469; 3.106290110265952; ...
];
D3_vals = [ ...
    0; 0.001562947226452005; 0.005442498353559632; 0.01129178427759813; 0.01895188002971826; 0.02831980912834679; 0.03932027665392549; 0.0518944347879317; ...
    0.06599427934156721; 0.08157946091452871; 0.09861530315648406; 0.1170714904450598; 0.1369211559601371; 0.1581402235138341; 0.1807069177462717; 0.2046013902759666; ...
    0.2298054282204924; 0.2563022227801863; 0.2840761826101484; 0.3131127812440791; 0.343398430849981; 0.3749203766549586; 0.4076666078114545; 0.4416257814986675; ...
    0.4767871577930153; 0.513140543386493; 0.5506762426389729; 0.589385014758778; 0.6292580361420926; 0.6702868670848057; 0.7124634222236516; 0.7557799441766963; ...
    0.8002289799434266; 0.8458033596971869; 0.8924961776613597; 0.940300774808531; 0.9892107231611094; 1.039219811504269; 1.090322032348997; 1.142511570005464; ...
    1.195782789645824; 1.250130227251396; 1.305548580352677; 1.362032699482089; 1.419577580269127; 1.478178356115996; 1.537830291399024; 1.598528775147415; ...
    1.66026931515627; 1.786859156380763; 1.851700019374668; 1.917566052892604; 1.984453282986619; 2.052357826386195; 2.121275886775424; 2.191203751288446; ...
    2.262137787206654; 2.334074438842687; 2.407010224597594; 2.480941734178737; 2.555865625967114; 2.631778624523745; 2.70867751822562; 2.786559157022532; ...
    2.865420450306806; 2.945258364888562; 3; 3.026069923069783; 3.107852200810937; 3.190602325984405; 3.274317476709395; 3.358994879763435; ...
    3.44463180906588; 3.531225584229198; 3.618773569174135; 3.707273170805101; 3.796721837742376; 3.887117059108; 3.978456363362383; 4.070737317188907; ...
    4.163957524423933; 4.258114625029845; 4.353206294108858; 4.44923024095552; 4.546184208145912; 4.644065970661731; 4.742873335047492; 4.842604138599262; ...
    4.943256248583351; 5.044827561483572; 5.147316002275675; 5.2507195237277; 5.355036105725053; 5.460263754619151; 5.566400502598583; 5.673444407081788; ...
    5.781393550130245; 5.890246037881338; 6; ...
];
D5_vals = [ ...
    0; 0.04168744415538648; 0.1451641119673897; 0.3011781962437861; 0.5054907977743708; 0.7553552938630932; 1.048763393570154; 1.384145488461686; ...
    1.760221194973943; 2.175914300587795; 3.122569423661957; 3.652006252147411; 4.217968223673568; 4.819874538656438; 5; 5.457195794515658; ...
    6.129446211241372; 6.836177458982517; 7.576973680243188; 8.351447420320891; 9.159236260076964; 10; ...
];
K6_labels = { ...
    'k6_1', 'k6_2', 'k6_3', 'k6_4', 'k6_5', 'k6_6', 'k6_7', 'k6_8', 'k6_9', 'k6_10', ...
    'k6_11', 'k6_12', 'k6_13', 'k6_14', 'k6_15', 'k6_16', 'k6_17', 'k6_18', 'k6_19', 'k6_20', ...
    'k6_21', 'k6_22', 'k6_23', 'k6_24', 'k6_25', 'k6_26', 'k6_27', 'k6_28', 'k6_29', 'k6_30', ...
    'k6_31', 'k6_32', 'k6_33', 'k6_34', 'k6_35', 'k6_36', 'k6_37', 'k6_38', 'k6_39', 'k6_40', ...
    'k6_41', 'k6_42', 'k6_43', 'k6_44', 'k6_45', 'k6_46', 'k6_47', 'k6_48', 'k6_49', 'k6_50', ...
    'k6_51', 'k6_52', 'k6_53', 'k6_54', 'k6_55', 'k6_56', 'k6_57', 'k6_58', 'k6_59', 'k6_60', ...
    'k6_61', 'k6_62', 'k6_63'};
K6_embed  = [ ...
    0; 4.986151667666141; 0.08807591426430779; 4.447566469328251; 4.191651527381288; 3.476364681501544; 0.3374026403767699; 0.8928273768559998; ...
    0.0166872652951201; 0.0441574709780132; 3.255121421296418; 1.356741820724434; 0.2824263652334963; 0.4648674624812373; 7.867725802998306; 0.9982874817753382; ...
    9.399233876403091; 5.86219130928596; 6.172712507690191; 0.1891401092833534; 11.09185521994494; 5.268992917712442; 10.65334567867396; 1.631977719350846; ...
    6.492622626978953; 8.23575233929164; 9.80710544614206; 2.101513588775673; 0.6167301830327316; 8.613630043554187; 12; 1.937297804142513; ...
    11.54071710190566; 0.7941694576363041; 6.822001072069405; 2.837857553061814; 0.003161645557195946; 7.160926261289241; 0.008366276287072091; 3.042317234527572; ...
    0.02850816092424094; 2.641646172971154; 9.001432850160183; 3.944538943601436; 0.398162370156751; 5.560978606446628; 10.22511911235601; 1.230121959476532; ...
    0.2330645291008517; 1.110677560442251; 4.712371146864415; 0.06392584645042754; 0.7021822281938646; 0.0005990198185594868; 0.5376734633215565; 6; ...
    1.490655292545732; 1.780821812371239; 2.453585176819657; 0.1504669754444905; 3.706140019623767; 7.509475658405702; 0.1168485194362127; ...
];
K8_labels = { ...
    'k8_1', 'k8_2', 'k8_3', 'k8_4', 'k8_5', 'k8_6', 'k8_7', 'k8_8', 'k8_9', 'k8_10', ...
    'k8_11', 'k8_12', 'k8_13', 'k8_14', 'k8_15', 'k8_16', 'k8_17', 'k8_18', 'k8_19', 'k8_20', ...
    'k8_21', 'k8_22', 'k8_23', 'k8_24', 'k8_25', 'k8_26', 'k8_27', 'k8_28', 'k8_29', 'k8_30', ...
    'k8_31', 'k8_32', 'k8_33', 'k8_34', 'k8_35', 'k8_36', 'k8_37', 'k8_38', 'k8_39', 'k8_40', ...
    'k8_41', 'k8_42', 'k8_43', 'k8_44', 'k8_45', 'k8_46', 'k8_47', 'k8_48', 'k8_49', 'k8_50', ...
    'k8_51', 'k8_52', 'k8_53', 'k8_54', 'k8_55', 'k8_56', 'k8_57', 'k8_58', 'k8_59', 'k8_60', ...
    'k8_61', 'k8_62', 'k8_63', 'k8_64', 'k8_65', 'k8_66', 'k8_67', 'k8_68'};
K8_embed  = [ ...
    7.186533028304645; 0.009260436701053384; 1.229383167712165; 0.7772291822159701; 0.8790477077257345; 4.922907916223693; 0.04887687793700633; 5.519055349824378; ...
    2.516567139181768; 13.28252099256581; 2.326116529922933; 12.27731665045162; 1.104981202774716; 7.926262782649183; 14.87758746380194; 3.141158543537917; ...
    0.09748918167959125; 0.03155502049463955; 0.4407166700047338; 0.3126111770889979; 0.5951382553095118; 9.53422682297534; 0.1665483966691108; 2.144349896031215; ...
    1.97115025890334; 8.708602761839726; 0; 0.2093547893410278; 1.649971684659835; 10.85525699705737; 11.31794660511288; 0.0006630411095816123; ...
    7.551114370922364; 16; 0.1293369093634774; 8.312064006327974; 6.488723260668968; 11.79194063483727; 0.003499551957042299; 4.366118443698288; ...
    13.80250060544776; 6.832431955372376; 14.33416481604525; 9.115962778017847; 0.01847074596591231; 0.07075803312044521; 1.501745976272022; 5.21601405691567; ...
    15.43284169907052; 2.715816384846283; 4.102240217670079; 6.15531792327806; 0.6826443002401011; 0.3734631378126316; 9.963476732952014; 0.5145509857639863; ...
    0.988249864652274; 3.367470211138102; 0.257973708367044; 8; 1.80639819305644; 3.847907238321552; 12.7741514312771; 4.639641617163543; ...
    3.603018217643361; 10.40379343977998; 5.832125753266341; 1.361593395846936; ...
];
ProblemData = { ...
    [0; 298578.125]; ... % x1 C
    K2_labels; ... % x2 K
    {D3_vals}; ... % x3 D
    [0; 5190.3125]; ... % x4 C
    {D5_vals}; ... % x5 D
    K6_labels; ... % x6 K
    [0; 5586546.875]; ... % x7 C
    K8_labels; ... % x8 K
};
x_anchor = {149289.0625, 'k2_26', 3, 2595.15625, 5, 'k6_56', 2793273.4375, 'k8_60'};
anchors_set = [ ...
    1 0 2; ...
    2 0 4; ...
    3 0 6; ...
    4 0 8; ...
    5 0 10; ...
    6 0 12; ...
    7 0 14; ...
    8 0 16];

PB = struct();
PB.name = 'WFG8_mix';
PB.problem = 'WFG8';
PB.source = 'MOModels_Matlab';
PB.type = 'MOO_MIXED';
PB.nvar = 8; PB.n = 8; PB.nobj = 3; PB.m = 3;
PB.var_types = var_types;
PB.type_counts = struct('C', 3, 'D', 2, 'K', 3);
PB.ProblemData = ProblemData;
PB.strategy = 'sobol_oscillatory'; PB.kappa = 1000000;
PB.lb_orig = lb_orig; PB.ub_orig = ub_orig;
PB.lb_C_work = lb_C_work; PB.ub_C_work = ub_C_work;
PB.x_anchor = x_anchor;
PB.anchors_set = anchors_set;
PB.K2_labels = K2_labels; PB.K2_embed = K2_embed;
PB.D3_vals = D3_vals;
PB.D5_vals = D5_vals;
PB.K6_labels = K6_labels; PB.K6_embed = K6_embed;
PB.K8_labels = K8_labels; PB.K8_embed = K8_embed;
PB.pareto_front_known = false;
PB.pareto_set_known = false;
PB.pf_type = 'unknown';
PB.ideal_point = [];
PB.nadir_point = [];
PB.core = @(xh) WFG8_orig(xh);
PB.decode = @(xr) decode(xr, PB);
PB.func_F = @(xr) objective(xr, PB);
PB_cached = PB;
else
    PB = PB_cached;
end

if nargin == 0
    varargout{1} = PB; return
end
arg1 = varargin{1};
if ischar(arg1) || (isstring(arg1) && isscalar(arg1))
    key = lower(char(arg1));
    switch key
        case {'problemdata','bounds','domain'}
            varargout{1} = PB.ProblemData; return
        case 'var_types'
            varargout{1} = PB.var_types; return
        case 'info'
            varargout{1} = PB; return
        otherwise
            error('Unknown string argument: %s', char(arg1));
    end
end
varargout{1} = PB.func_F(arg1);
end

function F = objective(xr, PB)
xh = decode(xr, PB);
F = PB.core(xh);
F = F(:);
end

function xh = decode(xr, PB)
if ~iscell(xr) || numel(xr) ~= 8
    error('WFG8_mix: input must be a cell array with exactly 8 entries.');
end
xh = zeros(8,1);
tmp = check_C(xr{1}, PB.lb_C_work(1), PB.ub_C_work(1), 'x1');
xh(1) = map_C_to_orig(tmp, PB.lb_C_work(1), PB.ub_C_work(1), PB.lb_orig(1), PB.ub_orig(1));
xh(2) = check_K(xr{2}, PB.K2_labels, PB.K2_embed, 'x2');
xh(3) = check_D(xr{3}, PB.D3_vals, 'x3');
tmp = check_C(xr{4}, PB.lb_C_work(4), PB.ub_C_work(4), 'x4');
xh(4) = map_C_to_orig(tmp, PB.lb_C_work(4), PB.ub_C_work(4), PB.lb_orig(4), PB.ub_orig(4));
xh(5) = check_D(xr{5}, PB.D5_vals, 'x5');
xh(6) = check_K(xr{6}, PB.K6_labels, PB.K6_embed, 'x6');
tmp = check_C(xr{7}, PB.lb_C_work(7), PB.ub_C_work(7), 'x7');
xh(7) = map_C_to_orig(tmp, PB.lb_C_work(7), PB.ub_C_work(7), PB.lb_orig(7), PB.ub_orig(7));
xh(8) = check_K(xr{8}, PB.K8_labels, PB.K8_embed, 'x8');
end

function v = check_C(val, a, b, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('WFG8_mix: %s must be a real scalar.', name);
end
if val < a || val > b
    error('WFG8_mix: %s=%g outside [%g,%g].', name, val, a, b);
end
v = double(val);
end

function xorig = map_C_to_orig(xwork, lbw, ubw, lbo, ubo)
if abs(ubw - lbw) <= 1e-14
    t = 0;
else
    t = (xwork - lbw) / (ubw - lbw);
end
t = max(0, min(1, t));
xorig = lbo + t * (ubo - lbo);
end

function v = check_D(val, grid, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('WFG8_mix: %s must be a real scalar.', name);
end
grid = grid(:);
[dmin, idx] = min(abs(grid - val));
if dmin > 1e-10 * max(1, max(abs(grid)))
    error('WFG8_mix: %s=%g not in grid.', name, val);
end
v = grid(idx);
end

function v = check_K(label, labels, embed, name)
if isstring(label), label = char(label); end
if ~(ischar(label) && isrow(label))
    error('WFG8_mix: %s must be a char vector or scalar string.', name);
end
idx = find(strcmp(label, labels), 1);
if isempty(idx)
    error('WFG8_mix: %s unknown label ''%s''.', name, label);
end
v = embed(idx);
end


% -------------------------------------------------------------------------
% Embedded original continuous MOO problem (top-level function renamed only)
% -------------------------------------------------------------------------
function f = WFG8_orig(z)
% WFG8 function
%
%   As described by Huband et al. in "A review of multiobjective test problems
%   and a scalable test problem toolkit", IEEE Transactions on Evolutionary 
%   Computing 10(5): 477-506, 2006.
%
%   Example WFG8.
%
%   This file is part of a collection of problems developed for
%   derivative-free multiobjective optimization in
%   A. L. Custódio, J. F. A. Madeira, A. I. F. Vaz, and L. N. Vicente,
%   Direct Multisearch for Multiobjective Optimization, 2010.
%
%   Written by the authors in June 1, 2010.
%   Adapted to MATLAB format in November 2025.
%
%   Input: z is a n-dimensional vector where n = k+l (k=4, l=4)
%
%   Problem characteristics:
%   n = 8 (k=4 position-related, l=4 distance-related); M = 3 objectives.
%   Variable z_i has bound [0, 2*i] (z_i in [0, zmax_i], zmax_i = 2*i).
%   Bounds: x1 in [0,2], x2 in [0,4], x3 in [0,6], x4 in [0,8], x5 in [0,10], x6 in [0,12], x7 in [0,14], x8 in [0,16]
%
%   Output: f is a M-dimensional vector (M=3) with the function values
%   Output: c is a vector of constraints (empty for this problem - bounds are
%          handled by the optimization algorithm)
% Parâmetros
M = 3;      % número de objetivos
k = 4;      % número de variáveis relacionadas à posição
l = 4;      % número de variáveis relacionadas à distância
n = k + l;  % número total de variáveis
pi = 4*atan(1);
pi2 = 2*atan(1);
% Parâmetros S
S = zeros(M, 1);
for m = 1:M
    S(m) = 2*m;
end
% Parâmetros A
A = ones(M-1, 1);  % neq WFG3
% Parâmetros zmax
zmax = zeros(n, 1);
for i = 1:n
    zmax(i) = 2*i;
end
% Transform z into [0,1] set
y = zeros(n, 1);
for i = 1:n
    y(i) = z(i)/zmax(i);
end
% First level mapping - Diferente do WFG7, função de inclinação dependente aplicada em l
w = ones(n, 1);  % default weight
AA = 0.98/49.98;
BB = 0.02;
CC = 50;
r_sum = zeros(n-k, 1);
% Cálculo de r_sum (soma ponderada das posições das variáveis anteriores)
for i = k+1:n
    sum_numerator = 0;
    sum_denominator = 0;
    for j = 1:i-1
        sum_numerator = sum_numerator + w(j)*y(j);
        sum_denominator = sum_denominator + w(j);
    end
    r_sum(i-k) = sum_numerator / sum_denominator;
end
% Cálculo de t1
t1 = zeros(n, 1);
for i = 1:n
    if i <= k
        t1(i) = y(i);
    else
        t1(i) = y(i)^(BB + (CC-BB)*(AA - (1-2*r_sum(i-k))*abs(floor(0.5-r_sum(i-k))+AA)));
    end
end
% Second level mapping - Similar ao WFG1/WFG2/WFG3/WFG7
t2 = zeros(n, 1);
for i = 1:n
    if i <= k
        t2(i) = t1(i);
    else
        t2(i) = abs(t1(i)-0.35)/abs(floor(0.35-t1(i))+0.35);
    end
end
% Third level mapping - Redução de dimensionalidade, como nos anteriores
t3 = zeros(M, 1);
for i = 1:M
    if i <= M-1
        numerator = 0;
        denominator = 0;
        for j = floor((i-1)*k/(M-1))+1 : floor(i*k/(M-1))
            numerator = numerator + w(j)*t2(j);
            denominator = denominator + w(j);
        end
        t3(i) = numerator / denominator;
    else
        numerator = 0;
        denominator = 0;
        for j = k+1 : n
            numerator = numerator + w(j)*t2(j);
            denominator = denominator + w(j);
        end
        t3(i) = numerator / denominator;
    end
end
% Define objective function variables - Idêntico ao WFG4-WFG7
x = zeros(M, 1);
for i = 1:M
    if i <= M-1
        x(i) = max(t3(M), A(i))*(t3(i)-0.5)+0.5;
    else
        x(i) = t3(M);
    end
end
% Define objective function function h - Idêntico ao WFG4-WFG7
h = zeros(M, 1);
% Compute h[1]
h(1) = 1.0;
for i = 1:M-1
    h(1) = h(1) * sin(x(i)*pi2);
end
% Compute h[m] for m = 2,...,M-1
for m = 2:M-1
    h(m) = 1.0;
    for i = 1:M-m
        h(m) = h(m) * sin(x(i)*pi2);
    end
    h(m) = h(m) * cos(x(M-m+1)*pi2);
end
% Compute h[M]
h(M) = cos(x(1)*pi2);
% The objective functions
f = zeros(M, 1);
for m = 1:M
    f(m) = x(M) + S(m)*h(m);
end
% Não há restrições de desigualdade para este problema
end

