function varargout = CAM1_mix(varargin)
%CAM1_MIX  Self-contained mixed-variable MOO adaptation of CAM1.
%
% Auto-generated by generate_selfcontained_wrappers_MOO_mix.m
% Source: CAM1, n=2, m=2, strategy=extreme, kappa=100000000
% Variable pattern: C,K
% D variables: nonuniform sorted finite sets with injected anchors.
% K variables: labels with permuted nonuniform numeric embeddings; labels carry no ordinal information.
%
%   x1   C [0.1,1] -> orig [0.1,1]
%   x2   K labels {k2_1,...,k2_119}, 119 levels, permuted embedding in [0,1]
%
% Usage:
%   PB = CAM1_mix()
%   F  = PB.func_F(xcell)       % recommended inside benchmark loops
%   F  = CAM1_mix(xcell)              % also valid; PB is memoized persistently
%   PD = CAM1_mix('ProblemData')
%

persistent PB_cached
if isempty(PB_cached)
lb_orig = [0.1; 0];
ub_orig = [1; 1];
lb_C_work = [0.1; 0];
ub_C_work = [1; 1];
var_types = {'C', 'K'};
K2_labels = { ...
    'k2_1', 'k2_2', 'k2_3', 'k2_4', 'k2_5', 'k2_6', 'k2_7', 'k2_8', 'k2_9', 'k2_10', ...
    'k2_11', 'k2_12', 'k2_13', 'k2_14', 'k2_15', 'k2_16', 'k2_17', 'k2_18', 'k2_19', 'k2_20', ...
    'k2_21', 'k2_22', 'k2_23', 'k2_24', 'k2_25', 'k2_26', 'k2_27', 'k2_28', 'k2_29', 'k2_30', ...
    'k2_31', 'k2_32', 'k2_33', 'k2_34', 'k2_35', 'k2_36', 'k2_37', 'k2_38', 'k2_39', 'k2_40', ...
    'k2_41', 'k2_42', 'k2_43', 'k2_44', 'k2_45', 'k2_46', 'k2_47', 'k2_48', 'k2_49', 'k2_50', ...
    'k2_51', 'k2_52', 'k2_53', 'k2_54', 'k2_55', 'k2_56', 'k2_57', 'k2_58', 'k2_59', 'k2_60', ...
    'k2_61', 'k2_62', 'k2_63', 'k2_64', 'k2_65', 'k2_66', 'k2_67', 'k2_68', 'k2_69', 'k2_70', ...
    'k2_71', 'k2_72', 'k2_73', 'k2_74', 'k2_75', 'k2_76', 'k2_77', 'k2_78', 'k2_79', 'k2_80', ...
    'k2_81', 'k2_82', 'k2_83', 'k2_84', 'k2_85', 'k2_86', 'k2_87', 'k2_88', 'k2_89', 'k2_90', ...
    'k2_91', 'k2_92', 'k2_93', 'k2_94', 'k2_95', 'k2_96', 'k2_97', 'k2_98', 'k2_99', 'k2_100', ...
    'k2_101', 'k2_102', 'k2_103', 'k2_104', 'k2_105', 'k2_106', 'k2_107', 'k2_108', 'k2_109', 'k2_110', ...
    'k2_111', 'k2_112', 'k2_113', 'k2_114', 'k2_115', 'k2_116', 'k2_117', 'k2_118', 'k2_119'};
K2_embed  = [ ...
    0.7556792552737903; 0.9400652505525491; 0.1600861046946819; 0.3055492161314705; 0.05410613214898881; 0.9013043078744057; 0.001566387292634739; 0.05046991616895338; ...
    0.8822800047893524; 0.01775405726878619; 0.2570766955919832; 0.06182545486076112; 0.1154681352299504; 0.624791834009325; 0.043635818878178; 0.5647318201340967; ...
    0.550267632920331; 0.2758804973389453; 0.8449395261978021; 1.065327609330518e-05; 0.03167104969213454; 0.3589722877864591; 0.005022815525697488; 0.6094444715124554; ...
    0.3263167071036271; 0.1464688492570214; 0.009562261005959204; 0.01096824631065168; 0.3478850805566908; 0.7385215912732508; 0.9797815354262602; 0.2663818145639151; ...
    0.026510579282043; 0.3370002434486604; 0.2052460399340199; 0.0007853191419311434; 0; 0.01248796936760881; 0.007081124076069962; 0.006000541837142797; ...
    0.7215933492362994; 0.002078094079827663; 0.1097786893715126; 0.3158333935729283; 5.622832832305574e-05; 0.1744145999128289; 0.003363764840634197; 0.08380722861957589; ...
    0.2479639967244509; 0.002675981966989865; 0.1671608024450119; 0.06591189748019759; 0.0937064760579135; 0.104256220903976; 0.2303112328112362; 0.5943193018302936; ...
    0.1818487696330577; 0.01412391749811495; 0.8266216535143753; 0.5360218879180122; 0.7906863636233407; 0.133552371768491; 0.6721762793846159; 0.07015170637932297; ...
    0.6884215860471384; 0.0002967748961272305; 0.008267441695862696; 0.4812041772840624; 0.02187712068401234; 0.213414162868748; 0.0404344227735137; 0.04698039221667254; ...
    0.6403623122570589; 0.0041449392810381; 0.7048936442040258; 0.9205657773570682; 0.1972632497021584; 0.4298041496393039; 0.00113689008382451; 0.01587850060150194; ...
    0.4945857457962707; 0.5; 0.02412899332491049; 0.5081819067431302; 0.4680362224279924; 0.5794153962399646; 0.03445389909154483; 0.1531892204171845; ...
    0.7730672211057694; 1; 0.05789075109684199; 0.127353590284823; 0.3702629260869359; 0.5219936322519489; 0.2217688279096785; 0.4423372045739316; ...
    0.0001487901541778456; 0.8634920263287841; 0.03737439694215487; 0.2390425639734322; 0.295463079084548; 0.3934586986858224; 0.09889929950215194; 0.0886762820076317; ...
    0.1399236763273109; 0.07454648347946552; 0.01975286014824052; 0.1213259706571161; 0.9598035603805494; 0.4053659143715078; 0.8085375527424298; 0.4550808956755873; ...
    0.4174807242227633; 0.2855738775676574; 0.381758048171415; 0.02902392989964243; 0.6561568235002581; 0.07909780623790014; 0.0005070037748812026; ...
];
ProblemData = { ...
    [0.1; 1]; ... % x1 C
    K2_labels; ... % x2 K
};
x_anchor = {0.5500000000000002, 'k2_82'};
anchors_set = [0.55 0.1 1; 0.5 0 1];

PB = struct();
PB.name = 'CAM1_mix';
PB.problem = 'CAM1';
PB.source = 'MOModels_Matlab';
PB.type = 'MOO_MIXED';
PB.nvar = 2; PB.n = 2; PB.nobj = 2; PB.m = 2;
PB.var_types = var_types;
PB.type_counts = struct('C', 1, 'D', 0, 'K', 1);
PB.ProblemData = ProblemData;
PB.strategy = 'extreme'; PB.kappa = 100000000;
PB.lb_orig = lb_orig; PB.ub_orig = ub_orig;
PB.lb_C_work = lb_C_work; PB.ub_C_work = ub_C_work;
PB.x_anchor = x_anchor;
PB.anchors_set = anchors_set;
PB.K2_labels = K2_labels; PB.K2_embed = K2_embed;
PB.pareto_front_known = false;
PB.pareto_set_known = false;
PB.pf_type = 'unknown';
PB.ideal_point = [];
PB.nadir_point = [];
PB.core = @(xh) CAM1_orig(xh);
PB.decode = @(xr) decode(xr, PB);
PB.func_F = @(xr) objective(xr, PB);
PB_cached = PB;
else
    PB = PB_cached;
end

if nargin == 0
    varargout{1} = PB; return
end
arg1 = varargin{1};
if ischar(arg1) || (isstring(arg1) && isscalar(arg1))
    key = lower(char(arg1));
    switch key
        case {'problemdata','bounds','domain'}
            varargout{1} = PB.ProblemData; return
        case 'var_types'
            varargout{1} = PB.var_types; return
        case 'info'
            varargout{1} = PB; return
        otherwise
            error('Unknown string argument: %s', char(arg1));
    end
end
varargout{1} = PB.func_F(arg1);
end

function F = objective(xr, PB)
xh = decode(xr, PB);
F = PB.core(xh);
F = F(:);
end

function xh = decode(xr, PB)
if ~iscell(xr) || numel(xr) ~= 2
    error('CAM1_mix: input must be a cell array with exactly 2 entries.');
end
xh = zeros(2,1);
tmp = check_C(xr{1}, PB.lb_C_work(1), PB.ub_C_work(1), 'x1');
xh(1) = map_C_to_orig(tmp, PB.lb_C_work(1), PB.ub_C_work(1), PB.lb_orig(1), PB.ub_orig(1));
xh(2) = check_K(xr{2}, PB.K2_labels, PB.K2_embed, 'x2');
end

function v = check_C(val, a, b, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('CAM1_mix: %s must be a real scalar.', name);
end
if val < a || val > b
    error('CAM1_mix: %s=%g outside [%g,%g].', name, val, a, b);
end
v = double(val);
end

function xorig = map_C_to_orig(xwork, lbw, ubw, lbo, ubo)
if abs(ubw - lbw) <= 1e-14
    t = 0;
else
    t = (xwork - lbw) / (ubw - lbw);
end
t = max(0, min(1, t));
xorig = lbo + t * (ubo - lbo);
end

function v = check_D(val, grid, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('CAM1_mix: %s must be a real scalar.', name);
end
grid = grid(:);
[dmin, idx] = min(abs(grid - val));
if dmin > 1e-10 * max(1, max(abs(grid)))
    error('CAM1_mix: %s=%g not in grid.', name, val);
end
v = grid(idx);
end

function v = check_K(label, labels, embed, name)
if isstring(label), label = char(label); end
if ~(ischar(label) && isrow(label))
    error('CAM1_mix: %s must be a char vector or scalar string.', name);
end
idx = find(strcmp(label, labels), 1);
if isempty(idx)
    error('CAM1_mix: %s unknown label ''%s''.', name, label);
end
v = embed(idx);
end


% -------------------------------------------------------------------------
% Embedded original continuous MOO problem (top-level function renamed only)
% -------------------------------------------------------------------------
function f = CAM1_orig(x)
%###############################################################################
%
%   As described by K. Deb in "Multi-objective Genetic Algorithms: Problem
%   Difficulties and Construction of Test Problems", Evolutionary Computation 
%   7(3): 205-230, 1999.
%
%   This file is part of a collection of problems developed for
%   derivative-free multiobjective optimization in
%   J. F. A. Madeira
%   Discrete Direct Multisearch for Multiobjective Optimization, 2021.
%
%   Written by the authors in February 24, 2021.
%
%   MATLAB version by J. F. A. Madeira
%   November 7, 2025
%
%###############################################################################
%
% Problem characteristics:
% - Number of variables: 2
% - Number of objectives: 2
%   Bounds: x1 in [0.1,1], x2 in [0,1]
%
%
M = 2; % Number of objectives (fixed)
% Check dimension
n = length(x);
if n ~= 2
    error('CAM1 requires exactly 2 variables, %d provided', n);
end
% Ensure x is a column vector
x = x(:);
% Initialize objectives
f = zeros(M, 1);
% g function
gx = 2 - exp(-((x(2)-0.2)/0.004)^2) - 1.9*exp(-((x(2)-0.6)/0.4)^2);
% Objective functions
f(1) = x(1);
f(2) = gx/x(1);
end

