function varargout = DTLZ1_5_mix(varargin)
%DTLZ1_5_MIX  Self-contained mixed-variable MOO adaptation of DTLZ1_5.
%
% Auto-generated by generate_selfcontained_wrappers_MOO_mix.m
% Source: DTLZ1_5, n=7, m=5, strategy=extreme, kappa=100000000
% Variable pattern: C,K,D,C,D,K,C
% D variables: nonuniform sorted finite sets with injected anchors.
% K variables: labels with permuted nonuniform numeric embeddings; labels carry no ordinal information.
%
%   x1   C [0,1] -> orig [0,1]
%   x2   K labels {k2_1,...,k2_71}, 71 levels, permuted embedding in [0,1]
%   x3   D sorted nonuniform grid [0,...,1], 46 values
%   x4   C [0,100000000] -> orig [0,1]
%   x5   D sorted nonuniform grid [0,...,1], 126 values
%   x6   K labels {k6_1,...,k6_44}, 44 levels, permuted embedding in [0,1]
%   x7   C [0,100000000] -> orig [0,1]
%
% Usage:
%   PB = DTLZ1_5_mix()
%   F  = PB.func_F(xcell)       % recommended inside benchmark loops
%   F  = DTLZ1_5_mix(xcell)              % also valid; PB is memoized persistently
%   PD = DTLZ1_5_mix('ProblemData')
%

persistent PB_cached
if isempty(PB_cached)
lb_orig = [0; 0; 0; 0; 0; 0; 0];
ub_orig = [1; 1; 1; 1; 1; 1; 1];
lb_C_work = [0; 0; 0; 0; 0; 0; 0];
ub_C_work = [1; 1; 1; 100000000; 1; 1; 100000000];
var_types = {'C', 'K', 'D', 'C', 'D', 'K', 'C'};
K2_labels = { ...
    'k2_1', 'k2_2', 'k2_3', 'k2_4', 'k2_5', 'k2_6', 'k2_7', 'k2_8', 'k2_9', 'k2_10', ...
    'k2_11', 'k2_12', 'k2_13', 'k2_14', 'k2_15', 'k2_16', 'k2_17', 'k2_18', 'k2_19', 'k2_20', ...
    'k2_21', 'k2_22', 'k2_23', 'k2_24', 'k2_25', 'k2_26', 'k2_27', 'k2_28', 'k2_29', 'k2_30', ...
    'k2_31', 'k2_32', 'k2_33', 'k2_34', 'k2_35', 'k2_36', 'k2_37', 'k2_38', 'k2_39', 'k2_40', ...
    'k2_41', 'k2_42', 'k2_43', 'k2_44', 'k2_45', 'k2_46', 'k2_47', 'k2_48', 'k2_49', 'k2_50', ...
    'k2_51', 'k2_52', 'k2_53', 'k2_54', 'k2_55', 'k2_56', 'k2_57', 'k2_58', 'k2_59', 'k2_60', ...
    'k2_61', 'k2_62', 'k2_63', 'k2_64', 'k2_65', 'k2_66', 'k2_67', 'k2_68', 'k2_69', 'k2_70', ...
    'k2_71'};
K2_embed  = [ ...
    0.1016337003470009; 0.0005210215844850676; 0.1308747048591663; 0.3650761820092453; 0.002749968409645898; 0.3463177386689404; 0.9327947529122463; 0.7473168228357525; ...
    0.8683006962557489; 0.4043371761221191; 0.2769784369341012; 0.1415900611005083; 0.5128930226551286; 0.2027172498756531; 0.610751240268841; 0.6634520370964685; ...
    0.03840773674424442; 0.467663124183514; 0.08449299890601486; 0.75; 0.2456516925736767; 0.07660756953804106; 0.4459567218456484; 0.8370603292200594; ...
    0.164512218753419; 1; 0; 0.05560207655106707; 0.6907608335269508; 3.730479896846038e-05; 0.0691690021387223; 0.5; ...
    0.7187143364868644; 0.1109031749048234; 0.3105195852047875; 0.25; 0.09283264809738133; 0.02479611978652466; 0.0001968959093947039; 0.4248496805467504; ...
    0.06216975242975416; 0.1767315575178832; 0.04945801632282962; 0.02895027292509972; 0.0334843686943801; 0.9660564883900643; 0.3844143249604619; 0.005485051034696387; ...
    0.001039222840180539; 0.2164954840665131; 0.01758849782927886; 0.04372938265213067; 0.9002108238386657; 0.2610409751564345; 0.2934695194581322; 0.1206479366565386; ...
    0.5605768498792567; 0.5853504664669779; 0.3281339205674119; 0.003981071705534973; 0.4899736541699637; 0.7765725275664881; 0.806485644880707; 0.5364258864359583; ...
    0.007276905358177676; 0.001775385687232841; 0.02101222243523014; 0.1528004565748137; 0.01177896546170356; 0.2308050653708056; 0.009370541835906819; ...
];
D3_vals = [ ...
    0; 0.001057346848562135; 0.003681895578460594; 0.007638986344833238; 0.01282110507930551; 0.01915858733228839; 0.0266004954620239; 0.03510701842793011; ...
    0.04464568099547286; 0.05518918645844859; 0.06671407597632657; 0.0791998407774501; 0.09262830523368362; 0.1069831816029002; 0.1222497386723279; 0.1384145488461686; ...
    0.1554652909573919; 0.1733905937126803; 0.192179909437029; 0.211823410854697; 0.2323119056838861; 0.2536367652142364; 0.2987635285494684; 0.3225504931933944; ...
    0.3471438620808935; 0.3725370760304653; 0.3987238835693844; 0.4256983154559961; 0.4534546621600019; 0.4819874538656438; 0.5; 0.5112914426392728; ...
    0.5413615864638133; 0.5721930348916671; 0.6037811161072931; 0.6361213252230462; 0.669209313658415; 0.7030408794747092; 0.7376119585554513; 0.7729186165379145; ...
    0.8089570414140125; 0.8457235367294851; 0.8832145153194411; 0.921426493526068; 0.9603560858509352; 1; ...
];
D5_vals = [ ...
    0; 0.0001680977794818411; 0.0005853504664669777; 0.00121445166626712; 0.002038308713233905; 0.003045846301945405; 0.00422896632865903; 0.005581339604868865; ...
    0.007097803193908699; 0.008774017445354238; 0.01060625285548796; 0.01259124892471117; 0.01472611607829784; 0.01700826487902779; 0.01943535334786223; 0.0220052467557475; ...
    0.02471598627448899; 0.02756576408751347; 0.03055290331769261; 0.03367584161750289; 0.03693311759122467; 0.04032335944013996; 0.04384527537603612; 0.0474976454581772; ...
    0.0512793145885052; 0.05518918645844859; 0.0592262182845093; 0.06338941620295654; 0.06767783121936272; 0.07209055562840257; 0.07662671983474477; 0.08128548951803888; ...
    0.08606606309470265; 0.09096766943701028; 0.09598956581629169; 0.1011310360421965; 0.1063913887741973; 0.1117699559849915; 0.1172660915583528; 0.122879170006402; ...
    0.1286085852932905; 0.1344537497540018; 0.1404140930984237; 0.1464890614920756; 0.1526781167059277; 0.158980735328652; 0.165396408035423; 0.1719246389080554; ...
    0.1785649448018494; 0.1853168547550201; 0.192179909437029; 0.1991536606325217; 0.2062376707579151; 0.2134315124079743; 0.2207347679299851; 0.2281470290233578; ...
    0.2356678963627049; 0.24329697924262; 0.2510338952425457; 0.2588782699102655; 0.2668297364626854; 0.274887935502684; 0.2913231287915738; 0.2996994388310926; ...
    0.3081811124690731; 0.3167678234804996; 0.3254592516086061; 0.3342550823676924; 0.3431550068552781; 0.3521587215730191; 0.3612659282558611; 0.3704763337089376; ...
    0.3797896496517587; 0.3892055925692693; 0.3987238835693844; 0.4083442482466356; 0.4180664165515918; 0.427890122665734; 0.4378151048814923; 0.4478411054871667; ...
    0.4579678706564755; 0.4681951503424894; 0.4785226981757251; 0.4889502713661887; 0.4994776306091678; 0.5; 0.510104539994588; 0.5208307669197598; ...
    0.531656082005347; 0.5425802590144079; 0.55360307477436; 0.5647243091017318; 0.5759437447295723; 0.5872611672373986; 0.5986763649835616; 0.6101891290399273; ...
    0.6217992531287654; 0.6335065335617526; 0.6453107691809952; 0.6572117613019863; 0.669209313658415; 0.6813032323487471; 0.6934933257845078; 0.7057794046401915; ...
    0.7181612818047345; 0.7306387723344867; 0.7432116934076229; 0.7558798642799351; 0.7686431062419512; 0.7815012425773307; 0.7944540985224853; 0.8075015012273787; ...
    0.8206432797174614; 0.8338792648566958; 0.8472092893116332; 0.8606331875165024; 0.8741507956392736; 0.8877619515486608; 0.901466494782031; 0.9152642665141866; ...
    0.9291551095269887; 0.9431388681797948; 0.9572153883806808; 0.9713845175584194; 0.9856461046351909; 1; ...
];
K6_labels = { ...
    'k6_1', 'k6_2', 'k6_3', 'k6_4', 'k6_5', 'k6_6', 'k6_7', 'k6_8', 'k6_9', 'k6_10', ...
    'k6_11', 'k6_12', 'k6_13', 'k6_14', 'k6_15', 'k6_16', 'k6_17', 'k6_18', 'k6_19', 'k6_20', ...
    'k6_21', 'k6_22', 'k6_23', 'k6_24', 'k6_25', 'k6_26', 'k6_27', 'k6_28', 'k6_29', 'k6_30', ...
    'k6_31', 'k6_32', 'k6_33', 'k6_34', 'k6_35', 'k6_36', 'k6_37', 'k6_38', 'k6_39', 'k6_40', ...
    'k6_41', 'k6_42', 'k6_43', 'k6_44'};
K6_embed  = [ ...
    0.03017697524530363; 0.5297965944561061; 0.0676679457154775; 0.49207993265237; 0.4559778765874937; 0.5691478603558253; 0.03793308384698292; 0.003346722363728435; ...
    0.2989590754353167; 0.005717467663310111; 0.6972039587252908; 0.4214700492172002; 0; 0.3571535587092933; 0.8406586495479124; 0.1592750302375037; ...
    0.1078333550919089; 0.008856022423939207; 0.6528324123000528; 0.2721019959185241; 0.2227524621131559; 0.001677902487669028; 0.8919837914617662; 0.6101533682290863; ...
    0.5; 0.1236886128097671; 0.9450918184905769; 0.02343460994055678; 0.0006340853162767534; 0.09323171324606479; 0.07985364198580791; 0.2002120168644218; ...
    0.743286660062327; 0.3273020614141733; 0.0001201367023077076; 0.3885356750588577; 1; 0.1408264880403315; 0.2467076899111482; 0.7910988687289068; ...
    0.0467423665854797; 0.01766410653640092; 0.01282067829283445; 0.05664215291824268; ...
];
ProblemData = { ...
    [0; 1]; ... % x1 C
    K2_labels; ... % x2 K
    {D3_vals}; ... % x3 D
    [0; 100000000]; ... % x4 C
    {D5_vals}; ... % x5 D
    K6_labels; ... % x6 K
    [0; 100000000]; ... % x7 C
};
x_anchor = {0.5, 'k2_32', 0.5, 50000000, 0.5, 'k6_25', 50000000};
anchors_set = [ ...
    0.5 0 1 0 0.25 0.75 1; ...
    0.5 0 1 0 0.25 0.75 1; ...
    0.5 0 1 0.5 0.5 0.5 0.5; ...
    0.5 0 1 0.5 0.5 0.5 0.5; ...
    0.5 0 1 0.5 0.5 0.5 0.5; ...
    0.5 0 1 0.5 0.5 0.5 0.5; ...
    0.5 0 1 0.5 0.5 0.5 0.5];

PB = struct();
PB.name = 'DTLZ1_5_mix';
PB.problem = 'DTLZ1_5';
PB.source = 'MOModels_Matlab';
PB.type = 'MOO_MIXED';
PB.nvar = 7; PB.n = 7; PB.nobj = 5; PB.m = 5;
PB.var_types = var_types;
PB.type_counts = struct('C', 3, 'D', 2, 'K', 2);
PB.ProblemData = ProblemData;
PB.strategy = 'extreme'; PB.kappa = 100000000;
PB.lb_orig = lb_orig; PB.ub_orig = ub_orig;
PB.lb_C_work = lb_C_work; PB.ub_C_work = ub_C_work;
PB.x_anchor = x_anchor;
PB.anchors_set = anchors_set;
PB.K2_labels = K2_labels; PB.K2_embed = K2_embed;
PB.D3_vals = D3_vals;
PB.D5_vals = D5_vals;
PB.K6_labels = K6_labels; PB.K6_embed = K6_embed;
PB.pareto_front_known = true;
PB.pareto_set_known = true;
PB.pf_type = 'simplex';
PB.ideal_point = [0;0;0;0;0];
PB.nadir_point = [0.5;0.5;0.5;0.5;0.5];
PB.core = @(xh) DTLZ1_5_orig(xh);
PB.decode = @(xr) decode(xr, PB);
PB.func_F = @(xr) objective(xr, PB);
PB_cached = PB;
else
    PB = PB_cached;
end

if nargin == 0
    varargout{1} = PB; return
end
arg1 = varargin{1};
if ischar(arg1) || (isstring(arg1) && isscalar(arg1))
    key = lower(char(arg1));
    switch key
        case {'problemdata','bounds','domain'}
            varargout{1} = PB.ProblemData; return
        case 'var_types'
            varargout{1} = PB.var_types; return
        case 'info'
            varargout{1} = PB; return
        otherwise
            error('Unknown string argument: %s', char(arg1));
    end
end
varargout{1} = PB.func_F(arg1);
end

function F = objective(xr, PB)
xh = decode(xr, PB);
F = PB.core(xh);
F = F(:);
end

function xh = decode(xr, PB)
if ~iscell(xr) || numel(xr) ~= 7
    error('DTLZ1_5_mix: input must be a cell array with exactly 7 entries.');
end
xh = zeros(7,1);
tmp = check_C(xr{1}, PB.lb_C_work(1), PB.ub_C_work(1), 'x1');
xh(1) = map_C_to_orig(tmp, PB.lb_C_work(1), PB.ub_C_work(1), PB.lb_orig(1), PB.ub_orig(1));
xh(2) = check_K(xr{2}, PB.K2_labels, PB.K2_embed, 'x2');
xh(3) = check_D(xr{3}, PB.D3_vals, 'x3');
tmp = check_C(xr{4}, PB.lb_C_work(4), PB.ub_C_work(4), 'x4');
xh(4) = map_C_to_orig(tmp, PB.lb_C_work(4), PB.ub_C_work(4), PB.lb_orig(4), PB.ub_orig(4));
xh(5) = check_D(xr{5}, PB.D5_vals, 'x5');
xh(6) = check_K(xr{6}, PB.K6_labels, PB.K6_embed, 'x6');
tmp = check_C(xr{7}, PB.lb_C_work(7), PB.ub_C_work(7), 'x7');
xh(7) = map_C_to_orig(tmp, PB.lb_C_work(7), PB.ub_C_work(7), PB.lb_orig(7), PB.ub_orig(7));
end

function v = check_C(val, a, b, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('DTLZ1_5_mix: %s must be a real scalar.', name);
end
if val < a || val > b
    error('DTLZ1_5_mix: %s=%g outside [%g,%g].', name, val, a, b);
end
v = double(val);
end

function xorig = map_C_to_orig(xwork, lbw, ubw, lbo, ubo)
if abs(ubw - lbw) <= 1e-14
    t = 0;
else
    t = (xwork - lbw) / (ubw - lbw);
end
t = max(0, min(1, t));
xorig = lbo + t * (ubo - lbo);
end

function v = check_D(val, grid, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('DTLZ1_5_mix: %s must be a real scalar.', name);
end
grid = grid(:);
[dmin, idx] = min(abs(grid - val));
if dmin > 1e-10 * max(1, max(abs(grid)))
    error('DTLZ1_5_mix: %s=%g not in grid.', name, val);
end
v = grid(idx);
end

function v = check_K(label, labels, embed, name)
if isstring(label), label = char(label); end
if ~(ischar(label) && isrow(label))
    error('DTLZ1_5_mix: %s must be a char vector or scalar string.', name);
end
idx = find(strcmp(label, labels), 1);
if isempty(idx)
    error('DTLZ1_5_mix: %s unknown label ''%s''.', name, label);
end
v = embed(idx);
end


% -------------------------------------------------------------------------
% Embedded original continuous MOO problem (top-level function renamed only)
% -------------------------------------------------------------------------
function f = DTLZ1_5_orig(x)
%###############################################################################
%
%   As described by K. Deb, L. Thiele, M. Laumanns and E. Zitzler in "Scalable
%   Multi-Objective Optimization Test Problems", Congress on Evolutionary 
%   Computation (CEC'2002): 825-830, 2002.
%
%   Example DTLZ1 with M = 5 objectives.
%
%   This file is part of a collection of problems developed for
%   derivative-free multiobjective optimization in
%   A. L. Custódio, J. F. A. Madeira, A. I. F. Vaz, and L. N. Vicente,
%   Direct Multisearch for Multiobjective Optimization, 2010.
%
%   Written by the authors in June 1, 2010.
%
%    MATLAB version by J. F. A. Madeira
%   November 16, 2025
%   DTLZ1 and DTLZ3 share the same multimodal g(x); they differ only in the objective functions (DTLZ1 linear simplex, DTLZ3 spherical).
%
%   This file is part of a collection of problems developed for
%   derivative-free multiobjective optimization.
%
%###############################################################################
%
% Problem characteristics:
% - Number of variables: n >= 5 (recommended n = 14, i.e., k = 10)
% - Number of objectives: M = 5 (fixed)
%   Bounds: x1 in [0,1], x2 in [0,1], x3 in [0,1], x4 in [0,1], x5 in [0,1], x6 in [0,1], x7 in [0,1]
%
% - Pareto front: Linear simplex with sum(fi) = 0.5, fi in [0, 0.5]
%
% Get dimension
n = length(x);
% Fixed parameters
M = 5;  % Number of objectives (fixed for DTLZ1_5)
k = n - M + 1;  % Calculate k from dimension
% Check minimum dimension
if n < M
    error('DTLZ1_5 requires n >= M, but n = %d and M = %d', n, M);
end
% Ensure x is a column vector
x = x(:);
% Initialize objectives
f = zeros(M, 1);
% Calculate g(x) - MULTIMODAL (canonical DTLZ1, matches AMPL .mod)
% NOTE: DTLZ1 and DTLZ3 share the SAME multimodal g(x) (with cosine term).
% They differ only in the objective functions: DTLZ1 uses linear products of
% x(j) with factor 0.5 (linear simplex front); DTLZ3 uses cos(0.5*pi*x(j))
% (spherical front).
sum_term = 0;
for i = M:n
    sum_term = sum_term + ((x(i)-0.5)^2 - cos(20*pi*(x(i)-0.5)));
end
gx = 100 * (k + sum_term);
% Alternative vectorized implementation:
% gx = 100 * (k + sum((x(M:n) - 0.5).^2));
% Calculate objectives
% f1
prod_term = 1;
for j = 1:(M-1)
    prod_term = prod_term * x(j);
end
f(1) = 0.5 * (1 + gx) * prod_term;
% f2 to fM
for i = 2:M
    prod_term = 1;
    for j = 1:(M-i)
        prod_term = prod_term * x(j);
    end
    f(i) = 0.5 * (1 + gx) * prod_term * (1 - x(M-i+1));
end
end

