function varargout = MLF2_mix(varargin)
%MLF2_MIX  Self-contained mixed-variable MOO adaptation of MLF2.
%
% Auto-generated by generate_selfcontained_wrappers_MOO_mix.m
% Source: MLF2, n=2, m=2, strategy=extreme, kappa=100000000
% Variable pattern: C,K
% D variables: nonuniform sorted finite sets with injected anchors.
% K variables: labels with permuted nonuniform numeric embeddings; labels carry no ordinal information.
%
%   x1   C [-2,2] -> orig [-2,2]
%   x2   K labels {k2_1,...,k2_93}, 93 levels, permuted embedding in [-2,2]
%
% Usage:
%   PB = MLF2_mix()
%   F  = PB.func_F(xcell)       % recommended inside benchmark loops
%   F  = MLF2_mix(xcell)              % also valid; PB is memoized persistently
%   PD = MLF2_mix('ProblemData')
%

persistent PB_cached
if isempty(PB_cached)
lb_orig = [-2; -2];
ub_orig = [2; 2];
lb_C_work = [-2; -2];
ub_C_work = [2; 2];
var_types = {'C', 'K'};
K2_labels = { ...
    'k2_1', 'k2_2', 'k2_3', 'k2_4', 'k2_5', 'k2_6', 'k2_7', 'k2_8', 'k2_9', 'k2_10', ...
    'k2_11', 'k2_12', 'k2_13', 'k2_14', 'k2_15', 'k2_16', 'k2_17', 'k2_18', 'k2_19', 'k2_20', ...
    'k2_21', 'k2_22', 'k2_23', 'k2_24', 'k2_25', 'k2_26', 'k2_27', 'k2_28', 'k2_29', 'k2_30', ...
    'k2_31', 'k2_32', 'k2_33', 'k2_34', 'k2_35', 'k2_36', 'k2_37', 'k2_38', 'k2_39', 'k2_40', ...
    'k2_41', 'k2_42', 'k2_43', 'k2_44', 'k2_45', 'k2_46', 'k2_47', 'k2_48', 'k2_49', 'k2_50', ...
    'k2_51', 'k2_52', 'k2_53', 'k2_54', 'k2_55', 'k2_56', 'k2_57', 'k2_58', 'k2_59', 'k2_60', ...
    'k2_61', 'k2_62', 'k2_63', 'k2_64', 'k2_65', 'k2_66', 'k2_67', 'k2_68', 'k2_69', 'k2_70', ...
    'k2_71', 'k2_72', 'k2_73', 'k2_74', 'k2_75', 'k2_76', 'k2_77', 'k2_78', 'k2_79', 'k2_80', ...
    'k2_81', 'k2_82', 'k2_83', 'k2_84', 'k2_85', 'k2_86', 'k2_87', 'k2_88', 'k2_89', 'k2_90', ...
    'k2_91', 'k2_92', 'k2_93'};
K2_embed  = [ ...
    1.896444972227676; -1.728318405763357; -1.118058461747235; -1.16064018072698; -1.682802939750624; -0.784876358742955; 0.07589078828485984; -0.5660559487734309; ...
    -1.52087389090726; -1.749548059669116; -0.325823878908166; 1.595237780361165; 0; 0.2958529608348264; 1.308069517085153; -1.633124587749391; ...
    -1.458107444307861; -1.930490107475803; -1.99891841609227; 0.6094377812582112; -1.550579018921054; -1.706074496448764; 1.694070858183338; 0.775071803844853; ...
    -0.9828682048063011; -1.920269733093753; -1.997842686879094; -1.991735729918978; -1.980547778521603; -1.856412705625371; -2; 0.5288427648228295; ...
    -1.984893939199738; 1.124328046396522; -1.824601761896441; -1.606692242741289; -0.3879202435896372; -1.789019537670357; 1.034746725022855; 0.1477772735168372; ...
    -1.074242549146905; 1.4022442493597; -1.88457616147813; 1.497964615728959; -1.42502301421496; -1.909222577375058; -0.6227460277226164; -0.1312606432789896; ...
    -0.6781067338599125; 0.4497188152620426; -0.8864384437500537; 0.372058159203938; -0.5080275294786534; 0.8601260560988755; -1.355395253491346; -1.281082196477503; ...
    -1.579181128356691; 1.215433204576466; 0.9466818698398547; -1.994291365910342; 1.794470915773631; 0.005427765211754032; -1.999922559311462; -1.658490600529474; ...
    -1.975548154102524; 2; -1.201997843929834; -1.939902395116453; -1.999591265595437; -0.197502583181361; 0.691511576807887; -1.769777120823532; ...
    -1.963488199376432; -0.9352900988946407; 0.2210953205434749; -0.73214712639236; -1.956380921005313; -1.897330559508596; -1.870942383621123; -1.988613633083801; ...
    -0.8363036812099063; -0.2623541733333867; -1.390789327914479; -0.06361996506901613; -1.318829816970314; -1.029182428486925; -1.948525963349945; -1.807289560962556; ...
    -1.840971052083089; -1.49005391425972; -1.969869648635952; -0.4486518915449529; -1.99631449320622; ...
];
ProblemData = { ...
    [-2; 2]; ... % x1 C
    K2_labels; ... % x2 K
};
x_anchor = {0, 'k2_13'};
anchors_set = [0 -2 2; 0 -2 2];

PB = struct();
PB.name = 'MLF2_mix';
PB.problem = 'MLF2';
PB.source = 'MOModels_Matlab';
PB.type = 'MOO_MIXED';
PB.nvar = 2; PB.n = 2; PB.nobj = 2; PB.m = 2;
PB.var_types = var_types;
PB.type_counts = struct('C', 1, 'D', 0, 'K', 1);
PB.ProblemData = ProblemData;
PB.strategy = 'extreme'; PB.kappa = 100000000;
PB.lb_orig = lb_orig; PB.ub_orig = ub_orig;
PB.lb_C_work = lb_C_work; PB.ub_C_work = ub_C_work;
PB.x_anchor = x_anchor;
PB.anchors_set = anchors_set;
PB.K2_labels = K2_labels; PB.K2_embed = K2_embed;
PB.pareto_front_known = false;
PB.pareto_set_known = false;
PB.pf_type = 'unknown';
PB.ideal_point = [];
PB.nadir_point = [];
PB.core = @(xh) MLF2_orig(xh);
PB.decode = @(xr) decode(xr, PB);
PB.func_F = @(xr) objective(xr, PB);
PB_cached = PB;
else
    PB = PB_cached;
end

if nargin == 0
    varargout{1} = PB; return
end
arg1 = varargin{1};
if ischar(arg1) || (isstring(arg1) && isscalar(arg1))
    key = lower(char(arg1));
    switch key
        case {'problemdata','bounds','domain'}
            varargout{1} = PB.ProblemData; return
        case 'var_types'
            varargout{1} = PB.var_types; return
        case 'info'
            varargout{1} = PB; return
        otherwise
            error('Unknown string argument: %s', char(arg1));
    end
end
varargout{1} = PB.func_F(arg1);
end

function F = objective(xr, PB)
xh = decode(xr, PB);
F = PB.core(xh);
F = F(:);
end

function xh = decode(xr, PB)
if ~iscell(xr) || numel(xr) ~= 2
    error('MLF2_mix: input must be a cell array with exactly 2 entries.');
end
xh = zeros(2,1);
tmp = check_C(xr{1}, PB.lb_C_work(1), PB.ub_C_work(1), 'x1');
xh(1) = map_C_to_orig(tmp, PB.lb_C_work(1), PB.ub_C_work(1), PB.lb_orig(1), PB.ub_orig(1));
xh(2) = check_K(xr{2}, PB.K2_labels, PB.K2_embed, 'x2');
end

function v = check_C(val, a, b, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('MLF2_mix: %s must be a real scalar.', name);
end
if val < a || val > b
    error('MLF2_mix: %s=%g outside [%g,%g].', name, val, a, b);
end
v = double(val);
end

function xorig = map_C_to_orig(xwork, lbw, ubw, lbo, ubo)
if abs(ubw - lbw) <= 1e-14
    t = 0;
else
    t = (xwork - lbw) / (ubw - lbw);
end
t = max(0, min(1, t));
xorig = lbo + t * (ubo - lbo);
end

function v = check_D(val, grid, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('MLF2_mix: %s must be a real scalar.', name);
end
grid = grid(:);
[dmin, idx] = min(abs(grid - val));
if dmin > 1e-10 * max(1, max(abs(grid)))
    error('MLF2_mix: %s=%g not in grid.', name, val);
end
v = grid(idx);
end

function v = check_K(label, labels, embed, name)
if isstring(label), label = char(label); end
if ~(ischar(label) && isrow(label))
    error('MLF2_mix: %s must be a char vector or scalar string.', name);
end
idx = find(strcmp(label, labels), 1);
if isempty(idx)
    error('MLF2_mix: %s unknown label ''%s''.', name, label);
end
v = embed(idx);
end


% -------------------------------------------------------------------------
% Embedded original continuous MOO problem (top-level function renamed only)
% -------------------------------------------------------------------------
function f = MLF2_orig(x)
% MLF2 function
%
%   As described by Huband et al. in "A review of multiobjective test problems
%   and a scalable test problem toolkit", IEEE Transactions on Evolutionary 
%   Computing 10(5): 477-506, 2006.
%
%   Example MLF2, see the previous cited paper for the original reference.
%
%   This file is part of a collection of problems developed for
%   derivative-free multiobjective optimization in
%   A. L. Custódio, J. F. A. Madeira, A. I. F. Vaz, and L. N. Vicente,
%   Direct Multisearch for Multiobjective Optimization, 2010.
%
%   Written by the authors in June 1, 2010.
%   Adapted to MATLAB format in November 2025.
%
% Problem characteristics:
% - Number of variables: 2
% - Number of objectives: 2
%   Bounds: x1 in [-2,2], x2 in [-2,2]
%
%
%   Input: x is a 2-dimensional vector
%   Output: f is a 2-dimensional vector with the function values
%   Output: c is a vector of constraints (empty for this problem - bounds are
%          handled by the optimization algorithm)
% Nota: Este problema é originalmente de maximização, 
% mas para manter a consistência com a interface da coleção DMS,
% convertemos para minimização multiplicando por -1.
% Cálculo da variável y
y = 2 * x;
% Função objetivo 1
f1 = -(5 - ((x(1)^2 + x(2) - 11)^2 + (x(1) + x(2)^2 - 7)^2) / 200);
% Função objetivo 2
f2 = -(5 - ((y(1)^2 + y(2) - 11)^2 + (y(1) + y(2)^2 - 7)^2) / 200);
% Vetor de funções objetivo
f = [f1; f2];
% Não há restrições de desigualdade para este problema
end

