function varargout = MOP2_mix(varargin)
%MOP2_MIX  Self-contained mixed-variable MOO adaptation of MOP2.
%
% Auto-generated by generate_selfcontained_wrappers_MOO_mix.m
% Source: MOP2, n=4, m=2, strategy=extreme, kappa=100000000
% Variable pattern: C,K,D,C
% D variables: nonuniform sorted finite sets with injected anchors.
% K variables: labels with permuted nonuniform numeric embeddings; labels carry no ordinal information.
%
%   x1   C [-4,4] -> orig [-4,4]
%   x2   K labels {k2_1,...,k2_55}, 55 levels, permuted embedding in [-4,4]
%   x3   D sorted nonuniform grid [-4,...,4], 21 values
%   x4   C [-400000000,400000000] -> orig [-4,4]
%
% Usage:
%   PB = MOP2_mix()
%   F  = PB.func_F(xcell)       % recommended inside benchmark loops
%   F  = MOP2_mix(xcell)              % also valid; PB is memoized persistently
%   PD = MOP2_mix('ProblemData')
%

persistent PB_cached
if isempty(PB_cached)
lb_orig = [-4; -4; -4; -4];
ub_orig = [4; 4; 4; 4];
lb_C_work = [-4; -4; -4; -400000000];
ub_C_work = [4; 4; 4; 400000000];
var_types = {'C', 'K', 'D', 'C'};
K2_labels = { ...
    'k2_1', 'k2_2', 'k2_3', 'k2_4', 'k2_5', 'k2_6', 'k2_7', 'k2_8', 'k2_9', 'k2_10', ...
    'k2_11', 'k2_12', 'k2_13', 'k2_14', 'k2_15', 'k2_16', 'k2_17', 'k2_18', 'k2_19', 'k2_20', ...
    'k2_21', 'k2_22', 'k2_23', 'k2_24', 'k2_25', 'k2_26', 'k2_27', 'k2_28', 'k2_29', 'k2_30', ...
    'k2_31', 'k2_32', 'k2_33', 'k2_34', 'k2_35', 'k2_36', 'k2_37', 'k2_38', 'k2_39', 'k2_40', ...
    'k2_41', 'k2_42', 'k2_43', 'k2_44', 'k2_45', 'k2_46', 'k2_47', 'k2_48', 'k2_49', 'k2_50', ...
    'k2_51', 'k2_52', 'k2_53', 'k2_54', 'k2_55'};
K2_embed  = [ ...
    -2.048197028988221; -3.170777131275447; 4; -4; -3.68663372940726; -3.500630084549394; -3.891475701793203; -2.200714175699017; ...
    0.1307243954889721; -1.364309784643737; -0.1069593133798317; -3.999443654008328; -3.973522744041626; -3.783538853726127; -3.860252205229465; 0.893632896764931; ...
    2.030091930254245; -1.174415693133494; -2.968446469303936; -3.992229732417326; -3.262406717148849; 1.444572176556662; 2.336005644611584; -2.739911685211305; ...
    -1.546543179018495; -3.347840829342954; -0.5578832609397502; -2.857511220466622; 2.97450493734659; 3.649042085762368; -1.888393313137961; 2.650785998544674; ...
    0.6309410944784304; -3.072829943494141; -2.346042907933919; -3.984501525874; -0.3364677390079076; -3.918198563143336; -3.630202487784154; -3.997063588251449; ...
    -3.737693526371179; -3.568249427820169; -3.940628194034625; -0.7712895363060062; -3.958988281823357; 0.3766645403033628; 0; 3.307233547961292; ...
    1.732972023621468; -0.9767715540722; -3.824334123172711; -2.615538131999315; 1.164817693193647; -3.427205320020219; -1.721206818111961; ...
];
D3_vals = [ ...
    -4; -3.963588715939478; -3.873208544603111; -3.736940340708053; -3.558486508332411; -3.340246044613553; -3.083973061691638; -2.791038510933614; ...
    -2.462560724503768; -2.099479704374818; -1.27263773092302; -0.810208931444925; -0.3158777837765925; 0; 0.2098484212402543; 0.7665072847196548; ...
    1.35367450926732; 1.970958507778528; 2.617996055648875; 3.294448736275498; 4; ...
];
ProblemData = { ...
    [-4; 4]; ... % x1 C
    K2_labels; ... % x2 K
    {D3_vals}; ... % x3 D
    [-400000000; 400000000]; ... % x4 C
};
x_anchor = {0, 'k2_47', 0, 0};
anchors_set = [0 -4 4; 0 -4 4; 0 -4 4; 0 -4 4];

PB = struct();
PB.name = 'MOP2_mix';
PB.problem = 'MOP2';
PB.source = 'MOModels_Matlab';
PB.type = 'MOO_MIXED';
PB.nvar = 4; PB.n = 4; PB.nobj = 2; PB.m = 2;
PB.var_types = var_types;
PB.type_counts = struct('C', 2, 'D', 1, 'K', 1);
PB.ProblemData = ProblemData;
PB.strategy = 'extreme'; PB.kappa = 100000000;
PB.lb_orig = lb_orig; PB.ub_orig = ub_orig;
PB.lb_C_work = lb_C_work; PB.ub_C_work = ub_C_work;
PB.x_anchor = x_anchor;
PB.anchors_set = anchors_set;
PB.K2_labels = K2_labels; PB.K2_embed = K2_embed;
PB.D3_vals = D3_vals;
PB.pareto_front_known = true;
PB.pareto_set_known = true;
PB.pf_type = 'concave';
PB.ideal_point = [0;0];
PB.nadir_point = [1;1];
PB.core = @(xh) MOP2_orig(xh);
PB.decode = @(xr) decode(xr, PB);
PB.func_F = @(xr) objective(xr, PB);
PB_cached = PB;
else
    PB = PB_cached;
end

if nargin == 0
    varargout{1} = PB; return
end
arg1 = varargin{1};
if ischar(arg1) || (isstring(arg1) && isscalar(arg1))
    key = lower(char(arg1));
    switch key
        case {'problemdata','bounds','domain'}
            varargout{1} = PB.ProblemData; return
        case 'var_types'
            varargout{1} = PB.var_types; return
        case 'info'
            varargout{1} = PB; return
        otherwise
            error('Unknown string argument: %s', char(arg1));
    end
end
varargout{1} = PB.func_F(arg1);
end

function F = objective(xr, PB)
xh = decode(xr, PB);
F = PB.core(xh);
F = F(:);
end

function xh = decode(xr, PB)
if ~iscell(xr) || numel(xr) ~= 4
    error('MOP2_mix: input must be a cell array with exactly 4 entries.');
end
xh = zeros(4,1);
tmp = check_C(xr{1}, PB.lb_C_work(1), PB.ub_C_work(1), 'x1');
xh(1) = map_C_to_orig(tmp, PB.lb_C_work(1), PB.ub_C_work(1), PB.lb_orig(1), PB.ub_orig(1));
xh(2) = check_K(xr{2}, PB.K2_labels, PB.K2_embed, 'x2');
xh(3) = check_D(xr{3}, PB.D3_vals, 'x3');
tmp = check_C(xr{4}, PB.lb_C_work(4), PB.ub_C_work(4), 'x4');
xh(4) = map_C_to_orig(tmp, PB.lb_C_work(4), PB.ub_C_work(4), PB.lb_orig(4), PB.ub_orig(4));
end

function v = check_C(val, a, b, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('MOP2_mix: %s must be a real scalar.', name);
end
if val < a || val > b
    error('MOP2_mix: %s=%g outside [%g,%g].', name, val, a, b);
end
v = double(val);
end

function xorig = map_C_to_orig(xwork, lbw, ubw, lbo, ubo)
if abs(ubw - lbw) <= 1e-14
    t = 0;
else
    t = (xwork - lbw) / (ubw - lbw);
end
t = max(0, min(1, t));
xorig = lbo + t * (ubo - lbo);
end

function v = check_D(val, grid, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('MOP2_mix: %s must be a real scalar.', name);
end
grid = grid(:);
[dmin, idx] = min(abs(grid - val));
if dmin > 1e-10 * max(1, max(abs(grid)))
    error('MOP2_mix: %s=%g not in grid.', name, val);
end
v = grid(idx);
end

function v = check_K(label, labels, embed, name)
if isstring(label), label = char(label); end
if ~(ischar(label) && isrow(label))
    error('MOP2_mix: %s must be a char vector or scalar string.', name);
end
idx = find(strcmp(label, labels), 1);
if isempty(idx)
    error('MOP2_mix: %s unknown label ''%s''.', name, label);
end
v = embed(idx);
end


% -------------------------------------------------------------------------
% Embedded original continuous MOO problem (top-level function renamed only)
% -------------------------------------------------------------------------
function f = MOP2_orig(x)
% MOP2 function
%
%   As described by Huband et al. in "A review of multiobjective test problems
%   and a scalable test problem toolkit", IEEE Transactions on Evolutionary 
%   Computing 10(5): 477-506, 2006.
%
%   Example MOP2, Van Valedhuizen's test suit.
%
%   This file is part of a collection of problems developed for
%   derivative-free multiobjective optimization in
%   A. L. Custódio, J. F. A. Madeira, A. I. F. Vaz, and L. N. Vicente,
%   Direct Multisearch for Multiobjective Optimization, 2010.
%
%   Written by the authors in June 1, 2010.
%   Adapted to MATLAB format in November 2025.
%
% Problem characteristics:
% - Number of variables: 4
% - Number of objectives: 2
%   Bounds: x1 in [-4,4], x2 in [-4,4], x3 in [-4,4], x4 in [-4,4]
%
%
%   Input: x is a 4-dimensional vector
%   Output: f is a 2-dimensional vector with the function values
%   Output: c is a vector of constraints (empty for this problem - bounds are
%          handled by the optimization algorithm)
% Número de variáveis
n = 4;
% Função objetivo 1
sum1 = 0;
for i = 1:n
    sum1 = sum1 + (x(i) - 1/sqrt(n))^2;
end
f1 = 1 - exp(-sum1);
% Função objetivo 2
sum2 = 0;
for i = 1:n
    sum2 = sum2 + (x(i) + 1/sqrt(n))^2;
end
f2 = 1 - exp(-sum2);
% Vetor de funções objetivo
f = [f1; f2];
% Não há restrições de desigualdade para este problema
end

