function varargout = SSFYY1_mix(varargin)
%SSFYY1_MIX  Self-contained mixed-variable MOO adaptation of SSFYY1.
%
% Auto-generated by generate_selfcontained_wrappers_MOO_mix.m
% Source: SSFYY1, n=2, m=2, strategy=extreme, kappa=100000000
% Variable pattern: C,K
% D variables: nonuniform sorted finite sets with injected anchors.
% K variables: labels with permuted nonuniform numeric embeddings; labels carry no ordinal information.
%
%   x1   C [-100,100] -> orig [-100,100]
%   x2   K labels {k2_1,...,k2_88}, 88 levels, permuted embedding in [-100,100]
%
% Usage:
%   PB = SSFYY1_mix()
%   F  = PB.func_F(xcell)       % recommended inside benchmark loops
%   F  = SSFYY1_mix(xcell)              % also valid; PB is memoized persistently
%   PD = SSFYY1_mix('ProblemData')
%

persistent PB_cached
if isempty(PB_cached)
lb_orig = [-100; -100];
ub_orig = [100; 100];
lb_C_work = [-100; -100];
ub_C_work = [100; 100];
var_types = {'C', 'K'};
K2_labels = { ...
    'k2_1', 'k2_2', 'k2_3', 'k2_4', 'k2_5', 'k2_6', 'k2_7', 'k2_8', 'k2_9', 'k2_10', ...
    'k2_11', 'k2_12', 'k2_13', 'k2_14', 'k2_15', 'k2_16', 'k2_17', 'k2_18', 'k2_19', 'k2_20', ...
    'k2_21', 'k2_22', 'k2_23', 'k2_24', 'k2_25', 'k2_26', 'k2_27', 'k2_28', 'k2_29', 'k2_30', ...
    'k2_31', 'k2_32', 'k2_33', 'k2_34', 'k2_35', 'k2_36', 'k2_37', 'k2_38', 'k2_39', 'k2_40', ...
    'k2_41', 'k2_42', 'k2_43', 'k2_44', 'k2_45', 'k2_46', 'k2_47', 'k2_48', 'k2_49', 'k2_50', ...
    'k2_51', 'k2_52', 'k2_53', 'k2_54', 'k2_55', 'k2_56', 'k2_57', 'k2_58', 'k2_59', 'k2_60', ...
    'k2_61', 'k2_62', 'k2_63', 'k2_64', 'k2_65', 'k2_66', 'k2_67', 'k2_68', 'k2_69', 'k2_70', ...
    'k2_71', 'k2_72', 'k2_73', 'k2_74', 'k2_75', 'k2_76', 'k2_77', 'k2_78', 'k2_79', 'k2_80', ...
    'k2_81', 'k2_82', 'k2_83', 'k2_84', 'k2_85', 'k2_86', 'k2_87', 'k2_88'};
K2_embed  = [ ...
    -99.93815924249967; -99.34897186409499; -81.86390686612054; -14.69482202235331; -30.52396037437796; -79.0234920844587; -85.68013300050546; -70.84326791373162; ...
    18.69135433505545; -92.62098788543737; 78.63691544206347; 58.66780306275575; -61.05334056458237; -41.84436339807092; 26.99358424359642; -52.00867295805385; ...
    -11.29995418025385; -58.89507856712966; 10.71467253978793; -36.33088503853345; 6.847241868487203; -86.83675197048898; -72.60543420374808; -24.41928885180499; ...
    -49.57401602709054; 22.80154372397793; -80.4738219514918; -98.88779769864293; -96.02569493060969; 3.059785608666417; -67.12505419868479; -99.97663015785091; ...
    -39.1240325120625; -96.56385289815043; 73.51500420426225; -93.40051423031242; -87.93695845973126; -99.99557224288723; -75.93921506518089; 100; ...
    -94.80970034878273; 63.53087411107725; -97.50603086157309; 44.58938512137186; -91.7902374581507; -94.12976105991807; -21.25397918066874; -27.50910813067642; ...
    -83.19448388759741; 89.14253747508349; -99.78927706831526; -77.51219349160009; -74.30385778872215; 94.52708206716309; -84.46630403206488; 35.62505169650564; ...
    -95.44133370888136; -88.98156727081221; -44.49243041809551; -33.46437447895197; -98.60193863668457; -65.16770527945638; -7.827554963736375; -47.06879270931841; ...
    -97.05691496028312; 49.19749442430631; 14.66255297118448; -69.01669312173922; -0.6481758647237967; -4.27712655732833; -54.37334314464666; -89.97141152801474; ...
    -18.01266114707441; -99.67360252508051; -90.90734381921297; -98.27726379914974; 31.26793510210402; -99.87665323364305; 40.06538569582031; -100; ...
    -56.66861352185148; 0; -99.52748120756509; -99.13629424766987; 53.89015456046795; -97.9123973719237; 83.8459537365209; 68.47979860000842; ...
];
ProblemData = { ...
    [-100; 100]; ... % x1 C
    K2_labels; ... % x2 K
};
x_anchor = {0, 'k2_82'};
anchors_set = [0 -100 100; 0 -100 100];

PB = struct();
PB.name = 'SSFYY1_mix';
PB.problem = 'SSFYY1';
PB.source = 'MOModels_Matlab';
PB.type = 'MOO_MIXED';
PB.nvar = 2; PB.n = 2; PB.nobj = 2; PB.m = 2;
PB.var_types = var_types;
PB.type_counts = struct('C', 1, 'D', 0, 'K', 1);
PB.ProblemData = ProblemData;
PB.strategy = 'extreme'; PB.kappa = 100000000;
PB.lb_orig = lb_orig; PB.ub_orig = ub_orig;
PB.lb_C_work = lb_C_work; PB.ub_C_work = ub_C_work;
PB.x_anchor = x_anchor;
PB.anchors_set = anchors_set;
PB.K2_labels = K2_labels; PB.K2_embed = K2_embed;
PB.pareto_front_known = false;
PB.pareto_set_known = false;
PB.pf_type = 'unknown';
PB.ideal_point = [];
PB.nadir_point = [];
PB.core = @(xh) SSFYY1_orig(xh);
PB.decode = @(xr) decode(xr, PB);
PB.func_F = @(xr) objective(xr, PB);
PB_cached = PB;
else
    PB = PB_cached;
end

if nargin == 0
    varargout{1} = PB; return
end
arg1 = varargin{1};
if ischar(arg1) || (isstring(arg1) && isscalar(arg1))
    key = lower(char(arg1));
    switch key
        case {'problemdata','bounds','domain'}
            varargout{1} = PB.ProblemData; return
        case 'var_types'
            varargout{1} = PB.var_types; return
        case 'info'
            varargout{1} = PB; return
        otherwise
            error('Unknown string argument: %s', char(arg1));
    end
end
varargout{1} = PB.func_F(arg1);
end

function F = objective(xr, PB)
xh = decode(xr, PB);
F = PB.core(xh);
F = F(:);
end

function xh = decode(xr, PB)
if ~iscell(xr) || numel(xr) ~= 2
    error('SSFYY1_mix: input must be a cell array with exactly 2 entries.');
end
xh = zeros(2,1);
tmp = check_C(xr{1}, PB.lb_C_work(1), PB.ub_C_work(1), 'x1');
xh(1) = map_C_to_orig(tmp, PB.lb_C_work(1), PB.ub_C_work(1), PB.lb_orig(1), PB.ub_orig(1));
xh(2) = check_K(xr{2}, PB.K2_labels, PB.K2_embed, 'x2');
end

function v = check_C(val, a, b, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('SSFYY1_mix: %s must be a real scalar.', name);
end
if val < a || val > b
    error('SSFYY1_mix: %s=%g outside [%g,%g].', name, val, a, b);
end
v = double(val);
end

function xorig = map_C_to_orig(xwork, lbw, ubw, lbo, ubo)
if abs(ubw - lbw) <= 1e-14
    t = 0;
else
    t = (xwork - lbw) / (ubw - lbw);
end
t = max(0, min(1, t));
xorig = lbo + t * (ubo - lbo);
end

function v = check_D(val, grid, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('SSFYY1_mix: %s must be a real scalar.', name);
end
grid = grid(:);
[dmin, idx] = min(abs(grid - val));
if dmin > 1e-10 * max(1, max(abs(grid)))
    error('SSFYY1_mix: %s=%g not in grid.', name, val);
end
v = grid(idx);
end

function v = check_K(label, labels, embed, name)
if isstring(label), label = char(label); end
if ~(ischar(label) && isrow(label))
    error('SSFYY1_mix: %s must be a char vector or scalar string.', name);
end
idx = find(strcmp(label, labels), 1);
if isempty(idx)
    error('SSFYY1_mix: %s unknown label ''%s''.', name, label);
end
v = embed(idx);
end


% -------------------------------------------------------------------------
% Embedded original continuous MOO problem (top-level function renamed only)
% -------------------------------------------------------------------------
function f = SSFYY1_orig(x)
% SSFYY1 function
%
%   As described by Huband et al. in "A review of multiobjective test problems
%   and a scalable test problem toolkit", IEEE Transactions on Evolutionary 
%   Computing 10(5): 477-506, 2006.
%
%   Example SSFYY1, see the previous cited paper for the original reference.
%
%   This file is part of a collection of problems developed for
%   derivative-free multiobjective optimization in
%   A. L. Custódio, J. F. A. Madeira, A. I. F. Vaz, and L. N. Vicente,
%   Direct Multisearch for Multiobjective Optimization, 2010.
%
%   Written by the authors in June 1, 2010.
%   Adapted to MATLAB format in November 2025.
%
% Problem characteristics:
% - Number of variables: 2
% - Number of objectives: 2
%   Bounds: x1 in [-100,100], x2 in [-100,100]
%
%
%   Input: x is a 2-dimensional vector
%   Output: f is a 2-dimensional vector with the function values
%   Output: c is a vector of constraints (empty for this problem - bounds are
%          handled by the optimization algorithm)
% Função objetivo 1
f1 = x(1)^2 + x(2)^2;
% Função objetivo 2
f2 = (x(1)-1)^2 + (x(2)-2)^2;
% Vetor de funções objetivo
f = [f1; f2];
% Não há restrições de desigualdade para este problema
end

