function varargout = WFG2_mix(varargin)
%WFG2_MIX  Self-contained mixed-variable MOO adaptation of WFG2.
%
% Auto-generated by generate_selfcontained_wrappers_MOO_mix.m
% Source: WFG2, n=8, m=3, strategy=extreme, kappa=100000000
% Variable pattern: C,K,D,C,D,K,C,K
% D variables: nonuniform sorted finite sets with injected anchors.
% K variables: labels with permuted nonuniform numeric embeddings; labels carry no ordinal information.
%
%   x1   C [0,2] -> orig [0,2]
%   x2   K labels {k2_1,...,k2_46}, 46 levels, permuted embedding in [0,4]
%   x3   D sorted nonuniform grid [0,...,6], 38 values
%   x4   C [0,800000000] -> orig [0,8]
%   x5   D sorted nonuniform grid [0,...,10], 95 values
%   x6   K labels {k6_1,...,k6_42}, 42 levels, permuted embedding in [0,12]
%   x7   C [0,1400000000] -> orig [0,14]
%   x8   K labels {k8_1,...,k8_129}, 129 levels, permuted embedding in [0,16]
%
% Usage:
%   PB = WFG2_mix()
%   F  = PB.func_F(xcell)       % recommended inside benchmark loops
%   F  = WFG2_mix(xcell)              % also valid; PB is memoized persistently
%   PD = WFG2_mix('ProblemData')
%

persistent PB_cached
if isempty(PB_cached)
lb_orig = [0; 0; 0; 0; 0; 0; 0; 0];
ub_orig = [2; 4; 6; 8; 10; 12; 14; 16];
lb_C_work = [0; 0; 0; 0; 0; 0; 0; 0];
ub_C_work = [2; 4; 6; 800000000; 10; 12; 1400000000; 16];
var_types = {'C', 'K', 'D', 'C', 'D', 'K', 'C', 'K'};
K2_labels = { ...
    'k2_1', 'k2_2', 'k2_3', 'k2_4', 'k2_5', 'k2_6', 'k2_7', 'k2_8', 'k2_9', 'k2_10', ...
    'k2_11', 'k2_12', 'k2_13', 'k2_14', 'k2_15', 'k2_16', 'k2_17', 'k2_18', 'k2_19', 'k2_20', ...
    'k2_21', 'k2_22', 'k2_23', 'k2_24', 'k2_25', 'k2_26', 'k2_27', 'k2_28', 'k2_29', 'k2_30', ...
    'k2_31', 'k2_32', 'k2_33', 'k2_34', 'k2_35', 'k2_36', 'k2_37', 'k2_38', 'k2_39', 'k2_40', ...
    'k2_41', 'k2_42', 'k2_43', 'k2_44', 'k2_45', 'k2_46'};
K2_embed  = [ ...
    0.1082305731369367; 1.072225158944271; 1.635377519438704; 0.002274164877045758; 0.006017844612725818; 0.3343781700165755; 0.7989079901546001; 0.2863973399898908; ...
    0.6422088197361375; 3.389598472039828; 0.01200311418265497; 2.041264859226033; 0.9759014855058897; 2.188332270151681; 2.837298412929469; 0.1676428165579842; ...
    0; 1.900130433811628; 2.665818577562864; 3.78997531952689; 2.50054166903036; 0.1360480754693719; 1.173878077832529; 4; ...
    1.76485856210654; 1.5116142229639; 0.3867473704705517; 0.02050585908832128; 3.58652821421459; 0.08404888974092058; 0.4436126996192938; 0.2031486795551346; ...
    2.341401865867911; 0.0004308736723892923; 0.06335281647169425; 2; 1.280941315118027; 0.2426929965065013; 0.8848240905300371; 0.03176237428917504; ...
    3.199125034699727; 0.04598172442261927; 0.5050781726654022; 0.571244389766689; 3.015045965127122; 1.393494160827505; ...
];
D3_vals = [ ...
    0; 0.009023772694573485; 0.03142260160926853; 0.06519381647230121; 0.1094198541247137; 0.1635061734669236; 0.2270180546135439; 0.2996157360365247; ...
    0.3810220625761969; 0.4710040744687644; 0.5693615656560966; 0.6759195070132407; 0.7905227812888433; 0.9130323831197538; 1.043322591115918; 1.181278809416497; ...
    1.326795884815837; 1.479776770667156; 1.807776051483364; 1.982632126804312; 2.164626034865108; 2.353688430292861; 2.549753824608566; 2.752760210197686; ...
    2.962648735364596; 3; 3.179363421730017; 3.402850917010391; 3.633060277582136; 3.869942776290415; 4.113451731789226; 4.363542356353112; ...
    4.620171619621626; 4.883298126156126; 5.152882005027248; 5.42888480992744; 5.711269428529627; 6; ...
];
D5_vals = [ ...
    0; 0.002807823881379661; 0.009777410646285494; 0.02028561234917743; 0.03404692138280543; 0.05087634121031381; 0.07063860502953292; 0.09322799314153843; ...
    0.1185582663532005; 0.1465569372459719; 0.177161709996338; 0.2103181227983988; 0.2459779095956492; 0.2840978176830949; 0.3246387277773339; 0.3675649823983234; ...
    0.4128438622287625; 0.4604451703763245; 0.5103408970977421; 0.5625049456967881; 0.6169129057272666; 0.6735418633278958; 0.7323702410941181; 0.7933776617268227; ...
    0.8565448310275823; 0.9218534367890732; 0.9892860608608716; 1.058826102224648; 1.130457709337181; 1.204165720328412; 1.279935609899161; 1.357753441966442; ...
    1.437605827266387; 1.519479885255; 1.603363209752357; 1.689243837861769; 1.777110221765955; 1.866951203060446; 1.958755989332779; 2.052514132736408; ...
    2.148215510342083; 2.245850306078036; 2.345408994094483; 2.44688232340854; 2.550261303703211; 2.655537192169216; 2.762701481291389; 2.982662340557781; ...
    3.095442973769451; 3.210080114692783; 3.326566276555616; 3.444894150173742; 3.565056596377154; 3.687046638897229; 3.810857457678694; 3.936482382583715; ...
    4.063914887458442; 4.193148584535128; 4.324177219145335; 4.456994664721933; 4.591594918069496; 4.72797209488455; 4.866120425508579; 5; ...
    5.006034250898174; 5.147708018798021; 5.291136280103482; 5.436313685400666; 5.583234981672783; 5.731895009162427; 5.882288698380277; 6.034411067251347; ...
    6.188257218390609; 6.343822336500404; 6.501101685882591; 6.660090608058871; 6.82078451949323; 6.983178909410781; 7.147269337707743; 7.313051432947645; ...
    7.480520890439085; 7.649673470390806; 7.820504996140026; 7.993011352450239; 8.167188483874991; 8.343032393184293; 8.520539139850536; 8.69970483859106; ...
    8.880525657964553; 9.062997819018728; 9.247117593986875; 9.432881305030939; 9.620285323029021; 9.809326066405236; 10; ...
];
K6_labels = { ...
    'k6_1', 'k6_2', 'k6_3', 'k6_4', 'k6_5', 'k6_6', 'k6_7', 'k6_8', 'k6_9', 'k6_10', ...
    'k6_11', 'k6_12', 'k6_13', 'k6_14', 'k6_15', 'k6_16', 'k6_17', 'k6_18', 'k6_19', 'k6_20', ...
    'k6_21', 'k6_22', 'k6_23', 'k6_24', 'k6_25', 'k6_26', 'k6_27', 'k6_28', 'k6_29', 'k6_30', ...
    'k6_31', 'k6_32', 'k6_33', 'k6_34', 'k6_35', 'k6_36', 'k6_37', 'k6_38', 'k6_39', 'k6_40', ...
    'k6_41', 'k6_42'};
K6_embed  = [ ...
    0.07691800301358079; 6.620029700485371; 10.64277906798018; 5.670103693608644; 7.656836805383425; 1.664002606241109; 0.1191414800409248; 8.208490433161504; ...
    4.804843704040813; 0.7620159037924032; 0.1724786268390482; 1.450699299123276; 0.001616218188595062; 7.127437958322791; 1.894561171021474; 3.660631484874071; ...
    0.02257308938207471; 4.021944052755331; 2.693484147773378; 0.2376380383430957; 1.074283762779303; 0.008530450741544886; 2.996724347398019; 6.134342990787927; ...
    11.30951469201372; 9.379595890405941; 9.999553810423972; 2.408941742896582; 4.403246756909745; 12; 6; 0.315269539624516; ...
    0; 0.04502398894370792; 1.254261085977068; 0.9103476502134804; 3.318997841969953; 0.6288325016607648; 8.782658409927429; 0.4059756538290926; ...
    0.5103198180516564; 5.227032313071063; ...
];
K8_labels = { ...
    'k8_1', 'k8_2', 'k8_3', 'k8_4', 'k8_5', 'k8_6', 'k8_7', 'k8_8', 'k8_9', 'k8_10', ...
    'k8_11', 'k8_12', 'k8_13', 'k8_14', 'k8_15', 'k8_16', 'k8_17', 'k8_18', 'k8_19', 'k8_20', ...
    'k8_21', 'k8_22', 'k8_23', 'k8_24', 'k8_25', 'k8_26', 'k8_27', 'k8_28', 'k8_29', 'k8_30', ...
    'k8_31', 'k8_32', 'k8_33', 'k8_34', 'k8_35', 'k8_36', 'k8_37', 'k8_38', 'k8_39', 'k8_40', ...
    'k8_41', 'k8_42', 'k8_43', 'k8_44', 'k8_45', 'k8_46', 'k8_47', 'k8_48', 'k8_49', 'k8_50', ...
    'k8_51', 'k8_52', 'k8_53', 'k8_54', 'k8_55', 'k8_56', 'k8_57', 'k8_58', 'k8_59', 'k8_60', ...
    'k8_61', 'k8_62', 'k8_63', 'k8_64', 'k8_65', 'k8_66', 'k8_67', 'k8_68', 'k8_69', 'k8_70', ...
    'k8_71', 'k8_72', 'k8_73', 'k8_74', 'k8_75', 'k8_76', 'k8_77', 'k8_78', 'k8_79', 'k8_80', ...
    'k8_81', 'k8_82', 'k8_83', 'k8_84', 'k8_85', 'k8_86', 'k8_87', 'k8_88', 'k8_89', 'k8_90', ...
    'k8_91', 'k8_92', 'k8_93', 'k8_94', 'k8_95', 'k8_96', 'k8_97', 'k8_98', 'k8_99', 'k8_100', ...
    'k8_101', 'k8_102', 'k8_103', 'k8_104', 'k8_105', 'k8_106', 'k8_107', 'k8_108', 'k8_109', 'k8_110', ...
    'k8_111', 'k8_112', 'k8_113', 'k8_114', 'k8_115', 'k8_116', 'k8_117', 'k8_118', 'k8_119', 'k8_120', ...
    'k8_121', 'k8_122', 'k8_123', 'k8_124', 'k8_125', 'k8_126', 'k8_127', 'k8_128', 'k8_129'};
K8_embed  = [ ...
    6.688859465944606; 0.03522216567156284; 4.29508915261174; 0.0001402219671627241; 10.40727719294543; 11.86326740764835; 1.596932823712223; 3.263784689489484; ...
    0.4534936919618995; 10.6422404880435; 3.631230965938075; 13.97979954863691; 14.82614010710717; 11.61286319591836; 0.01496412583372819; 6.160448601675355; ...
    0.6183715654227757; 3.758818464114383; 7.242805807178304; 5.024826544056069; 15.70163891400789; 0.02735256622193114; 0.2599937223833966; 2.91899515534089; ...
    2.295703038903279; 0.04427499286561692; 0.2879539468705152; 8.021711060847016; 0.6643018415899122; 5.178834402093729; 2.016327526564405; 3.146357821050023; ...
    8; 0; 0.07898112966162153; 12.37345184141389; 0.02061731110582648; 0.1258616633076495; 4.72491277889186; 1.301745510559153; ...
    5.33556113969578; 0.01033663203390827; 9.497851931673758; 0.4919342571101548; 0.1443677100391104; 0.1088188204120155; 4.43570941528347; 0.4168649015611571; ...
    0.3820226294405755; 0.8675543413269111; 2.493795767092506; 2.701516718410543; 0.001958425551964604; 9.278044853536148; 14.54080073433908; 0.8137672229065903; ...
    0.5743491774985175; 13.70411662822098; 7.055298568050331; 6.509902268446671; 2.200226141334042; 8.63655459152802; 11.36556956758487; 0.9233601177868861; ...
    2.107106613881227; 1.041111662909441; 15.40654879592023; 0.9812056373084298; 6.333769608026484; 0.2089981119832523; 0.003906250000000001; 6.870653995983607; ...
    13.16233297012208; 1.676270360269345; 12.63325404763746; 7.822628541260808; 5.495020300827719; 0.09320411289198091; 0.05455707095796188; 0.0661119703967291; ...
    1.444943662531451; 12.8962108072579; 0.3175938443763249; 10.88026944386909; 1.841722018223654; 1.103098648394002; 1.167186750336894; 5.657225329492693; ...
    3.888983427288334; 9.72066708996293; 9.946501976527509; 0.7619773418270941; 1.75786078616641; 8.428661975444694; 1.51983004333569; 0.2336848133423799; ...
    5.98992627722347; 3.383729066240396; 2.596444575348144; 4.157104289290497; 7.433188255428071; 16; 0.7121629270704175; 0.164370810937152; ...
    4.021740521482209; 1.927871763671534; 4.578979265624907; 2.39355405611733; 8.223718156243978; 2.809028272218324; 9.061234139371981; 0.1859037049527225; ...
    0.006673352502095204; 10.17536817248112; 3.506206140475565; 1.372255093744734; 13.4316313305771; 0.3489410717410698; 8.847408003878119; 7.626458373325634; ...
    12.116793282473; 0.5322113359996742; 4.87352391964795; 5.822189571675094; 15.11471931897272; 11.12137538343266; 0.0007400959797414056; 14.25869072411176; ...
    1.23339583933103; ...
];
ProblemData = { ...
    [0; 2]; ... % x1 C
    K2_labels; ... % x2 K
    {D3_vals}; ... % x3 D
    [0; 800000000]; ... % x4 C
    {D5_vals}; ... % x5 D
    K6_labels; ... % x6 K
    [0; 1400000000]; ... % x7 C
    K8_labels; ... % x8 K
};
x_anchor = {1, 'k2_36', 3, 400000000, 5, 'k6_31', 700000000, 'k8_33'};
anchors_set = [ ...
    1 0 2; ...
    2 0 4; ...
    3 0 6; ...
    4 0 8; ...
    5 0 10; ...
    6 0 12; ...
    7 0 14; ...
    8 0 16];

PB = struct();
PB.name = 'WFG2_mix';
PB.problem = 'WFG2';
PB.source = 'MOModels_Matlab';
PB.type = 'MOO_MIXED';
PB.nvar = 8; PB.n = 8; PB.nobj = 3; PB.m = 3;
PB.var_types = var_types;
PB.type_counts = struct('C', 3, 'D', 2, 'K', 3);
PB.ProblemData = ProblemData;
PB.strategy = 'extreme'; PB.kappa = 100000000;
PB.lb_orig = lb_orig; PB.ub_orig = ub_orig;
PB.lb_C_work = lb_C_work; PB.ub_C_work = ub_C_work;
PB.x_anchor = x_anchor;
PB.anchors_set = anchors_set;
PB.K2_labels = K2_labels; PB.K2_embed = K2_embed;
PB.D3_vals = D3_vals;
PB.D5_vals = D5_vals;
PB.K6_labels = K6_labels; PB.K6_embed = K6_embed;
PB.K8_labels = K8_labels; PB.K8_embed = K8_embed;
PB.pareto_front_known = false;
PB.pareto_set_known = false;
PB.pf_type = 'unknown';
PB.ideal_point = [];
PB.nadir_point = [];
PB.core = @(xh) WFG2_orig(xh);
PB.decode = @(xr) decode(xr, PB);
PB.func_F = @(xr) objective(xr, PB);
PB_cached = PB;
else
    PB = PB_cached;
end

if nargin == 0
    varargout{1} = PB; return
end
arg1 = varargin{1};
if ischar(arg1) || (isstring(arg1) && isscalar(arg1))
    key = lower(char(arg1));
    switch key
        case {'problemdata','bounds','domain'}
            varargout{1} = PB.ProblemData; return
        case 'var_types'
            varargout{1} = PB.var_types; return
        case 'info'
            varargout{1} = PB; return
        otherwise
            error('Unknown string argument: %s', char(arg1));
    end
end
varargout{1} = PB.func_F(arg1);
end

function F = objective(xr, PB)
xh = decode(xr, PB);
F = PB.core(xh);
F = F(:);
end

function xh = decode(xr, PB)
if ~iscell(xr) || numel(xr) ~= 8
    error('WFG2_mix: input must be a cell array with exactly 8 entries.');
end
xh = zeros(8,1);
tmp = check_C(xr{1}, PB.lb_C_work(1), PB.ub_C_work(1), 'x1');
xh(1) = map_C_to_orig(tmp, PB.lb_C_work(1), PB.ub_C_work(1), PB.lb_orig(1), PB.ub_orig(1));
xh(2) = check_K(xr{2}, PB.K2_labels, PB.K2_embed, 'x2');
xh(3) = check_D(xr{3}, PB.D3_vals, 'x3');
tmp = check_C(xr{4}, PB.lb_C_work(4), PB.ub_C_work(4), 'x4');
xh(4) = map_C_to_orig(tmp, PB.lb_C_work(4), PB.ub_C_work(4), PB.lb_orig(4), PB.ub_orig(4));
xh(5) = check_D(xr{5}, PB.D5_vals, 'x5');
xh(6) = check_K(xr{6}, PB.K6_labels, PB.K6_embed, 'x6');
tmp = check_C(xr{7}, PB.lb_C_work(7), PB.ub_C_work(7), 'x7');
xh(7) = map_C_to_orig(tmp, PB.lb_C_work(7), PB.ub_C_work(7), PB.lb_orig(7), PB.ub_orig(7));
xh(8) = check_K(xr{8}, PB.K8_labels, PB.K8_embed, 'x8');
end

function v = check_C(val, a, b, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('WFG2_mix: %s must be a real scalar.', name);
end
if val < a || val > b
    error('WFG2_mix: %s=%g outside [%g,%g].', name, val, a, b);
end
v = double(val);
end

function xorig = map_C_to_orig(xwork, lbw, ubw, lbo, ubo)
if abs(ubw - lbw) <= 1e-14
    t = 0;
else
    t = (xwork - lbw) / (ubw - lbw);
end
t = max(0, min(1, t));
xorig = lbo + t * (ubo - lbo);
end

function v = check_D(val, grid, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('WFG2_mix: %s must be a real scalar.', name);
end
grid = grid(:);
[dmin, idx] = min(abs(grid - val));
if dmin > 1e-10 * max(1, max(abs(grid)))
    error('WFG2_mix: %s=%g not in grid.', name, val);
end
v = grid(idx);
end

function v = check_K(label, labels, embed, name)
if isstring(label), label = char(label); end
if ~(ischar(label) && isrow(label))
    error('WFG2_mix: %s must be a char vector or scalar string.', name);
end
idx = find(strcmp(label, labels), 1);
if isempty(idx)
    error('WFG2_mix: %s unknown label ''%s''.', name, label);
end
v = embed(idx);
end


% -------------------------------------------------------------------------
% Embedded original continuous MOO problem (top-level function renamed only)
% -------------------------------------------------------------------------
function f = WFG2_orig(z)
% WFG2 function
%
%   As described by Huband et al. in "A review of multiobjective test problems
%   and a scalable test problem toolkit", IEEE Transactions on Evolutionary 
%   Computing 10(5): 477-506, 2006.
%
%   Example WFG2.
%
%   This file is part of a collection of problems developed for
%   derivative-free multiobjective optimization in
%   A. L. Custódio, J. F. A. Madeira, A. I. F. Vaz, and L. N. Vicente,
%   Direct Multisearch for Multiobjective Optimization, 2010.
%
%   Written by the authors in June 1, 2010.
%   Adapted to MATLAB format in November 2025.
%
% Problem characteristics:
% - Number of variables: 8
% - Number of objectives: 3
%   Bounds: x1 in [0,2], x2 in [0,4], x3 in [0,6], x4 in [0,8], x5 in [0,10], x6 in [0,12], x7 in [0,14], x8 in [0,16]
%
%
%   Input: z is a n-dimensional vector where n = k+l (k=4, l=4)
%   Output: f is a M-dimensional vector (M=3) with the function values
%   Output: c is a vector of constraints (empty for this problem - bounds are
%          handled by the optimization algorithm)
% Parâmetros
M = 3;      % número de objetivos
k = 4;      % número de variáveis relacionadas à posição
l = 4;      % número de variáveis relacionadas à distância
n = k + l;  % número total de variáveis
pi = 4*atan(1);
pi2 = 2*atan(1);
% Parâmetros S
S = zeros(M, 1);
for m = 1:M
    S(m) = 2*m;
end
% Parâmetros A
A = ones(M-1, 1);  % neq WFG3
% Parâmetros zmax
zmax = zeros(n, 1);
for i = 1:n
    zmax(i) = 2*i;
end
% Transform z into [0,1] set
y = zeros(n, 1);
for i = 1:n
    y(i) = z(i)/zmax(i);
end
% First level mapping
t1 = zeros(n, 1);
for i = 1:n
    if i <= k
        t1(i) = y(i);
    else
        t1(i) = abs(y(i)-0.35)/abs(floor(0.35-y(i))+0.35);
    end
end
% Second level mapping
AA = 2;
t2 = zeros(k+l/2, 1);
for i = 1:k+l/2
    if i <= k
        t2(i) = t1(i);
    else
        % Este nível de mapeamento é diferente do WFG1
        sum_val = 0;
        start_idx = k + 2*(i-k) - 1;
        end_idx = k + 2*(i-k);
        num_items = end_idx - start_idx + 1;
        
        for ii = start_idx:end_idx
            inner_sum = 0;
            for jj = 0:AA-2
                % Esta parte envolve cálculo de módulo para criar pares cíclicos
                idx1 = ii;
                tmp = mod(ii + jj - start_idx + 1, num_items);
                if tmp == 0
                    tmp = num_items;
                end
                idx2 = start_idx + tmp - 1;
                inner_sum = inner_sum + abs(t1(idx1) - t1(idx2));
            end
            sum_val = sum_val + (t1(ii) + inner_sum);
        end
        
        divisor = (num_items / AA) * ceil(AA/2) * (1 + 2*AA - 2*ceil(AA/2));
        t2(i) = sum_val / divisor;
    end
end
% Third level mapping
w = ones(n, 1);  % Note a diferença para WFG1, onde w(i) = 2*i
t3 = zeros(M, 1);
for i = 1:M
    if i <= M-1
        numerator = 0;
        denominator = 0;
        for j = floor((i-1)*k/(M-1))+1 : floor(i*k/(M-1))
            numerator = numerator + w(j)*t2(j);
            denominator = denominator + w(j);
        end
        t3(i) = numerator / denominator;
    else
        numerator = 0;
        denominator = 0;
        for j = k+1 : k+l/2  % Diferente do WFG1: aqui vai até k+l/2
            numerator = numerator + w(j)*t2(j);
            denominator = denominator + w(j);
        end
        t3(i) = numerator / denominator;
    end
end
% Define objective function variables
x = zeros(M, 1);
for i = 1:M
    if i <= M-1
        x(i) = max(t3(M), A(i))*(t3(i)-0.5)+0.5;
    else
        x(i) = t3(M);
    end
end
% Define objective function function h - diferente do WFG1 no último caso
alpha = 1;
beta = 1;
AAAA = 5;
h = zeros(M, 1);
% Compute h[1]
h(1) = 1.0;
for i = 1:M-1
    h(1) = h(1) * (1-cos(x(i)*pi2));
end
% Compute h[m] for m = 2,...,M-1
for m = 2:M-1
    h(m) = 1.0;
    for i = 1:M-m
        h(m) = h(m) * (1-cos(x(i)*pi2));
    end
    h(m) = h(m) * (1-sin(x(M-m+1)*pi2));
end
% Compute h[M] - diferente do WFG1
h(M) = 1 - (x(1))^alpha * cos(AAAA*(x(1))^beta*pi)^2;
% The objective functions
f = zeros(M, 1);
for m = 1:M
    f(m) = x(M) + S(m)*h(m);
end
% Não há restrições de desigualdade para este problema
end

