function varargout = Deb512c_mix(varargin)
%DEB512C_MIX  Self-contained mixed-variable MOO adaptation of Deb512c.
%
% Auto-generated by generate_selfcontained_wrappers_MOO_mix.m
% Source: Deb512c, n=2, m=2, strategy=sobol_digit_oscillatory, kappa=1000000
% Variable pattern: C,K
% D variables: nonuniform sorted finite sets with injected anchors.
% K variables: labels with permuted nonuniform numeric embeddings; labels carry no ordinal information.
%
%   x1   C [0,1] -> orig [0,1]
%   x2   K labels {k2_1,...,k2_53}, 53 levels, permuted embedding in [0,1]
%
% Usage:
%   PB = Deb512c_mix()
%   F  = PB.func_F(xcell)       % recommended inside benchmark loops
%   F  = Deb512c_mix(xcell)              % also valid; PB is memoized persistently
%   PD = Deb512c_mix('ProblemData')
%

persistent PB_cached
if isempty(PB_cached)
lb_orig = [0; 0];
ub_orig = [1; 1];
lb_C_work = [0; 0];
ub_C_work = [1; 1];
var_types = {'C', 'K'};
K2_labels = { ...
    'k2_1', 'k2_2', 'k2_3', 'k2_4', 'k2_5', 'k2_6', 'k2_7', 'k2_8', 'k2_9', 'k2_10', ...
    'k2_11', 'k2_12', 'k2_13', 'k2_14', 'k2_15', 'k2_16', 'k2_17', 'k2_18', 'k2_19', 'k2_20', ...
    'k2_21', 'k2_22', 'k2_23', 'k2_24', 'k2_25', 'k2_26', 'k2_27', 'k2_28', 'k2_29', 'k2_30', ...
    'k2_31', 'k2_32', 'k2_33', 'k2_34', 'k2_35', 'k2_36', 'k2_37', 'k2_38', 'k2_39', 'k2_40', ...
    'k2_41', 'k2_42', 'k2_43', 'k2_44', 'k2_45', 'k2_46', 'k2_47', 'k2_48', 'k2_49', 'k2_50', ...
    'k2_51', 'k2_52', 'k2_53'};
K2_embed  = [ ...
    0.4418512755206516; 0.267105595873055; 0.5652925102744851; 0.005612482194179324; 0.1134797270789169; 0.07838735086544352; 0.7845612140344083; 0.000401849992788396; ...
    0.6696970699848848; 0.2074268677142913; 0.3606960415397722; 0.7068088982368195; 0.03589682359365735; 7.613633641518198e-05; 0.9101646956939311; 0.6337475138960702; ...
    0.1009401544387394; 0.5327653291862174; 0.2263451799111488; 0.1563503851402328; 0.0590853664859649; 0.02403999758243661; 0.05060704708405261; 0; ...
    0.08924843668627475; 0.1268838679399454; 0.4710560729266132; 0.008125072994545143; 0.7450934941138824; 0.1724439634395233; 0.5013569413029385; 0.2889748456789333; ...
    1; 0.003623430917403958; 0.06833912070456943; 0.5; 0.3357572746071617; 0.8670867850363588; 0.02962285861716651; 0.01912458303861443; ...
    0.4137309182859328; 0.3118544339565853; 0.825222280179704; 0.5989495903719194; 0.2462335181284825; 0.1411688190784412; 0.01485162578895199; 0.954465857915882; ...
    0.386683180210497; 0.01119458360263941; 0.002120976977713276; 0.04288439236763809; 0.001063366530120279; ...
];
ProblemData = { ...
    [0; 1]; ... % x1 C
    K2_labels; ... % x2 K
};
x_anchor = {0.5, 'k2_36'};
anchors_set = [0.5 0 1; 0.5 0 1];

PB = struct();
PB.name = 'Deb512c_mix';
PB.problem = 'Deb512c';
PB.source = 'MOModels_Matlab';
PB.type = 'MOO_MIXED';
PB.nvar = 2; PB.n = 2; PB.nobj = 2; PB.m = 2;
PB.var_types = var_types;
PB.type_counts = struct('C', 1, 'D', 0, 'K', 1);
PB.ProblemData = ProblemData;
PB.strategy = 'sobol_digit_oscillatory'; PB.kappa = 1000000;
PB.lb_orig = lb_orig; PB.ub_orig = ub_orig;
PB.lb_C_work = lb_C_work; PB.ub_C_work = ub_C_work;
PB.x_anchor = x_anchor;
PB.anchors_set = anchors_set;
PB.K2_labels = K2_labels; PB.K2_embed = K2_embed;
PB.pareto_front_known = true;
PB.pareto_set_known = true;
PB.pf_type = 'concave';
PB.ideal_point = [0;0];
PB.nadir_point = [1;1];
PB.core = @(xh) Deb512c_orig(xh);
PB.decode = @(xr) decode(xr, PB);
PB.func_F = @(xr) objective(xr, PB);
PB_cached = PB;
else
    PB = PB_cached;
end

if nargin == 0
    varargout{1} = PB; return
end
arg1 = varargin{1};
if ischar(arg1) || (isstring(arg1) && isscalar(arg1))
    key = lower(char(arg1));
    switch key
        case {'problemdata','bounds','domain'}
            varargout{1} = PB.ProblemData; return
        case 'var_types'
            varargout{1} = PB.var_types; return
        case 'info'
            varargout{1} = PB; return
        otherwise
            error('Unknown string argument: %s', char(arg1));
    end
end
varargout{1} = PB.func_F(arg1);
end

function F = objective(xr, PB)
xh = decode(xr, PB);
F = PB.core(xh);
F = F(:);
end

function xh = decode(xr, PB)
if ~iscell(xr) || numel(xr) ~= 2
    error('Deb512c_mix: input must be a cell array with exactly 2 entries.');
end
xh = zeros(2,1);
tmp = check_C(xr{1}, PB.lb_C_work(1), PB.ub_C_work(1), 'x1');
xh(1) = map_C_to_orig(tmp, PB.lb_C_work(1), PB.ub_C_work(1), PB.lb_orig(1), PB.ub_orig(1));
xh(2) = check_K(xr{2}, PB.K2_labels, PB.K2_embed, 'x2');
end

function v = check_C(val, a, b, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('Deb512c_mix: %s must be a real scalar.', name);
end
if val < a || val > b
    error('Deb512c_mix: %s=%g outside [%g,%g].', name, val, a, b);
end
v = double(val);
end

function xorig = map_C_to_orig(xwork, lbw, ubw, lbo, ubo)
if abs(ubw - lbw) <= 1e-14
    t = 0;
else
    t = (xwork - lbw) / (ubw - lbw);
end
t = max(0, min(1, t));
xorig = lbo + t * (ubo - lbo);
end

function v = check_D(val, grid, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('Deb512c_mix: %s must be a real scalar.', name);
end
grid = grid(:);
[dmin, idx] = min(abs(grid - val));
if dmin > 1e-10 * max(1, max(abs(grid)))
    error('Deb512c_mix: %s=%g not in grid.', name, val);
end
v = grid(idx);
end

function v = check_K(label, labels, embed, name)
if isstring(label), label = char(label); end
if ~(ischar(label) && isrow(label))
    error('Deb512c_mix: %s must be a char vector or scalar string.', name);
end
idx = find(strcmp(label, labels), 1);
if isempty(idx)
    error('Deb512c_mix: %s unknown label ''%s''.', name, label);
end
v = embed(idx);
end


% -------------------------------------------------------------------------
% Embedded original continuous MOO problem (top-level function renamed only)
% -------------------------------------------------------------------------
function f = Deb512c_orig(x)
%###############################################################################
%
%   As described by K. Deb in "Multi-objective Genetic Algorithms: Problem
%   Difficulties and Construction of Test Problems", Evolutionary Computation 
%   7(3): 205-230, 1999.
%              
%   Example 5.1.2 (Non-convex local and convex global Pareto-optimal Front).
%
%   This file is part of a collection of problems developed for
%   derivative-free multiobjective optimization in
%   A. L. Custódio, J. F. A. Madeira, A. I. F. Vaz, and L. N. Vicente,
%   Direct Multisearch for Multiobjective Optimization, 2010.
%
%   Written by the authors in June 1, 2010.
%
%   MATLAB version by J. F. A. Madeira
%   November 7, 2025
%
%###############################################################################
%
% Problem characteristics:
% - Number of variables: 2
% - Number of objectives: 2
%   Bounds: x1 in [0,1], x2 in [0,1]
%
%
M = 2; % Number of objectives (fixed)
% Check dimension
n = length(x);
if n ~= 2
    error('Deb512c requires exactly 2 variables, %d provided', n);
end
% Ensure x is a column vector
x = x(:);
% Parameters
beta = 1;
% Initialize objectives
f = zeros(M, 1);
% Function f1
ff1 = 4 * x(1);
% g function
if x(2) <= 0.4
    gx = 4 - 3*exp(-((x(2)-0.2)/0.02)^2);
else
    gx = 4 - 2*exp(-((x(2)-0.7)/0.2)^2);
end
% Variable alpha
alpha = 0.25 + 3.75*(gx - 1);
% h function
if ff1 <= beta*gx
    h = 1 - (ff1/(beta*gx))^alpha;
else
    h = 0;
end
% Objective functions
f(1) = ff1;
f(2) = gx * h;
end

