function varargout = OKA2_mix(varargin)
%OKA2_MIX  Self-contained mixed-variable MOO adaptation of OKA2.
%
% Auto-generated by generate_selfcontained_wrappers_MOO_mix.m
% Source: OKA2, n=3, m=2, strategy=sobol_digit_oscillatory, kappa=1000000
% Variable pattern: C,K,D
% D variables: nonuniform sorted finite sets with injected anchors.
% K variables: labels with permuted nonuniform numeric embeddings; labels carry no ordinal information.
%
%   x1   C [-3.14159265359,3.14159265359] -> orig [-3.14159265359,3.14159265359]
%   x2   K labels {k2_1,...,k2_77}, 77 levels, permuted embedding in [-5,5]
%   x3   D sorted nonuniform grid [-5,...,5], 98 values
%
% Usage:
%   PB = OKA2_mix()
%   F  = PB.func_F(xcell)       % recommended inside benchmark loops
%   F  = OKA2_mix(xcell)              % also valid; PB is memoized persistently
%   PD = OKA2_mix('ProblemData')
%

persistent PB_cached
if isempty(PB_cached)
lb_orig = [-3.141592653589793; -5; -5];
ub_orig = [3.141592653589793; 5; 5];
lb_C_work = [-3.141592653589793; -5; -5];
ub_C_work = [3.141592653589793; 5; 5];
var_types = {'C', 'K', 'D'};
K2_labels = { ...
    'k2_1', 'k2_2', 'k2_3', 'k2_4', 'k2_5', 'k2_6', 'k2_7', 'k2_8', 'k2_9', 'k2_10', ...
    'k2_11', 'k2_12', 'k2_13', 'k2_14', 'k2_15', 'k2_16', 'k2_17', 'k2_18', 'k2_19', 'k2_20', ...
    'k2_21', 'k2_22', 'k2_23', 'k2_24', 'k2_25', 'k2_26', 'k2_27', 'k2_28', 'k2_29', 'k2_30', ...
    'k2_31', 'k2_32', 'k2_33', 'k2_34', 'k2_35', 'k2_36', 'k2_37', 'k2_38', 'k2_39', 'k2_40', ...
    'k2_41', 'k2_42', 'k2_43', 'k2_44', 'k2_45', 'k2_46', 'k2_47', 'k2_48', 'k2_49', 'k2_50', ...
    'k2_51', 'k2_52', 'k2_53', 'k2_54', 'k2_55', 'k2_56', 'k2_57', 'k2_58', 'k2_59', 'k2_60', ...
    'k2_61', 'k2_62', 'k2_63', 'k2_64', 'k2_65', 'k2_66', 'k2_67', 'k2_68', 'k2_69', 'k2_70', ...
    'k2_71', 'k2_72', 'k2_73', 'k2_74', 'k2_75', 'k2_76', 'k2_77'};
K2_embed  = [ ...
    -4.684716392749579; 3.20885670379074; -2.983480456619031; -2.590950767837863; -1.680854061198126; -4.306409079506976; -4.371139439236536; -3.745682947703555; ...
    -4.432201573099033; -2.003141935919079; -3.649542770230507; -4.489657410994002; 0.6703566990137908; -4.985426113299544; -4.165703517575462; 2.389701656093015; ...
    -3.335923144384222; 4.078670262821475; -4.998383709694217; -1.339205174276806; -4.009618376378453; -4.903308160405975; 3.493123033955456; -0.7897346726499519; ...
    -3.222819594280183; 1.134616710990865; -4.237950094335164; -4.99572300847338; -2.726323701168022; -4.880853203753225; -0.1949418992755128; 0.8998229991807127; ...
    1.374772598893886; -4.999693770250905; -3.549235969297946; 0.2272655482109389; 0; -0.3983049678787669; -2.85715204112303; -4.762351358022223; ...
    -4.641031764063427; -4.855618541684516; -4.940264926667672; -4.089611729210864; -2.15712730928582; 4.687114000674809; -4.827513677001019; 2.127755991365174; ...
    2.930219280961321; 1.871308294995369; -3.925668301660198; 5; -3.837707477744952; 4.380014416871523; -4.796452205862389; 0.4461827023629681; ...
    -4.923078564832164; -4.725131615570938; -4.977425903385265; -1.844397891515119; 3.783050300476408; 2.657178460704522; -0.9778764842860479; -0.5965567660432933; ...
    -3.444712487744304; 1.620325092489989; -4.594006231152148; -4.954974002043198; -4.967319952841748; -5; -2.306395666409062; -2.45098922133336; ...
    -1.512469851740452; -4.991469168621651; -4.543570521159087; 0.0135694130293853; -1.161020427930439; ...
];
D3_vals = [ ...
    -5; -4.997346550184151; -4.990760151072539; -4.980829689956958; -4.967824977245713; -4.951920838372088; -4.933245103173876; -4.911897678884399; ...
    -4.887960063268759; -4.86150075838959; -4.832578635048062; -4.801245160741758; -4.767545947860972; -4.731521871078384; -4.693209898900471; -4.652643728360183; ...
    -4.609854279867822; -4.564870090091558; -4.517717628799887; -4.468421557893526; -4.417004945733137; -4.363489446376652; -4.307895450903629; -4.250242216269941; ...
    -4.19054797587961; -4.128830035135401; -4.065104854538393; -3.999388122383468; -3.931694818696521; -3.862039271748483; -3.790435208238063; -3.716895798042857; ...
    -3.641433694285441; -3.564061069337922; -3.484789647288857; -3.403630733315263; -3.320595240335804; -3.235693713266236; -3.148936351152533; -3.06033302741898; ...
    -2.96989330843651; -2.87762647058958; -2.783541515997064; -2.687647187023111; -2.58995197969738; -2.490464156149781; -2.389191756152573; -2.286142607852099; ...
    -2.074744380091608; -1.966409985441835; -1.85632822896358; -1.744506017982345; -1.630950099156798; -1.515667065200544; -1.398663361202437; -1.279945290576351; ...
    -1.15951902066841; -1.0373905880471; -0.9135659034993875; -0.7880507567539468; -0.66085082095071; -0.5319716568743402; -0.4014187169677168; -0.2691973491402253; ...
    -0.1353128003843649; 0; 0.00022977978682448; 0.137425336070053; 0.2762689042592186; 0.416755608280214; 0.5588806573640737; 0.7026393433501319; ...
    0.8480270381114323; 0.9950391910952217; 1.143671326971888; 1.293919043386122; 1.445778008804566; 1.599243960454588; 1.754312702349177; 1.910980103393286; ...
    2.069242095567311; 2.229094672183582; 2.390533886212097; 2.553555848671921; 2.718156727084917; 2.884332743988661; 3.052080175505633; 3.221395349965885; ...
    3.392274646580621; 3.564714494164228; 3.738711369902491; 3.91426179816477; 4.091362349358167; 4.270009638821728; 4.450200325758823; 4.631931112206084; ...
    4.81519874203719; 5; ...
];
ProblemData = { ...
    [-3.141592653589793; 3.141592653589793]; ... % x1 C
    K2_labels; ... % x2 K
    {D3_vals}; ... % x3 D
};
x_anchor = {0, 'k2_37', 0};
anchors_set = [0 -3.141592653589793 3.141592653589793; 0 -5 5; 0 -5 5];

PB = struct();
PB.name = 'OKA2_mix';
PB.problem = 'OKA2';
PB.source = 'MOModels_Matlab';
PB.type = 'MOO_MIXED';
PB.nvar = 3; PB.n = 3; PB.nobj = 2; PB.m = 2;
PB.var_types = var_types;
PB.type_counts = struct('C', 1, 'D', 1, 'K', 1);
PB.ProblemData = ProblemData;
PB.strategy = 'sobol_digit_oscillatory'; PB.kappa = 1000000;
PB.lb_orig = lb_orig; PB.ub_orig = ub_orig;
PB.lb_C_work = lb_C_work; PB.ub_C_work = ub_C_work;
PB.x_anchor = x_anchor;
PB.anchors_set = anchors_set;
PB.K2_labels = K2_labels; PB.K2_embed = K2_embed;
PB.D3_vals = D3_vals;
PB.pareto_front_known = false;
PB.pareto_set_known = false;
PB.pf_type = 'unknown';
PB.ideal_point = [];
PB.nadir_point = [];
PB.core = @(xh) OKA2_orig(xh);
PB.decode = @(xr) decode(xr, PB);
PB.func_F = @(xr) objective(xr, PB);
PB_cached = PB;
else
    PB = PB_cached;
end

if nargin == 0
    varargout{1} = PB; return
end
arg1 = varargin{1};
if ischar(arg1) || (isstring(arg1) && isscalar(arg1))
    key = lower(char(arg1));
    switch key
        case {'problemdata','bounds','domain'}
            varargout{1} = PB.ProblemData; return
        case 'var_types'
            varargout{1} = PB.var_types; return
        case 'info'
            varargout{1} = PB; return
        otherwise
            error('Unknown string argument: %s', char(arg1));
    end
end
varargout{1} = PB.func_F(arg1);
end

function F = objective(xr, PB)
xh = decode(xr, PB);
F = PB.core(xh);
F = F(:);
end

function xh = decode(xr, PB)
if ~iscell(xr) || numel(xr) ~= 3
    error('OKA2_mix: input must be a cell array with exactly 3 entries.');
end
xh = zeros(3,1);
tmp = check_C(xr{1}, PB.lb_C_work(1), PB.ub_C_work(1), 'x1');
xh(1) = map_C_to_orig(tmp, PB.lb_C_work(1), PB.ub_C_work(1), PB.lb_orig(1), PB.ub_orig(1));
xh(2) = check_K(xr{2}, PB.K2_labels, PB.K2_embed, 'x2');
xh(3) = check_D(xr{3}, PB.D3_vals, 'x3');
end

function v = check_C(val, a, b, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('OKA2_mix: %s must be a real scalar.', name);
end
if val < a || val > b
    error('OKA2_mix: %s=%g outside [%g,%g].', name, val, a, b);
end
v = double(val);
end

function xorig = map_C_to_orig(xwork, lbw, ubw, lbo, ubo)
if abs(ubw - lbw) <= 1e-14
    t = 0;
else
    t = (xwork - lbw) / (ubw - lbw);
end
t = max(0, min(1, t));
xorig = lbo + t * (ubo - lbo);
end

function v = check_D(val, grid, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('OKA2_mix: %s must be a real scalar.', name);
end
grid = grid(:);
[dmin, idx] = min(abs(grid - val));
if dmin > 1e-10 * max(1, max(abs(grid)))
    error('OKA2_mix: %s=%g not in grid.', name, val);
end
v = grid(idx);
end

function v = check_K(label, labels, embed, name)
if isstring(label), label = char(label); end
if ~(ischar(label) && isrow(label))
    error('OKA2_mix: %s must be a char vector or scalar string.', name);
end
idx = find(strcmp(label, labels), 1);
if isempty(idx)
    error('OKA2_mix: %s unknown label ''%s''.', name, label);
end
v = embed(idx);
end


% -------------------------------------------------------------------------
% Embedded original continuous MOO problem (top-level function renamed only)
% -------------------------------------------------------------------------
function f = OKA2_orig(x)
% OKA2 function
%
%   As described by T. Okabe, Y. Jin, M. Olhofer, and B. Sendhoff. "On test
%   functions for evolutionary multi-objective optimization.", Parallel
%   Problem Solving from Nature, VIII, LNCS 3242, Springer, pp.792-802,
%   September 2004.
%
%   Test function OKA2.
%
%   This file is part of a collection of problems developed for
%   derivative-free multiobjective optimization in
%   A. L. Custódio, J. F. A. Madeira, A. I. F. Vaz, and L. N. Vicente,
%   Direct Multisearch for Multiobjective Optimization, 2010.
%
%   Written by the authors in June 1, 2010.
%   Adapted to MATLAB format in November 2025.
%
% Problem characteristics:
% - Number of variables: 3
% - Number of objectives: 2
%   Bounds: x1 in [-3.14159265359,3.14159265359], x2 in [-5,5], x3 in [-5,5]
%
%
%   Input: x is a 3-dimensional vector
%   Output: f is a 2-dimensional vector with the function values
%   Output: c is a vector of constraints (empty for this problem - bounds are
%          handled by the optimization algorithm)
% Parâmetros
pi = 4*atan(1);
% Função objetivo 1
f1 = x(1);
% Função objetivo 2
f2 = 1 - (x(1) + pi)^2 / (4 * pi^2) + abs(x(2) - 5*cos(x(1)))^(1/3) + abs(x(3) - 5*sin(x(1)))^(1/3);
% Vetor de funções objetivo
f = [f1; f2];
% Não há restrições de desigualdade para este problema
% As restrições de limites são tratadas pelo algoritmo de otimização
% Note: As restrições são
% -pi <= x(1) <= pi
% -5 <= x(2) <= 5
% -5 <= x(3) <= 5
end

