function varargout = WFG4_mix(varargin)
%WFG4_MIX  Self-contained mixed-variable MOO adaptation of WFG4.
%
% Auto-generated by generate_selfcontained_wrappers_MOO_mix.m
% Source: WFG4, n=8, m=3, strategy=sobol_digit_oscillatory, kappa=1000000
% Variable pattern: C,K,D,C,D,K,C,K
% D variables: nonuniform sorted finite sets with injected anchors.
% K variables: labels with permuted nonuniform numeric embeddings; labels carry no ordinal information.
%
%   x1   C [0,1177146.66696] -> orig [0,2]
%   x2   K labels {k2_1,...,k2_46}, 46 levels, permuted embedding in [0,4]
%   x3   D sorted nonuniform grid [0,...,6], 45 values
%   x4   C [0,2862.68950892] -> orig [0,8]
%   x5   D sorted nonuniform grid [0,...,10], 28 values
%   x6   K labels {k6_1,...,k6_125}, 125 levels, permuted embedding in [0,12]
%   x7   C [0,13805866.0823] -> orig [0,14]
%   x8   K labels {k8_1,...,k8_35}, 35 levels, permuted embedding in [0,16]
%
% Usage:
%   PB = WFG4_mix()
%   F  = PB.func_F(xcell)       % recommended inside benchmark loops
%   F  = WFG4_mix(xcell)              % also valid; PB is memoized persistently
%   PD = WFG4_mix('ProblemData')
%

persistent PB_cached
if isempty(PB_cached)
lb_orig = [0; 0; 0; 0; 0; 0; 0; 0];
ub_orig = [2; 4; 6; 8; 10; 12; 14; 16];
lb_C_work = [0; 0; 0; 0; 0; 0; 0; 0];
ub_C_work = [1177146.666962771; 4; 6; 2862.689508920011; 10; 12; 13805866.08232005; 16];
var_types = {'C', 'K', 'D', 'C', 'D', 'K', 'C', 'K'};
K2_labels = { ...
    'k2_1', 'k2_2', 'k2_3', 'k2_4', 'k2_5', 'k2_6', 'k2_7', 'k2_8', 'k2_9', 'k2_10', ...
    'k2_11', 'k2_12', 'k2_13', 'k2_14', 'k2_15', 'k2_16', 'k2_17', 'k2_18', 'k2_19', 'k2_20', ...
    'k2_21', 'k2_22', 'k2_23', 'k2_24', 'k2_25', 'k2_26', 'k2_27', 'k2_28', 'k2_29', 'k2_30', ...
    'k2_31', 'k2_32', 'k2_33', 'k2_34', 'k2_35', 'k2_36', 'k2_37', 'k2_38', 'k2_39', 'k2_40', ...
    'k2_41', 'k2_42', 'k2_43', 'k2_44', 'k2_45', 'k2_46'};
K2_embed  = [ ...
    0.6422088197361375; 1.280941315118027; 2.665818577562864; 0.9759014855058897; 1.900130433811628; 1.5116142229639; 3.389598472039828; 2.188332270151681; ...
    0.002274164877045758; 0.06335281647169425; 1.173878077832529; 2.50054166903036; 0.04598172442261927; 1.635377519438704; 0.3867473704705517; 0.03176237428917504; ...
    1.393494160827505; 1.072225158944271; 0.571244389766689; 2.041264859226033; 3.58652821421459; 0.1082305731369367; 2.341401865867911; 0.1676428165579842; ...
    0.006017844612725818; 1.76485856210654; 0.8848240905300371; 4; 0; 0.7989079901546001; 0.2863973399898908; 0.08404888974092058; ...
    0.0004308736723892923; 3.015045965127122; 0.4436126996192938; 0.5050781726654022; 0.2031486795551346; 3.78997531952689; 0.3343781700165755; 0.02050585908832128; ...
    0.01200311418265497; 2.837298412929469; 0.1360480754693719; 0.2426929965065013; 3.199125034699727; 2; ...
];
D3_vals = [ ...
    0; 0.006605967499806657; 0.0230033149122903; 0.0477259620095891; 0.08010219501828982; 0.1196967725693914; 0.1661914524451888; 0.2193375079004561; ...
    0.2789320439777128; 0.3448045195207831; 0.416808371140047; 0.4948154665398353; 0.5787122501646407; 0.6683969613715092; 0.7637775642188407; 0.8647701673501116; ...
    0.9712977920245485; 1.08328939401084; 1.200679074783468; 1.323405436642857; 1.451411049130032; 1.584642002801482; 1.866579696538781; 2.015193101468782; ...
    2.168844664153728; 2.32749340490954; 2.491100266518893; 2.659627955054614; 2.833040799183645; 3; 3.011304625233293; 3.194386645779853; ...
    3.382255359901009; 3.574880463539741; 3.772232768675416; 3.974284130199913; 4.18100737956247; 4.392376264383881; 4.60836539335437; 4.828950185824421; ...
    5.05410682557747; 5.283812218340584; 5.518043952646115; 5.756780263705791; 6; ...
];
D5_vals = [ ...
    0; 0.02651827222128617; 0.09234198727952256; 0.1915858733228839; 0.3215534761682876; 0.4804976105464343; 0.6671407597632657; 0.880484462421748; ...
    1.119714239232519; 1.384145488461686; 1.67318986209456; 1.986332999880807; 2.323119056838861; 3.066024978938952; 3.471438620808935; 3.89907144677824; ...
    4.348638264667875; 4.819874538656438; 5; 5.312533800545117; 5.826385507791136; 6.361213252230462; 6.916813247759668; 7.492993042577012; ...
    8.089570414140125; 8.706372414244527; 9.343234538535935; 10; ...
];
K6_labels = { ...
    'k6_1', 'k6_2', 'k6_3', 'k6_4', 'k6_5', 'k6_6', 'k6_7', 'k6_8', 'k6_9', 'k6_10', ...
    'k6_11', 'k6_12', 'k6_13', 'k6_14', 'k6_15', 'k6_16', 'k6_17', 'k6_18', 'k6_19', 'k6_20', ...
    'k6_21', 'k6_22', 'k6_23', 'k6_24', 'k6_25', 'k6_26', 'k6_27', 'k6_28', 'k6_29', 'k6_30', ...
    'k6_31', 'k6_32', 'k6_33', 'k6_34', 'k6_35', 'k6_36', 'k6_37', 'k6_38', 'k6_39', 'k6_40', ...
    'k6_41', 'k6_42', 'k6_43', 'k6_44', 'k6_45', 'k6_46', 'k6_47', 'k6_48', 'k6_49', 'k6_50', ...
    'k6_51', 'k6_52', 'k6_53', 'k6_54', 'k6_55', 'k6_56', 'k6_57', 'k6_58', 'k6_59', 'k6_60', ...
    'k6_61', 'k6_62', 'k6_63', 'k6_64', 'k6_65', 'k6_66', 'k6_67', 'k6_68', 'k6_69', 'k6_70', ...
    'k6_71', 'k6_72', 'k6_73', 'k6_74', 'k6_75', 'k6_76', 'k6_77', 'k6_78', 'k6_79', 'k6_80', ...
    'k6_81', 'k6_82', 'k6_83', 'k6_84', 'k6_85', 'k6_86', 'k6_87', 'k6_88', 'k6_89', 'k6_90', ...
    'k6_91', 'k6_92', 'k6_93', 'k6_94', 'k6_95', 'k6_96', 'k6_97', 'k6_98', 'k6_99', 'k6_100', ...
    'k6_101', 'k6_102', 'k6_103', 'k6_104', 'k6_105', 'k6_106', 'k6_107', 'k6_108', 'k6_109', 'k6_110', ...
    'k6_111', 'k6_112', 'k6_113', 'k6_114', 'k6_115', 'k6_116', 'k6_117', 'k6_118', 'k6_119', 'k6_120', ...
    'k6_121', 'k6_122', 'k6_123', 'k6_124', 'k6_125'};
K6_embed  = [ ...
    0.2824263652334963; 2.018431566741011; 0.07543766257595411; 0.8426562722771238; 9.001432850160183; 0.3092019581744917; 0.2570545067686881; 6.656123384914023; ...
    0.9982874817753382; 1.422779582656513; 0.8928273768559998; 8.806286220365699; 2.101513588775673; 0.7473503780077653; 1.780821812371239; 2.837857553061814; ...
    0.5764113291191926; 9.601906353464027; 5.413837520182223; 1.937297804142513; 1.356741820724434; 0.0441574709780132; 5.126434442629027; 11.09185521994494; ...
    0.05350979007546584; 0.003161645557195946; 10.01484007464556; 6.492622626978953; 4.848134093392595; 1.110677560442251; 0.06392584645042754; 7.867725802998306; ...
    1.560383282292638; 9.199079047259175; 8.050512328634596; 0.1691591557668327; 0.9446990857268773; 0.02850816092424094; 0.5376734633215565; 3.82425587085358; ...
    4.318503212151423; 0.1168485194362127; 6.822001072069405; 0.101870071966188; 12; 11.54071710190566; 0.7941694576363041; 10.22511911235601; ...
    4.578852180236016; 0.3374026403767699; 0.4648674624812373; 4.447566469328251; 1.490655292545732; 0.0005990198185594868; 4.191651527381288; 1.705452611664838; ...
    8.423455155093148; 7.509475658405702; 0.08807591426430779; 1.053608424975133; 6.99026546016891; 0.008366276287072091; 0.398162370156751; 0.001585112946039784; ...
    3.476364681501544; 3.590180087255861; 3.944538943601436; 6.016283295635262; 5.710426463326014; 0.6586479423729419; 0.0166872652951201; 0.1330386544978281; ...
    5.560978606446628; 10.43795138647789; 0.5004983584038964; 1.858099024278984; 3.255121421296418; 9.80710544614206; 0.7021822281938646; 5.268992917712442; ...
    6.172712507690191; 1.169510326026496; 2.362579984476163; 10.87131072568652; 0.2330645291008517; 0.6167301830327316; 0.01211168306163912; 3.706140019623767; ...
    0.1891401092833534; 3.042317234527572; 1.631977719350846; 4.067000452785951; 4.986151667666141; 8.23575233929164; 1.292527505210912; 0.03583534962904574; ...
    0.0001134930328323334; 8.613630043554187; 2.738726904072635; 11.31498781016007; 1.230121959476532; 11.76905165818744; 0.3670492970003779; 2.641646172971154; ...
    2.453585176819657; 2.939050304156276; 2.186557012596035; 7.160926261289241; 0.2104340473017093; 7.33399312882116; 3.147670316773075; 6.331488965906285; ...
    4.712371146864415; 0.005401286474202047; 10.65334567867396; 0.1504669754444905; 0; 9.399233876403091; 3.36468231860109; 7.687383388846404; ...
    5.86219130928596; 0.02213865458520998; 0.4307618831238882; 6; 2.546603065925508; ...
];
K8_labels = { ...
    'k8_1', 'k8_2', 'k8_3', 'k8_4', 'k8_5', 'k8_6', 'k8_7', 'k8_8', 'k8_9', 'k8_10', ...
    'k8_11', 'k8_12', 'k8_13', 'k8_14', 'k8_15', 'k8_16', 'k8_17', 'k8_18', 'k8_19', 'k8_20', ...
    'k8_21', 'k8_22', 'k8_23', 'k8_24', 'k8_25', 'k8_26', 'k8_27', 'k8_28', 'k8_29', 'k8_30', ...
    'k8_31', 'k8_32', 'k8_33', 'k8_34', 'k8_35'};
K8_embed  = [ ...
    8; 4.477571930441461; 0.360417506545848; 3.477159351383684; 0.4965769429506772; 13.83345079697854; 1.314030882765877; 0.6587985041611001; ...
    0.1607306097149689; 10.04037322704872; 0.09408373737217879; 9.201181885060162; 0.003377307323481089; 10.92259364210767; 0.04716953479526452; 16; ...
    5.628400795230999; 2.244861767510024; 0; 14.89374923767283; 8.404398118925668; 5.03381081065306; 7.649386456402629; 11.84845144328439; ...
    0.01782553492177811; 1.066382541036491; 6.262062360354469; 2.620948818123355; 1.902295004273151; 12.81854248004857; 0.2489622972393153; 3.958942773212942; ...
    6.935496579237856; 0.8483412440890082; 1.592335682550558; ...
];
ProblemData = { ...
    [0; 1177146.666962771]; ... % x1 C
    K2_labels; ... % x2 K
    {D3_vals}; ... % x3 D
    [0; 2862.689508920011]; ... % x4 C
    {D5_vals}; ... % x5 D
    K6_labels; ... % x6 K
    [0; 13805866.08232005]; ... % x7 C
    K8_labels; ... % x8 K
};
x_anchor = {588573.3334813853, 'k2_46', 3, 1431.344754460005, 5, 'k6_124', 6902933.041160023, 'k8_1'};
anchors_set = [ ...
    1 0 2; ...
    2 0 4; ...
    3 0 6; ...
    4 0 8; ...
    5 0 10; ...
    6 0 12; ...
    7 0 14; ...
    8 0 16];

PB = struct();
PB.name = 'WFG4_mix';
PB.problem = 'WFG4';
PB.source = 'MOModels_Matlab';
PB.type = 'MOO_MIXED';
PB.nvar = 8; PB.n = 8; PB.nobj = 3; PB.m = 3;
PB.var_types = var_types;
PB.type_counts = struct('C', 3, 'D', 2, 'K', 3);
PB.ProblemData = ProblemData;
PB.strategy = 'sobol_digit_oscillatory'; PB.kappa = 1000000;
PB.lb_orig = lb_orig; PB.ub_orig = ub_orig;
PB.lb_C_work = lb_C_work; PB.ub_C_work = ub_C_work;
PB.x_anchor = x_anchor;
PB.anchors_set = anchors_set;
PB.K2_labels = K2_labels; PB.K2_embed = K2_embed;
PB.D3_vals = D3_vals;
PB.D5_vals = D5_vals;
PB.K6_labels = K6_labels; PB.K6_embed = K6_embed;
PB.K8_labels = K8_labels; PB.K8_embed = K8_embed;
PB.pareto_front_known = false;
PB.pareto_set_known = false;
PB.pf_type = 'unknown';
PB.ideal_point = [];
PB.nadir_point = [];
PB.core = @(xh) WFG4_orig(xh);
PB.decode = @(xr) decode(xr, PB);
PB.func_F = @(xr) objective(xr, PB);
PB_cached = PB;
else
    PB = PB_cached;
end

if nargin == 0
    varargout{1} = PB; return
end
arg1 = varargin{1};
if ischar(arg1) || (isstring(arg1) && isscalar(arg1))
    key = lower(char(arg1));
    switch key
        case {'problemdata','bounds','domain'}
            varargout{1} = PB.ProblemData; return
        case 'var_types'
            varargout{1} = PB.var_types; return
        case 'info'
            varargout{1} = PB; return
        otherwise
            error('Unknown string argument: %s', char(arg1));
    end
end
varargout{1} = PB.func_F(arg1);
end

function F = objective(xr, PB)
xh = decode(xr, PB);
F = PB.core(xh);
F = F(:);
end

function xh = decode(xr, PB)
if ~iscell(xr) || numel(xr) ~= 8
    error('WFG4_mix: input must be a cell array with exactly 8 entries.');
end
xh = zeros(8,1);
tmp = check_C(xr{1}, PB.lb_C_work(1), PB.ub_C_work(1), 'x1');
xh(1) = map_C_to_orig(tmp, PB.lb_C_work(1), PB.ub_C_work(1), PB.lb_orig(1), PB.ub_orig(1));
xh(2) = check_K(xr{2}, PB.K2_labels, PB.K2_embed, 'x2');
xh(3) = check_D(xr{3}, PB.D3_vals, 'x3');
tmp = check_C(xr{4}, PB.lb_C_work(4), PB.ub_C_work(4), 'x4');
xh(4) = map_C_to_orig(tmp, PB.lb_C_work(4), PB.ub_C_work(4), PB.lb_orig(4), PB.ub_orig(4));
xh(5) = check_D(xr{5}, PB.D5_vals, 'x5');
xh(6) = check_K(xr{6}, PB.K6_labels, PB.K6_embed, 'x6');
tmp = check_C(xr{7}, PB.lb_C_work(7), PB.ub_C_work(7), 'x7');
xh(7) = map_C_to_orig(tmp, PB.lb_C_work(7), PB.ub_C_work(7), PB.lb_orig(7), PB.ub_orig(7));
xh(8) = check_K(xr{8}, PB.K8_labels, PB.K8_embed, 'x8');
end

function v = check_C(val, a, b, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('WFG4_mix: %s must be a real scalar.', name);
end
if val < a || val > b
    error('WFG4_mix: %s=%g outside [%g,%g].', name, val, a, b);
end
v = double(val);
end

function xorig = map_C_to_orig(xwork, lbw, ubw, lbo, ubo)
if abs(ubw - lbw) <= 1e-14
    t = 0;
else
    t = (xwork - lbw) / (ubw - lbw);
end
t = max(0, min(1, t));
xorig = lbo + t * (ubo - lbo);
end

function v = check_D(val, grid, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('WFG4_mix: %s must be a real scalar.', name);
end
grid = grid(:);
[dmin, idx] = min(abs(grid - val));
if dmin > 1e-10 * max(1, max(abs(grid)))
    error('WFG4_mix: %s=%g not in grid.', name, val);
end
v = grid(idx);
end

function v = check_K(label, labels, embed, name)
if isstring(label), label = char(label); end
if ~(ischar(label) && isrow(label))
    error('WFG4_mix: %s must be a char vector or scalar string.', name);
end
idx = find(strcmp(label, labels), 1);
if isempty(idx)
    error('WFG4_mix: %s unknown label ''%s''.', name, label);
end
v = embed(idx);
end


% -------------------------------------------------------------------------
% Embedded original continuous MOO problem (top-level function renamed only)
% -------------------------------------------------------------------------
function f = WFG4_orig(z)
% WFG4 function
%
%   As described by Huband et al. in "A review of multiobjective test problems
%   and a scalable test problem toolkit", IEEE Transactions on Evolutionary 
%   Computing 10(5): 477-506, 2006.
%
%   Example WFG4.
%
%   This file is part of a collection of problems developed for
%   derivative-free multiobjective optimization in
%   A. L. Custódio, J. F. A. Madeira, A. I. F. Vaz, and L. N. Vicente,
%   Direct Multisearch for Multiobjective Optimization, 2010.
%
%   Written by the authors in June 1, 2010.
%   Adapted to MATLAB format in November 2025.
%
% Problem characteristics:
% - Number of variables: 8
% - Number of objectives: 3
%   Bounds: x1 in [0,2], x2 in [0,4], x3 in [0,6], x4 in [0,8], x5 in [0,10], x6 in [0,12], x7 in [0,14], x8 in [0,16]
%
%
%   Input: z is a n-dimensional vector where n = k+l (k=4, l=4)
%   Output: f is a M-dimensional vector (M=3) with the function values
%   Output: c is a vector of constraints (empty for this problem - bounds are
%          handled by the optimization algorithm)
% Parâmetros
M = 3;      % número de objetivos
k = 4;      % número de variáveis relacionadas à posição
l = 4;      % número de variáveis relacionadas à distância
n = k + l;  % número total de variáveis
pi = 4*atan(1);
pi2 = 2*atan(1);
% Parâmetros S
S = zeros(M, 1);
for m = 1:M
    S(m) = 2*m;
end
% Parâmetros A
A = ones(M-1, 1);  % neq WFG3
% Parâmetros zmax
zmax = zeros(n, 1);
for i = 1:n
    zmax(i) = 2*i;
end
% Transform z into [0,1] set
y = zeros(n, 1);
for i = 1:n
    y(i) = z(i)/zmax(i);
end
% First level mapping - Completamente diferente dos anteriores
AA = 30;
BB = 10;
CC = 0.35;
t1 = zeros(n, 1);
for i = 1:n
    % Função de mapeamento multimodal
    t1(i) = (1 + cos((4*AA+2)*pi*(0.5-abs(y(i)-CC)/(2*(floor(CC-y(i))+CC)))) + 4*BB*(abs(y(i)-CC)/(2*(floor(CC-y(i))+CC)))^2) / (BB+2);
end
% Second level mapping - Similar ao WFG3 mas com todas as variáveis l
w = ones(n, 1);
t2 = zeros(M, 1);
for i = 1:M
    if i <= M-1
        numerator = 0;
        denominator = 0;
        for j = floor((i-1)*k/(M-1))+1 : floor(i*k/(M-1))
            numerator = numerator + w(j)*t1(j);
            denominator = denominator + w(j);
        end
        t2(i) = numerator / denominator;
    else
        numerator = 0;
        denominator = 0;
        for j = k+1 : n  % Diferente do WFG2/WFG3: aqui usa todas as variáveis l
            numerator = numerator + w(j)*t1(j);
            denominator = denominator + w(j);
        end
        t2(i) = numerator / denominator;
    end
end
% Define objective function variables
x = zeros(M, 1);
for i = 1:M
    if i <= M-1
        x(i) = max(t2(M), A(i))*(t2(i)-0.5)+0.5;
    else
        x(i) = t2(M);
    end
end
% Define objective function function h - Diferente de WFG3, igual a forma do WFG1
h = zeros(M, 1);
% Compute h[1]
h(1) = 1.0;
for i = 1:M-1
    h(1) = h(1) * sin(x(i)*pi2);
end
% Compute h[m] for m = 2,...,M-1
for m = 2:M-1
    h(m) = 1.0;
    for i = 1:M-m
        h(m) = h(m) * sin(x(i)*pi2);
    end
    h(m) = h(m) * cos(x(M-m+1)*pi2);
end
% Compute h[M]
h(M) = cos(x(1)*pi2);
% The objective functions
f = zeros(M, 1);
for m = 1:M
    f(m) = x(M) + S(m)*h(m);
end
% Não há restrições de desigualdade para este problema
end

