function varargout = Deb41_mix(varargin)
%DEB41_MIX  Self-contained mixed-variable MOO adaptation of Deb41.
%
% Auto-generated by generate_selfcontained_wrappers_MOO_mix.m
% Source: Deb41, n=2, m=2, strategy=progressive, kappa=1000000
% Variable pattern: C,K
% D variables: nonuniform sorted finite sets with injected anchors.
% K variables: labels with permuted nonuniform numeric embeddings; labels carry no ordinal information.
%
%   x1   C [0.1,1] -> orig [0.1,1]
%   x2   K labels {k2_1,...,k2_76}, 76 levels, permuted embedding in [0,1]
%
% Usage:
%   PB = Deb41_mix()
%   F  = PB.func_F(xcell)       % recommended inside benchmark loops
%   F  = Deb41_mix(xcell)              % also valid; PB is memoized persistently
%   PD = Deb41_mix('ProblemData')
%

persistent PB_cached
if isempty(PB_cached)
lb_orig = [0.1; 0];
ub_orig = [1; 1];
lb_C_work = [0.1; 0];
ub_C_work = [1; 1];
var_types = {'C', 'K'};
K2_labels = { ...
    'k2_1', 'k2_2', 'k2_3', 'k2_4', 'k2_5', 'k2_6', 'k2_7', 'k2_8', 'k2_9', 'k2_10', ...
    'k2_11', 'k2_12', 'k2_13', 'k2_14', 'k2_15', 'k2_16', 'k2_17', 'k2_18', 'k2_19', 'k2_20', ...
    'k2_21', 'k2_22', 'k2_23', 'k2_24', 'k2_25', 'k2_26', 'k2_27', 'k2_28', 'k2_29', 'k2_30', ...
    'k2_31', 'k2_32', 'k2_33', 'k2_34', 'k2_35', 'k2_36', 'k2_37', 'k2_38', 'k2_39', 'k2_40', ...
    'k2_41', 'k2_42', 'k2_43', 'k2_44', 'k2_45', 'k2_46', 'k2_47', 'k2_48', 'k2_49', 'k2_50', ...
    'k2_51', 'k2_52', 'k2_53', 'k2_54', 'k2_55', 'k2_56', 'k2_57', 'k2_58', 'k2_59', 'k2_60', ...
    'k2_61', 'k2_62', 'k2_63', 'k2_64', 'k2_65', 'k2_66', 'k2_67', 'k2_68', 'k2_69', 'k2_70', ...
    'k2_71', 'k2_72', 'k2_73', 'k2_74', 'k2_75', 'k2_76'};
K2_embed  = [ ...
    0.05861378599048317; 0.9371904018254612; 0.06491722516320722; 0.02101222243523014; 0.8767444084341136; 0.7904499172995297; 0.9682981346372206; 0.03254670144569972; ...
    0.325752552129051; 0.07159933499747269; 0.04711717842993464; 0.6090382541972487; 0.1955841242299839; 0.006166446820814373; 0.3093654171791679; 0.4750326084529071; ...
    0.2347114216549523; 0.01780574926515427; 0.1022370154364403; 0.001504461153181454; 0.00794059357229376; 0.02453245021801351; 0.5175503677029233; 0.2486859586863869; ...
    0.04191070413949605; 0.2081651504504331; 0.2631341778871472; 0.4346253514779282; 0.683415627402425; 0.5853504664669779; 0.6332759902034314; 0.2212060226325093; ...
    0.2934695194581322; 0.6580672632168687; 3.161207239581158e-05; 0.09397930805043883; 0.1394075913296177; 0.5; 0.004648030151566838; 0.5622090028034751; ...
    0.0004415134916675889; 0.003373558642540585; 0.2780605589449344; 0.01490448634189986; 0; 0.1109031749048234; 0.1717825201086575; 0.9066735768635092; ...
    0.05268262446074727; 0.03705626215522679; 1; 0.396297552790453; 0.0786663505365737; 0.4545670912564836; 0.1605522049340344; 0.4960257616860672; ...
    0.1199833636905772; 0.002330322179873383; 0.5396102025687737; 0.0001668495184087952; 0.7628383082493139; 0.08612435885098703; 0.0008806370377962118; 0.1497622543309589; ...
    0.02837464124092226; 0.847399618009957; 0.41520348737857; 0.7357976783249014; 0.377903555740975; 0.3426351685931084; 0.1294830485332442; 0.01229951420396986; ...
    0.009981490832800071; 0.7093246032323672; 0.3600174570069686; 0.818635899237781; ...
];
ProblemData = { ...
    [0.1; 1]; ... % x1 C
    K2_labels; ... % x2 K
};
x_anchor = {0.5500000000000002, 'k2_38'};
anchors_set = [0.55 0.1 1; 0.5 0 1];

PB = struct();
PB.name = 'Deb41_mix';
PB.problem = 'Deb41';
PB.source = 'MOModels_Matlab';
PB.type = 'MOO_MIXED';
PB.nvar = 2; PB.n = 2; PB.nobj = 2; PB.m = 2;
PB.var_types = var_types;
PB.type_counts = struct('C', 1, 'D', 0, 'K', 1);
PB.ProblemData = ProblemData;
PB.strategy = 'progressive'; PB.kappa = 1000000;
PB.lb_orig = lb_orig; PB.ub_orig = ub_orig;
PB.lb_C_work = lb_C_work; PB.ub_C_work = ub_C_work;
PB.x_anchor = x_anchor;
PB.anchors_set = anchors_set;
PB.K2_labels = K2_labels; PB.K2_embed = K2_embed;
PB.pareto_front_known = true;
PB.pareto_set_known = true;
PB.pf_type = 'convex';
PB.ideal_point = [0;0];
PB.nadir_point = [1;1];
PB.core = @(xh) Deb41_orig(xh);
PB.decode = @(xr) decode(xr, PB);
PB.func_F = @(xr) objective(xr, PB);
PB_cached = PB;
else
    PB = PB_cached;
end

if nargin == 0
    varargout{1} = PB; return
end
arg1 = varargin{1};
if ischar(arg1) || (isstring(arg1) && isscalar(arg1))
    key = lower(char(arg1));
    switch key
        case {'problemdata','bounds','domain'}
            varargout{1} = PB.ProblemData; return
        case 'var_types'
            varargout{1} = PB.var_types; return
        case 'info'
            varargout{1} = PB; return
        otherwise
            error('Unknown string argument: %s', char(arg1));
    end
end
varargout{1} = PB.func_F(arg1);
end

function F = objective(xr, PB)
xh = decode(xr, PB);
F = PB.core(xh);
F = F(:);
end

function xh = decode(xr, PB)
if ~iscell(xr) || numel(xr) ~= 2
    error('Deb41_mix: input must be a cell array with exactly 2 entries.');
end
xh = zeros(2,1);
tmp = check_C(xr{1}, PB.lb_C_work(1), PB.ub_C_work(1), 'x1');
xh(1) = map_C_to_orig(tmp, PB.lb_C_work(1), PB.ub_C_work(1), PB.lb_orig(1), PB.ub_orig(1));
xh(2) = check_K(xr{2}, PB.K2_labels, PB.K2_embed, 'x2');
end

function v = check_C(val, a, b, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('Deb41_mix: %s must be a real scalar.', name);
end
if val < a || val > b
    error('Deb41_mix: %s=%g outside [%g,%g].', name, val, a, b);
end
v = double(val);
end

function xorig = map_C_to_orig(xwork, lbw, ubw, lbo, ubo)
if abs(ubw - lbw) <= 1e-14
    t = 0;
else
    t = (xwork - lbw) / (ubw - lbw);
end
t = max(0, min(1, t));
xorig = lbo + t * (ubo - lbo);
end

function v = check_D(val, grid, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('Deb41_mix: %s must be a real scalar.', name);
end
grid = grid(:);
[dmin, idx] = min(abs(grid - val));
if dmin > 1e-10 * max(1, max(abs(grid)))
    error('Deb41_mix: %s=%g not in grid.', name, val);
end
v = grid(idx);
end

function v = check_K(label, labels, embed, name)
if isstring(label), label = char(label); end
if ~(ischar(label) && isrow(label))
    error('Deb41_mix: %s must be a char vector or scalar string.', name);
end
idx = find(strcmp(label, labels), 1);
if isempty(idx)
    error('Deb41_mix: %s unknown label ''%s''.', name, label);
end
v = embed(idx);
end


% -------------------------------------------------------------------------
% Embedded original continuous MOO problem (top-level function renamed only)
% -------------------------------------------------------------------------
function f = Deb41_orig(x)
%###############################################################################
%
%   As described by K. Deb in "Multi-objective Genetic Algorithms: Problem
%   Difficulties and Construction of Test Problems", Evolutionary Computation 
%   7(3): 205-230, 1999.
%
%   Example 4.1 (Multi-modal Multi-objective Problem).
%
%   This file is part of a collection of problems developed for
%   derivative-free multiobjective optimization in
%   A. L. Custódio, J. F. A. Madeira, A. I. F. Vaz, and L. N. Vicente,
%   Direct Multisearch for Multiobjective Optimization, 2010.
%
%   Written by the authors in June 1, 2010.
%
%   MATLAB version by J. F. A. Madeira
%   November 7, 2025
%
%###############################################################################
%
% Problem characteristics:
% - Number of variables: 2
% - Number of objectives: 2
%   Bounds: x1 in [0.1,1], x2 in [0,1]
%
%
M = 2; % Number of objectives (fixed)
% Check dimension
n = length(x);
if n ~= 2
    error('Deb41 requires exactly 2 variables, %d provided', n);
end
% Ensure x is a column vector
x = x(:);
% Initialize objectives
f = zeros(M, 1);
% g function
gx = 2 - exp(-((x(2)-0.2)/0.004)^2) - 0.8*exp(-((x(2)-0.6)/0.4)^2);
% Objective functions
f(1) = x(1);
f(2) = gx/x(1);
end

