function varargout = lovison3_mix(varargin)
%LOVISON3_MIX  Self-contained mixed-variable MOO adaptation of lovison3.
%
% Auto-generated by generate_selfcontained_wrappers_MOO_mix.m
% Source: lovison3, n=2, m=2, strategy=progressive, kappa=1000000
% Variable pattern: C,K
% D variables: nonuniform sorted finite sets with injected anchors.
% K variables: labels with permuted nonuniform numeric embeddings; labels carry no ordinal information.
%
%   x1   C [0,6] -> orig [0,6]
%   x2   K labels {k2_1,...,k2_75}, 75 levels, permuted embedding in [-4,4]
%
% Usage:
%   PB = lovison3_mix()
%   F  = PB.func_F(xcell)       % recommended inside benchmark loops
%   F  = lovison3_mix(xcell)              % also valid; PB is memoized persistently
%   PD = lovison3_mix('ProblemData')
%

persistent PB_cached
if isempty(PB_cached)
lb_orig = [0; -4];
ub_orig = [6; 4];
lb_C_work = [0; -4];
ub_C_work = [6; 4];
var_types = {'C', 'K'};
K2_labels = { ...
    'k2_1', 'k2_2', 'k2_3', 'k2_4', 'k2_5', 'k2_6', 'k2_7', 'k2_8', 'k2_9', 'k2_10', ...
    'k2_11', 'k2_12', 'k2_13', 'k2_14', 'k2_15', 'k2_16', 'k2_17', 'k2_18', 'k2_19', 'k2_20', ...
    'k2_21', 'k2_22', 'k2_23', 'k2_24', 'k2_25', 'k2_26', 'k2_27', 'k2_28', 'k2_29', 'k2_30', ...
    'k2_31', 'k2_32', 'k2_33', 'k2_34', 'k2_35', 'k2_36', 'k2_37', 'k2_38', 'k2_39', 'k2_40', ...
    'k2_41', 'k2_42', 'k2_43', 'k2_44', 'k2_45', 'k2_46', 'k2_47', 'k2_48', 'k2_49', 'k2_50', ...
    'k2_51', 'k2_52', 'k2_53', 'k2_54', 'k2_55', 'k2_56', 'k2_57', 'k2_58', 'k2_59', 'k2_60', ...
    'k2_61', 'k2_62', 'k2_63', 'k2_64', 'k2_65', 'k2_66', 'k2_67', 'k2_68', 'k2_69', 'k2_70', ...
    'k2_71', 'k2_72', 'k2_73', 'k2_74', 'k2_75'};
K2_embed  = [ ...
    -3.99272424881309; -0.5696227430273519; -2.172413931456054; -3.826398736640322; -2.060833429217429; -3.653737189898042; -3.515737693639629; -3.083727038706945; ...
    0.4582153637707238; -3.97212793438827; -1.308659054673517; -2.762676502421904; 1.232074441128135; -2.580746867405527; -3.463659194696031; -3.980747068725923; ...
    -4; 3.490862943390474; -0.2444038669822262; 0.8361176834139687; -3.949053320664511; -3.61072172510102; 3.243590601463602; -3.987570264988726; ...
    -3.288447590507821; -3.765571034573536; 0.2759588121840357; -0.0753194375954771; -2.930221642269251; -3.876860352746759; -1.702686402062632; -3.998621502924024; ...
    -1.57537883046252; 3.742990455530194; -3.996352251639249; -1.826006941667964; -1.444048223473455; -3.917533739035532; 4; 1.646324023197433; ...
    1.436897911310492; -0.725822028448472; -3.408452149714837; -3.56474046514209; -3.797314902586652; -2.384099960673697; -2.848225881324472; -3.350065045278257; ...
    -3.69384419257104; -3.999738823643132; -3.852890355742963; -3.223550642607413; 0.6449248031577426; -1.945376947115085; -3.155326139507692; -1.169176258124434; ...
    -3.934395465295252; -2.28015655092903; 2.530632572957934; -2.673530812952055; -3.008707261545807; 2.763502850654471; 0; 2.079100244063348; ...
    1.031824248430915; 1.860381862642917; 2.302507717089563; -0.8777917277921086; -3.731101814356848; -0.4091608901775805; -1.025565212789743; -3.898382419513156; ...
    3.00114634282501; 0.09812427757619613; -3.961598355008227; ...
];
ProblemData = { ...
    [0; 6]; ... % x1 C
    K2_labels; ... % x2 K
};
x_anchor = {3, 'k2_63'};
anchors_set = [3 0 6; 0 -4 4];

PB = struct();
PB.name = 'lovison3_mix';
PB.problem = 'lovison3';
PB.source = 'MOModels_Matlab';
PB.type = 'MOO_MIXED';
PB.nvar = 2; PB.n = 2; PB.nobj = 2; PB.m = 2;
PB.var_types = var_types;
PB.type_counts = struct('C', 1, 'D', 0, 'K', 1);
PB.ProblemData = ProblemData;
PB.strategy = 'progressive'; PB.kappa = 1000000;
PB.lb_orig = lb_orig; PB.ub_orig = ub_orig;
PB.lb_C_work = lb_C_work; PB.ub_C_work = ub_C_work;
PB.x_anchor = x_anchor;
PB.anchors_set = anchors_set;
PB.K2_labels = K2_labels; PB.K2_embed = K2_embed;
PB.pareto_front_known = false;
PB.pareto_set_known = false;
PB.pf_type = 'unknown';
PB.ideal_point = [];
PB.nadir_point = [];
PB.core = @(xh) lovison3_orig(xh);
PB.decode = @(xr) decode(xr, PB);
PB.func_F = @(xr) objective(xr, PB);
PB_cached = PB;
else
    PB = PB_cached;
end

if nargin == 0
    varargout{1} = PB; return
end
arg1 = varargin{1};
if ischar(arg1) || (isstring(arg1) && isscalar(arg1))
    key = lower(char(arg1));
    switch key
        case {'problemdata','bounds','domain'}
            varargout{1} = PB.ProblemData; return
        case 'var_types'
            varargout{1} = PB.var_types; return
        case 'info'
            varargout{1} = PB; return
        otherwise
            error('Unknown string argument: %s', char(arg1));
    end
end
varargout{1} = PB.func_F(arg1);
end

function F = objective(xr, PB)
xh = decode(xr, PB);
F = PB.core(xh);
F = F(:);
end

function xh = decode(xr, PB)
if ~iscell(xr) || numel(xr) ~= 2
    error('lovison3_mix: input must be a cell array with exactly 2 entries.');
end
xh = zeros(2,1);
tmp = check_C(xr{1}, PB.lb_C_work(1), PB.ub_C_work(1), 'x1');
xh(1) = map_C_to_orig(tmp, PB.lb_C_work(1), PB.ub_C_work(1), PB.lb_orig(1), PB.ub_orig(1));
xh(2) = check_K(xr{2}, PB.K2_labels, PB.K2_embed, 'x2');
end

function v = check_C(val, a, b, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('lovison3_mix: %s must be a real scalar.', name);
end
if val < a || val > b
    error('lovison3_mix: %s=%g outside [%g,%g].', name, val, a, b);
end
v = double(val);
end

function xorig = map_C_to_orig(xwork, lbw, ubw, lbo, ubo)
if abs(ubw - lbw) <= 1e-14
    t = 0;
else
    t = (xwork - lbw) / (ubw - lbw);
end
t = max(0, min(1, t));
xorig = lbo + t * (ubo - lbo);
end

function v = check_D(val, grid, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('lovison3_mix: %s must be a real scalar.', name);
end
grid = grid(:);
[dmin, idx] = min(abs(grid - val));
if dmin > 1e-10 * max(1, max(abs(grid)))
    error('lovison3_mix: %s=%g not in grid.', name, val);
end
v = grid(idx);
end

function v = check_K(label, labels, embed, name)
if isstring(label), label = char(label); end
if ~(ischar(label) && isrow(label))
    error('lovison3_mix: %s must be a char vector or scalar string.', name);
end
idx = find(strcmp(label, labels), 1);
if isempty(idx)
    error('lovison3_mix: %s unknown label ''%s''.', name, label);
end
v = embed(idx);
end


% -------------------------------------------------------------------------
% Embedded original continuous MOO problem (top-level function renamed only)
% -------------------------------------------------------------------------
function f = lovison3_orig(x)
% LOVISON3 function
%
%   As described by A. Lovison in "A synthetic approach to multiobjective
%   optimization", arxiv Item: http://arxiv.org/abs/1002.0093.
%
%   Example 3.
%
%   In the above paper/papers the variables bounds were not set.
%   We considered 0<=x[1]<=6 and -4<=x[2]<=4.
%
%   This file is part of a collection of problems developed for
%   derivative-free multiobjective optimization in
%   A. L. Custódio, J. F. A. Madeira, A. I. F. Vaz, and L. N. Vicente,
%   Direct Multisearch for Multiobjective Optimization, 2010.
%
%   Written by the authors in June 1, 2010.
%   Adapted to MATLAB format in November 2025.
%
%   Input: x is a 2-dimensional vector
%   Output: f is a 2-dimensional vector with the function values
%   Output: c is a vector of constraints (empty for this problem - bounds are
%          handled by the optimization algorithm)
% Nota: Este problema é originalmente de maximização, 
% mas para manter a consistência com a interface da coleção DMS,
% convertemos para minimização multiplicando por -1.
% Função objetivo 1
%
%   Bounds: x1 in [0,6], x2 in [-4,4]
%
f1 = -(-x(1)^2-x(2)^2);
% Função objetivo 2
f2 = -(-(x(1)-6)^2+(x(2)+0.3)^2);
% Vetor de funções objetivo
f = [f1; f2];
% Não há restrições de desigualdade para este problema
% As restrições de limites são tratadas pelo algoritmo de otimização
end

