function varargout = MOP4_mix(varargin)
%MOP4_MIX  Self-contained mixed-variable MOO adaptation of MOP4.
%
% Auto-generated by generate_selfcontained_wrappers_MOO_mix.m
% Source: MOP4, n=3, m=2, strategy=progressive, kappa=1000000
% Variable pattern: C,K,D
% D variables: nonuniform sorted finite sets with injected anchors.
% K variables: labels with permuted nonuniform numeric embeddings; labels carry no ordinal information.
%
%   x1   C [-5,5] -> orig [-5,5]
%   x2   K labels {k2_1,...,k2_108}, 108 levels, permuted embedding in [-5,5]
%   x3   D sorted nonuniform grid [-5,...,5], 79 values
%
% Usage:
%   PB = MOP4_mix()
%   F  = PB.func_F(xcell)       % recommended inside benchmark loops
%   F  = MOP4_mix(xcell)              % also valid; PB is memoized persistently
%   PD = MOP4_mix('ProblemData')
%

persistent PB_cached
if isempty(PB_cached)
lb_orig = [-5; -5; -5];
ub_orig = [5; 5; 5];
lb_C_work = [-5; -5; -5];
ub_C_work = [5; 5; 5];
var_types = {'C', 'K', 'D'};
K2_labels = { ...
    'k2_1', 'k2_2', 'k2_3', 'k2_4', 'k2_5', 'k2_6', 'k2_7', 'k2_8', 'k2_9', 'k2_10', ...
    'k2_11', 'k2_12', 'k2_13', 'k2_14', 'k2_15', 'k2_16', 'k2_17', 'k2_18', 'k2_19', 'k2_20', ...
    'k2_21', 'k2_22', 'k2_23', 'k2_24', 'k2_25', 'k2_26', 'k2_27', 'k2_28', 'k2_29', 'k2_30', ...
    'k2_31', 'k2_32', 'k2_33', 'k2_34', 'k2_35', 'k2_36', 'k2_37', 'k2_38', 'k2_39', 'k2_40', ...
    'k2_41', 'k2_42', 'k2_43', 'k2_44', 'k2_45', 'k2_46', 'k2_47', 'k2_48', 'k2_49', 'k2_50', ...
    'k2_51', 'k2_52', 'k2_53', 'k2_54', 'k2_55', 'k2_56', 'k2_57', 'k2_58', 'k2_59', 'k2_60', ...
    'k2_61', 'k2_62', 'k2_63', 'k2_64', 'k2_65', 'k2_66', 'k2_67', 'k2_68', 'k2_69', 'k2_70', ...
    'k2_71', 'k2_72', 'k2_73', 'k2_74', 'k2_75', 'k2_76', 'k2_77', 'k2_78', 'k2_79', 'k2_80', ...
    'k2_81', 'k2_82', 'k2_83', 'k2_84', 'k2_85', 'k2_86', 'k2_87', 'k2_88', 'k2_89', 'k2_90', ...
    'k2_91', 'k2_92', 'k2_93', 'k2_94', 'k2_95', 'k2_96', 'k2_97', 'k2_98', 'k2_99', 'k2_100', ...
    'k2_101', 'k2_102', 'k2_103', 'k2_104', 'k2_105', 'k2_106', 'k2_107', 'k2_108'};
K2_embed  = [ ...
    -2.404204127241115; -4.980189524384147; -4.990067880539479; -0.6002139841833296; -4.973717845969865; 0.4358361217931623; -1.135645811174949; 0.2799788061305; ...
    -1.388278706881858; -4.999288866851511; -3.999631081590526; -3.749196849064864; 1.779197322458907; -4.99986526546323; -2.700115014002126; -3.539646811400482; ...
    -1.005579353542742; -3.814871732092341; 4.126164082678489; -4.998118215249141; 2.516498692437416; 2.328005425372187; -3.310931136380248; -4.799180796178926; ...
    -2.975352654861996; -0.0238335098788367; -2.885877256324579; -4.924109708814944; 3.706632841022181; -5; 4.557256708094355; -4.957457659631062; ...
    -4.842061657540389; -4.632927400358348; 3.501174553009246; -0.7378771286209096; -4.267841792141752; -1.976771385331429; 1.427098406179329; 0.7555171887645482; ...
    -2.300899918258714; -3.062579203779475; -4.821371429331451; 3.298572653933256; -4.448127337390572; -4.564253278206811; -4.9104433261803; -1.263207604459234; ...
    3.914958909545783; 2.707790339517938; -4.694834836731738; -4.993587801709924; 0.5943446722276828; -3.878489802185656; -4.315706775300309; -3.681446579826934; ...
    -4.996246616739826; -4.985621478551689; -4.057192751651181; -4.966156214523201; -4.861281959380336; 1.959366674780066; -3.611602597160663; -1.748689399246466; ...
    -4.405827716550167; 0.9193663121140014; -2.603796150656077; -4.895439682834835; -4.11277455124114; -4.361694870546728; -4.488616161429396; -4.936475247876031; ...
    1.255144499138935; -1.510873210526666; 1.085904594065994; -0.1718144420500831; -4.947577959204408; -4.527317041729597; -4.723314809885428; 3.098815683662256; ...
    -3.230351720167437; 4.777166480564668; 2.901892112394608; -4.664714348170144; -1.863939886503803; 1.6017786099143; 0.1267599015355225; -2.19523646653754; ...
    -4.750180842151842; -4.218078650333055; 0; -2.794136740722713; -2.505164389098675; -4.166396430840736; -1.631005328797963; -3.940069887691915; ...
    -3.389328611900907; -0.317196006894612; -4.599448641721843; 2.142298718118756; -0.8729943740489921; 5; 4.340259618098845; -2.087198623790234; ...
    -4.879063792599889; -0.4599914162998946; -4.775460181361574; -3.46556136239486; ...
];
D3_vals = [ ...
    -5; -4.996071473245641; -4.986320075284275; -4.971617674680099; -4.952363735331507; -4.928817092505667; -4.901167002820426; -4.869561382485359; ...
    -4.834120891838078; -4.794946950616842; -4.752126719135007; -4.705736396851876; -4.655843514532308; -4.602508588581873; -4.545786352188245; -4.485726695006281; ...
    -4.422375395802323; -4.355774704127776; -4.285963809415614; -4.212979224486322; -4.13685510286769; -4.057623504162063; -3.975314618087413; -3.889956955251286; ...
    -3.801577510856347; -3.710201906166407; -3.615854511538314; -3.518558554050193; -3.418336212162758; -3.315208699390348; -3.209196338598233; -3.100318628258246; ...
    -2.988594301768048; -2.874041380757138; -2.756677223155293; -2.636518566678867; -2.513581568291778; -2.387881840116564; -2.25943448220326; -1.994354894381169; ...
    -1.857750561841399; -1.718454442845024; -1.576479480772863; -1.431838254298774; -1.284542995799717; -1.13460560844425; -0.9820376820812422; -0.8268505080369977; ...
    -0.669055092917187; -0.5086621714995934; -0.3456822187947584; -0.1801254613435619; -0.01200188781393852; 0; 0.1586787410473178; 0.3319068830571092; ...
    0.50767320578717; 0.685968578262381; 0.8667840631285699; 1.050110909255557; 1.235940544744281; 1.42426457030945; 1.615074753011749; 1.808363020315714; ...
    2.00412145445144; 2.202342287060057; 2.403017894104496; 2.606140791028575; 2.811703628148741; 3.019699186263976; 3.230120372470575; 3.44296021616934; ...
    3.658211865253833; 3.87586858246898; 4.095923741930241; 4.318370825794123; 4.543203421071546; 4.77041521657614; 5; ...
];
ProblemData = { ...
    [-5; 5]; ... % x1 C
    K2_labels; ... % x2 K
    {D3_vals}; ... % x3 D
};
x_anchor = {0, 'k2_91', 0};
anchors_set = [0 -5 5; 0 -5 5; 0 -5 5];

PB = struct();
PB.name = 'MOP4_mix';
PB.problem = 'MOP4';
PB.source = 'MOModels_Matlab';
PB.type = 'MOO_MIXED';
PB.nvar = 3; PB.n = 3; PB.nobj = 2; PB.m = 2;
PB.var_types = var_types;
PB.type_counts = struct('C', 1, 'D', 1, 'K', 1);
PB.ProblemData = ProblemData;
PB.strategy = 'progressive'; PB.kappa = 1000000;
PB.lb_orig = lb_orig; PB.ub_orig = ub_orig;
PB.lb_C_work = lb_C_work; PB.ub_C_work = ub_C_work;
PB.x_anchor = x_anchor;
PB.anchors_set = anchors_set;
PB.K2_labels = K2_labels; PB.K2_embed = K2_embed;
PB.D3_vals = D3_vals;
PB.pareto_front_known = false;
PB.pareto_set_known = false;
PB.pf_type = 'unknown';
PB.ideal_point = [];
PB.nadir_point = [];
PB.core = @(xh) MOP4_orig(xh);
PB.decode = @(xr) decode(xr, PB);
PB.func_F = @(xr) objective(xr, PB);
PB_cached = PB;
else
    PB = PB_cached;
end

if nargin == 0
    varargout{1} = PB; return
end
arg1 = varargin{1};
if ischar(arg1) || (isstring(arg1) && isscalar(arg1))
    key = lower(char(arg1));
    switch key
        case {'problemdata','bounds','domain'}
            varargout{1} = PB.ProblemData; return
        case 'var_types'
            varargout{1} = PB.var_types; return
        case 'info'
            varargout{1} = PB; return
        otherwise
            error('Unknown string argument: %s', char(arg1));
    end
end
varargout{1} = PB.func_F(arg1);
end

function F = objective(xr, PB)
xh = decode(xr, PB);
F = PB.core(xh);
F = F(:);
end

function xh = decode(xr, PB)
if ~iscell(xr) || numel(xr) ~= 3
    error('MOP4_mix: input must be a cell array with exactly 3 entries.');
end
xh = zeros(3,1);
tmp = check_C(xr{1}, PB.lb_C_work(1), PB.ub_C_work(1), 'x1');
xh(1) = map_C_to_orig(tmp, PB.lb_C_work(1), PB.ub_C_work(1), PB.lb_orig(1), PB.ub_orig(1));
xh(2) = check_K(xr{2}, PB.K2_labels, PB.K2_embed, 'x2');
xh(3) = check_D(xr{3}, PB.D3_vals, 'x3');
end

function v = check_C(val, a, b, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('MOP4_mix: %s must be a real scalar.', name);
end
if val < a || val > b
    error('MOP4_mix: %s=%g outside [%g,%g].', name, val, a, b);
end
v = double(val);
end

function xorig = map_C_to_orig(xwork, lbw, ubw, lbo, ubo)
if abs(ubw - lbw) <= 1e-14
    t = 0;
else
    t = (xwork - lbw) / (ubw - lbw);
end
t = max(0, min(1, t));
xorig = lbo + t * (ubo - lbo);
end

function v = check_D(val, grid, name)
if ~isnumeric(val) || ~isscalar(val) || ~isreal(val)
    error('MOP4_mix: %s must be a real scalar.', name);
end
grid = grid(:);
[dmin, idx] = min(abs(grid - val));
if dmin > 1e-10 * max(1, max(abs(grid)))
    error('MOP4_mix: %s=%g not in grid.', name, val);
end
v = grid(idx);
end

function v = check_K(label, labels, embed, name)
if isstring(label), label = char(label); end
if ~(ischar(label) && isrow(label))
    error('MOP4_mix: %s must be a char vector or scalar string.', name);
end
idx = find(strcmp(label, labels), 1);
if isempty(idx)
    error('MOP4_mix: %s unknown label ''%s''.', name, label);
end
v = embed(idx);
end


% -------------------------------------------------------------------------
% Embedded original continuous MOO problem (top-level function renamed only)
% -------------------------------------------------------------------------
function f = MOP4_orig(x)
% MOP4 function
%
%   As described by Huband et al. in "A review of multiobjective test problems
%   and a scalable test problem toolkit", IEEE Transactions on Evolutionary 
%   Computing 10(5): 477-506, 2006.
%
%   Example MOP4, Van Valedhuizen's test suit.
%
%   This file is part of a collection of problems developed for
%   derivative-free multiobjective optimization in
%   A. L. Custódio, J. F. A. Madeira, A. I. F. Vaz, and L. N. Vicente,
%   Direct Multisearch for Multiobjective Optimization, 2010.
%
%   Written by the authors in June 1, 2010.
%   Adapted to MATLAB format in November 2025.
%
% Problem characteristics:
% - Number of variables: 3
% - Number of objectives: 2
%   Bounds: x1 in [-5,5], x2 in [-5,5], x3 in [-5,5]
%
%
%   Input: x is a 3-dimensional vector
%   Output: f is a 2-dimensional vector with the function values
%   Output: c is a vector of constraints (empty for this problem - bounds are
%          handled by the optimization algorithm)
% Função objetivo 1
f1 = 0;
for i = 1:2
    f1 = f1 + (-10 * exp(-0.2 * sqrt(x(i)^2 + x(i+1)^2)));
end
% Função objetivo 2
f2 = 0;
for i = 1:3
    f2 = f2 + (abs(x(i))^0.8 + 5*sin(x(i)^3));
end
% Vetor de funções objetivo
f = [f1; f2];
% Não há restrições de desigualdade para este problema
end

